### ISSUE TITLE
[MainUI] In the list of profiles on a link, showing "(No Profile)" and "Default" is confusing and redundant

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1038]
## The problem

Based on the docs, when no profile is selected on a Link, the default profile is used. Therefore it is confusing and redundant to show both "(No Profile)" and "Default" in the list as they are essentially equivalent options.

## Your suggestion

Eliminate the "(No Profile)" options and make the "Default" option be the one that is selected automatically by default.

## Your environment

```yaml

```

I can provide all this other info if needed but don't think it's necessary for this issue. I'm running the SNAPSHOT from yesterady.

**Comment by hubsif** [comment]
Duplicate of #884, which I planned working on soon.

**Comment by rkoshak** [comment]
I searched yet somehow missed it. I'll close this one.
