### ISSUE TITLE
Wrong value's (temperature, humidity, wind speed ...)

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab-webui#1050]
Hi, 
I have some wrong temperature, humidity, windspeed and ... values since the update yesterday (oh3-snapshot) .
![2021-05-12 20_21_18-Window](https://user-images.githubusercontent.com/16850444/118025158-cb5bfb00-b35f-11eb-897a-9d9aa45dddd5.png)
The first value should be 12,25 °C.

It's a problem in netatmo, openweathermap, deconz ... bindings
The decimal point missing?

My settings are metric units and german language.

thanks
LukaNoah

**Comment by wborn** [comment]
This issue is similar to https://github.com/openhab/openhab-addons/issues/10673.

**Comment by ghys** [comment]
Please go to https://github.com/openhab/openhab-core/issues/2360 for updates on this matter, it's not an UI issue.
