### ISSUE TITLE
[Main UI] Managed Items cannot be assigned to Groups in Item Edit page

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#1062]
## The problem

Managed Items cannot be assigned to Groups in Item Edit page

![grafik](https://user-images.githubusercontent.com/5131747/118961449-9f92d380-b964-11eb-9940-72e4676e0dc1.png)

![grafik](https://user-images.githubusercontent.com/5131747/118961483-a7527800-b964-11eb-8d1f-227038067901.png)

## Expected behavior

Groups should be available.

## Steps to reproduce

1. Got to Settings -> Items page

2. Choose Item

3. Click Edit button in top right corner

## Your environment

```yaml

```

## Browser console

```txt

```

## Additional information

Workaround: Edit the Group and assign members.

**Comment by ghys** [comment]
It works here, any JS errors to report when you open the list? If you click the orange icon (which brings up the model-based view) what happens?

**Comment by cweitkamp** [comment]
No JS error in the developer console.

![grafik](https://user-images.githubusercontent.com/5131747/119185952-ba09a180-ba77-11eb-885d-e12012bd000f.png)

When clicking on the orange threes line on the left hand side of "Parent Group(s)" I can see this popup.

![grafik](https://user-images.githubusercontent.com/5131747/119186103-e9b8a980-ba77-11eb-8dea-ce3d550c96b4.png)

Picking a Group from over there is working.

When clicking on the grey error on the right hand side I get an empty popup:

![grafik](https://user-images.githubusercontent.com/5131747/119186205-0e148600-ba78-11eb-9cef-445ab422f8b4.png)

**Comment by ghys** [comment]
Maybe it's a regression introduced by #1000, there were changes in that area in this PR.
@hubsif would be appreciated if you could have a look!

**Comment by hubsif** [comment]
Unfortunately, that's the case again 😢. I'm going to provide a fix soon...
