### ISSUE TITLE
Update Framework7 to v6 and Vue.js to v3

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#1069]
There have been major new versions of Vue (v3) and Framework7 (v6) with lots of improvements that have not yet been incorporated into the WebUI.

Release notes:
- Framework7 v6: https://framework7.io/release-notes/
- Vue v3: https://v3.vuejs.org/guide/migration/introduction.html#notable-new-features

Migrations are described here:
- https://v3.vuejs.org/guide/migration/introduction.html
- https://framework7.io/docs/migration-from-v5.html

@ghys Are you working on this? Have you already checked if there are packages WebUI needs that are not compatible with Vue v3 yet? If not, I'm willing to give this a shot and start with checking the used packages for obvious problems.

**Comment by ghys** [comment]
Of course it's been considered, and the cost-benefit is being monitored, but I think it's still insufficient to undertake the amount of work that would be required, especially to replace every occurrence of the deprecated prototype extensions (https://framework7.io/vue/migration-from-v5.html#vue-component-extensions) which basically mandates a migration to Vue3's composition API for most if not all components.
So for now it's not in the plans. But if you want to have a look, by all means!

**Comment by eikowagenknecht** [comment]
I've looked at the packages openHAB uses and there are quite some problematic ones:

- vue-async-computed
  - no vue3 version, vue2 version actively developed
  - probably can be refactored to work without it
- vue-codemirror
  - no vue3 version, last update 3 years ago
  - seems like there's no replacement (yet?) and codemirror has to be used without the vue package
- vue-grid-layout
  - vue3 version still in beta with some bugs
- vue-fullscreen
  - vue3 version in the making, should be ready soon
- vue-knob-control
  - vue3 compatibility unclear, last update 2 years ago
- vue-magic-grid
  - vue3 compatibility unclear, last update 2 years ago, but not used anyways as far as I can see
- vuetrend
  - vue3 compatibility unclear, last update 2 years ago

The other vue related packages should be usable (soma with migrations) with Vue 3.

**Comment by eikowagenknecht** [comment]
Closing my issues with openHAB that seem to have gone stale.
