### ISSUE TITLE
Add support for rule templates

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-webui#1082]
Paper UI had support for rule templates, which is a feature still missing in the Main UI.

Rule templates are a feature to easily create rules that are not empty, but readily usable. Allowing users to choose a template should therefore best be added as an option to the "+" button for adding new rules.

Available rule templates can be retrieved through `/rest/templates`.
Besides a uid, a template mainly has a label and description which can be used to show them in a list.
Additionally, a rule template has a config description, i.e. a list of parameters that the user should be requested to fill in.

When this is done, all the UI needs to do is to POST to `rest/rules` and instead of providing lists of modules as normally, simply pass the `templateUID` and the `configuration` with it. This should be it - a new rule will be created!

**Comment by rkoshak** [comment]
One thing PaperUI never supported (or I couldn't figure out how to do it) was creating/importing rule templates. Do we have a concept for how one might create templates beyond hand coding the JSON? Perhaps a new section under Developer Tools or something like that similar to how custom widgets are created.

To me import is more important than creating templates. Those who will be writing rule templates don't need to have their hand held as much as those who would be wanting to use the templates. We can manage hand coding JSON if we need to. But until we have a marketplace again we'll need an easy way for users to import a template. Of course, having a nice UI for creating rule templates would be fantastic.

I've already a bunch of rules that I'd love to turn into templates which will make configuring and using them easier for most users. I'm keen to have such a feature and am happy to test things out where I'm able.

**Comment by ghys** [comment]
> Available rule templates can be retrieved through /rest/templates.

On that point, can you explain why in [`org.openhab.core.automation.template`](https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/template`) there is a `Template` interface and only one `RuleTemplate` class implementing it?
In the context of automation, what other types of templates could we have besides rules?

The reason I'm asking is that the "templates" concept and its related REST endpoint `/rest/templates` appear very generic and might suggest we could have other types of templates besides rules: things, items, UI pages/sitemaps/widgets... which would construct the "real" objects based on a set of parameters (which btw would be very interesting to have as well).

In the REST API Explorer (Swagger UI) there's nothing suggesting that the templates concept is only related to automation. If we want to reuse the templates concept, it would probably be wise to move these generic classes out of the automation bundle and into a more generic core package, and only keep `RuleTemplate` and their providers/registry (including a new JSONDB-managed one) in `org.openhab.automation`.

On the other hand, if the template concept is going to be restricted to rules, maybe consolidate the REST endpoint into `/rest/rules`, for instance `/rest/rules/templates`, or at least rename it to `/rest/rule-templates`.

I believe now would be a good time to make these kinds of changes to the API while it's not really in use.
