### ISSUE TITLE
Propagate Widget-props to other widgets

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-webui#1088]
## The problem
I could imagine, that it would be a great feature to have the possibility to referece two witgets with same ID, regarding props.
Especially if you would want to use one widget on different pages.

## Your suggestion
- For each widget it would be nice, to not set the probs, but link it with an already configured widget of same type and therefore automatically set all props to the same values --> Maybe via some dropdown at the very top of each props-page, listing all widgets of especially the same type?
- If you then choose to link two widgets, it would be great if you would immediately see all the props taken from the referenced widget
- If you now would like to change the prop-values, it would be nice to NOT have to search for the initial widget and change the settings there, instead it should be able to directly change the values in the new widget, which is then also propagated backwards to the initial widget
- OPTIONAL: In some Situations it could be useful to have a checkbox besides each value in the props window, to deactivate the link to another widget to have the possiblity to link every prop, but exclude some props with then are individual only to the second widget

**To make it clear i have prepared an example for usage of this feature:**
![sdfdh](https://user-images.githubusercontent.com/68030498/120639616-d6431080-c471-11eb-96be-8db0ea7a03df.jpg)

**- Left Page:** Overview Page
**- Right Page:** "Schlafzimmer" Page

**- Action 1:** I made this widget, to be customizable for background, text and action to open page "Schlafzimmer"
**- Action 2:** Same widget, configured exactly the same way with the exception of the target page --> Overview (because i want to get back)

At the moment this looks like there is not much stuff, but im planning to have on these very same widgets the opportunity to add much more content information regarding the target page
As soon as there are much more probs to configure this can get more and more work
I know i can copy the yaml-code and change ony the target-page-prop, but as soon as there is like 50% of equal props and 50% of individual props for each widget, it can also get more difficult or time-consuming

I know this is not a super-important feature and only makes sense if you are creating excessively detailled pages and want to save time by not having to always change stuff in multiple places
Therefore it is ok if this feature gets rejected --> Not sure if anyone else besides me wants to have such things ;-)

## Your environment

```yaml

```

**Comment by ghys** [comment]
Sounds quite complicated and confusing, to be honest.
Since #1049 you can define default values for props and `prop.prop1` will have the default value unless you override it.
_(note! since yesterday and #1077 `defaultValue` was renamed to `default`)._

Another possibility is to make widgets that are simply references to another widget, that way you can have fewer props in your "simplified" widgets and configure the rest with your shared configuration.
Something like:
```yaml
uid: notAsManyProps
props:
  parameters:
    - name: prop1
      type: TEXT
    - name: prop2
      type: INTEGER
component: widget:lotsOfProps
config:
  prop1: =props.prop1
  prop2: =props.prop2
  prop3: 123
  prop4: abc
  ...
```

**Comment by SHU-red** [comment]
OK thanks for these possibilities.
But i think both mechanisms are not helping me or dont make things easier for this specific use case.

I agree with you, that this is surely high effort for few use cases.
