### ISSUE TITLE
[PaperUI] Grouping not enabled

### ISSUE THREAD

**Issue by robkamp** [openhab/openhab-webui#109]
I am not able to add a thing to a group in PaperUI when 'Simple Mode' is OFF. The UI is disabled. 

I have a movie to show this. It is on youtube, see https://youtu.be/JDLB-JZD3UA

**Comment by robkamp** [comment]
I can add a group, but still not able to select this group in a thing.

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
