### ISSUE TITLE
Z-Wave Thing  Mfg List 

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhab-webui#110]
I have a Zooz switch that is properly recognized & functional with the zwave binding. In the Habmin UI, The Manufacturer attribute shows as unknown.
Perhaps a Habmin database was supposed to update from tj Zwave manufacturer list?

![image](https://user-images.githubusercontent.com/51490785/63936419-c8a36000-ca2d-11e9-83ec-dac1c1a22e07.png)

List is at https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-manufacturer-list/manufacturers

![image](https://user-images.githubusercontent.com/51490785/63936603-33ed3200-ca2e-11e9-83fb-46ed0cd4c179.png)

**Comment by cdjackson** [comment]
The manufacturer list in HABmin is not linked to the database at all - this is purely a cosmetic display issue in HABmin.

**Comment by bwosborne2** [comment]
My concern is that I have seen users confused by this, thinking the device has not been properly recognized.
I am also assuming HABmin is still actively developed even though the PaperUI has been emphasized for many admin tasks.

**Comment by lolodomo** [comment]
habmin UI was removed in OH3.
