### ISSUE TITLE
Every refresh of the progress bar clears the search field but not the result filter

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#1108]
## The problem
![image](https://user-images.githubusercontent.com/1475672/122668042-917be100-d1b6-11eb-82f1-02e60a8b88b2.png)

While searching for new things, the progress bar is updated every few seconds. Every update clears the filter, but does not clear the application of the filter on the results, resulting in a filtered view that is not recognizable as such any more. Also it makes typing in the search bar almost impossible.

## Expected behavior
Refresh bar should not have side effects.

## Steps to reproduce

1. Search for things.
2. Type in search bar while search is running

## Your environment
openHAB 3.1.0.M5

**Comment by florian-h05** [comment]
Seems to have been solved meanwhile, cannot reproduce on 4.3.0.
Please create a new issue if the issue persists.
