### ISSUE TITLE
Fixed Format overview Page will not display 

### ISSUE THREAD

**Issue by dp3049** [openhab/openhab-webui#1133]
## The problem
Following a fresh openhabian (1.6.5) install - after configuring a Fixed Format overview page, I continue to receive ‘Overview Page Not Configured Yet - Edit the layout page with the ID "overview" to display important controls here.’ Run Mode when in the Pages editor displays as expected. I have rebuilt the openhab installation several times, Flexible Format overview page works.

## Expected behavior
overview page displays as configured. 

## Steps to reproduce
1.  Build fresh openhabian (1.6.5) installation with default settings
2. go to settings → pages → Overview. 
3. Select Fixed Format
4. Add one label widget
5. save overview page
6. select 'Run Mode' and check panel displays as expected.
7. Close Run Mode
8. Select "openhab" icon in top left of browser page.
9. Webpage will display default - unconfigured mainUI panel - ‘Overview Page Not Configured Yet - Edit the layout page with the ID "overview" to display important controls here.’ 

## Your environment

Platform information:
Hardware: Raspberry Pi 4 - 8GB
OS: Raspbian GNU/Linux 10 (buster)
Java Runtime Environment: OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
openHAB version: openHAB 3.1.0 - Release Build

```yaml

```

## Browser console

```txt

```

## Additional information

uicomponents_ui_page.json  used to test:
`
{
  "overview": {
    "class": "org.openhab.core.ui.components.RootUIComponent",
    "value": {
      "uid": "overview",
      "timestamp": "Jul 19, 2021, 4:42:46 PM",
      "component": "oh-layout-page",
      "config": {
        "label": "Overview",
        "layoutType": "fixed"
      },
      "slots": {
        "default": [],
        "grid": [
          {
            "component": "oh-grid-item",
            "config": {
              "x": 6.0,
              "y": 0.0,
              "h": 1.0,
              "w": 4.0
            },
            "slots": {
              "default": [
                {
                  "component": "oh-label-card",
                  "config": {
                    "label": "Pool Controller"
                  }
                }
              ]
            }
          }
        ]
      }
    }
  },
  "home": {
    "class": "org.openhab.core.ui.components.RootUIComponent",
    "value": {
      "uid": "home",
      "timestamp": "Jul 19, 2021, 4:40:43 PM",
      "component": "oh-home-page",
      "config": {
        "label": "Home Page",
        "displayModelCardsTo": [
          "role:administrator",
          "role:user"
        ]
      },
      "slots": {
        "locations": [
          {
            "component": "oh-locations-tab",
            "config": {},
            "slots": {}
          }
        ],
        "equipment": [
          {
            "component": "oh-equipment-tab",
            "config": {},
            "slots": {}
          }
        ],
        "properties": [
          {
            "component": "oh-properties-tab",
            "config": {},
            "slots": {}
          }
        ]
      }
    }
  }`

**Comment by ssukram** [comment]
I can confirm this Bug, which also is there in 3.2.0 M1.

**Comment by grssnbchr** [comment]
Can also confirm

Platform information:
Hardware: Raspberry Pi 3 - 1GB
OS: Linux/5.10.52-v7+ (arm)
Java Runtime Environment: OpenJDK Runtime Environment 11.0.12 (Zulu11.50+19-CA)
openHAB version: openHAB 3.1.0 - Release Build

**Comment by dixi83** [comment]
Same thing here fresh install off openHAB 3.1.0 Release Build on Debian 11.0.0 x64
```
config:
  label: Overview
  layoutType: fixed
blocks: []
masonry: null
grid:
  - component: oh-grid-item
    config:
      x: 0
      y: 0
      h: 2
      w: 2
    slots:
      default:
        - component: oh-label-card
          config:
            title: Test Widget
            label: Some Text
```

**Comment by ghys** [comment]
Fixed layouts are not supported in the overview page, the ability to do so in the designer (when the page was still empty) was a bug and has been removed.
