### ISSUE TITLE
[Main UI] Scripts in rules created via web UI lose unicode characters after reboot??

### ISSUE THREAD

**Issue by unrelentingtech** [openhab/openhab-webui#1135]
In the web UI, I've created a bunch of rules that execute scripts (`application/vnd.openhab.dsl.rule`). These scripts contain non-ASCII characters in strings. After restarting, all the non-ASCII characters inside these scripts got replaced with question marks :(

**Comment by ghys** [comment]
I've seen it before - I believe it's an issue with deserialization of the JSON DB when the system charset isn't set to UTF-8. So not a web UI issue at all.

**Comment by unrelentingtech** [comment]
oh, huh, by system charset do you mean the locale? Yeah this server doesn't have one set (so it's `C`), I'll test with a proper one. I guess the openhab launch scripts should either set it or warn about that…

**Comment by unrelentingtech** [comment]
Restarted openhab a couple times now with `LC_ALL=en_US.UTF-8` and the unicode characters are fine.

**Comment by ghys** [comment]
Closing at it a problem with the system's configuration and not the web UI per se.
