### ISSUE TITLE
Disable Things via MainUI not working in latest SNAPSHOT (30.08.2021)

### ISSUE THREAD

**Issue by t2000** [openhab/openhab-webui#1150]
I have just updated my openHAB installation to the latest SNAPSHOT: openHAB3-Distribution number 2477
see https://ci.openhab.org/job/openHAB3-Distribution/2477/

Unfortunately I cannot disable a Thing via the Main UI anymore. (Doesn't matter if the thing was created as a JSON file via the UI or text based via a .things file)

It works on the console, hence I think its a bug in the UI

```
openhab> things disable tradfri:gateway:ikeagw
tradfri:gateway:ikeagw successfully disabled.
```

The error I get is: "Error while disabling or enabling: Unsupported Media Type", see Screenshot.

![disableThing](https://user-images.githubusercontent.com/123778/131369353-89737453-dae7-4f35-91bc-cacbeff2583b.png)

I am using Chromium Version 92.0.4515.159 (Official Build) Arch Linux (64-bit)

**Comment by lolodomo** [comment]
Possible link with this API change from yesterday? 
https://github.com/openhab/openhab-core/pull/2469

**Comment by lolodomo** [comment]
@ghys : can you please check what content type you are using when passing the value. 
I set it to text/plain in the API.

**Comment by t2000** [comment]
@lolodomo Bingo thats the issue:

https://github.com/openhab/openhab-webui/blob/cf9ae4a06b92752ac2a0deb2ee915ab23774f767/bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue#L493

The UI sends `application/json`.

But what should be the correct type now? Since its just a `String` the `text/plain` is probably correct, so it should be changed in the WebUI, correct?
