### ISSUE TITLE
UI should not show "add link to item" for trigger channels

### ISSUE THREAD

**Issue by svenb1234** [openhab/openhab-webui#1160]
## The problem

![grafik](https://user-images.githubusercontent.com/46424536/132981849-932fcac7-6c8c-41da-9b70-c3aaf0ad5402.png)

E.g. the astro-binding shows the functionality "add link to item..." in the channels list below a channel. For a trigger channel the user assumes that it is possible to add a link to an item. However, the linking will fail because for the new item to be created an error message "there is no profile available for the selected item" appears as soon as the user tries to link it.

As far as I was told, this is due to the fact that trigger channels cannot be linked to an item.

## Expected behavior

Do not show functionalty which must by definition not work for that channel.

## Steps to reproduce

1. Click on "add link to item" below a trigger channel (in the astro-binding's) channel list
2. Configure the item
3. Click on "Link"

## Your environment

runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.50-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 25523656
  totalMemory: 98537472
bindings:
  - astro
  - knx
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1440
    height: 960
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101
    Firefox/91.0
timestamp: 2021-09-12T09:12:39.781Z

**Comment by kaikreuzer** [comment]
> As far as I was told, this is due to the fact that trigger channels cannot be linked to an item.

This is not correct. Trigger channels can be linked to an item, if a suitable profile is available, see also https://github.com/openhab/openhab-webui/issues/886.

**Comment by svenb1234** [comment]
Ok, fair point.

I would have said that in that case there should be a distinction between channels for which a suitable profile exists (shows the "add link to item") and those for which there is no suitable profile (do not show "add link to item").

For "normal" users, that would avoid the risk of trying something which is nt possible. And since knowing which transformation add-on would suit the channel is not trivial, not to mention creating one's own transformation service, I think that might be reasonable.

Does it make sense to assume that advanced users will install the suitable profile before trying to set it up with the channel? If so it would not matter that they are not offered any longer a hint which may lead them to the reason for the link/create item error at the bottom of the link/create dialogue.

Or maybe it is too complex check whether suitable profiles are available. Then I would suggest to improve the hint towards normal users.

For example:
Trigger channels can only be linked to items if a suitable profile/transformation is available. You can either install a Transformation service add-on or use Rules to work with the Trigger Channel without any need to link it to an Item.

**Comment by kaikreuzer** [comment]
I agree that this option should not be shown, if no suitable profile is available. I cannot tell whether the UI can easily check whether this is the case or not. That's probably something @ghys is able to assess.

**Comment by ghys** [comment]
> I would have said that in that case there should be a distinction between channels for which a suitable profile exists (shows the "add link to item") and those for which there is no suitable profile available (do not show "add link to item").

> Then I would suggest to improve the hint towards normal users at the bottom of the link/create item dialogue (at least in case no suitable profile is available).

The former option could be done at the cost of some additional API requests/complexity when opening the channel "accordion", but it's not out of the question. The latter is easier as the compatible profiles are already known in the context of the "add link" page, and it's then only a matter of displaying a message + disabling the "Add link" button instead of showing an error when clicking "Add link".

**Comment by florian-h05** [comment]
Closing this issue as with recent 5.0.0 snapshot (where profile selection has been fixed) it is indeed possible to link an Item to a trigger channel with the correct profile (the UI suggestes/enforces a compatible profile).
