### ISSUE TITLE
Build fails under MacOS on Apple M1 processors

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-webui#1165]
## The problem

Build fails because node.js 12.x is not available for ARM architecture.

## Expected behavior

Build succeeds.

## Steps to reproduce

1. Clone repo on a ARM machine running MacOS BigSur
2. `man clean install`

## Additional information

Solution: Upgrade to NodeJS 16.9.1 (Basic UI build fails with npm error on simple upgrade, Main UI succeeds)

**Comment by ghys** [comment]
Fixed by #1353.
