### ISSUE TITLE
Remove Blockly as an option when GraalVM JavaScript add-on is installed

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1169]
## The problem

The built in Nashorn JavaScript and GraalVM JavaScript add-on are not compatible. When the GraalVM add-on is installed, anything written in Nashorn will break. Since Blockly ends up resolving to Nashorn, that means anything written using Nashorn will also break.

## Your suggestion

Somehow detect when the GraalVM add-on is installed and hide the option to use Blockly.

## Additional information

A number of users, including highly advanced users with years of experience have run into this and related problems when the add-on is installed.

**Comment by ghys** [comment]
#1170 seems to make the Blockly code run in GraalVM, following my remark in https://github.com/openhab/openhab-core/issues/2433#issuecomment-929992683.
This supposes the user has a working GraalVM (in particular, this supposes a manual creation of the `conf/automation/lib/javascript/personal` directory for now, see https://github.com/openhab/openhab-addons/issues/11219).

Then the following works:

![image](https://user-images.githubusercontent.com/2004147/135247055-d0fc46d6-19ad-4438-9458-d5da2a297645.png)

![image](https://user-images.githubusercontent.com/2004147/135247130-5e7b36d0-c08a-409e-9784-2b73a88f7b11.png)

But note the "create text from" blocks that were not required in Nashorn (GraalVM is more strict with method resolution and will only accept java.lang.String in these cases, perhaps adding a few `.toString()` for these blocks wouldn't hurt).

**Comment by rkoshak** [comment]
I think this issue as written can be closed. With the introduction of the new MIMEType for JS Scripting, the two can happily live side-byy-side.
