### ISSUE TITLE
[PaperUI] ColorPicker not woking properly

### ISSUE THREAD

**Issue by t09** [openhab/openhab-webui#119]
Hi guys,

hope this is the right place:
Configured my Fibaro RGBW module - show up in PaperUI - everything fine.

![grafik](https://user-images.githubusercontent.com/15147513/64906312-39f93900-d6e5-11e9-8205-213bb47532fb.png)

Now I turn on the lights by momantary switch or in panel.

![grafik](https://user-images.githubusercontent.com/15147513/64906321-5eedac00-d6e5-11e9-90e1-64b8fab68cf6.png)

The **brightness** slider goes up and runs like the **dimmer** in percentage.
(I don't know why there are 2 sliders for this?)

Now I want to pick a color "blue" but the slider jumps back to original position and nothing changes. The problem seems to be that the **Saturation** slider should jump up to 100% when choosing a color - but its not doing anything.

If I put the **Saturation** slider on 100% the pre-set color will be shown by the led strip (which ist red)

![grafik](https://user-images.githubusercontent.com/15147513/64906373-2d291500-d6e6-11e9-91ea-57ce3ebeb7da.png)

Now I can choose any color and the led strip reacts.
Maybe you can remove this step between by setting **Saturation** to  full if a color is picked.

Thanks in advance and keep up the good work!!

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
