### ISSUE TITLE
Z-Wave Association Settings not displayed and settings of multiple endpoints makes a mess

### ISSUE THREAD

**Issue by robmachab** [openhab/openhab-webui#1194]
Many valid association settings do not work. In this case setting two endpoints into a group that supports five associations.

## Expected behavior

The associations set on the device are 20.1, 20.2   

The UI should show that the two endpoints are set

The Code page should show the associations set

## Steps to reproduce

1. For any group that supports multiple associations select more than one endpoint association.

2. Save.

3. The associations are set and the UI and Code should show the correct set associations.

## Your environment

```runtimeInfo:
  version: 3.2.0.M3
  buildString: Milestone Build
locale: en-GB
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.12
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.50+19-CA
  osName: Linux
  osVersion: 5.10.52-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 21430248
  totalMemory: 194838528
bindings:
  - zigbee
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: en-GB
    languages:
      - en-GB
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1620
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/95.0.4638.54 Safari/537.36
timestamp: 2021-11-03T16:43:59.482Z


```

## Browser console

```txt

```

**Comment by ghys** [comment]
Please provide some screenshots or details.

**Comment by robmachab** [comment]
I thought I had. Post must have failed. Will try to make some new ones but it is also easy to reproduce.

**Comment by robmachab** [comment]
looking in the case statement in the binding the binding expects and array of nodes but it has a fixup for strings.

https://github.com/openhab/org.openhab.binding.zwave/blob/main/src/main/java/org/openhab/binding/zwave/handler/ZWaveThingHandler.java
`          case "group":
                    if (cfg.length < 2) {
                        logger.debug("NODE {}: Association invalid {}", nodeId, configurationParameter.getKey());
                        continue;
                    }

                    Integer groupIndex = Integer.valueOf(cfg[1]);

                    // Get the configuration information.
                    // This should be an array of nodes, and/or nodes and endpoints
                    ArrayList<String> paramValues = new ArrayList<String>();
                    Object parameter = configurationParameter.getValue();
                    if (parameter instanceof List) {
                        paramValues.addAll((List) configurationParameter.getValue());
                    } else if (parameter instanceof String) {
                        String strParam = ((String) parameter).trim();
                        // Some UIs seem to be sending arrays as strings!!!
                        // It's a kludge, but let's try and handle this format...
                        if (strParam.startsWith("[") && strParam.endsWith("]")) {
                            strParam = strParam.substring(1, strParam.length() - 1);

                            if (strParam.contains(",")) {
                                String[] splits = strParam.split(",");
                                for (String split : splits) {
                                    paramValues.add(split.trim());
                                }
                            }
                        } else {
                            paramValues.add(strParam);
                        }
                    }
                    logger.debug("NODE {}: Association {} consolidated to {}", nodeId, groupIndex, paramValues);`

**Comment by robmachab** [comment]
you can see here that while the UI is supposed to be sending node 20 endpoint 1 it is showing node 20 no endpoint.

![image](https://user-images.githubusercontent.com/48614861/140192239-910c1ace-2935-41e7-83a6-c05028cd4e32.png)

**Comment by robmachab** [comment]
If I try to set two endpoints on the same device it looks like it works but when you reinitialise the node.
![image](https://user-images.githubusercontent.com/48614861/140195312-6beb2efe-577e-4d14-8c1d-b90b3b9a8c81.png)
so when you reinitialise or restart you end up with

![image](https://user-images.githubusercontent.com/48614861/140195427-dcc6a03b-687b-4c42-994a-9b9682050024.png)
and
![image](https://user-images.githubusercontent.com/48614861/140195523-8b444e10-191c-459f-9b80-484a8028afb7.png)

**Comment by robmachab** [comment]
I can set it correctly using the PCController application but then things get weird when put back into openHAB.

**Comment by robmachab** [comment]
Do you have any z-wave to test with?

**Comment by ghys** [comment]
> you can see here that while the UI is supposed to be sending node 20 endpoint 1 it is showing node 20 no endpoint.

You're showing the Response tab while the content of the request (what is sent) appears in the Headers tab, under Request payload (at the bottom). 
You should also be looking at the "config" PUT request, NOT the "(thingUID)" one.

If the config is changed by the binding and the response is different that what was sent, then the UI is not at fault.
Especially if the association options are "node_20_1" & "node_20_2" and the API returns "node_20" which isn't a valid option, so it's expected that the control will not have anything selected.

I don't have nodes with multiple endpoints to test.

I think it's better to move it to the Z-Wave repo.

**Comment by robmachab** [comment]
Hi, Is the UI sending a string or an array of nodes?

**Comment by ghys** [comment]
An array.

**Comment by robmachab** [comment]
Many thanks. I will collect some logs and check zniffer for a few other devices. I can see that it is an array that gets to binding so seems unlikely there is an issue between UI and binding. Nothing in the code looks wrong when reading it so possibly bug is in device firmware. Apologies if that is the case.

**Comment by ghys** [comment]
I think it can safely be deemed a Z-Wave problem rather than a problem with the UI. Since apparently the move-bot doesn't work anymore, please feel free to reopen an issue in the Z-Wave binding repo.
