### ISSUE TITLE
Improve logo location for market place bindings

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-webui#1203]
## The problem

The location for the logo/icon for market place items differ from how the regular bindings are rendered.

The selection page it works good
![image](https://user-images.githubusercontent.com/5871213/141474604-786f6b30-fed1-48ca-887a-8cb03d1a22c6.png)

However, when going to the detail the redering differs
Current rendering
![image](https://user-images.githubusercontent.com/5871213/141474776-8a65f477-33c5-49d3-b6e4-0d556a85af19.png)

desired rendering (as is applicable for normal bindings). The logo appears next to the binding name

![image](https://user-images.githubusercontent.com/5871213/141474701-0ce21930-f475-42a0-b8e6-21d1e2c64bc4.png)

## Your environment

Openhab 3.2M3

**Comment by wborn** [comment]
I think this is already fixed in 3.2.0.M4 with https://github.com/openhab/openhab-webui/pull/1192.

**Comment by marcelrv** [comment]
you're totally right.
