### ISSUE TITLE
[habmin] Z-Wave Network Viewer does not work with multiple networks

### ISSUE THREAD

**Issue by martin67** [openhab/openhab-webui#121]
I have a setup with two Z-wave controllers, running separate networks (one in my house, the other one at my summer house).

When I try to run the Z-Wave Network Viewer in HABmin, the result is just a blank page. The menu item "Device Tools" is there but disabled.

Looking at the Console (running Chrome), I see the following error message:

```
Setting network options                         zwaveNetwork.js:288
Setting network options DONE                    angular.js:13920
Error: Cannot add item: item with id 1 already exists
    at DataSet._addItem (vis.js:6894)
    at DataSet.add (vis.js:6274)
    at NodesHandler.setData (vis.js:29620)
    at Network.setData (vis.js:28868)
    at new Network (vis.js:28675)
    at angular-vis.js:136
    at Scope.$digest (angular.js:17524)
    at Scope.$apply (angular.js:17790)
    at angular.js:19621
    at completeOutstandingRequest (angular.js:5964)
message                                         eventModel.js:21 message
```
My guess would be that it tries to add the second controller (id 1 as well) to the DataSet.

I'm running 2.5.0M3 and tested it with Chrome.

**Comment by Mr-Eskildsen** [comment]
I can confirm this behaviour running 2.5.0M5 and tested with Chrome

**Comment by lolodomo** [comment]
habmin UI was removed in OH3.
