### ISSUE TITLE
Thing Creation forcing to choose attributes not accepted by homematic config

### ISSUE THREAD

**Issue by MaximilianHerrmann** [openhab/openhab-webui#1224]
When I try to add manually a HG-HM-CC-TC wall mounted thermo controller [https://ref.homegear.eu/device.html?directory=HomeMatic+BidCoS&file=rf_cc_tc_le_v1_9.xml&familyLink=homematicbidcos&name=HM-CC-TC](url)
the ui requests inputs between 10 and 1440 for the timeouts (see link above). So I need to manually change all values from 0 to a value between 10 and 1440.

The value 0 i guess represents not set, but is not selectable. 

When adding the device via auto scan, I can add it and the 0 values are accepted by openhub. Unfortunately I cannot save any changes to the item, since it says I have to change all timeout values set to 0 to something in between 10 and 1440 (which represents min of a day for the time schedule programming of the homamatic thermocontroller)

<!--

Unfortunately I could not upload a screen shot here.

## Expected behavior

I would expect, that the item can be added with the default values and the 0 would also be accepted by openhab.

## Steps to reproduce

A HG-HM-CC-TC is needed. Try to do the steps described above.

1. 

## Your environment

untimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.13
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.52+13-CA
  osName: Linux
  osVersion: 5.10.78-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 64200296
  totalMemory: 247332864
bindings:
  - astro
  - deconz
  - homematic
  - hue
  - openweathermap
  - telegram
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1.25
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1536
    height: 864
    colorDepth: 32
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
timestamp: 2021-12-10T08:42:55.744Z

UID: homematic:HG-HM-CC-TC:a5232d2af4:GEQ0162133
label: Heizung Wandthermostat Büro
thingTypeUID: homematic:HG-HM-CC-TC
configuration:
  HMP_2_TEMPERATUR_FRIDAY_12: 20
  HMP_2_TEMPERATUR_FRIDAY_13: 20
  HMP_0_BUTTON_LOCK: false
  HMP_2_TEMPERATUR_FRIDAY_14: 20
  HMP_2_TEMPERATUR_FRIDAY_15: 20
  HMP_2_TEMPERATUR_THURSDAY_19: 20
  HMP_2_TEMPERATUR_MONDAY_19: 20
  HMP_2_TEMPERATUR_FRIDAY_10: 20
  HMP_2_TEMPERATUR_MONDAY_17: 20
  HMP_2_TEMPERATUR_FRIDAY_11: 20
  HMP_2_TEMPERATUR_MONDAY_18: 20
  HMP_2_TEMPERATUR_MONDAY_15: 20
  HMP_2_TEMPERATUR_MONDAY_16: 20
  HMP_2_TEMPERATUR_MONDAY_13: 20
  HMP_2_TEMPERATUR_THURSDAY_9: 20
  HMP_2_TEMPERATUR_MONDAY_14: 20
  HMP_2_TEMPERATUR_THURSDAY_8: 20
  HMP_2_TEMPERATUR_FRIDAY_16: 20
  HMP_2_TEMPERATUR_MONDAY_11: 20
  HMP_2_TEMPERATUR_FRIDAY_17: 20
  HMP_2_TEMPERATUR_MONDAY_12: 20
  HMP_2_TEMPERATUR_FRIDAY_18: 20
  HMP_2_TEMPERATUR_FRIDAY_19: 20
  HMP_2_TEMPERATUR_MONDAY_10: 20
  HMP_2_TEMPERATUR_PARTY_VALUE: 20
  HMP_2_TEMPERATUR_THURSDAY_21: 20
  HMP_2_DECALCIFICATION_HOUR: 11
  HMP_2_TEMPERATUR_THURSDAY_20: 20
  HMP_2_TEMPERATUR_THURSDAY_24: 20
  HMP_2_TEMPERATUR_THURSDAY_23: 20
  HMP_2_TEMPERATUR_THURSDAY_22: 20
  HMP_2_TEMPERATUR_FRIDAY_23: 20
  HMP_2_TEMPERATUR_TUESDAY_3: 21
  HMP_2_TEMPERATUR_FRIDAY_24: 20
  HMP_2_TEMPERATUR_TUESDAY_4: 17
  HMP_2_TEMPERATUR_TUESDAY_5: 20
  HMP_2_TIMEOUT_TUESDAY_19: 1440
  HMP_2_TEMPERATUR_TUESDAY_6: 20
  HMP_2_TIMEOUT_TUESDAY_18: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_8: 20
  HMP_2_TEMPERATUR_WEDNESDAY_9: 20
  HMP_2_TEMPERATUR_FRIDAY_20: 20
  HMP_2_TEMPERATUR_FRIDAY_21: 20
  HMP_2_TEMPERATUR_WEDNESDAY_6: 20
  HMP_2_TEMPERATUR_TUESDAY_1: 17
  HMP_2_TEMPERATUR_FRIDAY_22: 20
  HMP_2_TEMPERATUR_WEDNESDAY_7: 20
  HMP_2_TEMPERATUR_TUESDAY_2: 21
  HMP_2_TEMPERATUR_SATURDAY_15: 20
  HMP_2_TIMEOUT_TUESDAY_13: 1440
  HMP_2_TEMPERATUR_SATURDAY_14: 20
  HMP_2_TIMEOUT_TUESDAY_12: 1440
  HMP_2_TEMPERATUR_SATURDAY_17: 20
  HMP_2_TIMEOUT_TUESDAY_11: 1440
  HMP_2_TEMPERATUR_MONDAY_24: 20
  HMP_2_TEMPERATUR_SATURDAY_16: 20
  HMP_2_MODE_TEMPERATUR_VALVE: AUTO
  HMP_2_TIMEOUT_TUESDAY_10: 1440
  HMP_2_TEMPERATUR_SATURDAY_11: 20
  HMP_2_TEMPERATUR_TUESDAY_7: 20
  HMP_2_TIMEOUT_TUESDAY_17: 1440
  HMP_2_TEMPERATUR_MONDAY_22: 20
  HMP_2_TEMPERATUR_SATURDAY_10: 20
  HMP_2_TEMPERATUR_TUESDAY_8: 20
  HMP_2_TIMEOUT_TUESDAY_16: 1440
  HMP_2_TEMPERATUR_MONDAY_23: 20
  HMP_2_TEMPERATUR_SATURDAY_13: 20
  HMP_2_TEMPERATUR_TUESDAY_9: 20
  HMP_2_TEMPERATUR_MONDAY_20: 20
  HMP_2_TIMEOUT_TUESDAY_15: 1440
  HMP_2_TEMPERATUR_SATURDAY_12: 20
  HMP_2_TEMPERATUR_MONDAY_21: 20
  HMP_2_TIMEOUT_TUESDAY_14: 1440
  HMP_2_TEMPERATUR_THURSDAY_3: 21
  HMP_-1_ROAMING: false
  HMP_2_TEMPERATUR_THURSDAY_2: 21
  HMP_2_TEMPERATUR_THURSDAY_1: 17
  HMP_2_TEMPERATUR_THURSDAY_7: 20
  HMP_2_TEMPERATUR_THURSDAY_6: 20
  HMP_2_TEMPERATUR_THURSDAY_5: 20
  HMP_2_TEMPERATUR_THURSDAY_4: 17
  HMP_0_ROAMING: false
  HMP_2_TIMEOUT_WEDNESDAY_10: 1440
  HMP_2_TEMPERATUR_SATURDAY_20: 20
  HMP_2_TIMEOUT_THURSDAY_4: 1440
  HMP_2_TIMEOUT_TUESDAY_24: 1440
  HMP_2_TIMEOUT_WEDNESDAY_17: 1440
  HMP_2_TIMEOUT_THURSDAY_5: 1440
  HMP_2_TIMEOUT_TUESDAY_23: 1440
  HMP_2_TIMEOUT_WEDNESDAY_18: 1440
  HMP_2_TIMEOUT_THURSDAY_2: 720
  HMP_2_TIMEOUT_TUESDAY_22: 1440
  HMP_2_TIMEOUT_WEDNESDAY_15: 1440
  HMP_2_TIMEOUT_THURSDAY_3: 1380
  HMP_2_TIMEOUT_TUESDAY_21: 0
  HMP_2_TIMEOUT_WEDNESDAY_16: 1440
  HMP_2_TEMPERATUR_SATURDAY_22: 20
  HMP_2_TIMEOUT_WEDNESDAY_13: 1440
  HMP_2_TIMEOUT_THURSDAY_1: 360
  HMP_2_TEMPERATUR_SATURDAY_21: 20
  HMP_2_TIMEOUT_WEDNESDAY_14: 1440
  HMP_2_TEMPERATUR_SATURDAY_24: 20
  HMP_2_TIMEOUT_WEDNESDAY_11: 1440
  HMP_2_TEMPERATUR_SATURDAY_23: 20
  HMP_2_TIMEOUT_WEDNESDAY_12: 0
  HMP_2_TIMEOUT_THURSDAY_8: 0
  HMP_2_TEMPERATUR_SATURDAY_19: 20
  HMP_2_TIMEOUT_TUESDAY_20: 1440
  HMP_2_TIMEOUT_THURSDAY_9: 1440
  HMP_2_TEMPERATUR_SATURDAY_18: 20
  HMP_2_TIMEOUT_THURSDAY_6: 1440
  HMP_2_TIMEOUT_WEDNESDAY_19: 1440
  HMP_2_TIMEOUT_THURSDAY_7: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_4: 17
  HMP_2_TEMPERATUR_WEDNESDAY_5: 20
  HMP_2_TEMPERATUR_WEDNESDAY_2: 21
  HMP_2_TEMPERATUR_WEDNESDAY_3: 21
  HMP_2_TEMPERATUR_WEDNESDAY_1: 17
  HMP_2_TIMEOUT_WEDNESDAY_20: 1440
  HMP_2_TIMEOUT_WEDNESDAY_21: 1440
  HMP_2_TIMEOUT_WEDNESDAY_24: 1440
  HMP_2_TIMEOUT_WEDNESDAY_22: 1440
  HMP_2_TIMEOUT_WEDNESDAY_23: 1440
  HMP_2_TEMPERATUR_FRIDAY_2: 21
  HMP_2_TIMEOUT_THURSDAY_11: 1440
  HMP_2_TEMPERATUR_FRIDAY_1: 17
  HMP_2_TIMEOUT_THURSDAY_12: 1440
  HMP_2_TIMEOUT_THURSDAY_10: 1440
  HMP_2_TIMEOUT_THURSDAY_15: 1440
  HMP_2_TIMEOUT_THURSDAY_16: 1440
  HMP_2_TIMEOUT_THURSDAY_13: 1440
  HMP_2_TIMEOUT_THURSDAY_14: 1440
  HMP_2_DISPLAY_TEMPERATUR_UNIT: CELSIUS
  HMP_2_TIMEOUT_THURSDAY_19: 1440
  HMP_2_TIMEOUT_THURSDAY_17: 1440
  HMP_2_TIMEOUT_THURSDAY_18: 1440
  HMP_-1_DISPLAY_BACKLIGHT_TIME: 0s
  HMP_2_TIMEOUT_THURSDAY_22: 1440
  HMP_2_TIMEOUT_THURSDAY_23: 0
  HMP_2_TIMEOUT_THURSDAY_20: 1440
  HMP_2_TIMEOUT_THURSDAY_21: 1440
  HMP_2_TIMEOUT_WEDNESDAY_5: 1440
  HMP_2_PARTY_END_TIME: 0
  HMP_2_TIMEOUT_WEDNESDAY_4: 1440
  HMP_2_TIMEOUT_WEDNESDAY_7: 1440
  HMP_2_TIMEOUT_THURSDAY_24: 1440
  HMP_2_TIMEOUT_WEDNESDAY_6: 1440
  HMP_2_TIMEOUT_WEDNESDAY_1: 360
  HMP_2_TIMEOUT_WEDNESDAY_3: 1380
  HMP_2_TIMEOUT_WEDNESDAY_2: 720
  HMP_2_TIMEOUT_FRIDAY_8: 1440
  HMP_2_TIMEOUT_FRIDAY_7: 1440
  HMP_2_TIMEOUT_FRIDAY_6: 1440
  HMP_2_MODE_TEMPERATUR_REGULATOR: MANUAL
  HMP_2_TIMEOUT_FRIDAY_5: 1440
  HMP_2_TIMEOUT_WEDNESDAY_9: 1440
  HMP_2_TIMEOUT_FRIDAY_4: 1440
  HMP_2_TIMEOUT_WEDNESDAY_8: 1440
  HMP_2_TIMEOUT_FRIDAY_3: 1380
  HMP_2_TIMEOUT_FRIDAY_2: 720
  HMP_2_TIMEOUT_FRIDAY_1: 360
  HMP_2_TEMPERATUR_FRIDAY_6: 20
  HMP_2_TEMPERATUR_FRIDAY_5: 20
  HMP_2_TEMPERATUR_FRIDAY_4: 17
  HMP_2_TEMPERATUR_FRIDAY_3: 21
  HMP_2_TEMPERATUR_FRIDAY_9: 20
  HMP_2_TEMPERATUR_FRIDAY_8: 20
  HMP_2_TEMPERATUR_FRIDAY_7: 20
  HMP_2_TIMEOUT_FRIDAY_9: 1440
  HMP_2_DECALCIFICATION_MINUTE: 0
  HMP_0_DISPLAY_BACKLIGHT_TIME: 0s
  HMP_2_TIMEOUT_TUESDAY_9: 1440
  HMP_2_TEMPERATUR_MONDAY_3: 21
  HMP_2_TIMEOUT_FRIDAY_21: 1440
  HMP_2_TIMEOUT_TUESDAY_2: 720
  HMP_2_TEMPERATUR_MONDAY_2: 21
  HMP_2_TIMEOUT_FRIDAY_22: 1440
  HMP_2_TIMEOUT_TUESDAY_1: 360
  HMP_2_TEMPERATUR_MONDAY_5: 20
  HMP_2_TIMEOUT_FRIDAY_23: 1440
  HMP_2_TIMEOUT_TUESDAY_4: 1440
  HMP_2_TEMPERATUR_SUNDAY_1: 17
  HMP_2_TEMPERATUR_MONDAY_4: 17
  HMP_2_TIMEOUT_FRIDAY_24: 1440
  HMP_2_TIMEOUT_TUESDAY_3: 1380
  HMP_2_TEMPERATUR_MONDAY_7: 20
  HMP_2_TIMEOUT_TUESDAY_6: 0
  HMP_2_TEMPERATUR_MONDAY_6: 20
  HMP_2_TIMEOUT_TUESDAY_5: 1440
  HMP_2_TEMPERATUR_MONDAY_9: 20
  HMP_2_TIMEOUT_TUESDAY_8: 1440
  HMP_2_TEMPERATUR_MONDAY_8: 20
  HMP_2_TIMEOUT_TUESDAY_7: 1440
  HMP_2_TIMEOUT_SUNDAY_1: 360
  HMP_2_TEMPERATUR_SUNDAY_7: 20
  HMP_2_TEMPERATUR_SUNDAY_6: 20
  HMP_2_TIMEOUT_SUNDAY_3: 1380
  HMP_2_TEMPERATUR_SUNDAY_9: 20
  HMP_2_TIMEOUT_SUNDAY_2: 720
  HMP_2_TEMPERATUR_SUNDAY_8: 20
  HMP_2_TIMEOUT_SUNDAY_5: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_22: 20
  HMP_2_TEMPERATUR_SUNDAY_3: 21
  HMP_2_TIMEOUT_SUNDAY_4: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_23: 20
  HMP_2_TEMPERATUR_SUNDAY_2: 21
  HMP_2_TEMPERATUR_WEDNESDAY_20: 20
  HMP_2_TIMEOUT_SUNDAY_7: 1440
  HMP_2_TEMPERATUR_MONDAY_1: 17
  HMP_2_TEMPERATUR_SUNDAY_5: 20
  HMP_2_TEMPERATUR_WEDNESDAY_21: 20
  HMP_2_TIMEOUT_SUNDAY_6: 1440
  HMP_2_TEMPERATUR_SUNDAY_4: 17
  HMP_2_TIMEOUT_SUNDAY_9: 0
  HMP_2_TIMEOUT_SUNDAY_8: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_24: 20
  HMP_2_TIMEOUT_MONDAY_5: 1440
  HMP_2_TEMPERATUR_SATURDAY_8: 20
  HMP_2_TIMEOUT_MONDAY_4: 1440
  HMP_2_TEMPERATUR_SATURDAY_7: 20
  HMP_2_TIMEOUT_MONDAY_7: 1440
  HMP_2_TEMPERATUR_SATURDAY_6: 20
  HMP_2_TIMEOUT_MONDAY_6: 1440
  HMP_2_TEMPERATUR_SATURDAY_5: 20
  HMP_2_TIMEOUT_MONDAY_1: 360
  HMP_2_TEMPERATUR_SATURDAY_4: 17
  HMP_2_TEMPERATUR_SATURDAY_3: 21
  HMP_2_TIMEOUT_MONDAY_3: 1380
  HMP_2_TEMPERATUR_SATURDAY_2: 21
  HMP_2_TIMEOUT_MONDAY_2: 720
  HMP_2_TEMPERATUR_SATURDAY_1: 17
  HMP_2_TIMEOUT_MONDAY_9: 1440
  HMP_2_TIMEOUT_MONDAY_8: 1440
  HMP_2_TEMPERATUR_WEDNESDAY_11: 20
  HMP_2_TEMPERATUR_WEDNESDAY_12: 20
  HMP_2_TEMPERATUR_WEDNESDAY_10: 20
  HMP_2_TEMPERATUR_WEDNESDAY_15: 20
  HMP_2_TEMPERATUR_WEDNESDAY_16: 20
  HMP_2_TEMPERATUR_WEDNESDAY_13: 20
  HMP_2_TEMPERATUR_WEDNESDAY_14: 20
  HMP_0_DISPLAY_BACKLIGHT_MODE: OFF
  HMP_2_TEMPERATUR_WEDNESDAY_19: 20
  HMP_2_TEMPERATUR_WEDNESDAY_17: 20
  HMP_2_TEMPERATUR_WEDNESDAY_18: 20
  HMP_2_TEMPERATUR_LOWERING_VALUE: 17
  HMP_-1_DISPLAY_BACKLIGHT_MODE: OFF
  HMP_2_TIMEOUT_SUNDAY_20: 1440
  HMP_2_TIMEOUT_SUNDAY_21: 1440
  HMP_2_TIMEOUT_MONDAY_10: 1440
  HMP_2_TIMEOUT_MONDAY_14: 1440
  HMP_2_TIMEOUT_MONDAY_13: 1440
  HMP_2_TIMEOUT_MONDAY_12: 1440
  HMP_2_TIMEOUT_SATURDAY_11: 1440
  HMP_2_TIMEOUT_MONDAY_11: 1440
  HMP_2_TIMEOUT_SATURDAY_10: 1440
  HMP_2_TIMEOUT_SUNDAY_22: 1440
  HMP_2_TIMEOUT_MONDAY_18: 1440
  HMP_2_TIMEOUT_SUNDAY_23: 1440
  HMP_2_TIMEOUT_MONDAY_17: 1440
  HMP_2_TIMEOUT_SUNDAY_24: 0
  HMP_2_TIMEOUT_MONDAY_16: 1440
  HMP_2_TIMEOUT_MONDAY_15: 0
  HMP_2_TIMEOUT_SATURDAY_17: 1440
  HMP_2_TIMEOUT_SATURDAY_16: 1440
  HMP_2_TIMEOUT_SATURDAY_19: 1440
  HMP_2_TIMEOUT_MONDAY_19: 1440
  HMP_2_TIMEOUT_SATURDAY_18: 0
  HMP_2_TIMEOUT_SATURDAY_13: 1440
  HMP_2_TIMEOUT_SATURDAY_12: 1440
  HMP_2_TIMEOUT_SATURDAY_15: 1440
  HMP_2_TIMEOUT_SATURDAY_14: 1440
  HMP_2_DECALCIFICATION_DAY: SATURDAY
  HMP_2_TIMEOUT_SUNDAY_10: 1440
  HMP_2_TIMEOUT_MONDAY_21: 1440
  HMP_2_TIMEOUT_MONDAY_20: 1440
  HMP_2_TEMPERATUR_COMFORT_VALUE: 21
  HMP_2_TIMEOUT_SUNDAY_15: 1440
  HMP_2_TIMEOUT_SATURDAY_20: 1440
  HMP_2_TIMEOUT_SUNDAY_16: 1440
  HMP_2_TIMEOUT_MONDAY_24: 1440
  HMP_2_DISPLAY_TEMPERATUR_HUMIDITY_CHANGE: TEMPERATUR_AND_HUMIDITY
  HMP_2_TIMEOUT_SUNDAY_17: 1440
  HMP_2_TIMEOUT_MONDAY_23: 1440
  HMP_2_TIMEOUT_SATURDAY_22: 1440
  HMP_2_TIMEOUT_SUNDAY_18: 1440
  HMP_2_TIMEOUT_MONDAY_22: 1440
  HMP_2_TIMEOUT_SATURDAY_21: 1440
  HMP_2_TIMEOUT_SUNDAY_11: 1440
  HMP_2_TIMEOUT_SUNDAY_12: 1440
  HMP_2_TIMEOUT_SUNDAY_13: 1440
  HMP_2_TIMEOUT_SUNDAY_14: 1440
  HMP_2_TIMEOUT_SUNDAY_19: 1440
  HMP_2_TIMEOUT_SATURDAY_24: 1440
  HMP_2_TIMEOUT_SATURDAY_23: 1440
  HMP_-1_BUTTON_LOCK: false
  HMP_2_TIMEOUT_SATURDAY_9: 1440
  HMP_2_TIMEOUT_SATURDAY_7: 1440
  HMP_2_TIMEOUT_SATURDAY_8: 1440
  HMP_2_TEMPERATUR_SUNDAY_20: 20
  HMP_2_TIMEOUT_SATURDAY_1: 360
  HMP_2_TEMPERATUR_SUNDAY_21: 20
  HMP_2_TIMEOUT_SATURDAY_2: 720
  HMP_2_TEMPERATUR_SUNDAY_22: 20
  HMP_2_TEMPERATUR_SUNDAY_23: 20
  HMP_2_TEMPERATUR_SUNDAY_24: 20
  HMP_2_TIMEOUT_SATURDAY_5: 1440
  HMP_2_TIMEOUT_SATURDAY_6: 1440
  HMP_2_TIMEOUT_SATURDAY_3: 0
  HMP_2_TIMEOUT_SATURDAY_4: 1440
  HMP_2_DISPLAY_TEMPERATUR_INFORMATION: ACTUAL_VALUE
  HMP_2_TEMPERATUR_SUNDAY_10: 20
  HMP_2_TEMPERATUR_SUNDAY_11: 20
  HMP_2_TEMPERATUR_SUNDAY_12: 20
  HMP_2_TEMPERATUR_SUNDAY_13: 20
  HMP_2_TEMPERATUR_SUNDAY_14: 20
  HMP_2_TEMPERATUR_SUNDAY_15: 20
  HMP_2_TEMPERATUR_SUNDAY_16: 20
  HMP_2_TEMPERATUR_SUNDAY_17: 20
  HMP_2_TEMPERATUR_SUNDAY_18: 20
  HMP_2_TEMPERATUR_SUNDAY_19: 20
  HMP_2_TEMPERATUR_TUESDAY_10: 20
  HMP_2_TEMPERATUR_TUESDAY_11: 20
  HMP_2_TEMPERATUR_TUESDAY_12: 20
  HMP_2_TEMPERATUR_TUESDAY_13: 20
  HMP_2_TEMPERATUR_TUESDAY_14: 20
  HMP_2_TEMPERATUR_TUESDAY_15: 20
  HMP_2_TEMPERATUR_TUESDAY_16: 20
  HMP_2_TEMPERATUR_TUESDAY_17: 20
  HMP_2_TEMPERATUR_TUESDAY_18: 20
  HMP_2_TEMPERATUR_TUESDAY_19: 20
  HMP_2_TEMPERATUR_TUESDAY_20: 20
  HMP_2_TEMPERATUR_TUESDAY_21: 20
  HMP_2_TEMPERATUR_SATURDAY_9: 20
  HMP_2_TEMPERATUR_TUESDAY_22: 20
  HMP_2_TEMPERATUR_TUESDAY_23: 20
  HMP_2_TIMEOUT_FRIDAY_18: 1440
  HMP_2_TEMPERATUR_TUESDAY_24: 20
  HMP_2_TIMEOUT_FRIDAY_19: 1440
  HMP_2_TIMEOUT_FRIDAY_10: 1440
  HMP_2_TIMEOUT_FRIDAY_11: 1440
  HMP_2_TIMEOUT_FRIDAY_12: 1440
  HMP_2_TIMEOUT_FRIDAY_13: 1440
  HMP_2_TIMEOUT_FRIDAY_14: 0
  HMP_2_TIMEOUT_FRIDAY_15: 1440
  HMP_2_TIMEOUT_FRIDAY_16: 1440
  HMP_2_TIMEOUT_FRIDAY_17: 1440
  HMP_2_TEMPERATUR_THURSDAY_10: 20
  HMP_2_TIMEOUT_FRIDAY_20: 1440
  HMP_2_TEMPERATUR_THURSDAY_14: 20
  HMP_2_TEMPERATUR_THURSDAY_13: 20
  HMP_2_TEMPERATUR_THURSDAY_12: 20
  HMP_2_TEMPERATUR_THURSDAY_11: 20
  HMP_2_TEMPERATUR_THURSDAY_18: 20
  HMP_2_TEMPERATUR_THURSDAY_17: 20
  HMP_2_TEMPERATUR_THURSDAY_16: 20
  HMP_2_TEMPERATUR_THURSDAY_15: 20
bridgeUID: homematic:bridge:a5232d2af4

```

## Browser console

<!--
couldn't find this.
-->


## Browser network traffic

<!--
Open the developer tools in your browser, go to the Network tab and paste
screenshots of the network traffic and the details of individual requests that failed.
-->

## Additional information

<!--
Provide any information not pertinent to the above sections that you'd still like to share.
-->

**Comment by ghys** [comment]
This is likely a problem with the homematic binding, not the UI in itself. You should seek help in the community forum first and as a last resort open an issue in openhab-addons.
