### ISSUE TITLE
Missing f7 / material icons in latest builds

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#1242]
I'm still trying to track down this on my end, but i just pulled down the latest build 3.2.0.202112181015 and none of my widgets that use `f7:...` or `material:...` are displaying.  Interesting enough, loading system local images with `oh:...` does work.  I also tested this on a version 3.2.0.202112122130 which i have running for development purposes, and the issue is not there, so either something is wrong with my main system, or this is a recent regression. 

![theme](https://user-images.githubusercontent.com/1903737/146650086-98a40ca1-82e0-47df-9185-fc88feed1928.gif)

## Steps to reproduce

1. 

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by digitaldan** [comment]
And if this helps ....

![image](https://user-images.githubusercontent.com/1903737/146650420-ffff91e1-e2fd-4a55-8635-829457928ecc.png)

There is a `<!---->` where the img tag should be 

On my older dev build, this looks like

![image](https://user-images.githubusercontent.com/1903737/146650447-52954c12-127b-41b3-82a0-c17fc848f857.png)

**Comment by digitaldan** [comment]
I can confirm that reverting #1233 fixes this issue for me.

**Comment by ghys** [comment]
Yikes. Clearly a regression by #1233. Thanks for reporting this in time 😅

**Comment by ghys** [comment]
@digitaldan can you easily try with `:style="(config) ? config.style : null"` instead of `:style="config.style"` in `oh-icon.vue` lines 12 & 19?
I believe this is why it fails to render in some cases, `config` is not necessarily defined...
This would allow to keep #1183 solved.

**Comment by digitaldan** [comment]
Yes i can confirm that indeed does solve the issue !
