### ISSUE TITLE
Script editor throwing exception when editing existing script

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#1244]
Using build 3.2.0.202112182011 (from today)
In certain cases, editing a rule throws an error and no longer has syntax highlighting/code completion.  This happens when modifying a rule action  by clicking on the rule -> edit module (on action) -> edit script.   This does not happen when clicking directly on "execute a given script", which takes you directly to the script editor (see image below)

![theme](https://user-images.githubusercontent.com/1903737/146658071-ca216e2f-1150-458c-b29a-434681ff2aa1.gif)

The error being thrown is:

```javascript
app.js:7 TypeError: Cannot read property 'indexOf' of undefined
    at i.onCmReady (33.app.js:1)
    at qe (app.js:7)
    at i.n (app.js:7)
    at qe (app.js:7)
    at i.e.$emit (app.js:7)
    at initialize (33.app.js:1)
    at i.mounted (33.app.js:1)
    at qe (app.js:7)
    at tn (app.js:7)
    at Object.insert (app.js:7)
```

**Comment by ghys** [comment]
Those are different editors, this is indeed perhaps confusing.
The first is the default editor for TEXT configuration parameters with a "script" context. It doesn't have any info about the "mode" (i.e. language) which is in another parameter. So it's very bare-bones with no syntax highlighting & only basic completion from the existing text.

The full-fledged editor (recognizable by the bottom toolbar with Run Now and the rule's status) is the one that gets launched when you click on the action module list item outside the small "edit module" icon, and has more features including highlighting and language-aware completion for JS.

That said I believe the exception is new, probably a recent regression again.
