### ISSUE TITLE
[mainui] No way to uninstall bindings if they are removed from the marketplace after installed.

### ISSUE THREAD

**Issue by Skinah** [openhab/openhab-webui#1250]
Using 3.2 Stable build.

## Expected behavior

That any marketplace bindings that are installed, can still be seen and uninstalled from the mainUI, even after the marketplace removes them from being `published`. I removed the 'published' tag from the forum to remove a binding from showing up in the marketplace, after doing this I found the binding can not been seen and hence it can not be uninstalled as the list no longer can display a binding that is not currently in the marketplace. 

## Steps to reproduce

1. Install a binding from the marketplace.
2. Remove the published tag from the forum.
3. Try and find the binding to uninstall it from the main UI and it can not be seen.

**Comment by J-N-K** [comment]
This should be solved with https://github.com/openhab/openhab-core/pull/2607.

**Comment by florian-h05** [comment]
Closing as this was solved by the linked core issue.
