### ISSUE TITLE
[BasicUI] Implement default colour for valuecolor= labelcolor= options.

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-webui#1298]
It is possible to have a sitemap widget show coloured state display text e.g.
` Text item=myItem valuecolor=["red"]`
It is possible to assign dynamic colours by Item state e.g.
` Text item=myItem valuecolor=["X"="blue", "Y"="green", "Z"="red"]`
where the conditions are evaluated until first match.  In case of no match, the default is then black.

` Text item=myItem valuecolor=["X"="blue", "Y"="green", "Z"="red", "yellow"]`
appears to be acceptable sitemap syntax, where we would expect the default no-match colour to be set to yellow.
But this doesn't seem to be implemented in BasicUI, the no-match is shown black.

Untested, but presumed to also apply to similar `labelcolor=`

Not known if this also affects other sitemap based UIs.

**Comment by lolodomo** [comment]
This is simply not a feature imagined for sitemap. This would required to change the sitemap syntax and the OH core framework. I don't thing any UI needs to be updated as the right color is I believe computed by the server.

**Comment by Rossko57** [comment]
Ah, if it comes from the server that makes it all simpler.

I don't really see it as unimaginable.  We can already choose a single color.  We can already choose colors according to true/false conditions.  All this is missing is the function of "anything else" or "no match" condition.

The sitemap parser already does not complain about syntax roughly reading
conditionX=colorA 
else
conditionY=colorB
else
colorC
but the colorC part is just ignored at present.

**Comment by lolodomo** [comment]
@Rossko57 : this is implemented, it was finally very easy.
