### ISSUE TITLE
Sitemap syntax check false positive

### ISSUE THREAD

**Issue by Chasbrot** [openhab/openhab-webui#1299]
## The problem

The syntax check of the sitemap code wrongly identifies my item as "incorrect" code. If I configure it with the design tab it generates the code below, saves it and it works. But if i open the code tab it generates this error and i cannot save anymore. It somehow dosen't like the combination with the mapping and all those bracets and '". And no I cannot change the item, it only works with exactly this code. I have tried many combinations otherwise either the binding cannot interpret it as valid json code or openHAB cannot process the sitemap. This is some strange edge case where both works.

### Error:
Error: Syntax error at line 13 col 94:

          Switch icon="robot" item=DreameF9_ExecuteCommand label="Dreame OG[]" mappings=[action{
                                                                                               ^
Unexpected lbrace token: "{". Instead, I was expecting to see one of the following:

A equals token based on:
    Mapping → MappingCommand ● %equals MappingLabel
    Mappings →  ● Mapping
    WidgetAttrValue → %lbracket _ ● Mappings _ %rbracket
    WidgetAttr → WidgetAttrName ● WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Widget → %lwidget _ Widget$ebnf$3 __ %lbrace __ ● Widgets __ %rbrace
    Widgets → Widgets _ ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _

### Code:
Switch icon="robot" item=DreameF9_ExecuteCommand label="Dreame OG[]" mappings=[action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}="AN",action{'did':'vacuum-stop-sweeping','siid':2,'aiid':2,'in':[]}="AUS",action{"did":"battery-start-charge","siid":3,"aiid":1,"in":[]}'="LADEN"]

### Screenshot:
![image](https://user-images.githubusercontent.com/58513998/152593771-9a2a1995-a674-4bcf-975b-d33f69cd4308.png)

## Expected behavior

No error from the syntax checker

## Steps to reproduce

1. Make a new switch item in a sitemap
2. Configure with the mappings from the screenshot above

## Your environment

Raspbian on Pi3, Kernel 5.10.63
openHAB Release 3.20 via apt

**Comment by Rossko57** [comment]
> mappings=[action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}="AN",

Well yes, this is not an appropriate place to put curly braces in a sitemap.
You'd need to wrap those in string quotes, from `action(` to `[]}`
		`Switch icon="robot" item=DreameF9_ExecuteCommand label="Dreame OG[]" mappings=["action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}"="AN","action{'did':'vacuum-stop-sweeping','siid':2,'aiid':2,'in':[]}"="AUS",'action{"did":"battery-start-charge","siid":3,"aiid":1,"in":[]}'="LADEN"]`

There seems to be some confusion if your Item state contains 'did' or "did" etc.

**Comment by Chasbrot** [comment]
Now i have changed the code to following:
Switch icon="robot" item=DreameF9_ExecuteCommand label="Dreame OG[]" mappings=["action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}"="AN","action{'did':'vacuum-stop-sweeping','siid':2,'aiid':2,'in':[]}"="AUS","action{'did':'battery-start-charge','siid':3,'aiid':1,'in':[]}"="LADEN"]

Now it doesn't generate any errors, but it is strange how this code ever worked.

I don't know how I could miss such a trivial mistake. Thank you!

**Comment by ghys** [comment]
Looks like it's solved then!

**Comment by Chasbrot** [comment]
I have tested it some more and finally found the reason for this strange behavior.

OpenHAB automatically changes the quotes and therefore the code breaks. 

The string inside the mapping (design tab, saved):

_"action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}"=AN_

When i switch to the code tab:

_action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}="AN"_

When i switch back to the design tab: 

_action{'did':'vacuum-start-sweep','siid':2,'aiid':1,'in':[]}=AN_

It generates code it doesn't accept. The first part has to have quotes as mentioned by Rossko57 above.

It removes the quotes from the first part and always adds them at the second. When I correct it inside the code tab, save! and go back, it doesn't update in the mapping entry and if i switch back it changed the code again. 

It only works if you correctly enter it in the code tab, save it and never ever open the design tab again.

It was so hard to diagnose because everytime i changed something and switched tabs, it silently changed the code and i didn't know why it wasn't working.
