### ISSUE TITLE
Tabs on Android device very hard to switch

### ISSUE THREAD

**Issue by s-pw** [openhab/openhab-webui#1315]
## The problem
While taping on tab the UI most of the time UI isn't recognizing the input. I discovered that you have to keep the tap perfectly steady so there it is not recognized as a swipe. The bigger the screen the harder it gets, on a 10" tablet with a stylus, it takes about 5 tries to switch the tab.

## Expected behavior
The tab is changed regardless if there was any touchmove event while taping.

## Steps to reproduce

1. Open https://demo.openhab.org/ on any touch screen device
2. Set theme to dark Android
3. Move finger slightly when taping on a tab

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by florian-h05** [comment]
I’ve tried to open apps from the Home Screen of Android Tablets and iPads when swiping a bit with my finger, and the both OSs recognise this as a swipe and don’t open the app. Same behaviour with Apple Pencil: I sometimes need three or more tries to open an app from the Home Screen.

So this is a touch sensitivity problem of the OS, and nothing that openHAB UI can influence. Therefore I’ll close this issue.
