### ISSUE TITLE
Securing openhan ui [reverse proxy]

### ISSUE THREAD

**Issue by reinethernal** [openhab/openhab-webui#133]
Made all steps described [here](https://www.openhab.org/docs/installation/security.html#running-openhab-behind-a-reverse-proxy), but openhab still accessible by typing externalip:8080 or my.openhab2server.com:8080

**Comment by bwosborne2** [comment]
In the file /etc/default/openhab2 set the line OPENHAB_HTTP_ADDRESS=127.0.0.1 assuming your reverse proxy is on the same server as openHAB.

**Comment by florian-h05** [comment]
See https://www.openhab.org/docs/installation/security.html#authentication-and-access-control.
