### ISSUE TITLE
Allow changing add-on log-levels

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-webui#1351]
## The problem

Add-on logger levels can't be changed from the UI. See openhab/openhab-webui#1376. Core support was added in https://github.com/openhab/openhab-core/pull/2772.

## Your suggestion

<img width="1176" alt="Bildschirmfoto 2022-04-10 um 13 30 56" src="https://user-images.githubusercontent.com/5159123/162616375-757b4a4a-5009-4376-b717-11f01328370e.png">

## Additional information

This was done by changing `addon-details.vue`

```
              <div class="addon-header-actions">
                <f7-preloader v-if="isPending(addon)" color="blue" />
                <f7-button v-else-if="addon.installed" class="install-button" text="Remove" color="red" round small fill @click="openAddonPopup" />
                <f7-button v-else class="install-button" :text="installableAddon(addon) ? 'Install' : 'Add'" color="blue" round small fill @click="openAddonPopup" />
                <f7-link v-if="!isPending(addon) && bindingInfo && bindingInfo.configDescriptionURI" icon-f7="gears" tooltip="Configure Binding" color="blue" :href="'/settings/addons/' + bindingInfo.id + '/config'" round small />
                <select v-if="addon.installed" class="button button-round button-fill color-lime">
                  <option value="TRACE">
                    Log: TRACE
                  </option>
                  <option value="DEBUG">
                    Log: DEBUG
                  </option>
                  <option value="INFO">
                    Log: INFO
                  </option>
                  <option value="WARN">
                    Log: WARN
                  </option>
                  <option value="ERROR">
                    Log: ERROR
                  </option>
                </select>
              </div>
```

I'm pretty sure this is not the correct way to do it, but I have no idea what is the correct way. Also functionality is missing, that's why I didn't make a PR.

**Comment by ghys** [comment]
I would rather (re) use the dedicated page to configure bindings and generalize it to all add-ons.
On that page you would then have both the log level configuration and the eventual binding parameters, if any.
It would also be nice to have a SSE/websocket endpoint to stream the related logs (if at all possible), which could be shown on this page as well.

**Comment by mherwege** [comment]
@J-N-K That’s indeed also what I was trying to achieve.

I am aware you can configure marketplace bindings from the add a thing page.

Don’t just focus on bindings. There are other types of add-ons, and the logger level and configuration should ideally be done in the same way. The addons Rest end-point could work for all of them, but looking at the underlying code, it will probably indeed require braking changes.

**Comment by J-N-K** [comment]
It should work out-of-the-box for all distribution add-ons, no matter what type they are:

```
{
    "id": "voice-porcupineks",
    "label": "Porcupine Keyword Spotter",
    "version": "3.3.0.SNAPSHOT",
    "compatible": true,
    "contentType": "application/vnd.openhab.feature;type=karaf",
    "link": "https://www.openhab.org/addons/voice/porcupineks/",
    "author": "openHAB",
    "verifiedAuthor": true,
    "installed": false,
    "type": "voice",
    "configDescriptionURI": "",
    "keywords": "",
    "countries": "",
    "connection": "",
    "properties": {},
    "loggerPackages": [
      "org.openhab.voice.porcupineks"
    ]
  },
```

**Comment by mhilbush** [comment]
@J-N-K @ghys I'm a bit confused by this. In recent snapshots (3299 in my case), I'm no longer seeing the binding config. All I see is the option to set the log level. It was working in 3292.

https://community.openhab.org/t/binding-configuration-missing-in-recent-4-0-0-builds/144118
