### ISSUE TITLE
Recursive group membership ?

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-webui#1360]
using OH3.0.0, I can declare a group to be part of itself. I guess its not intended.
Here gGarage is part of gGarage. 

![grafik](https://user-images.githubusercontent.com/33855380/104020513-a42ccb80-51bd-11eb-8145-2676633e0ca8.png)

**Comment by florian-h05** [comment]
I've tried to reproduce on openHAB 4.0.0, it is solved:

When trying to make a group member of itself, a alert pops up and says: `Cannot add this group as a member of itself`.
