### ISSUE TITLE
Schedule calendar display is off by one day

### ISSUE THREAD

**Issue by DeanCording** [openhab/openhab-webui#1373]
In Openhab v3.0 M2, I have created a schedule rule to trigger on 05:50 every Monday to Friday:

    triggers:
      - id: "1"
        configuration:
          cronExpression: 0 50 5 ? * MON,TUE,WED,THU,FRI *
        type: timer.GenericCronTrigger`

In the schedule calendar display, it is shown on Tuesday to Saturday

![Schedule](https://user-images.githubusercontent.com/251170/98869177-197d6800-24bd-11eb-8cf0-74da60cf25d9.png)

**Comment by ghys** [comment]
Since https://github.com/openhab/openhab-core/pull/2125 the occurrences are computed server-side, so time zone issues have probably been resolved. If any remain it should probably be fixed in the server-side implementation.
