### ISSUE TITLE
Config appears to be double JSON escaped when set from UI

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-webui#1374]
Not sure if this is core, UI or user error issue.

While developing a serial binding I spotted that I wasn't sending new line characters over the serial interface.

With the following thing defined in configuration it works as I expect, if I send an UP command to the 'serialRollo' channel it sends 'Rollo_UP' followed by a LF to the serial port

```
Thing serialDevice rollershutter [patternMatch=".*"] {
        Channels:
            Type rollershutter : serialRollo [transform="REGEX(Position:([0-9.]*))", up="Rollo_UP\n", down="Rollo_DOWN\n", stop="Rollo_STOP\n"]
            Type switch : roloAt100 [transform="REGEX(s/Position:100/ON/)"]
    }
```
If I configure the thing in the UI and set the channel config parameter 'up' to 'Rollo_UP\n' it sends 'Rollo_UP\n' with no LF.

I'm guessing that its being JSON escaped when sent from the UI and again JSON escaped when stored in the JSON db.

**Comment by ghys** [comment]
Closing as answered, there's nothing we can easily do in the UI. Eventually escape sequences could be interpreted by the binding.
