### ISSUE TITLE
Item with type number:temperature is wrongly formatted in default item widget 

### ISSUE THREAD

**Issue by FSeidinger** [openhab/openhab-webui#1375]
I'm using openHAB 3.0 with docker on a linux host OS.

I've linked a `number:temperature` item via KNX bridge to a heating actor object with DPT 9.002 to shift the nominal value of the room temperature. I've noticed to issues with this configuration

1. The value of the item is a floating point number in degrees celsius. When sending the command `1.5` to the item, the internal state is `1.5 °C`, but the default item widget, e.g. when selecting the item in the semantic model, formats this value as `2`. So the unit is missing and it is only shown as integer (or rounded?). See attached image for details.
1. When sending a command to the item via API, the item gets updated, but no telegram is send to the KNX bus.

![image](https://user-images.githubusercontent.com/4890418/103422212-931e0200-4ba0-11eb-8498-cfb0bb1629c9.png)

As you can see in the next image, the formatting in the item list is correct as floating point and unit.

![image](https://user-images.githubusercontent.com/4890418/103422319-248d7400-4ba1-11eb-82c9-b3fda490cdf5.png)

BTW, how can the unit be changed to Kelvin (K) which is the right unit for DPT 9.002 according the the KNX specification.

**Comment by ghys** [comment]
> I think I recall it was the KNX binding that added a %d pattern to the state description so the displayed state loses the decimals and the unit.

IIRC it has been fixed since. Closing.
