### ISSUE TITLE
User-friendly solution for plug-in debugging

### ISSUE THREAD

**Issue by bgilmer77** [openhab/openhab-webui#1376]
This Issue is prompted by discussion in openhab/openhab-docs#645

Frequently new users to OH do not experience the "happy path" for a number of reasons.  One area that causes issues is understanding add-ons.  The point of this Issue is to request a simple way for end-users to see potentially helpful log output for add-ons without having to have a PhD in Karaf, Javascript, OH2, or RAML, etc...).

Use case -
A new user to OH is having problems with their system.  They do not know they are missing a plugin, or perhaps they have two two networks in their house and mDNS is not working between them.  In any case, OH does not work, and they are "dead in the water" with nowhere to go.

Imagine a debug feature in an OH2 UI (Paper, perhaps), where the user can enter the name of the device and they get a simple result - such as below:

```
> smarthome:debug sonos
Debugging for sonos add-on enabled.

> smarthome:debug sonos
Debugging for sonos add-on disabled.
```

Or perhaps they see the following:
```
>smarthome:debug sonos
Debugging for sonos add-on enabled.
Analyzing logs...
Sonos plugin installed and running.
No Sonos devices found on network.
Analysis complete.
```
This Issue could be interpreted as a big and complex ask.  So a "crawl, walk, run" approach might be appropriate.  In any case, providing users with information they can understand when they are on the "unhappy path" can increase OH2 adoption and lead to a higher WAF (less time spent heads-down trying to get all the promised benefits of home automation delivered).

WDYT?

**Comment by ghys** [comment]
Duplicate of #1351
