### ISSUE TITLE
[mainui] allow editing transformations

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-webui#1378]
*@J-N-K commented on Dec 27, 2020, 9:34 AM UTC:*

Curently it is necessary to create files and edit their content to change or add transformations. Since transformations are a basic feature, they should be editable from the UI.

*This issue was moved by [ghys](https://github.com/ghys) from [openhab/openhab-webui#707](https://github.com/openhab/openhab-webui/issues/707).*

**Comment by florian-h05** [comment]
Implemented since openHAB 4.0.
