### ISSUE TITLE
What happened to habmin?

### ISSUE THREAD

**Issue by bd8392** [openhab/openhab-webui#143]
Hi :-) I was looking for a advanced webui and came to habmin but the GitHub repository and docs seem to be offline...is it still developed? Looks very cool!

Kind regards

**Comment by wborn** [comment]
All openHAB GitHub UI repositories were integrated into this repo (openhab-webui).

So the HABmin code got integrated:
* from: https://github.com/openhab/org.openhab.ui.habmin
* to: https://github.com/openhab/openhab-webui/tree/master/bundles/org.openhab.ui.habmin

Maybe @cdjackson can tell you more about the current state and future plans of HABmin?

Note that a new UI is being developed that should replace and further integrate most of the current UIs.
For more on that see https://github.com/openhab/openhab-webui/issues/24.

**Comment by kaikreuzer** [comment]
FTR: HABmin has been removed from master with https://github.com/openhab/openhab-webui/pull/154 - functionality to be integrated in the new UI.
