### ISSUE TITLE
NotificationAction only available when OpenHAB Cloud Connector is installed

### ISSUE THREAD

**Issue by horde3d** [openhab/openhab-webui#1449]
While the default blockly blocks provide a "send notification to email" block, the code seem to rely on OpenHAB Cloud Connector being installed. Otherwise an error message can be seen in the log:

java.lang.RuntimeException: java.lang.ClassNotFoundException: org.openhab.io.openhabcloud.NotificationAction cannot be found by org.openhab.core.automation.module.script_3.3.0

Tested with OpenHab 3.3 (just updated from 3.2)

I would expect the default blockly blocks to be running out of the box. Otherwise this shouldn't be offered in the editor

**Comment by stefan-hoehn** [comment]
I would say the documentation clearly says that it is not using the mail functionality but the openHAB cloud:

https://www.openhab.org/docs/configuration/blockly/rules-blockly-notifications.html#notification-blocks

There is hardly an easy way that the blockly editor would know if the openHAB Cloud Connector was installed (at least the effort is most likely so high that it has no relation to the outcome). I think the documentation should be sufficient for that.

**Comment by ghys** [comment]
> There is hardly an easy way that the blockly editor would know if the openHAB Cloud Connector was installed (at least the effort is most likely so high that it has no relation to the outcome). I think the documentation should be sufficient for that.

Agreed. After all the cloud notification actions are documented in the main docs (https://www.openhab.org/docs/configuration/actions.html#cloud-notification-actions) and there's no mention either that they need to be configured first (add-on installed, cloud service working, user account set up) as it's all kind of implied.

Such a mention could be made in the blocks' tooltips, if really needed.

**Comment by horde3d** [comment]
I can understand your opinion. When I played with the blockly things, I would have guessed that something like https://community.openhab.org/t/mail-actions/138423 would be available out of the box and not only the cloud connector block.

**Comment by stefan-hoehn** [comment]
@horde3d Volker, I have added a note to the notification blocks' tooltip: "(requires openHAB Cloud Connector)". Do you mind closing the issue then?

**Comment by horde3d** [comment]
Sure thanks.
