### ISSUE TITLE
[Paper UI] Stale rule instances displayed after reloading JSR223 Python rules file

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-webui#145]
openHAB 2.5 MS 5

When reloading NGRE JSR223 Python rules, Paper UI will show stale rules (from before reloading the rules file) as well as live rules (currently active). Reloading the page in the browser triggers an update and deletes the outdated rules in the rules list.

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
