### ISSUE TITLE
Webpage not updated, when Item expire 

### ISSUE THREAD

**Issue by palsbo** [openhab/openhab-webui#1460]
## The problem

An item (lamp) is activatet by a rule (Pir event). The Pir has an expire of "1s"
Items:
```
Switch pir5 "Pir 5" <motion> {channel="mqtt:topic:rflink:pir5", expire="1s"}

Switch pir6 "Pir 6" <motion> {channel="mqtt:topic:rflink:pir6", expire="1s"}

Switch entre        "Entre"     <light> {channel="mqtt:topic:tasmota:Sonoff4CHPRO_3", expire="45s,command=OFF"}`

```
Sitemaps:

`Switch label="Entrelys" item=entre mappings=[OFF="Slukket",ON="Tændt"]`

Rules:

```
`rule "On Motion Entre ON"

when

    Item pir5 received update or

    Item pir6 received update

then

    sendCommand(entre, ON)

end

`

```
**Problem:**
On item expire, the webui (sitemap) is not updatet. Page refresh is required to se the update.

## Expected behavior

**Web page shuld update to 'OFF' when light goes out. (on expire)**

## Steps to reproduce

1. produce items file, sitemap item and rule as described.

## Your environment

```yaml
Hardware: Synology DS716+II
OS: DSM 7.1-42661 Update 3
Environment: Docker
Openhab verson:  Openhab 3.4.0:snapshot

```

## Browser console

```txt
Webbrowser: Chrome and  Edge teted.

```

## Browser network traffic

low

**Comment by florian-h05** [comment]
Closing as this is stale and there is not enough context (which website? BasicUI?) provided.
If the issue persists with openHAB 4.3.0, please open a new issue for BasicUI.
