### ISSUE TITLE
[Habpanel] Selection of server-side panels does not work on echo show

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-webui#148]
Hi. 
here is an animation that describes the problem: 

https://s5.gifyu.com/images/ezgif.com-video-to-gif63362cfdda55cc7f.gif

I am running OH 2.5m4 on ubuntu and this is an amazon echo show 2nd gen from early 2019. 

All the other buttons and selections seem to work, but not that radio button. 
There is no other browser available on the amazon echo show. 

best regards
PhiL

**Comment by ghys** [comment]
Interesting... Never seen this before. Do you know if it's specific to
habpanel radio buttons, for example does
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio work on
your device?

**Comment by DevSchertler** [comment]
Hey OpenPhil,
I had the same problem. I solved it this way:
In Echo show Save your Configuration as new Panel Config.
After that it is possible to open another :)
best regards
Daniel

**Comment by openPhiL** [comment]
Hi. I can confirm that the workaround works. 

> does [...]radio work on your device

Sorry, I haven't tried that part yet.
