### ISSUE TITLE
[Blockly] Text / Finding Text results in ".indexOf is not a function in <eval>"

### ISSUE THREAD

**Issue by BigGeorgeTx** [openhab/openhab-webui#1488]
## The problem

These blocks / code result in the following error:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/13175983/189236002-2c2a5363-4912-4f74-be5e-5a68d044c3ff.png">
(this is an extract from a longer sequence that I made to isolate the error).
`var CurrentEventTitle;

var logger = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + ctx.ruleUID);

CurrentEventTitle = event.itemState;
logger.info((String(CurrentEventTitle) + String(CurrentEventTitle.indexOf('openHAB') + 1)));
`
This results in this error message:
`2022-09-08 16:00:02.711 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'SetExteriorLightsSchemeFromCalendarTitle' failed: TypeError: CurrentEventTitle.indexOf is not a function in <eval> at line number 7`

## Expected behavior

Although the last computer language I mastered was FORTRAN, I can generally follow code even if I couldn't write it.  I studied the code and it seemed odd that the String function's closing parenthesis was after the indexOf method call instead of after the variable to which it is applied.  So I tried copying the code generated by Blockly to a new rule and moving the parenthesis:
`var CurrentEventTitle;

var logger = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + ctx.ruleUID);

CurrentEventTitle = event.itemState;
logger.info((String(CurrentEventTitle) + String(CurrentEventTitle).indexOf('openHAB') + 1));
`
This code produced the expected result:
`2022-09-08 16:00:02.703 [INFO ] [org.openhab.rule.b548aa61e2         ] - UNDEF-11` 

## Steps to reproduce

1. 

## Your environment

```runtimeInfo:
  version: 3.4.0.M1
  buildString: Milestone Build
locale: en-US
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.16
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.61-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 479916840
  totalMemory: 1021313024
  startLevel: 70
bindings:
  - amazonechocontrol
  - astro
  - denonmarantz
  - harmonyhub
  - icalendar
  - icloud
  - ipcamera
  - mail
  - mqtt
  - myq
  - network
  - omatic
  - openweathermap
  - remoteopenhab
  - tplinksmarthome
  - tuya
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: en-US
    languages:
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1707
    height: 1067
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/105.0.0.0 Safari/537.36
timestamp: 2022-09-08T22:29:43.811Z


```

## Browser console

```txt

```

**Comment by ghys** [comment]
Thanks for the report.
The problem you're facing is that the output type of the "contextual info" block isn't a JavaScript string - it's a Java type reprensenting the state (one implementing https://next.openhab.org/javadoc/latest/org/openhab/core/types/primitivetype). There's no `indexOf` method for those.

If you want to perform string operations on it you should therefore convert it to a proper string first, to do that you can use the mutable "create text with" block adding only one item.

![image](https://user-images.githubusercontent.com/2004147/194140068-05719ad0-f625-4f7c-acb8-a42d1e8d19e1.png)

it will then generate valid code:

```js
currentEventTitle = String(event.itemState);
logger.error((String(currentEventTitle) + String(currentEventTitle.indexOf('openHAB') + 1)));
```

I don't think there's an obvious fix to make in the code (maybe a clarification in the docs), so I'll close the issue hoping the explanation above is enough.

**Comment by BigGeorgeTx** [comment]
Thanks for providing me with a solution that will solve this problem for me.

In an ideal world, blocks would only go together if they were going to work.  But I realize that is a difficult challenge and am happy to have a solution.
