### ISSUE TITLE
[thing-details] Extend special handling of "actions" parameter group to all bindings

### ISSUE THREAD

**Issue by mbronk** [openhab/openhab-webui#1491]
## The problem
Currently, the Thing Details view handles Z-Wave binding special, and presents a list of <b>actions</b> (`<parameter-group name="actions">`) as clickable buttons, with confirmation prompt. 
<img src="https://user-images.githubusercontent.com/2566147/189873931-69cdd00b-0abe-40a8-81f3-a503f2c874ac.png" width="50%">

This behavior is nice and desirable, but **specific to Z-Wave binding** only:

- https://github.com/openhab/openhab-webui/blob/60fd5f3c4636764c1b5908b542f601a95fc6af48/bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue#L374-L378

- https://github.com/openhab/openhab-webui/blob/60fd5f3c4636764c1b5908b542f601a95fc6af48/bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue#L110-L119

## Your suggestion
Make the abovementioned behavior more **generic** (remove hard-code for Z-Wave, allow **other bindings** to use it).

### Exemplary proposal
Use the "action" behavior IFF the following heuristic match is true:
`groupName == 'actions' && groupLabel === 'Actions' && groupDescription === 'Actions' && action.type === 'BOOLEAN'`
^--- The values have been picked to be backwards-compatible with [existing Zwave binding's implementation](https://github.com/openhab/org.openhab.binding.zwave/blob/6fe69d4b2267cf8657e4c437e505e2eb4151a18b/src/main/java/org/openhab/binding/zwave/internal/ZWaveConfigProvider.java#L195). Assumption is these values would never be i18n'ed and we want to avoid extra conditions. 

_Note:_ A bigger (more semantically correct) change may include changing the Configuration Description DSL to include a new parameter group and/or type (say: `action`) and remove the heuristic matching by group/param name. This would be a OH-core change, though and given this Z-Wave hardcode has been around for ~3y now, seems to be an overkill to introduce now IMHO.

### Rationale
It is customary for some devices to include a "_reset to factory default_" functionality. Z-Wave binding's paradigm of showing such one-off "commands" as actions seems appropriate and would create consistent UX.

## Your environment

```yaml
runtimeInfo:
  version: 3.4.0
```

## Additional information
_Disclaimer:_ I'm currently developing a binding which would benefit from this functionality.

**Comment by ghys** [comment]
Hi @mbronk,
this makes perfect sense and would be glad to accept a PR with the implementation.
I had some concerns about "actions" groups not necessarily meant as buttons therefore it was limited to the Z-Wave binding in the original implementation (to emulate functionality from HABmin mostly), but this could certainly be extended.

**Comment by mbronk** [comment]
Hi @ghys,
Thx for the comment. Since this is a very subtle change, I've created a naive PR https://github.com/openhab/openhab-webui/pull/1498 for the changes mentioned above (and added a very basic "support" (extra disclaimer/color) for `verify` param as well).

FYI - I do *not* have a fully-functional Z-Wave setup at this time, so I guess it wouldn't hurt if someone who does, also took a 2nd look as well...

----
_Full disclosure:_ I actually don't even have a full on node/vue dev env, and the changes seemed small enough not to invest in setting everything up. Alas, I have **not** run full set of automated tests _(taking a leap of faith and trusting the CI here, as far as I've seen this should be transparent to them though)_, and made only a rudimentary smoke test proving that the buttons do seem to work on my setup...

Sorry if this seems half-baked. I won't be able to allocate more time to it in near future and figured it is worth submitting as-is. If the PR creates more chaos than it helps - feel free to reject right off the bat.

Cheers!
