### ISSUE TITLE
Change expression parsers

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#1506]
As the community gets more involved in advanced custom widget creation, more and more users are running up against the limitations of the expression-eval library.  In particular, I've seen many issues with users wanting regex expressions or js methods that require functions as parameters.  Expression-eval does not handle either of these two cases.

There's a recent fork of expression-eval, [jse-eval](https://github.com/6utt3rfly/jse-eval/), which adopts the jsep plug-in system which, in turn would allow the addition of regex and arrow plug-ins.  Is it feasible/acceptable to move MainUI from expression-eval to jse-eval?

**Comment by ghys** [comment]
Yes I knew about jse-eval and thought the same thing, but didn't look into whether or not it could be a drop-in replacement for expression-eval (or only minor changes). The goal would be to allow the extra features _without_ breaking any existing expressions, of course.

I think it could work - it's certainly worth looking at.

**Comment by ghys** [comment]
I think it might be fair to ping @6utt3rfly so that they know their work is being considered for inclusion as a replacement of expression-eval, as they might have additional insight.

There's an established ecosystem around these expressions, so it would be unwise to make any breaking change without careful consideration.

**Comment by 6utt3rfly** [comment]
Thanks for the ping @ghys  🙂 . I had originally created the [jse-eval](https://github.com/6utt3rfly/jse-eval) fork, and [PR](https://github.com/donmccurdy/expression-eval/pull/63) to update expression-eval, but after waiting awhile, ended up publishing it as a separate package. I'm happy to help or update things if there are any conflicts between the two packages, but I believe jse-eval should be an easy drop-in replacement. It uses a newer (major) version of `jsep` though, which may cause some breaking changes for certain use cases (see [v1.0.0 release notes](https://github.com/EricSmekens/jsep/releases/tag/v1.0.0)). Even though `jse-eval` doesn't mention an `eval` export like `expression-eval`'s docs, jse-eval kept it for compatibility and added `evaluate` to avoid warnings from lint and other tools about using `eval`.
