### ISSUE TITLE
[PaperUI] not able to remove field, leaves empty string

### ISSUE THREAD

**Issue by cputoaster** [openhab/openhab-webui#153]
OH2.5.0 stable on ubuntu 18.04 LTS

I had a strange problem: For one of my rollershutter shellys using MQTTv2, setting the position would result in working ok if set to anything but 0 or 100 via a slider in a sitemap. 0 or 100 resulted in "(null)" being set instead of an integer.
It worked for all other blinds with the same setup.
After checking, I found that this one MQTT Thing has
```
          "label": "Position",
          "configuration": {
            "properties": {
              "commandTopic": "shellies/shellyswitch-5598F5/roller/0/command/pos",
              "stop": "",
              "stateTopic": "shellies/shellyswitch-5598F5/roller/0/pos",
              "off": "",
              "on": ""
            }
          },
```
in its jsondb, while all others do not have the entries for "stop","off" and "on".

The problem can be fixed by removing these entries from the jsondb, works fine after that. As far as I know, there is nothing that can be done directly via PaperUI. Once a field is edited (which is probably what happened at some point), the fields cannot be removed again and will stay as empty string. Which can have strange consequences, as with this MQTT thing.

This is not visible in the UI (not existing or empty looks the same).

(I reported this under web ui, but maybe it should be reported for mqtt?)

**Comment by wborn** [comment]
Since there won't be any 2.5.x releases, you might want to close all Paper UI, Habmin, Homebuilder etc. issues in this repo @openhab/webui-maintainers.
