### ISSUE TITLE
Refactor namespace to org.openhab

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-webui#156]
The core packages have changed their namespace with https://github.com/openhab/openhab-core/pull/1294, so the existing code in this repo has to be adapted to compile again.

@cweitkamp Does the script that you used work for this as well?

**Comment by cweitkamp** [comment]
Yes, I think the first and second parts (`moveAll` and `replaceAll`) should work. The third part (`corePatches`) is for OHC specific changes. You can find the script [here](https://gist.github.com/Hilbrand/94c3a1049a494d763223e2d33f4e8e73).
