### ISSUE TITLE
[cometvisu] Remove PHP support for CometVisu

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#1592]
Is it OK to remove "PHP support for CometVisu" in openHAB 4.0 @peuter?

According to the [CometVisu documentation](https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.cometvisu/README.md) it was already deprecated and scheduled for removal:

> **"PHP support for CometVisu"-binding is not needed anymore**
> 
> If you want to use this binding to serve the CometVisu, you do not need the additional "PHP support for CometVisu" binding anymore.
> That binding is deprecated and will be removed in future openHAB versions. This binding provides everything that is needed to 
> run CometVisus own file-manager and editors. The only things that are not supported are plugins that use PHP-Code.

**Comment by peuter** [comment]
Ok I am obviously not up-to-date ;-) With 3.4 is has been marked as deprecated, then it can be removed for 4.0

**Comment by wborn** [comment]
Great! The new major version allows for some cleanups and other breaking changes like this. :slightly_smiling_face:
