### ISSUE TITLE
[cometvisu] does not install with 3.4

### ISSUE THREAD

**Issue by peuter** [openhab/openhab-webui#1595]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [ ] HABPanel
- [ ] HABot
- [x] CometVisu

## The problem

When I try to install the cometvisu-binding with the just released 3.4. I get the following error:

```
2022-12-19 19:04:18.788 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-ui-cometvisu': Error:
	Error downloading mvn:org.rrd4j/rrd4j/3.8.2
```
which I don't understand. That version is available in the maven repository and it did work locally when I increased the version requirement.

**Comment by kaikreuzer** [comment]
Could you try again?

**Comment by peuter** [comment]
Thanks its working now.
