### ISSUE TITLE
Visual bug of textually defined empty String-Item in Items menu

### ISSUE THREAD

**Issue by Marmoset-threat** [openhab/openhab-webui#1604]
## The problem

When viewing Items with MainUI, textually-defined String Items which are empty (have the state ""), the lock-icon that indicates that the specific item is textually-defined draws in place of where the State is normally displayed. 

![image](https://user-images.githubusercontent.com/54677116/209380124-48b73a90-776d-4349-be70-37cede777efb.png)

## Expected behavior

The "Lock" Icon is on the right, next to the item Name. 

## Steps to reproduce

Have textually-defined String Item and set the state to an empty string ""

## Your environment

OpenHab 3.4, viewed in Firefox

**Comment by stefan-hoehn** [comment]
I tried to reproduce it. I created the Item as follows

<img width="669" alt="image" src="https://user-images.githubusercontent.com/5937600/213554919-12ba7e74-d89f-412d-8601-bf5f9c24d0a6.png">

and wrote a rule that sets the item to ""

<img width="442" alt="image" src="https://user-images.githubusercontent.com/5937600/213554976-6033fa7a-4461-4a09-84a2-a3b76dcec39f.png">

> events.sendCommand('EmptyStringItem', '');

However, it looks fine to me:

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/5937600/213555110-5172ca1f-2fa9-4600-9298-0c0bae84a258.png">

Can you check if you have any metadata created and can you please provide a screen of your item?

**Comment by Marmoset-threat** [comment]
@stefan-hoehn This is only in items that are defined textually, via an entry in a `.items` file in the items folder of the openhab configuration, not the GUI. All these items show the lock symbol because they're not editable in the MainUI, but on an empty string, the lock symbol slides to the right. This is shown in the screenshot I posted. 

Example item might be (in a '.items' file)

`String ExampleItem "Example Item"`

**Comment by stefan-hoehn** [comment]
Oh sorry, sure, that I did overlook. I will have a further look into it then.

**Comment by stefan-hoehn** [comment]
I was able to reproduce it and have provided a fix: ^
