### ISSUE TITLE
Increase blockly version to 9.x

### ISSUE THREAD

**Issue by stefan-hoehn** [openhab/openhab-webui#1608]
@ghys 

I am sure you remember that we once tried to increase the blockly version and you even tried youself but it had a lot of impact on other dependencies as well. I remember you told me you'd rather do this yourself in a more calm moment, so nothing breaks.

Can you try this again and try to increase blockly to 9.2.x. This is actually a good time as we currently incorporating graalvm and I need to to test all blocks anyway.

cc: @florian-h05

**Comment by ghys** [comment]
If I recall correctly you updated all the dependencies in package.json with an unfortunate npm update and put it in a PR.
I tried to update blockly and the 2 other packages (slider & zoom-to-fit) in #1609 only and it worked.

Then I tried to test it but the Blockly editor didn't load, the generator API having changed: https://github.com/google/blockly/releases/tag/blockly-v9.0.0
So I tried the provided update scripts on the files as instructed and it seemed to fix the problem at first sight.
Should probably be tested more.

**Comment by stefan-hoehn** [comment]
@ghys 
Thanks to your work, @florian-h05 was so kind to integrate your changes into our current branch, so I am able to build all the new stuff for 4.0 on latest blockly version. 
I works 95% out of the box. It is a bit pickier (which is good) on the right shadow types in the workspace block setup which I had to fix and there is a comment that a particular mutator should be implemented differently for 10.x but other than that surprisingly compatible.

Thanks, Pal!
