### ISSUE TITLE
Display page markup on Main UI overview page (including background colors/images)

### ISSUE THREAD

**Issue by Dennis1984120** [openhab/openhab-webui#1627]
When designing a page in the Main UI, you can choose to use a custom background-image. This works in general, but not when that specific page is (displayed on the) overview page of the Main UI, both in the browser and on mobile. 

For this reason, you cannot create the new style that for example the Apple Home app and the Homey app uses (colored background and semi-transparant/white widgets on top). 

While designing ("correct"): 
![background-correct](https://user-images.githubusercontent.com/10367266/211168821-e846b95a-b68b-413b-8158-d58b48410c7e.png)

Displaying ("wrong"): 
![background-white](https://user-images.githubusercontent.com/10367266/211168826-688d5df3-7a52-4be5-bccf-f5c096857f03.png)

My suggestion is to display the background-properties on the overview page when they are defined as such.

**Comment by stefan-hoehn** [comment]
Can you please provide the information how you configured the background image?

**Comment by Dennis1984120** [comment]
Yes, of course. 

This is my YAML right at the top of the page: 

`
config:
  label: Startpagina
  style:
    background-image: url(/static/backgrounds/one.png)
    background-size: cover
`

And to emphasize again... it works on all pages, but on the overview page some style information is just 'deleted'. If I display the specific page just by linking to it directly (without the overview page) it just works.

**Comment by hmerk** [comment]
Just tried and can confirm this wrong behavior.
Somehow the style gets ignored.
Opening overwiew page in editor and pressing run is working fine, but not when calles as homepage.

**Comment by stefan-hoehn** [comment]
I can confirm that it doesn't work. What confuses me though that you do seem to see it during the design phase. I don't see it even even there. 

Would you mind providing the code of a very much simplified overview page so I am able to reproduce the issue on my side? (you can just delete most of your code in the code tab, just make sure you don't save it or make a backup of the code beforehand to be able to restore it).

Here is my indenting:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/5937600/212466813-64ea83b2-4eae-4eb5-b290-6dac0791b4bf.png">

@hmerk Can you see it in edit mode?

**Comment by stefan-hoehn** [comment]
Justin actually noticed that seems to be related to the tabbed pages:
https://community.openhab.org/t/overview-page-background-image/138139/7

**Comment by stefan-hoehn** [comment]
I have a provided a PR that fixes the issue ^

<img width="984" alt="image" src="https://user-images.githubusercontent.com/5937600/212490377-3038b325-d1e4-4480-a65d-94d27ca0b413.png">

**Comment by hmerk** [comment]
@stefan-hoehn But what about the background color, that's what I was testing and it did not work.

**Comment by stefan-hoehn** [comment]
I am pretty sure it'll work as well. I am going to check tomorrow

**Comment by hmerk** [comment]
@stefan-hoehn Did not check the PR before my comment. Now that I have read it, I believe it will solve both issues.
Thanks !

**Comment by stefan-hoehn** [comment]
Me too, but nothing works before it is actually verified and tested.... Old QA wisdom 😀

**Comment by Dennis1984120** [comment]
This is really great @stefan-hoehn . Thanks a lot! And also thanks @hmerk for confirming this issue. Really great if this makes it into OH4 or earlier, so I can finally complete my preferred styling all through my UI. 

Can I buy you a coffee/anything else or do you want me to make a donation to OpenHAB foundation?

**Comment by stefan-hoehn** [comment]
> Can I buy you a coffee/anything else or do you want me to make a donation to OpenHAB foundation? 

"Applause feeds the hunger of the artist" <3 

You can become a "sustaining member", Dennis,  if you like:

https://www.openhabfoundation.org/join/

**Comment by hmerk** [comment]
Donations are also always welcome ;-)
