### ISSUE TITLE
Item does not show all metadata of the item

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-webui#1633]
## The problem

I have metadata on the item which is not shown in the UI
```json
    "metadata": {
      "HABApp": {
        "value": "ThingPlugin"
      }
```

![grafik](https://user-images.githubusercontent.com/10754716/211731893-3f1843f9-174a-4423-80d6-b08837533234.png)

## Expected behavior

Metadata should be shown

## Steps to reproduce

Add metadata to the item that is not in the namespace 
```
semantics,stateDescription,commandDescription,synonyms,widget,listWidget,cellWidget,widgetOrder,autoupdate,expire,alexa,homekit,ga
```

## Fix

Metadata selector when doing item request should be e.g. `.*`

**Comment by florian-h05** [comment]
Will be fixed by #1623.
