### ISSUE TITLE
Edit TXT files with internal file editor as a developer tool

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-webui#1658]
## The problem

You can pause and resume rules in the main ui txt, but not edit them. To edit them, I have to edit the files directly in the file system (e.g. /etc/openhab). if I am remote, the whole thing is even more uncomfortable.

## Your suggestion

If the txt files cannot be edited directly in the rule manager via ui, it would be very useful to have a file editor under "developer tools" with which you can edit all the files in the /etc/openhab directory. If possible, you could also use the same editor that you already use to edit ui rules.

## Your environment

OH 3.4.1

**Comment by lolodomo** [comment]
This is not a question of editor but rather the fact that any file in config directory should be read only and so not editable in MainUI.

**Comment by rkoshak** [comment]
OH provides a way to edit through MainUI via managed Items, Things and Rules (i.e. not text files configs). For many reasons, including security, providing a way to edit the files in `/etc/openhab` is a bad idea. For one, it completely invalidates the protections provided by the Exec binding whitelist.

**Comment by Gifford47** [comment]
Ok. But why can I deactivate e.g. complete rules, things or items in the manui that were created by text files?

**Comment by florian-h05** [comment]
As already mentioned, there are good reasons that files on the file system are not editable though the UI.

If you want to have rules editable through the UI, you need to use UI rules.

Therefore closing this.
