### ISSUE TITLE
Add JS Scripting installation for Blockly in script creation & in wizard as well as rrd4j

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-webui#1659]
With Blockly support for JS Scripting merged in #1617 and the NashornJS engine removed from core, Blockly depends on at least one JS automation addon being installed. For several reasons, the GraalJS based JS Scripting add-on is the way to take for the future.

Installing JS Scripting (GraalJS) by default was rejected in https://github.com/openhab/openhab-distro/pull/1455 with some good reasons, the consensus was to handle JS Scripting installation through the first start wizard and possibly the script creation page where you can select Blockly as an option as well.

Discussed in this distro PR as well: addind rrd4j persistence to the installtion wizard and not installing it by default.

/cc @rkoshak @stefan-hoehn @ghys

**Comment by rkoshak** [comment]
And rrd4j too.

**Comment by dilyanpalauzov** [comment]
Is in Openhab 4 Blockly itself an add-on?  If it is not, it shall be made an addon, as it can only work when another addon is installed.  I want to save memory, so for me a system without Blockly (that is, where Blockly is an addon) is better.

**Comment by rkoshak** [comment]
> Is in Openhab 4 Blockly itself an add-on? If it is not, it shall be made an addon, as it can only work when another addon is installed.

It is not itself an add-on but it depends on the JS Scripting add-on. It's not stand alone. 

> I want to save memory, so for me a system without Blockly (that is, where Blockly is an addon) is better.

Blockly is implemented 100% on the client side (i.e. in the browser). There would be no way to make it an add-on. It's part of MainUI and MainUI doesn't support independent add-ons like that. There is no impact to the memory on the server side. On the client side, if JS Scripting is not installed, I suspect that Blockly is simply not shown as an option and would be willing to bet that the Blockly JS libraries don't get loaded in the web page either.
