### ISSUE TITLE
No more language translation in bindings page

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1666]
With snapshot 3286, I was really happy to discover that bindings in the addons page have translated label/description. It proved this is doable. Unfortunately, the translation disappeared in snapshot 3294.
I am not sure whether it is a MainUI or a core bug.

**Comment by lolodomo** [comment]
Ok, this might be a bug in the REST API (addons) as I can see using snapshot 3294 that it returns untranslated labels/descriptions.

**Comment by lolodomo** [comment]
@J-N-K is certainly aware about all this stuff. I can see that the REST resource is considering the locale when requesting the addons from the service:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java#L158
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java#L164
I tried using "karaf" as service id in the API but it makes no difference.

**Comment by J-N-K** [comment]
Which language did you use and what add-on should be translated? I don't use that, so I have no idea what it did look like before.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java#L86
`locale` parameter is currently ignored.

@J-N-K : could it be something that you changed in https://github.com/openhab/openhab-core/pull/3293

**Comment by lolodomo** [comment]
I am trying with "fr" as language and I am currently checking with the ecowatt binding.

**Comment by lolodomo** [comment]
I have the feeling that the problem is that methods in class `KarafAddonService` are ignoring the `locale` parameter.
What is strange is that it worked one week ago.

**Comment by lolodomo** [comment]
Ok, at least, this call should be done with `locale` as parameter.
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java#L136

I am going to try enhancing the class `KarafAddonService` to consider locale, it is not a complicated class.

**Comment by J-N-K** [comment]
I'm not 100% sure, but IIRC this was always the case. Maybe the difference now is the integration of the `bindings` endpoint in the `addons` endpoint. Probably it would be sufficient to consider the locale when requesting from the `AddonInfoRegistry`.

**Comment by lolodomo** [comment]
> Probably it would be sufficient to consider the locale when requesting from the `AddonInfoRegistry`.

Yes, that is what I am trying to do... Will have the answer in few minutes.

**Comment by lolodomo** [comment]
Note that last week, I saw it worked for installed bindings, I am not sure it was working for uninstalled bindings.

**Comment by lolodomo** [comment]
Calling the registry with `locale` does not resolve the problem.
@J-N-K : in your PR, I see that you made a change in class `AddonI18nLocalizationService` that could be something to investigate. I am going to try undoing this change...

**Comment by lolodomo** [comment]
So the problem seems to be in the `AddonInfoProvider`. Maybe the problem is when inferring the key ? Or not searching the translations at the right place ?
I am now a little lost with all these classes.

**Comment by J-N-K** [comment]
I think the issue is in `AddonI18nUtil`:

```
    private String inferKey(String bindingId, String lastSegment) {
        return "binding." + bindingId + "." + lastSegment;
    }
```

This needs to be

```
    private String inferKey(String addonId, String lastSegment) {
        return "addon." + addonId + "." + lastSegment;
    }
```

**Comment by lolodomo** [comment]
Oh you are certainly right.

**Comment by lolodomo** [comment]
Bingo, it works.
I am preparing a PR.

**Comment by lolodomo** [comment]
With the fix in core framework:
![image](https://user-images.githubusercontent.com/10186704/215264792-321dfaa8-84b1-45b6-824a-720c13f58a35.png)

It is another story but it could be an idea to add in the first "block" the small description returned by the API. This will allow having a localized description, while the text below is from the documentation and will always be in English.

**Comment by lolodomo** [comment]
Description is only provided for installed bindings so I understand why it is not used in UI.

**Comment by lolodomo** [comment]
Issue fixed by the PR in core framework.
