### ISSUE TITLE
Why so big logo for addons and why different sizes ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1668]
Why do we have different sizes of logo for the addons ?
Logo for "JavaScript Scripting is really too big and not at all the same size as the logo for "Jython Scipting".
The result on a mobile phone is even worse, one logo takes more than half the screen.
![image](https://user-images.githubusercontent.com/10186704/215278349-bc9f4aaf-70e5-44a3-9ce1-aa80c2b3c8c0.png)

**Comment by florian-h05** [comment]
The featured addons are displayed much bigger, see https://www.openhab.org/addons/#automation.

**Comment by florian-h05** [comment]
After thinking a bit about this, IMO we have these options:

- add a break point to only show the big logos on large displays
- completely remove the large icons for featured addons
- make the icons a bit smaller
- leave it as is

If we want to keep the „featured“ thing (which is also on the addons website) IMO we should go with the third option and make them smaller, e.g. double the size of the icons of the „normal“ addons.

**Comment by kaikreuzer** [comment]
I'd also prefer the third option (where "a bit" can even be "a significant bit").

**Comment by lolodomo** [comment]
Any option except the last one.

**Comment by ghys** [comment]
I apologize for not answering the initial "why" question sooner. Here's some context:

- I wanted this "featured" part on these add-on sections to promote add-ons users would want to see first
- the 3 - (not so) arbitrarily chosen number based on the number of available add-ons per section - featured addons would be justified right whenever possible
  ![image](https://user-images.githubusercontent.com/2004147/220754053-b7650d77-b726-4ac7-b31d-304ac2af18cd.png)
- the logos often aren't enough to illustrate which add-on it is, so add-on titles have to be shown
- the titles shouldn't be cut/abbreviated too much for clarity, as much as possible
  ![image](https://user-images.githubusercontent.com/2004147/220754971-84555386-3910-474d-9f16-48a62d0ed579.png)

Design is hard, but I don't have a design training so I did my best. I wish good luck and godspeed to whoever attempts some improvement.
