### ISSUE TITLE
"Add-on Management" not translated

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1669]
In settings page, all system services are correctly translated except "Add-on Management".
![image](https://user-images.githubusercontent.com/10186704/215282891-75132028-fe0a-4084-8774-01ec804d3bab.png)

The translation seems to be correctly defined:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_fr.properties#L6

Now, when I open this page, the parameters are properly translated except the title "Add-on Management":
![image](https://user-images.githubusercontent.com/10186704/215283006-e04456c2-38aa-4ab3-a45e-6f3924d00acc.png)

**Comment by florian-h05** [comment]
Given that this part of the settings page is generated based on the API response from core, see:

https://github.com/openhab/openhab-webui/blob/5b680e3a0811d8d8e6eb05b9e9226bfe02ec7a26/bundles/org.openhab.ui/web/src/pages/settings/settings-menu.vue#L121-L125

I’d say this is some core issue. You can check what the API returns for `/rest/services`.

**Comment by lolodomo** [comment]
Result of GET /services

![image](https://user-images.githubusercontent.com/10186704/223235254-22a0f1b3-c185-4cab-8680-ee1fd153e863.png)

All services are translated except one.
So you are right, the problem is in core framework, not in MainUI.

**Comment by florian-h05** [comment]
Okay, let‘s move this to core.

@kaikreuzer Can you please transfer this to core?

**Comment by lolodomo** [comment]
I am not sure but the problem could be that the files addons.properties and addons_*.properties are in org.openhab.core bundle and not in the bundle containing the service. I don't know why they are in this bundle.
The code is searching the translation in the bundle of the service:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java#L312
