### ISSUE TITLE
SIP Client cannot be used over insecure HTTP 

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1690]
## The problem

I create SIP card and connect to the SIP server using WSS (secured Web sockets).  Then I load the openhab Webpage using insecure HTTP (http://192.168.0.176:8080).  The system says:

> **openHAB**
> Please ensure that HTTPS is in use and WebRTC is supported in this browser.

This happens under Linux when I use Firefox, Chromium or Epiphany/Web (WebKit).

## Expected behavior

Functional SIP client.  There might be a warning, which I should be able to suppress in the future.

But now the SIP client is not functional.  I expect it to be functional.

When I connect over HTTPS to the MainUI, the SIP-client does work.
## Your environment

OpenHAB 3.4

**Comment by digitaldan** [comment]
The SIP card uses the Camera/Microphone API and WebRTC which most/all browsers only allow over SSL.  We don't do any specific blocking or checks, but our app is getting denied in this case when we try to ask for media devices, and so we prompt with this error.

**Comment by dilyanpalauzov** [comment]
This is not documented at https://www.openhab.org/docs/ui/components/oh-sipclient-card.html and https://www.openhab.org/docs/ui/components/oh-sipclient.html .

Can you add an option to hide the SIP component completely, when loaded over insecure HTTPS, instead of generating an error?

**Comment by digitaldan** [comment]
Understood. Maybe we should look at not using an alert and instead disable the widget with some message in the widget

**Comment by florian-h05** [comment]
> When I am at home I connect to the local address, which is insecure HTTP.

Just access openHAB over port 8443 and you have a HTTPS connection using the self-signed openHAB certificate. 
I'd recommend to use HTTPS on your local network as well, because with all the smart devices today in my network, I don't want to have any credentials send over my local network unsecured. 

I'll update the alert message to indicate that the SIP component won't work over HTTP, but I won't change anything more.
