### ISSUE TITLE
SIP Widget: there is no need for two distinct dialogs to provide the password 

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1692]
With openHAB 3.4 configuring the SIP widget can be done:
* by clicking on “Local Settings”, where one can adjust SIP Credentials (username, password, Own SIP address); and
* by clicking on “Configure Widget”, where the available settings are: WebSocket URL, Domain, Username, Password, Hide Caller ID, Phonebook, Enable Video, Enable Local Videw View, and “advanced settings”.

Since the “Local Settings” provide no space for domain, I assume that the username must contain the domain.  But since the “Configure Widget” asks separately for Domain and Username, I assume that the username shall not be included the domain.  So what is the purpose of having the Domain as separate value?

I think it is very confising to offer some settings over two different dialogs, and some over a single dialog.  password can be entered over both dialogs above, but Websocket URL and Own SIP address only over a single (distinct) dialog.  In fact, after configuring “Local Settings” I have assumed that I am ready and nothing more needs to be configured.  Please move the Own SIP Address property to the “Configure Widged” dialog and remove the “Local Settings” dialog.

“Own SIP address” with comment “ SIP Address (phone number) of this client. Used by the client to remove itself from the dial popup.” is not documented at https://www.openhab.org/docs/ui/components/oh-sipclient.html and https://www.openhab.org/docs/ui/components/oh-sipclient-card.html and I do not understand its purpose.

**Comment by florian-h05** [comment]
There is need for two distinct dialogs. Don't assume something you don't know. You did not create that component - I did.

I'd rather name that issue: oh-sipclient documentation doesn't explain local settings.

The normal widget configuration is stored on the openHAB server and therefore username and passwort set there are shared across all clients. 

But what if you want to create an intercom (means one MainUI client can call another MainUI client)? You have to use the local configuration that is only stored in the local browser to set a different set of username/password for each client. The phonebook however is shared across all clients, therefore you need to set the SIP address of your local configuration as well to hide yourself from the dial dialogue.

I will see if I can improve the docs.
