### ISSUE TITLE
Allow using theme colors as label/value colors

### ISSUE THREAD

**Issue by alltime84** [openhab/openhab-webui#1716]
Hi!
For the Android Client primary and secondary will be added to the [the list of known colors](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/values/arrays.xml#L93-L113).
So that the theme-colors can be used as label or value color as well.
https://github.com/openhab/openhab-android/issues/3248

Maybe this would be an idea for the webUI as well? Or at least to check that this option is not causing any issue?

Thanks!
Tim

**Comment by lolodomo** [comment]
We have apparently a primary color for each theme in BasicUI:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.basic/web-src/_theming.scss#L2
But what would be the secondary color?

**Comment by alltime84** [comment]
Isn't it:
Secondary=`#FF4081`
Primary=`#3f51b5`
![Screenshot 2023-02-17 121346](https://user-images.githubusercontent.com/15026656/219635149-2bdcfbd1-d3df-4fc3-bb96-b6532317c5af.jpg)

**Comment by lolodomo** [comment]
I think the intention is not to use Android App colors in BasicUI but rather use in BasicUI two specific colors depending on BasicUI theme.

Pink is also used in BasicUI as background color for buttons, whatever the theme.
And a kind of blue is used as color for switch, whatever the theme.

The wish is a little vague IMHO.

Is your wish for MainUI or BasicUI ?

**Comment by alltime84** [comment]
The intention is to add this possibility in the Android app. Where I originally placed this request.
As BasicUI, Android and iOS client all use sitemaps, I was asked to also mention the request here - not to cause any issue in BasicUI.

**Comment by mueller-ma** [comment]
The word "theme" is used in Android for different color themes, not for bright/dark mode. There are three themes:
1. Orange
2. Blue and pink
3. (Only on newer Android versions) the color of your wallpaper

As there are no themes by this meaning in Basic UI, it should be blue for `primary` and pink for `secondary`.

**Comment by lolodomo** [comment]
> As there are no themes by this meaning in Basic UI, it should be blue for `primary` and pink for `secondary`.

The main color in BaiscUI is the one to display label and states and it is white for dark theme and black for default (white) theme. I assure this color should be one of primary and secondary ?

**Comment by alltime84** [comment]
I do not think there is a benefit if black or white are one of the primary or secondary colors. Because it would be the same as having set no value or label color in the Sitemap.

Background why I originally asked for this feature for the Android client:
In the Android app I am using the secondary theme-color to better differentiate between label and value. And I think it is a nice design element being able to also select design colors. Especially for the Android app as there is an option to have dynamic design based on the wallpaper used.

**Comment by mueller-ma** [comment]
In Material Design primary and secondary color refer to colors used by interactive elements like buttons, not text. In case of Basic UI it's blue and pink.

**Comment by florian-h05** [comment]
Am I right that this issue is about BasicUI?
I’d adjust labels then …

**Comment by lolodomo** [comment]
I add this feature to my TODO list, it should not too much difficult.

**Comment by lolodomo** [comment]
> Isn't it: Primary=`#3f51b5` Secondary=`#FF4081`

Making a little search, I understand that using `mdl-button--colored` will use the primary color while using `mdl-button--accent` will use the accent color and so probably the secondary color. And in BasicUI, you are setting `mdl-button--accent`. So your hypothesis looks good to me.
