### ISSUE TITLE
HTTP-Status response 503 when try to subscribe /rest/sitemaps/events/subscribe

### ISSUE THREAD

**Issue by DefCon-CC** [openhab/openhab-webui#172]
I'm using OpenHAB Version 2.5.0 and when accessing Sitemap via BasicUI I'm getting the Message "SSE subscription failed: running in fallback mode". I have the evidence that it has something to do with
HTTP-Status response 503 (message: Max number of subscriptions is reached.) when try to subscribe to /rest/sitemaps/events/subscribe.

![image](https://user-images.githubusercontent.com/25898240/72156733-8b28e900-33b6-11ea-8df0-04c8d86e2c47.png)

![image](https://user-images.githubusercontent.com/25898240/72156760-9d0a8c00-33b6-11ea-86c6-2456241cb4e5.png)

**Comment by DefCon-CC** [comment]
Still present in OpenHAB Version 3.0.1

**Comment by lolodomo** [comment]
Certainly something wrong with your setup.

**Comment by lolodomo** [comment]
No more feedback
