### ISSUE TITLE
Icons aren't scaled 

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#1744]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

SVG icons smaller than 32x32 aren't scaled to fit the icon (CSS class `mdl-form__icon`):

Icon from classic looks fine:
![classic](https://user-images.githubusercontent.com/22525368/222361015-aae92ea5-169e-44b7-aaeb-e0695dd98d19.PNG)

Icon from mdi is too small:
![mdi](https://user-images.githubusercontent.com/22525368/222361010-786971cb-4e5f-4d7a-ad42-bdfb032a1c67.PNG)

````svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 - Generated from iconify iconset mdi
 - Author Pictogrammers
 - See https://github.com/Templarian/MaterialDesign
 - License: Apache 2.0, https://github.com/Templarian/MaterialDesign/blob/master/LICENSE
 - SPDX-License-Identifier: Apache-2.0
-->
<svg xmlns="http://www.w3.org/2000/svg" width="1em" viewBox="0 0 24 24">
<path fill="currentColor" d="M12 2a7 7 0 0 0-7 7c0 2.38 1.19 4.47 3 5.74V17a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2.26c1.81-1.27 3-3.36 3-5.74a7 7 0 0 0-7-7M9 21a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-1H9v1Z"/>
</svg>

````

## Expected behavior

All icons should be scaled to 32x32 px. The Android app scales all icons to the same size as well.

## Steps to reproduce

1. Use the icon from above.

## Your environment

```yaml
openHAB 3.4.2
```

## Browser console

```txt

```

## Additional information

Suggestion: The CSS could be update to: 
![grafik](https://user-images.githubusercontent.com/22525368/222361545-06237bc5-bcb7-4fd9-b458-e8d0dcb0004a.png)

But that may cause issues with non-square icons.

**Comment by lolodomo** [comment]
How is defined your icon attribute in your sitemap? Just to understand what icon source you use. 
In case it us a custom icon in OH classic iconset, shouldn't it have the proper size?

**Comment by lolodomo** [comment]
With the same icon either retrieved directly from iconify or from the same icoo defined as custom OH icon:
```
sitemap test8 label="Tests"
{
        Frame {
                Switch item=TestDimmer icon="mdi_lightbulb"
                Switch item=TestDimmer icon="if:mdi:lightbulb"
        }
}
```
![image](https://user-images.githubusercontent.com/10186704/222915543-64908066-41b5-4edb-9c79-76e36ab011ed.png)
![image](https://user-images.githubusercontent.com/10186704/222915602-3d9bb0b3-2e10-414a-ac69-40eea3b4f4f2.png)
So yes, OH icons are noit scaled while iconify icons are.
I am going to fix that.
