### ISSUE TITLE
overview page customization

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-webui#1750]
There's an annoying detail of the Main UI overview page I keep stumbling about:
its title and the date it displays at the top.

Both I can neither remove nor customize.

This has been a long-standing issue up to current 3.4.2 (not sure if there are changes in OH4).

**Comment by ghys** [comment]
You have a per-device setting in Help & About, Miscellaneous to transform these to regular navigation bars (1st option, "Simple navigation bar on home page").

**Comment by mstormi** [comment]
oh, ok.
Thanks!

**Comment by mstormi** [comment]
it work but I'm loosing this on ex/import.
can you please tell me where this property is stored ?
Is there any property name I could use in a .cfg file to have this set one a new installation ?
