### ISSUE TITLE
Icon "player" from classic icon set broken

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#1768]
## The problem

The text "Power on" from the SVG version of the icon "player" is broken in the PNG version:
* https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/player.png
* https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/player.svg

## Expected behavior

Both should look the same.

## Steps to reproduce

1. Open the links above.

**Comment by lolodomo** [comment]
We have the convert script (convert, sh) that converts all SVG in PNG. You could check if it fixes the player icon.

**Comment by lolodomo** [comment]
The `.convert.sh` script requires a Linux environment and the following tools: scour, rsvg-convert, optipng and pngquant.

**Comment by lolodomo** [comment]
Noone has a Linux DEV env to try to run the convert script (after installing the different required tools) ?
Just to check if it fixes the player.png file ?

**Comment by mueller-ma** [comment]
Actually you need Docker to run the script: https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/Dockerfile#L6

This way the tool versions are independent of the developer machine and the outcome should always be the same.
