### ISSUE TITLE
Some classic icons are hard to see in dark mode

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#1769]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

None: Issue is in the classic icon set.

## The problem

Some icons from the classic icon set are hard to see when the UI is in dark mode. This could be Basic UI, Android app or the [website](https://www.openhab.org/docs/configuration/iconsets/classic/#icons).

* https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/network.png
* https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/motion.png
* https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/movecontrol.png

## Expected behavior

These icon should be easy to see on all backgrounds.

Suggestion: At least for the SVG version this issue could be fixed by replacing `fill="#323232"` with `fill="currentColor"`. The Android app and Basic UI (hopefully soon) will then color this icon light gray or dark gray depending on the background.

- https://github.com/openhab/openhab-webui/issues/1743
- https://github.com/openhab/openhab-android/pull/3282

## Steps to reproduce

1. Open https://www.openhab.org/docs/configuration/iconsets/classic/#icons when the browser is set to dark mode.

**Comment by lolodomo** [comment]
In our classic iconset, I believe all the icons have colors and the renderihould remain the same for SVG and PNG icons. So your idea with currentColor could be not suitable for this iconset. 

Regarding support in BasicUI of color control for OH icons (delivered by the OH icon server), I am not yet sure that is easily doable, this would be a big change in the way to render these icons. We cannot assume this will be done until someone contributee something.

**Comment by lolodomo** [comment]
But I agree that we have to change the colors of these icons.

**Comment by lolodomo** [comment]
And for other iconsets containing only SVG, I think your solution is good and currentColor should then be the preference in these SVG icons.

**Comment by lolodomo** [comment]
@mueller-ma : for motion icons, here is the current result in dark mode and bright mode:
![image](https://github.com/openhab/openhab-webui/assets/10186704/7483b9a4-0290-4903-bf92-bf3aad11a4cb)
![image](https://github.com/openhab/openhab-webui/assets/10186704/0a7a3b9c-16af-490a-9602-e12d6d0affc2)

That is no so bad, no ?
I could switch to "currentColor" to have black in bright theme and white in dark theme.

**Comment by lolodomo** [comment]
@mueller-ma : changes are proposed for review but we have first to wait for the deletion of all PNG icons from the classic icon set.

**Comment by mueller-ma** [comment]
Nice!

**Comment by lolodomo** [comment]
We can now search if we have other mono-color icons and in that case we could switch the color to currentColor. But I believe most of our icons are multi-colors.

**Comment by lolodomo** [comment]
"qualityofservice" icon is certainly also not adapted to dark theme.


> We can now search if we have other mono-color icons and in that case we could switch the color to currentColor. But I believe most of our icons are multi-colors.

Mono-color icons: carbondioxide, climate/smoke, flow, smoke.

**Comment by lolodomo** [comment]
We have to check how these icons with currentColor are rendered in MainUI, in bright and dark themes.

**Comment by lolodomo** [comment]
Unfortunately, MainUI does not support currentColor:
![image](https://github.com/openhab/openhab-webui/assets/10186704/4c965c3b-50e4-44b0-8d4a-9097e82d92ce)
![image](https://github.com/openhab/openhab-webui/assets/10186704/125f0b38-6baa-4170-a65d-66972e840fcb)

That means in the official icon set, we must keep hardcoded colors and choose colors that are acceptable in bright and dark themes.

**Comment by lolodomo** [comment]
For motion icons, I think there is simply nothing to do, the current icons are ok in bright and dark modes. I closed my PR and I will probably use this grey color in the other icons to be updated.

**Comment by mueller-ma** [comment]
> That means in the official icon set, we must keep hardcoded colors and choose colors that are acceptable in bright and dark themes.

Support for `currentColor` in Main UI could be added as well, but going to grey is probably also fine.

**Comment by lolodomo** [comment]
movecontrol and network icons are now updated.
