### ISSUE TITLE
[MainUI] To-Dos for Sitemap editor

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-webui#1770]
To-Dos for the Sitemap editor inside MainUI:

- [x] Remove list element (refs https://github.com/openhab/openhab-core/pull/3423 & https://github.com/openhab/openhab-webui/pull/1755#issuecomment-1454895367)
- [x] Add inputHint parameter to input element (refs https://github.com/openhab/openhab-core/pull/3418)
- [x] Extend iconcolor attribute to all elements (refs https://github.com/openhab/openhab-core/pull/3403)

/cc @lolodomo

**Comment by mherwege** [comment]
Thank you for listing this up. I can work on these.

**Comment by mherwege** [comment]
PR to remove List widget config: https://github.com/openhab/openhab-webui/pull/1771

**Comment by mherwege** [comment]
PR to extend iconcolor to all widgets: https://github.com/openhab/openhab-webui/pull/1772

**Comment by florian-h05** [comment]
With #1824, all to dos are completed and this issue can be closed.
