### ISSUE TITLE
Some label/value colors have a low contrast ratio

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#1780]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

Some colors are quite bright, so the contrast ratio between them and the white background is low and thus hard to read. Example with `labelcolor=["pink"]`:

![grafik](https://user-images.githubusercontent.com/22525368/223347615-ee3fbb90-0390-4876-aac0-eb8f9f8f471d.png)

## Your suggestion

This issue has been discussed and fixed in the Android app: https://github.com/openhab/openhab-android/issues/637

For the color names mentioned in the docs (https://www.openhab.org/docs/ui/sitemaps.html#label-and-value-colors) the app has a list with hexcodes for the light and for the dark theme to make sure a high contrast version is used: https://github.com/openhab/openhab-android/commit/68a0dc0c1d80ef5e17f8c97a09c9bb7ece49e421#diff-6e07de53fc6b88f960de082644106654b0ea82d22616dcfe3180a11f307d1625

The docs also mention this behavior:

> Colors defined by a human-readable name may be adjusted for higher contrast, e.g. on a dark theme black may be displayed as white, because white has a higher contrast to the dark background compared to black.

**Comment by lolodomo** [comment]
It should be doable. I imagine to add an option to enable/disable this feature.

**Comment by lolodomo** [comment]
Some users will prefer to get exactly the color they set in the sitemap  I am one of these users.

**Comment by lolodomo** [comment]
But I am ok to have by default a color remapping depending on theme for high contrast. So the new option can be enabled by default.

**Comment by lolodomo** [comment]
I will implement that as soon as the local settings stuff is done.

**Comment by lolodomo** [comment]
@mueller-ma : you forgot to cover 2 colours in Android app: pink and gold ? Or do you consider these two colours are fine with bright and dark themes without the need to remap them ?

**Comment by mueller-ma** [comment]
I added these two colors as "well-known" to the docs and Android app a few years ago: https://github.com/openhab/openhab-android/commit/e9bff16fc04f24d76c772e598de407d616c7f4e9
