### ISSUE TITLE
`oh-cell` title slot layout changed in SNAPSHOT 3386, due to 1129 possibly

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-webui#1817]
I just upgraded to the latest SNAPSHOT (Build #3386) and since then my ```oh-cell``` have changed layout.

![image](https://user-images.githubusercontent.com/84638697/228550477-7ea0030b-5adb-4bc9-a13c-b2b541b45557.png)

![image](https://user-images.githubusercontent.com/84638697/228550530-0b076bf3-3afa-4dbd-b796-1342202d5398.png)

The ```f7-chips``` as ```f7-list-item``` have moved to the same line as the "Title"

I have two similasr setups and both affected.

I suspect that it has something to do with:

https://github.com/openhab/openhab-webui/pull/1798

Code for the two cells is as follows?

[Cell 1.txt](https://github.com/openhab/openhab-webui/files/11101294/Cell.1.txt)
[Cell 2.txt](https://github.com/openhab/openhab-webui/files/11101296/Cell.2.txt)

Any suggestions please?

EDIT: This is what they used to look like

![image](https://user-images.githubusercontent.com/84638697/228550638-d7793a97-a93c-440a-b277-84a2802e7a10.png)
![image](https://user-images.githubusercontent.com/84638697/228550684-3074cadf-9667-4825-b003-ea679e42a04f.png)

**Comment by florian-h05** [comment]
See my answer in https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/291?u=florian-h05, this is no regression but instead the correct behaviour for your widget definition.
