### ISSUE TITLE
[BasicUI] Offer theme following system

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1828]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

When the desktop is in “dark mode”, and the browser loads pages in “dark mode” I want to see BasicUI in dark mode, too.

With openHAB 3.4 this is not the case

**Comment by lolodomo** [comment]
I do not understand. You have a setting to choose between bright and dark themes. 
Would you expect an automatic switch between both depending on OS mode?

**Comment by dilyanpalauzov** [comment]
> Would you expect an automatic switch between both depending on OS mode?

Yes.  This happens already when e.g. /settings/services/org.openhab.basicui is loaded.

For the record at /settings/services/org.openhab.basicui as theme I can select between “Default” and “Dark”.  My reading is that Default=System preference.  I would expect for completeness to see also as option “Light” (when Default=Dark).

**Comment by lolodomo** [comment]
For me, default means light theme.

**Comment by dilyanpalauzov** [comment]
For me Default mean System (Desktop) preference.  Light and Dark are concrete values, which overwrite the system preferences.

I tried now the explicit Dark mode.  I have to say that for SetPoint items the UP and DOWN arrow are black on dark-grey background and therefore hard to perceive in openHAB 3.4/Basic UI.  For  `Switch item=r3_manual mappings=[ON="Ръчно", OFF="Автоматично"]` when the current value is OFF the text “Ръчно” is presented in black on dark--gray background.  This has very low contrast and is therefore suboptimal.

**Comment by lolodomo** [comment]
Looking at code, I see only 2 hardcoded color themes, one bright (default) and one dark.

**Comment by dilyanpalauzov** [comment]
Let’s take as example the openHAB-Android application. It has under Settings → Design the values: Light, “Follow system”, Dark, and Black.  Now Black has even more contrast then Dark.

My perception, based on experience with applications offering light and dark modes is, that there are ideally three states: Light, Dark and “System preference”.

**Comment by lolodomo** [comment]
I believe there is simply no “System preference” yet implemented in Basic UI.

**Comment by lolodomo** [comment]
You have these 3 choices in MainUI for example, not in Basic UI.

**Comment by lolodomo** [comment]
I will see if I can add the "system preference" mode.
