### ISSUE TITLE
Consolidate per device MainUI and global BasicUI settings

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1832]
My understanding of the web interfaces in openHAB 3.4 so far is:

*  For MainUI any unauthenticated user can visit `/about` and setup the “Mode preferences”: Auto (System preference), Light, Dark; and the “Enable Web Audio sink support”. These settings are per device (per browser, actually)
 * The above settings are however irrelevant for BasicUI. To adjust the latter one has to visit `/settings/services/org.openhab.basicui`. Then the settings are not per device, but for all BasicUI instances, whereever they are loaded. Moreover to alter that settings the user has to authenticate towards openHAB.

For me these two-fold settings are contradicting each other. I suggest removing from the URL `/settings/services/org.openhab.basicui` the settings, which are duplicated from `/about` (like color mode and Web Audio sink preferences). Then use on the device where BasicUI is loaded the preferences set at `/about`. This will simplify things.

Moreover it would be good to be able set the default WebAudio (ON) for all devices.  So that it is not necessary to enable it everywhere manually.

**Comment by lolodomo** [comment]
I agree that the theme setting should be rather per device.
But I am not really in favour to make Basic UI suddenly depends on Main UI.

@ghys : can you tell me where are stored these per device Main UI settings ?

**Comment by lolodomo** [comment]
While I understand the idea to have the theme setting per device, I think it should be the same for WEB audio, for consistency.

**Comment by lolodomo** [comment]
@florian-h05 : maybe you can explain how to retrieve these Main UI settings ?

**Comment by florian-h05** [comment]
MainUI stores the theme settings in local browser storage, for dark/light/auto the key is `org.openhab.ui:theme.dark`: https://github.com/openhab/openhab-webui/blob/3f817adcd7ba6c1628a986e43c2170128ae77f62/bundles/org.openhab.ui/web/src/components/theme-switcher.vue#L98
Valid values are `light` and `dark`, for `auto` the key-value pair is removed.

Browser Dev Tools allow you to check content of local storage:
![image](https://user-images.githubusercontent.com/73423173/231708653-b1fc12c5-2518-4e78-ba37-044ef36b0206.png)

**Comment by lolodomo** [comment]
Thank you @florian-h05

**Comment by lolodomo** [comment]
Ok, I believe the proper solution would be to create a new settings page in Basic UI for settings that should be per device, and use the local browser storage. 
For same settings as in Main UI, the same keys would be used.

**Comment by lolodomo** [comment]
I plan to work on this very soon.
