### ISSUE TITLE
[BasicUI] Use more than two columns

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1836]
As far as I see in openHAB 3.4 BasicUI presents the data in up to two columns, even if there is place for more columns.

Please adjust the webinterface to use more colums for displaying data, if the portview is wide enough.

**Comment by lolodomo** [comment]
My understanding of grid provided with Material Design Lite and my understanding of how it was implemented in Baisc UI, it was done to have 2 columns for desktop while only 1 column for tablet and phone. Note the UI is responsive, meaning it automatically switches back to 1 column if you reduce the width of your browser window.

I can probably even create an advanced setting that will define how columns to consider in desktop mode.

We could probably try with 3 or 4 columns for desktop, maybe 2 columns for tablet and keep 1 column for phone.
@kaikreuzer : as you are certainly the one who decided these ratio initially, WDYT ?

**Comment by kaikreuzer** [comment]
I do not recall any specific decision on this, but I personally also never felt the need for more columns.
But I'd be ok with making it behave more responsive - so if there is more screen size available, add additional columns. 4 should probably be the maximum, though.
And for "backward compatibility", it might be good to have a config parameter to specify the maximum number of columns the user wants to have.

**Comment by lolodomo** [comment]
In fact, the page content is limited in CSS to a width of 1080 pixels. If we want to have 3 columns, we need also to increase this value to not have columns that are too small.
What I do not yet find is where is defined the width limit at which there is a switch between 2 and 1 column.

**Comment by felixschndr** [comment]
> I would appreciate a setting for the maximum of columns.

I think this is the way to go. With this everyone can set the view up as they please. 

Maybe a parameter in the first line of Basic UI (the one where the name is defined too)?
