### ISSUE TITLE
[PaperUI] MQTT Item in PaperUI has no decimal points

### ISSUE THREAD

**Issue by moonilightshaker** [openhab/openhab-webui#184]
Hello
After upgrading from 2.4 to 2.5.1-2 using APT package on Ubuntu , all mqtt items in the PaperUI have no decimal points and no decimal value. The value is rounded to the nearest whole number.

more details: [https://github.com/openhab/openhab-addons/issues/6859](url)

kind regards

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
