### ISSUE TITLE
[Blockly] Add "state as number", "state as quantity", and "raw state" to the "get x from item" block

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1841]
This is a feature request but I wasn't sure how to get it labeled as such.

I've helped a few people on the forum a couple times now deal with converting Item states to a format that works to do math with. The problem becomes particularly troublesome when we throw units into the mix.

openhab-js has `.rawState` and relatively recently added `.numericState` and `.quantityState` to the `Item` class which greatly simplify converting an Item's state into a format needed to do math in rules. 

I propose that these three be added as options to the "get x from item" block so that users can simply pull the state in the form needed without requiring adding additional blocks to convert the String state to a form needed. 

I'm running 4.0 SNAPSHOT #3408.

Edit:
Reviewing the code, is it really as simple as adding these to the following line?

https://github.com/openhab/openhab-webui/blob/f1e4e91c1bd033fd35e100864f861db3504a5aba/bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js#L149

I can do that but don't know how to test it.

**Comment by stefan-hoehn** [comment]
I wouldn't call it a bug, though 🤣

Many that's it but a bit more complex because I would make sure that a QuantityState will behave as a "quantity" type and a numericState is a Number type but it is quite manageable.

I'll take care of it soon. While working in I will also provide the extend String-to-Quantity block like mentioned in https://community.openhab.org/t/oh4-blockly-calculations-with-items-states/146027/28 

@florian-h05 please assign it to me.

**Comment by florian-h05** [comment]
@rkoshak I agree on adding the numeric and the Quantity states, but I wonder for what the `rawState` would be used, because the additional functionality it provides (e.g. `distanceFrom(LocationType)` is not available via other Blocks. WDYT?

**Comment by rkoshak** [comment]
I mainly listed it for completeness. I've personally run into many circumstances where I've been happy to have it, but you are right, there is no way to actually use rawState for anything in Blockly outside of the inline script block. The rest of the blocks wouldn't know what to do with it.

**Comment by stefan-hoehn** [comment]
@rkoshak Have fun with it, Mr Koshak 🥇
