### ISSUE TITLE
[Blockly] Option to save a Timer in the shared cache

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#1858]
## The problem

Many use cases, particularly for users migrating from Rules DSL, are addressed by having one Timer accessed and controlled from multiple rules (e.g. a condition that won't run the rule actions if the timer exists). 

## Your suggestion

Provide some way to choose to save and retrieve Timers in the shared cache, not just the private cache. I'm hoping there's a way to make this possible using the exiting blocks, maybe just providing an option to tell the block which cache to use. I don't like the idea of duplicating all the Timer blocks.

## Your environment

```yaml

```

**Comment by stefan-hoehn** [comment]
<h1> The solution </h1>

<img width="436" alt="image" src="https://user-images.githubusercontent.com/5937600/235502709-ff639edc-05b4-47e1-8cde-df7cda318a55.png">

I have add the possibility to say if the time is private or shared. Here are two blocks that I have already changed. I did a test case where I put the first block into one rule and the cancel-block into the second and I was able to cancel the timer of the first rule from the second rule.

If that's what you were looking for, give a thumbs up and I'll proceed with that approach.

FYI here is the code that is generated

```
if (cache.shared.exists('MyTimer') === false || cache.shared.get('MyTimer').hasTerminated()) {
  cache.shared.put('MyTimer', actions.ScriptExecution.createTimer('MyTimer', time.ZonedDateTime.now().plusSeconds(5), function () {
    console.info('abc');
    cache.shared.remove('MyTimer');
  }));
};
```

or 

```
if (cache.private.exists('MyTimer') === false || cache.private.get('MyTimer').hasTerminated()) {
  cache.private.put('MyTimer', actions.ScriptExecution.createTimer('MyTimer', time.ZonedDateTime.now().plusSeconds(5), function () {
    console.info('abc');
    cache.private.remove('MyTimer');
  }));
};

```
and the cancel block

```
if (cache.shared.exists('MyTimer')) { cache.shared.remove('MyTimer').cancel(); };

```

**Comment by stefan-hoehn** [comment]
Here are the other blocks

<img width="536" alt="image" src="https://user-images.githubusercontent.com/5937600/235506204-11e38be2-b072-49f7-a6a8-78211b8e0939.png">

which generate the following code

```
if (cache.shared.exists('MyTimer') === false || cache.shared.get('MyTimer').hasTerminated()) {
  cache.shared.put('MyTimer', actions.ScriptExecution.createTimer('MyTimer', time.ZonedDateTime.now().plusSeconds(10), function () {
    cache.shared.remove('MyTimer');
  }));
} else {
  cache.shared.get('MyTimer').reschedule(time.ZonedDateTime.now().plusSeconds(10));
};

if (cache.shared.exists('MyTimer')) { cache.shared.remove('MyTimer').cancel(); };

if (cache.shared.exists('MyTimer')) { cache.shared.get('MyTimer').reschedule(time.ZonedDateTime.now().plusSeconds(10)); };

cache.private.exists('MyTimer') && cache.private.get('MyTimer').isActive();

cache.private.exists('MyTimer') && cache.private.get('MyTimer').isRunning();

cache.private.exists('MyTimer') && cache.private.get('MyTimer').hasTerminated();

```
