### ISSUE TITLE
SIP does not unregister when page is left

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1872]
I have a SIP widget. When I change within the Main UI from Overview to Location/Equipment/Property the SIP widget does unregister (sends REGISTER with Expires:0).  When I load the page, where thr SIP widget is shown, the SIP widget does again register.

The SIP widget shall unregister also when the page is left: tab is closed or a completely different page is typed in the URL.

openHAB 3.4.2, openhab-android 3.4.6

**Comment by florian-h05** [comment]
> The SIP widget shall unregister also when the page is left: tab is closed or a completely different page is typed in the URL.

For tab change, #1878 fixes this. For the other cases where the tab is effectively killed, there is no real solution since the events that would allow to handle it are not reliable fired especially on mobile browsers.
