### ISSUE TITLE
Unit as pre-defined metadata

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1890]
With the new UoM in core separating the internal unit from the display unit, the user will need to frequently define a "unit" metadata if he does not want the default unit as internal unit.

A new entry has to be added in that pop-up:
![image](https://github.com/openhab/openhab-webui/assets/10186704/e5d57e2f-5882-410f-b605-23d49d455cb9)

I suggest to place it just after "State Description", so in second position.

**Comment by spacemanspiff2007** [comment]
When creating a UoM item the `unit` should be mandatory, see [core issue](https://github.com/openhab/openhab-core/issues/3615). 
The system default should be (pre-)selected but the `unit` should be visible directly on the site with the `create` button.
