### ISSUE TITLE
Is there a ReadMe.md for this?   

### ISSUE THREAD

**Issue by PeteCal** [openhab/openhab-webui#191]
I downloaded and unzipped to tmp.  What do I do now?

**Comment by openhab-5iver** [comment]
It would help to know what you downloaded and unzipped to tmp.

**Comment by PeteCal** [comment]
Well, I started here:
[From OpenHAB to Here](https://github.com/openhab/org.openhab.ui.habminl)
Where the Readme took me to
[New HabMin](https://github.com/openhab/openhab-webui)
Where I think I should select "Clone or download".
That got me to option to Download ZIP.
What should I have done?

**Comment by openhab-5iver** [comment]
It sounds like you are trying to install Habmin? The best place for support is in the user forum... https://community.openhab.org, but you may want to start with the documentation... https://www.openhab.org/docs.

If you are planning on development, keep in mind that it has been removed for OH 3.0 and is no longer available in master.

**Comment by PeteCal** [comment]
It still would have been good to have a readme

**Comment by kaikreuzer** [comment]
Agreed.

**Comment by openhab-5iver** [comment]
A readme for a UI that no longer exists?!

**Comment by kaikreuzer** [comment]
No, a README.md in the root of this repo.

**Comment by eikowagenknecht** [comment]
This can be closed, #527 added a readme.md.
