### ISSUE TITLE
[MainUI] Manual Add Things Don't Show On Marketplace

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-webui#1912]
At some point recently (I can't be exactly sure, just noticed this was broken today), addons that are added from the marketplace don't show available things.  They show perfectly when the addon jar (identical from the marketplace) is placed in the addons folder.  Also, on the "Choose Binding" page, notice the description doesn't load.  I've tested this on snapshot versions 3337 and 3477 and both exhibit this behavior.

Example...

From https://community.openhab.org/t/ring-binding-3-2-0-4-0-0/145245

![Ring-Marketplace-Choose](https://github.com/openhab/openhab-webui/assets/53797132/7193e1e2-355a-49a5-95b8-bd5bb5bba1ef)
![Ring-Marketplace](https://github.com/openhab/openhab-webui/assets/53797132/c0648794-3659-4c99-bd44-827a24709fcc)

versus

![Ring-AddonsFolder-Choose](https://github.com/openhab/openhab-webui/assets/53797132/0c710cae-2e41-45c3-94f2-b6b2f3618bee)
![Ring-AddonsFolder](https://github.com/openhab/openhab-webui/assets/53797132/b12c2eae-305a-4b84-b108-c0db9c2ef1f7)

**Comment by florian-h05** [comment]
I‘d rather expect that this is a core bug, there were no recent changes to these parts of MainUI.

Can you please share a screenshot of the network tab when opening that page? I need to know what is requested and returned from the REST API.

**Comment by morph166955** [comment]
I guess what's confusing me is why the same jar is handled differently.  And that's probably related to my lack of knowledge of how the jar is installed by the marketplace bits.  In my head, I'm looking at it from the karaf perspective.  When I drop the jar into my addons folder, the core sees that and installs it into karaf for use.  I assumed that a similar thing was happening with the marketplace.  Something (presumably the UI) was downloading the jar file from the forum and putting it in a folder, which was then being watched by the core, and then the same installation process was happening.  I never assumed that the name had anything to do with it, I always assumed it was pulling the information out of the xml files inside of the jar.
