### ISSUE TITLE
Number:ElectricConductivity missing in mainUI config dialog

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab-webui#1926]
## The problem
in the openHAB docs [Units Of Measurement | openHAB](https://next.openhab.org/docs/concepts/units-of-measurement.html#list-of-units) at currently
supported units, there is ElectricConductivity listed, but in the item config dialog Number:ElectricConductivity is missing.

![MissingConductivity](https://github.com/openhab/openhab-webui/assets/8472266/9013e3bc-8d37-4a7c-a9dc-71420c881779)

## Expected behavior
Show the Number:ElectricConductivity in the list.

## Steps to reproduce

1. 

## Your environment
Hardware: raspberry pi 4
OS: openhabian 64 bit
Java Runtime Environment: 17
openHAB version: 4 Build #3493

```yaml

```

## Browser console

```txt

```

**Comment by florian-h05** [comment]
See also https://github.com/openhab/openhab-distro/issues/1545.

**Comment by juantxorena** [comment]
> See also [openhab/openhab-distro#1545](https://github.com/openhab/openhab-distro/issues/1545).

Seen. So is this fixed? I only see bugs referencing other bugs that reference other bugs, or merged PR, but I still cannot see ElectricConductivity on the frontend.

**Comment by florian-h05** [comment]
No, this is not fixed. I just linked the issue to be aware of it.
