### ISSUE TITLE
How to add a base URL for reverse proxies?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [openhab/openhab-webui#193]
Is there a way to do so? I'm using Nginx and so far have a sub folder config working with the exception of having to manually add in `/openhab`  after the domain name, and the path?

Thanks
Kacey

**Comment by florian-h05** [comment]
Unfortunately not, and as this would require several independent servlets (e.g. icon, Main UI, REST, Basic UI, SSE) to serve on a subpath, I don’t think there is one wanting to contribute that.
I usually just prefer sticking to a subdomain for openHAB.

I will close this feature request as won’t work on, as I don’t think there is one who wants to contribute all the required changes and I don’t see an urgent need for this.

**Comment by rkoshak** [comment]
Related:  https://github.com/openhab/openhab-core/issues/150
