### ISSUE TITLE
[Basic UI] In Chart element icon and label are ignored

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1931]
The documentation at https://www.openhab.org/docs/ui/sitemaps.html#element-type-chart for the Chart element in sitemaps contains the optional parameters `[icon="<iconname>"] [label="<labelname>"]`.

When the parameters are provided, they are not displayed in OH 3.4.2.

**Comment by lolodomo** [comment]
Yes, I think it was a deliberate choice to ignore them.

**Comment by lolodomo** [comment]
I close it as duplicate of #1367
