### ISSUE TITLE
Redesign (add-on) configuration page

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-webui#1935]
*In https://github.com/openhab/openhab-webui/pull/1891#issuecomment-1589767165 @ghys wrote:*

> In fact maybe having the add-on's (formerly only binding's) configuration in the add-on store was a bad idea after all, as we could just have add-ons add entries to the settings menu like on iOS. So you would have e.g. "Philips Hue" directly under Settings and users wouldn't have to look for it in the add-on store, which was in the end really meant for browsing, installing and uninstalling, nothing more.
>  As for the logging, in fact it could have been a single consolidated page where you would configure levels for all loggers at once.
>
>  The removal of "Other Services" however offers an opportunity to adjust the Settings menu to keep it balanced when presented on two columns, as we could layout it like this:
> 
>  - Left column
>    - 1st-tier Configuration: Things, Model, Items, Pages
>    -  2nd-tier Configuration: Persistence, Tags (?), Transformations no need to have a section header title for those, just separate them from the 1st tier. There would be room for more, for instance "Metadata Namespaces" (allow the user to define their own namespaces).
>    -  Automation: Rules, Scenes, Scripts, Schedule
>  -  Right column
>    -  Add-ons: Bindings, Automation, UI, Other
>    -  Services (formerly System Services)

*In https://github.com/openhab/openhab-webui/pull/1891#issuecomment-1590818187 @florian-h05 wrote:*

> > 2nd-tier Configuration: Persistence, ...

> I'd probably keep persistence out of the main settings and only have it under the add-on settings in the right column.

For the addon setting, I can imagine having the list of installed addon with its icon and instead of just opening the addon settings from the config description, open the addon settings page as in the addon store.

**Comment by ghys** [comment]
Just putting it out there, for future redesigns, I like the UI on the left here (with "cells" for the most important entities).

![image](https://github.com/openhab/openhab-webui/assets/2004147/22fdeddd-2947-4c8d-b3a5-dd810abe9258)
(source: https://sarunw.com/posts/swiftui-list-row-badge/)

I could see Things, Model, Pages, Rules, Scenes, Scripts (has to be an even number) as the cells and the rest of the configuration (Items, Schedule, Transformations...) in a regular list below.
