### ISSUE TITLE
[Basic UI] After `GenericItem.setCategory(…)` icons are not updated until manual reload

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1938]
I update an icon of an item using `.setCategory()`, as described at https://github.com/openhab/openhab-android/issues/3427 .  The icons are not updated in Basic UI, until I manually reload the page.

After I manually reload (F5) the webpage, the new icon is shown, so `.setCategory()` has indeed performed the desired change.

I have openHAB 3.4.2.

**Comment by lolodomo** [comment]
I don't think it is really expected to use `setCategory` inside a rule.
IMHO, the category of an item should only be updated during configuration, either in config file or using MainUI and REST API.
So, I am not surprised that the category is not dynamically updated by BasicUI. I am even not sure that this information is sent by the server to the UI through SSE.

**Comment by mueller-ma** [comment]
I cannot say anything about when this function should or should not be called, but couldn't the server send a "item changed" sse event anyway?

**Comment by lolodomo** [comment]
Few additional information:

1. I believe the principle of sitemap UIs is to react to item state changes, not to item setup changes.
2. But even on an item state change (after a change of item category), Basic UI will not update the icon type until the page is reloaded, this information is parsed only once (using the sitemap REST API) when the page is opened and not later when the page is updated (SSE events).
3. It looks like there is an `icon` member in the DTO `SitemapWidgetEvent` used by the SSE mechanism but looking at the code, I believe it is never set by the server.

I will probably not investigate more, my opinion is that sitemap UIs are not conceived to react in real time to setup changes. A simple page reload after a change of setup looks fine to me. And changing the category of an item or sitemap widget is a setup change.

**Comment by dilyanpalauzov** [comment]
https://github.com/openhab/openhab-android/issues/3427 described the use case for this request and states, that the server does not send category-changed events.

Page reload does not help here. The item is suuposed to present many properties of a device(equipment) in a compact way.  One piece of the presentation is the icon(category).  When the state of one item changes, the icon of of another item is modifed.

E.g. when one item is ON the icon of another item presents the symbol `I`.  When the item changes to OFF, the icon of the second item is updated to to show `O`.

**Comment by lolodomo** [comment]
Ok, I propose to extend the syntax for icon parameter to make it more dynamic:, that is with conditions on possible other item states. This will also add a dynamic feature when using non openHAB icons.
The proposed syntax is just similar to iconcolor/labelcolor/valuecolor:
`icon=[item1==0=temperature, item2==1=oh:classic:humidity, ==0=material::settings, material::home]`
The dynamic computation of the icon will be done by the server. There will be only a minor change required in sitemap UIs to take into account the changed icon coming in a field of the SSE events.

**Comment by lolodomo** [comment]
With openhab/openhab-core#3819 and openhab/openhab-core#3820 merged, I believe your use cases are now covered by the ability to define more complex rules in the sitemap.
