### ISSUE TITLE
[Basic UI] Change settings for loaded Charts

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1939]
In openHAB-Android for Chart items, once loaded, I can select in the user interface to show or hide the legend, or alter the default duration for the displayed data - to one, four, eight, twelve hours, one, two, three days.

Please add an option in Basic UI for charts, which permit the user to change the duration for the displayed data (1 hour, 4h, 8h, 12h and so on), and to toggle the “legend”

**Comment by lolodomo** [comment]
For the duration selection, I assume you are aware that it is already available for any sitemap UI using an additional item and the visibility property. You have the choice between buttons and a selection list.
![image](https://github.com/openhab/openhab-webui/assets/10186704/0420631c-d957-4ef6-b2da-c1a559b2a5f2)

That being said, I agree that it could simplify the sitemap if the UI will handle that without defining something in the sitemap. It would just be something specific to each sitemap UI.

**Comment by lolodomo** [comment]
It is implemented, I will submit a PR soon.
