### ISSUE TITLE
No content when loading http://demo.openhab.org

### ISSUE THREAD

**Issue by hardillb** [openhab/openhab-webui#1954]
## The problem

I maintain a full screen, launch on startup web browser (thin wrapper round Android WebView) code here: https://github.com/hardillb/AndroidWebAutoLaunch

A user has [reported](https://github.com/hardillb/AndroidWebAutoLaunch/issues/16) that the OpenHab Web UI doesn't render when used with my app and just shows a blank white page, I'm trying to get to the bottom of why.

I don't have an OpenHab install but I came across https://demo.openhab.org in an iframe on your site and this appears to show the same behaviour.

I'm trying to work out what options I need to pass to the WebView to make it play nice, but having difficultly working out what the root cause is.

In theory, the WebView should be able to behave exactly the same as Chrome on Android.

From the WebView Console log I see the following error:

```
[INFO:CONSOLE(7)] "Initializing state tracking store proxy", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)
[INFO:CONSOLE(7)] "TypeError: Cannot read property 'getItem' of null", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)
[INFO:CONSOLE(35)] "sseConnected false", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (35)
[INFO:CONSOLE(7)] "TypeError: Cannot read property 'getItem' of null", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)
```
Since the code appears minified this doesn't help very much.

Do you have an unminified version I could test against?

Or a suggestion as to what needs to be enabled? JavaScript is already enabled and I've tried with multiple screen sizes both on real devices and in the Android emulator.

Thanks

## Expected behavior

Page to load correctly

## Steps to reproduce

1. Install AutoWebLauncher (https://play.google.com/store/apps/details?id=uk.me.hardill.weblauncher)
2. Long press on the screen
3. pick settings from the menu
4. Enter https://demo.openhab.org as the URL
5. hit back twice to get back to the full screen webview

To exit the app you can long press to get the action bar up, then swipe up from the bottom to dismiss the application (This is designed to be used in a kiosk mode style environment with the phone/tablet mounted on the wall)

## Your environment

NA (using demo.openhab.org)

```yaml
```

## Browser console

```txt
[INFO:CONSOLE(7)] "Initializing state tracking store proxy", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)
[INFO:CONSOLE(7)] "TypeError: Cannot read property 'getItem' of null", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)
[INFO:CONSOLE(35)] "sseConnected false", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (35)
[INFO:CONSOLE(7)] "TypeError: Cannot read property 'getItem' of null", source: https://demo.openhab.org/js/app.b85df14c3a7ad94c41f1.js (7)

```

## Browser network traffic

NA

**Comment by hardillb** [comment]
Apologies I think I've worked it out, it needed either Database or DOM storage enabling.

**Comment by ghys** [comment]
Yes looking for occurences of `.getItem(` in the minified JS file it seems to be mostly unchecked `localStorage` accesses and a few `sessionStorage` which are assumed to exist (by enabling DOM storage as you found out, https://www.tutorialspoint.com/how-to-enable-web-view-session-storage-in-android). Other features in `window` or `navigator` should be checked first (mostly).

> For future reference, do you have a list of the minimum browser feature requirements anywhere?

Not really, but the official Android app (https://github.com/openhab/openhab-android) also has a WebView to display that web UI, I've seen it working with a pretty old System WebView version 65ish. You might want to check their implementation (https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt)
