### ISSUE TITLE
[Main UI] - other services menu missing

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-webui#1977]
## The problem

I have installed JavaScripting, HomeKit, Basic UI, and other services but since 2 weeks with OH4.0 snapshots the other services menu is missing, I have also installed from scratch without restore backup and is same effect.

<img width="1501" alt="Zrzut ekranu 2023-07-22 o 11 07 58" src="https://github.com/openhab/openhab-webui/assets/28867813/9ad9f520-2f49-4f72-8492-944cf6d1a672">

## Expected behavior

show other services menu

## Steps to reproduce

install OH4.0 snapshot

1. 

## Your environment
OH4.0 latest snapshot
macOS

## Browser console

No error

## Browser network traffic
N/A

## Additional information
N/A

**Comment by lolodomo** [comment]
Yes, it was removed. Now you must go to each binding and then you have an access to its settings.
