### ISSUE TITLE
[blockly] bug in "after" block (count script)

### ISSUE THREAD

**Issue by Hamlet3000** [openhab/openhab-webui#2002]
## The problem

A script that should count up from 0 to 10 every second aborts after the second run with ECMAScript 262 edition 11:.

![image](https://github.com/openhab/openhab-webui/assets/75612866/f7fd0e1b-ec41-4e66-be86-fbf1f044ad07)

```
var count;

console.info('SCRIPT count');
count = 0;
if (cache.private.exists('MyTimer') === false || cache.private.get('MyTimer').hasTerminated()) {
  cache.private.put('MyTimer', actions.ScriptExecution.createTimer('MyTimer', time.ZonedDateTime.now().plusSeconds(1), function () {
    if (count <= 10) {
      count = (typeof count === 'number' ? count : 0) + 1;
      console.info(count);
      if (cache.private.exists('MyTimer')) { cache.private.get('MyTimer').reschedule(time.ZonedDateTime.now().plusSeconds(1)); };
    }
    cache.private.remove('MyTimer');
  }));
};
```

## Expected behavior
The output ends after the 2nd pass but should count to 10:

```
==> /var/log/openhab/openhab.log <==
2023-07-31 13:08:01.617 [INFO ] [nhab.automation.script.ui.a08104671c] - SCRIPT count
2023-07-31 13:08:02.619 [INFO ] [nhab.automation.script.ui.a08104671c] - 1
2023-07-31 13:08:03.620 [INFO ] [nhab.automation.script.ui.a08104671c] - 2
```

## Steps to reproduce
See Screenshot and code above.

## Your environment
runtimeInfo:
  version: 4.0.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.7
  javaVendor: Raspbian
  osName: Linux
  osVersion: 6.1.21-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 273486896
  totalMemory: 766193664
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.100000023841858
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/115.0.0.0 Safari/537.36
timestamp: 2023-08-02T18:36:14.830Z

**Comment by MeisterPiffer** [comment]
I have the same issue on openHAB 4.0.1

**Comment by alaub81** [comment]
Same her in openHAB 4.0.2.

**Comment by Dash** [comment]
#metoo
Surprised this isn't kippering everyone.  How do other people deal with ongoing monitoring without using a timer loop?

**Comment by rkoshak** [comment]
@florian-h05 , @stefan-hoehn asked me to ping you to assign this one to him.
