### ISSUE TITLE
New items not showing up in rule triggers

### ISSUE THREAD

**Issue by PottiMc** [openhab/openhab-webui#2004]
I created a new switch. When I search for it now for it when creating a When-trigger for a rule the item is not showing up. It is showing up in the item search and the developer bar.

Here is the item:
![grafik](https://github.com/openhab/openhab-distro/assets/39881308/06775fdc-854a-482f-ba4a-b540a971ba1a)

Here is the rule creation:
![grafik](https://github.com/openhab/openhab-distro/assets/39881308/a7d68815-85a3-413d-b993-ce4f6d5c44a7)

OH Version:  4.0.1
Browser: Firefox and Edge

**Comment by florian-h05** [comment]
This is a known issue with Firefox when caching is enabled. openHAB 4 introduced caching in several parts of the UI, and this works very fine with Chromium-based and WebKit-based browsers.
Currently the only "solution" is to use MainUI with a different browser than Firefox, e.g. Chrome or Chromium.
