### ISSUE TITLE
Openhab 4 translation fallback in main Ui

### ISSUE THREAD

**Issue by chr1s692** [openhab/openhab-webui#2006]
## The problem
Hello everyone,
I successfully migrate to Openhab 4 (from 3.4 / docker Version) and everything seems to work fine :).
The only thing I recognize is that the translation in the main UI sometimes switches between german and english (seems that it fallback to english).
Going to the setting menu and open the regional settings and saving it without changing anything, changes the language back to german. After some hours or days it switches back to english.
The “problem” occurs in the tab “Geräte” or “Eigenschaften” as you can see in the screenshot
![image](https://github.com/openhab/openhab-webui/assets/26146982/bf6349ea-7ac7-42b3-9a84-f638011b2a41)

## Expected behavior
The tab “Geräte” or “Eigenschaften” is translated and don't fallback after some time to english.

## Steps to reproduce
I don't really know, in my case it happens after some time.

1. 

## Your environment
openhab 4.0.1 // docker version 

```yaml

```

## Browser console

```txt

```

**Comment by lolodomo** [comment]
That could be the sign that the REST API is sometimes called without the proper language parameter. Just a hint.

**Comment by florian-h05** [comment]
AFAIK, the  REST API decides which language to return based on the `Accept-Language` header that is added by the browser.

**Comment by florian-h05** [comment]
With
