### ISSUE TITLE
[HABPanel] manifest.json display property

### ISSUE THREAD

**Issue by Owlbertz** [openhab/openhab-webui#201]
Hi,

is there a way to customize the `manifest.json`-file in my installation? I am unable to find it on my machine and hope its not part of any JAR-file?

I am using openHABian.

**Comment by ghys** [comment]
It's in the JAR, so you can't customize it without building a new one, but try this: https://community.openhab.org/t/force-habpanel-landscape/33926/3. I haven't checked lately if it still works.

**Comment by Owlbertz** [comment]
Hi,

thanks for the fast response.
The solution you posted seems reasonable. Could've came up with Thatcher myself.
Will try it later.

**Comment by Owlbertz** [comment]
@ghys just for your information: the workaround linked by you worked well.
I would, however, suggest that the `display` property should be set to `standalone` instead of `fullscreen`. That would (at least for Android) render the navigation controls at the bottom making leaving the PWA much easier.
