### ISSUE TITLE
Help button missing on Blockly UoM palette

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#2014]
For @stefan-hoehn!

## The problem

There's no "Help" button on the "openHAB > Units of Measurement" block type palette as there is on the others.

![image](https://github.com/openhab/openhab-webui/assets/2004147/c388606f-5143-4f40-b34d-f1c156c4751f)

![image](https://github.com/openhab/openhab-webui/assets/2004147/04fbb1c9-14d5-4676-8517-ca68b1cb28c6)

This is especially important as I think users with no prior knowledge would be confused by these similarly looking "Qty" blocks with different colors (I kind of did even if I understand the Quantity types and all).

Also labels in blocks are all lowercase so I would suggest renaming the "Qty" label to "qty." (dot optional).

## Expected behavior

A Help button should be added to https://next.openhab.org/docs/configuration/blockly/rules-blockly-uom.html. (ideally with a version switch to link to "www" or "next")
Optionally the Qty blocks should have the same lowercase look as the other blocks.

## Steps to reproduce

1. Go to a Blockly editor, and open the openHAB > Units of Measurement palette.

## Your environment

```txt
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3520"
```
The rest is irrelevant.

## Browser console

Irrelevant.

## Browser network traffic

Irrelevant.

## Additional information

Irrelevant.

**Comment by florian-h05** [comment]
> A Help button should be added to https://next.openhab.org/docs/configuration/blockly/rules-blockly-uom.html. (ideally with a version switch to link to "www" or "next")

👍 

> Optionally the Qty blocks should have the same lowercase look as the other blocks.

We deliberately chose to use uppercase, because in openhab-js `Quantity` is the factory method for the Quantity class.

**Comment by stefan-hoehn** [comment]
thx, @ghys, for catching the missing "help" in the UOM and I agree that this is really necessary for that topic in particular.

With regards on showing the right link for next or www. Is there a way that I can detect the "version" I am running on to provide similarly like we are checking we are on graals

blocky-editor.vue

```
watch: {
    isGraalJs: function () {
      this.initBlockly(this.blockLibraries)
    }
  },
```


<img width="811" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/b160777f-7147-4e14-995b-e58bc6dc4d48">

**Comment by ghys** [comment]
Yes you can check the "store" (Vuex) for `state.runtimeInfo.buildString` and see if it's `Release Build` or not), there are some ways to do it:

https://github.com/search?q=repo%3Aopenhab%2Fopenhab-webui+%22Release+Build%22&type=code

**Comment by stefan-hoehn** [comment]
@ghys I implemented this now and also added more help buttons for the standard sections that contain openHAB additions. Do you mind reviewing and merging it? 🙏🏻
