### ISSUE TITLE
The addon store sub-categories

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2047]
The new [addon store](https://github.com/openhab/openhab-webui/pull/1997) link on the left looks nice!

One suggestion is to add the sub-sections on the left with:
- Bindings
- Automation
- UI 
- Other (or should we expand this to)
- System Integrations
- Persistence
- Transformation
- Voice & Speech

**Comment by florian-h05** [comment]
I like that idea!

WDYT @ghys?
