### ISSUE TITLE
Expand the collapsed settings sections by default

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2048]
I would like to make a suggestion to expand the `System Settings` and `Add-on Settings` section by default. On my screen, there's no reason for them to be collapsed. My preference is for there to be no collapsing at all. I can always use the browser's scroll bar if necessary.

It might make more sense for the two-column layout.

If the aim is to have a somewhat neater default layout, they should be made around the same length as the first column, and if that were the case, display MRU (most recently used) items at the top. But all this is probably making it too complicated and I'd be happier if there's no collapsing at all.

<img width="1639" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/941f4c8e-c4e5-4c1d-8281-d3dfb8c261e2">

**Comment by florian-h05** [comment]
When having three colums, most screens should be big enough to have those uncollapsed by default, so we could do this on those screen sizes.

For two colums or even one column (on phones), I would not uncollapse by default. For the add-on settings, the hidden entries are add-ons which have no settings, just the log level, so there IME is little probability that a user actually needs that setting very often.

WDYT @ghys?

**Comment by florian-h05** [comment]
I decided to expand the system settings by default on large screens when three columns are displayed, but kept the addon settings collapsed (see above comment for reason). This change is included in #2053.
