### ISSUE TITLE
How to setup dev environment

### ISSUE THREAD

**Issue by thomas-tran** [openhab/openhab-webui#205]
Hi all,

I need to modify the paper UI to add some additional field for the item. Does anyone have the guideline how to run the build and bundle?

Thanks
Thomas

**Comment by digitaldan** [comment]
Hi @thomas-tran , the paper UI is mainly receiving critical bug fixes at this point, a new UI for our 3.0 release is being developed on the master branch .  Is this something you think can wait? Can you describe what fields you want to expose?

Thanks!

**Comment by thomas-tran** [comment]
Hi Dan, 

I've changed the theme color and hide some advanced menu for the current paper ui and add some additional fields to the thing items such as tag , customer id, etc.
I just need to know how to rebuild and replace the paper ui in the current openhab version 2.5 deployed in the gateway.  

About the new UI 3.0 what's the release date for it? 

Thanks

**Comment by digitaldan** [comment]
I see, and indeed our repo does not have a readme or build instructions.  It was until recently part of the main OH project, but was moved into its own repo.  The core build instructions still apply here, see https://github.com/openhab/openhab-addons/blob/2.5.x/README.md   After making your modifications you will need to build the paperui addon using maven.  Then on your OH instance you will want to uninstall the current paperui addon and then install your jar , using the karaf console 

>About the new UI 3.0 what's the release date for it?

GA is not for a while (end of year), but milestone releases will come sooner than that.

**Comment by florian-h05** [comment]
See https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/CONTRIBUTING.md.
