### ISSUE TITLE
UI Integrated Help Feature

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#2058]
As part of the recent discussion about attracting and keeping new OH users, [I proposed setting up a UI-based help panel](https://community.openhab.org/t/openhab-marketing-is-lacking/149280/108) that would offer things like basic beginner step-by-steps instructions, simple FAQs and possibly more context aware links to help docs.

Obviously, we don't want this to grow so large that it begins to bog down the UI:
<img src="https://github.com/openhab/openhab-webui/assets/77952587/c554a048-7407-475f-8a41-89651c26a4bd" width="200"/>

But, this could turn into a fairly large project, so before I go too deep into a PR for this, I'd like to get a discussion started about:
1) feasibility - are maintainers even in agreement that this is a needed feature
2) scope -  how much or little to build in
3) best mechanism - I started with the developer panel because that was the quickest and easiest way to render an example and I like the idea of a panel because it can sit side-by-side with the actual content for best ease of use, but what other options might work? A separate page linked in the left panel, context aware pop-overs, or...
4) specific ideas for content -  I certainly have some of my own ideas of what the most critical basic information is, but the experience of others is critical here as well

Here are the images of the quick mock-up that I built to get an idea of where my thinking is starting:
| ![image](https://github.com/openhab/openhab-webui/assets/77952587/b61424d2-e3d9-406d-88af-0ef271d1ba60)
![image](https://github.com/openhab/openhab-webui/assets/77952587/72bf69b8-cb88-453a-aa67-0d39ef4df496)
![image](https://github.com/openhab/openhab-webui/assets/77952587/48e7fdd2-6d9a-4295-a5b9-6bc51ad7fb2f)

**Comment by rkoshak** [comment]
As I said on the forum, I really like this idea. Some things to consider:

- would animated gifs be possible here, so we actually show the steps instead of just a text based description
- could we kick off wizards from here to walk the users through the steps somehow?
- what's long term maintenance going to look like?
- if there were an API, binding's could add their own binding specific help perhaps
- could it be made context aware so that the quick start tab or perhaps a fifth tab shows relevant help based on what page is open?

**Comment by JustinGeorgi** [comment]
> would animated gifs be possible here

I don't see why not.  That hadn't occurred to me, but it's a solid idea.

> could we kick off wizards from here to walk the users through the steps somehow?

As Yannick said, by integrating the help into the UI it has access to all the internal app routes.  If actual interactive wizards can be developed then there's no reason they can't be linked.  I wouldn't even know where to begin with an interactive wizard however, and I wonder if the return on investment is worth it when this panel can have step-by-step follow along instructions so very easily.

> what's long term maintenance going to look like?

A fair question.  My vision is that minimal update should be required.  We don't want to duplicate the full help docs, that's wasted effort, so I see this help as being lite on a lot of the more potentially malleable details.  This should be pared down to simple enough that basics changes are really only required with major UI overhauls.  The basics of adding a Thing aren't going to change all that often, one would imagine.  If we get the balance right then most of the maintenance will be when the organization changes a little, for example add-ons get a new "Store" page.  But changing the text on one step and updating the link isn't too terrible an upkeep task.

> if there were an API, binding's could add their own binding specific help perhaps

Hoo boy.  Adding to the core API is waaay above my paygrade.  On the one hand, I'm not sure that letting bindings add their own help stays within the pared down vision.  On the other hand I could see a few places where binding quickhelp could be very useful...e.g., formatting transformation strings in the html binding.  If this goes in that direction however, then it becomes someone else's project that I'm assisting on, but I'm happy to do that too.

> could it be made context aware so that the quick start tab or perhaps a fifth tab shows relevant help based on what page is open?

I'd love to see this go that direction in the long run.  I assume that there's a way to do this but haven't really though it through so I don't have a framework in mind.

> we can argue that the inline help would still be a developer tool

This is my thinking too.  I don't think that much help is needed for basic user roles because that's just interacting with with whatever pages the administrator has developed.  So, I agree that the help can have some of the same limiting assumptions as the developer sidebar.

> what about merging the 2 sidebars into one, with the ability to switch (not sure how to design it yet)

There are some good options here too.  We could just accordion them.  Or we could take advantage of the f7 resizable grid, so users could adjust the ratio of the two:
![image](https://github.com/openhab/openhab-webui/assets/77952587/c4b272a5-83e6-4556-a173-1af305b3c875)

Or we could fully integrate the two with just an extra segmental button set:
![image](https://github.com/openhab/openhab-webui/assets/77952587/deab7a66-b1d4-4492-8a0a-7c476997f6eb)

![image](https://github.com/openhab/openhab-webui/assets/77952587/7c122c26-4e75-4f9f-9745-33c5126877e2)

I like the look of this option a lot...

> accessing the sidebar with Shift-Alt-H is probably not going to work

It worded on chrome, but I'm not picky, that can be worked out toward the end of development for this, or it could be completely moot since I think the combined panel works fairly well.

> I noticed these "open documentation" links recently which I missed during review, and I find them too prominent

I agree.  Several of them (at least in the milestone) also lead to 404s.  I haven't looked through them exhaustively so I don't know which, but I've hit a couple.

> The less prominent help icons could open the inline help (where you could access the full docs if desired) or directly go to the full docs if the sidebar can't be displayed because of screen size constraints.

I think that's a great solution to the small screen issue.

Here's another question that's come up as I've been thinking about this: One of the main points of this increasing the first impression user friendliness of OH.  Is it worth setting these help texts up through i18n or is just english OK?  I myself couldn't provide any of the translations (I could make my way around a German city 25 years ago, and I can swear in Chinese but that's about it), but I could put the framework in.

**Comment by rkoshak** [comment]
> On the one hand, I'm not sure that letting bindings add their own help stays within the pared down vision. On the other hand I could see a few places where binding quickhelp could be very useful...e.g., formatting transformation strings in the html binding. If this goes in that direction however, then it becomes someone else's project that I'm assisting on, but I'm happy to do that too.

I don't think this would be an instead of but an in addition to. Mostly just something to consider for future versions. It's definitely not a prerequisite for this issue.
