### ISSUE TITLE
[basicui] new header line not working on android google chrome

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#2070]
On my Android phone, the new Basic UI does not work (see screenshot below). There are two problems..

1. The two left most icons do not display properly.
2. None of the four icons actually does anything.

Samsung Galaxy S21 // Android v13 // Google Chrome 117.0.5938.60

![Screenshot_20230915_140859_Chrome](https://github.com/openhab/openhab-webui/assets/893994/88af4355-d6f9-4316-b8ce-e2ad529232dc)

**Comment by lolodomo** [comment]
Works well for me with the same Chrome version on phone with Android 11.

**Comment by lolodomo** [comment]
What is your server version? Mine is 4.1 M1.

**Comment by lolodomo** [comment]
Looks like your browser instance did not load the updated font from the OH server. Maybe you should clean browser cache?

**Comment by andrewfg** [comment]
> What is your server version? Mine is 4.1 M1.

4.1 M1 too

**Comment by andrewfg** [comment]
> clean browser cache?

OK that worked.

**Comment by lolodomo** [comment]
> OK that worked.

Fine. 
So you can close the issue.
