### ISSUE TITLE
Proposal to remove PNG icons from the classic icon set

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2071]
In order to simplify the maintenance of the classic icon set and in order to improve it more easily, I suggest to only provide SVG icons and so to remove all PNG files.
We could then also remove all the stuff in charge of converting SVG into PNG.

To be really clear, I do not propose to remove the support of the PNG format because this format could be used by certain users for their custom icons.
My proposal is only to simplify the classic icon set to have only one file per icon and not 2 as it is now.

This will fix #1768 for example.
And it will allow in a second step to simplify the update of our icons to make their color automatically adjustable to the selected theme ( #1769 ) and their color adjustable by the user (iconcolor field in sitemap syntax), something not possible if we have to keep the PNG version of the icon.

But we need first to know if certain UIs are still relying exclusively on the PNG format. Basic UI already uses by default the SVG format and do not need PNG icons. I am almost certain that Main UI and the Android app can also work without the PNG icons, I have only a doubt about the iOS app.
@openhab/webui-maintainers 
@openhab/ios-maintainers 
@openhab/android-maintainers 
Please let me know.

**Comment by maniac103** [comment]
> and their color adjustable by the user (iconcolor field in sitemap syntax), something not possible if we have to keep the PNG version of the icon.

That's not entirely true, at least for the Android app. There we set a color filter to apply iconcolor, so it'll also work with PNG icons (the filter just applies filter color multiplied with icon alpha). I imagine there's similar possibilities with CSS.

Having said that, the Android app certainly is fine with SVG icons. What does the icon servlet do when PNG is configured, but not present for the respective icon, though? Will it fall back to SVG?

**Comment by lolodomo** [comment]
> What does the icon servlet do when PNG is configured, but not present for the respective icon, though? Will it fall back to SVG?

It will return the SVG icon in case the parameter `anyFormat` is passed with value `true`. If not, the icon servlet probably returns that the icon is not found.

**Comment by lolodomo** [comment]
That's why I want to be sure first that no official UI is requesting PNG and only PNG to the icon servlet.

**Comment by lolodomo** [comment]
Noone fixed or enhanced the classic icon set since several years and one of the reasons is certainly that it is too much complex to maintain it. For example, you need apparently docker to run the script that converts the SVG file to the PNG file.
If the PNG files were really necessary, I could understand this complexity but I am really not sure it is necessary today.

**Comment by maniac103** [comment]
I just double checked for Android: it passes `anyFormat=true` and is able to cope with either format being returned, which is differentiated by the content-type response header.

**Comment by lolodomo** [comment]
> I just double checked for Android: it passes `anyFormat=true` and is able to cope with either format being returned, which is differentiated by the content-type response header.

Same for Basic UI.

**Comment by lolodomo** [comment]
Thank you @maniac103 for confirming that.

**Comment by lolodomo** [comment]
@digitaldan @timbms can we have your feedback for the iOS app?

**Comment by timbms** [comment]
The iOS app can handle SVG and relies for that purpose on SVGKit as there is no native API. 
SVGKit has some shortcomings, for instance causing crashes on "malformed" SVGs: I gave feedback and corrected some issues on SVGKit. Also some openHAB icons were corrected for that reason. Having said this: I am still positive to remove PNG from the classic icon set.

**Comment by lolodomo** [comment]
> Also some openHAB icons were corrected for that reason. Having said this: I am still positive to remove PNG from the classic icon set.

If all SVG icons from the classic set are ok, that's good. 
Thank you for your feedback.

**Comment by lolodomo** [comment]
@florian-h05 @ghys : what about Main UI?

**Comment by ghys** [comment]
The main UI uses `anyFormat=true` and all browsers support SVG so I'm good with that.

> But we need first to know if certain UIs are still relying exclusively on the PNG format. 

There was a Kodi add-on to display sitemaps that I used until about a year ago, but it's not maintained and not official anyway.

**Comment by lolodomo** [comment]
> The main UI uses `anyFormat=true` and all browsers support SVG so I'm good with that.

Thank you @ghys

**Comment by kaikreuzer** [comment]
Sounds as if your proposal can hence be accepted, @lolodomo! 🚀

**Comment by ghys** [comment]
I would even argue that `anyFormat=true` should be the default by now, I don't recall if there is a reason why it is not the case (with SVG taking precedence over PNG if both are available - if a client doesn't support SVG then it can always request the PNG version explicitely).

**Comment by lolodomo** [comment]
@stefan-hoehn : I need your thoughts. We have strange code here with README.sh + README.md. It looks like README.md is generated by running README.sh. Finally README.md does not render properly in Github ! It also looks like it contain some HTML code. Is there a link with this page ? https://www.openhab.org/docs/configuration/iconsets/classic/
I have a doubt because the beginning of this page is different from the beginning of README.md.
Does the documentation host a copy of all icons somewhere ?
If I change links to replace .png by .svg in README.md/READMEZ.sh, will there be an impact on documentation and will it work well ?

**Comment by lolodomo** [comment]
> I would even argue that `anyFormat=true` should be the default by now, I don't recall if there is a reason why it is not the case (with SVG taking precedence over PNG if both are available - if a client doesn't support SVG then it can always request the PNG version explicitely).

When I introduced the `anyFormat` parameter, the idea was to not break UIs that do not yet use it. That is the reason why it was false by default.
I agree we could probably make it true by default now, I am just not sure of the impact on the iOS app.

**Comment by lolodomo** [comment]
I finally kept the script `.convert.sh` and the docker file in case someone wants to generate the PNG files again. And the script can still be useful in case we want to compress new SVG files.

**Comment by stefan-hoehn** [comment]
@lolodomo To be honest, I have no clue and I need to look into that what the shell script does and where it is used and what impact it has on the documentation. I am happy to look into it but unfortunately my time is a bit limited atm.

I am also looping in @Confectrician - maybe he has an idea right away?

**Comment by Flole998** [comment]
Unfortunately this broke the iOS App on some systems, as the iOS App is requesting with "anyFormat=true", so OH will respond with the SVG files even though it requested the PNG files. Some iOS systems don't support SVG (or there is something else wrong), and then the App will just crash. Took me a long time to figure out the root cause, ~~now that I am rewriting the parameter I no longer see the crashes on iOS (but no icons either, except for my custom ones which contain PNGs for every SVG)~~.  I have now converted the SVG files to PNG and dumped them in the appropriate folder in `/etc/openhab`, which now allows me to see the icons again.

I suggest having an "on-the-fly" converter that reads the SVG and generates a PNG in Memory whenever it is requested. That would allow all the nice features mentioned above (dynamic colors) while not killing the iOS App (and possibly other clients that might have issues with SVG icons).

**Comment by florian-h05** [comment]
FYI @openhab/ios-maintainers .

**Comment by florian-h05** [comment]
Which iOS devices and which iOS versions are affected?

**Comment by Flole998** [comment]
At least the iPad Air running on 12.5.7, but I suspect that other models with the same version are also affected.

**Comment by florian-h05** [comment]
Hmm okay. I am sorry but I don‘t know how to help here, apart from asking the iOS maintainers for help.
