### ISSUE TITLE
Missing Add-on Settings menu item for third party bundles

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2076]
I've just updated to `4.1.0-SNAPSHOT - Build #3630` which includes #2053.

When I installed the official JRuby automation addon, the `JRuby settings` item would show up as an entry in the `Add-on Settings`.

However, when I am using a custom built jrubyscripting addon jar that I dropped into the `addons/` folder, the "Add-on Settings" would not show up the JRuby settings item.

I can still go to Add-on store -> Automation -> find the custom JRuby Scripting addon then click on the little blue cog wheel icon, in order to get to the settings page.

The same thing happened with jsscripting too.
This is when it's installed from the official distribution:
<img width="367" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/b80ee6cd-5a36-4597-99e5-cf1e5be021bc">

And this is when it's installed as a jar inside `addons/` folder:
<img width="380" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/ef3b12b1-14c3-43af-a031-d400de15876f">

Note that it's still not there even if I expanded / clicked "Show all".

**Comment by rkoshak** [comment]
Does it appear under "Show All" or not appear at all? I didn't follow the PR that closely but it's clear that the sorting isn't strictly alphabetical. I could see it putting stuff in the addons folder lower on the list. 

Of course, there have always been some UI elements that do not work when the jar is dropped into addons, maybe that is what's going on here.

**Comment by jimtng** [comment]
> Does it appear under "Show All" or not appear at all?

It does not appear at all.

Here's both JS and Jruby installed as jar files in /addons/ folder:
<img width="1013" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/f5792e39-e524-4dd5-8e8b-b59ce8966da8">

And here's the add-on settings, fully expanded:

<img width="749" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/8808586a-9f43-48bf-84b9-74117457fbc3">



> I didn't follow the PR that closely but it's clear that the sorting isn't strictly alphabetical. I could see it putting stuff in the addons folder lower on the list.

@florian-h05 says that when it's collapsed, it will show add-ons that have settings to configure other than just log prefix.



> Of course, there have always been some UI elements that do not work when the jar is dropped into addons

Could you please elaborate on this?

**Comment by florian-h05** [comment]
What does `/rest/addons` return for the JARs?

I guess that is the root cause of the problem, however I am curious how the Addon Detail page from the store gets the Addon settings there.

**Comment by jimtng** [comment]
For jsscripting from jar (with missing setting menu)

```
  {
    "uid": "automation-jsscripting",
    "id": "jsscripting",
    "label": "JavaScript Scripting",
    "version": "4.1.0.SNAPSHOT",
    "compatible": true,
    "contentType": "application/vnd.openhab.feature;type=karaf",
    "link": "https://www.openhab.org/addons/automation/jsscripting/",
    "author": "openHAB",
    "verifiedAuthor": true,
    "installed": false,
    "type": "automation",
    "configDescriptionURI": "",
    "keywords": "",
    "countries": [],
    "connection": "",
    "properties": {},
    "loggerPackages": [
      "org.openhab.automation.jsscripting"
    ]
  },
```


When jsscripting is installed from an official source / not jar

```
  {
    "uid": "automation-jsscripting",
    "id": "jsscripting",
    "label": "JavaScript Scripting",
    "version": "4.1.0.SNAPSHOT",
    "compatible": true,
    "contentType": "application/vnd.openhab.feature;type=karaf",
    "link": "https://www.openhab.org/addons/automation/jsscripting/",
    "author": "openHAB",
    "verifiedAuthor": true,
    "installed": true,
    "type": "automation",
    "description": "This adds a JS (ECMAScript-2021) script engine.",
    "configDescriptionURI": "automation:jsscripting",
    "keywords": "",
    "countries": [],
    "connection": "none",
    "properties": {},
    "loggerPackages": [
      "org.openhab.automation.jsscripting"
    ]
  },
```

**Comment by jimtng** [comment]
The webui might be requesting just `/rest/addons` without passing on `serviceId=all`. When I requested with `serviceId=all` I can see the ones installed from jar.
