### ISSUE TITLE
oh-stepper-item ignoring 2+ decimal places

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-webui#2089]
The stepper widget only shows one decimal place at most.
You can define scale: 0.01 and it's honored the value changes but you have to click 10 times "+" before the shown value is changed.

The value should be shown with as many decimal places as the display pattern defined in item metadata.

**Comment by JustinGeorgi** [comment]
Oh, I noted this a while back.  It's an easy fix, it just slipped my mind and I never submitted it.
