### ISSUE TITLE
Grouping things by Loacation

### ISSUE THREAD

**Issue by d51x** [openhab/openhab-webui#2099]
It would be convenient to group tnings not only by type of binding, but also by location
![image](https://github.com/openhab/openhab-webui/assets/10882718/66e84f55-8da8-438b-b68a-c84f883b7534)

**Comment by clinique** [comment]
...yes, and by Status

**Comment by rkoshak** [comment]
+1 for Location.

For Status you can use search

<img width="762" alt="image" src="https://github.com/openhab/openhab-webui/assets/6385096/ab0fa032-0cb7-4a85-bd77-a75e5bea3a9c">

**Comment by d51x** [comment]
added PR #2107

**Comment by d51x** [comment]
and one more plus is that searching things works by location too
![image](https://github.com/openhab/openhab-webui/assets/10882718/361608fa-7b57-4083-a980-762598796680)
