### ISSUE TITLE
[Basic UI] Use sitemap labels in sitemap selection

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2101]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

I created two sitemaps with Main UI. The auto-generated id of the sitemaps are meaningless. When opening Basic UI I get asked which sitemap I want to open and the id is used here.

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/5fbea16a-9927-4cce-b20d-7aafa3c34233)

## Your suggestion

Both sitemaps have a meaningful label and thus the label should be used in that selection (similar to the Android app).

The theming could be improved here as well, but that's a minor issue to me.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.3
  buildString: Release Build
locale: de-DE
```

**Comment by lolodomo** [comment]
Yes, I have this in my TODO list. My intention was to show the label + the id in parenthesis, in case several sitemaps have the same label.
Another thing that I would like to change is to sort the sitemaps. What sort criteria do you use in the Android app ?

**Comment by lolodomo** [comment]
> What sort criteria do you use in the Android app ?

Maybe they should even be sorted directly by the REST API.

**Comment by mueller-ma** [comment]
AFAIK the Sitemaps in the selection dialog aren't sorted. In the side menu the Sitemaps are sorted by label ascending, expect that the default Sitemap is the first: https://github.com/openhab/openhab-android/blob/48a9692515e81a59f9dfdd1d83a43810233e7016/mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt#L89-L97

Be aware if you do the sorting on the server you need to add a property like "order" for each Sitemap as JSON is an unordered collection: https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects
It may work, but at any time some JSON interpreter may re-order the sitemaps.
Also having the default one as first Sitemap should be kept and this cannot be done on the server as it doesn't know about the default one.

**Comment by lolodomo** [comment]
I will finally keep the sort at Basic UI level. 
And I will add the sitemap name in addition to the sitemap label only when several sitemaps have the same label. 
I have code almost finished.
