### ISSUE TITLE
[MainUI] Tabbed pages code tab in the UI does not show the config section

### ISSUE THREAD

**Issue by schmidmuc** [openhab/openhab-webui#2103]
## The problem

Tabbed pages code tab in the UI does not show the config section. Therefore it's not possible to overwrite configurations.
See also: https://community.openhab.org/t/oh3-hide-navbar/115117/28

## Expected behavior

Config section should be shown in "Code" tab as for (mostly?) all configuration objects.

## Steps to reproduce

Create a tabbed page and go to the "Code" tab - you will not see the config section.

**Comment by rkoshak** [comment]
I'd like to note that there is a `configuration` section shown for rules but that configuration is limited to the parameters selected when a rule is created as part of a rule template. Changing the parameters there does not change them in the rule. Missing are the rule's name, description, and tags though.

I too have found it annoying that these properties are not included in the code tab. But there might be complexities with rules.
