### ISSUE TITLE
Vertical scroll bars in input fields

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2113]
<img width="795" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/b854a90e-299e-49ee-9925-79774004c528">

<img width="745" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/71d3231b-dc0a-449a-a79d-9df6ea1aafcc">

<img width="731" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/1e064253-9d34-43ca-8179-3bd62727d256">

<img width="746" alt="image" src="https://github.com/openhab/openhab-webui/assets/2554958/12ddea28-1ead-453c-816d-8a73ded8cc44">

**Comment by florian-h05** [comment]
Have you been able to fix that problem?

**Comment by jimtng** [comment]
No, I haven't investigated it any further, but the problem is still there for me. Since it seems to be specific to my computer, I'll close this and update it in the future should I find out the cause.
