### ISSUE TITLE
Rules list: Grouping rules/scripts by semantic and by all tags and Filtering by Multiple tags

### ISSUE THREAD

**Issue by d51x** [openhab/openhab-webui#2123]
Features:
1. grouping by semantics
2. grouping by tags
3. filtering by tags

PR with description is here #2122 

## Group by semantic 
![image](https://github.com/openhab/openhab-webui/assets/10882718/3d4b31e7-a64a-4a7e-9fd9-e3df3a0b3a01)
![image](https://github.com/openhab/openhab-webui/assets/10882718/3bf18f51-5c02-49f3-9305-97416d4e2457)

## Group by tags (all tags)
![image](https://github.com/openhab/openhab-webui/assets/10882718/bc1ec2b1-8317-4745-b120-9284f43b8340)

### without filtering
![image](https://github.com/openhab/openhab-webui/assets/10882718/7de9149b-8e47-44da-b291-ddb2f77c08eb)

### filter by multiple tags
![image](https://github.com/openhab/openhab-webui/assets/10882718/cc3ef085-1f71-4d02-b30b-33a30a5d3cde)

**Comment by rkoshak** [comment]
For rules, is there really any real difference between a semantic tag and a random tag? Rules don't often fit well into the semantic model so it's hard to use those tags effectively. I wonder if it's worth even having the Semantic category at all.

**Comment by d51x** [comment]
> For rules, is there really any real difference between a semantic tag and a random tag? Rules don't often fit well into the semantic model so it's hard to use those tags effectively. I wonder if it's worth even having the Semantic category at all.

the standard rules functionality allows you to use tags and you can use any tags as you wish to organize the rules belonging to objects and entities, for easy navigation by rules

**Comment by florian-h05** [comment]
> I wonder if it's worth even having the Semantic category at all.

IMO it’s not, and #2083 removes the semantic tag picker for rules.

Wrt to filtering and grouping by tags. IMO this is not really needed, because the searchbar is able to search tags. So if you want to get all ruled with a tag, just type the tag name (of course there might be other rules that match the search query as well). 
@rkoshak @ghys WDYT?

**Comment by florian-h05** [comment]
> I think allowing grouping of rules by tag does add some usability to the Rules page.

That‘s definitely true. 

There is one more thing to consider:
Whilst Things have one binding, rules can have multiple tags. When grouping by tags, a single rule can appear several times in the list. Therefore filtering by tags using the nice-looking tags filter would probably be the better option, wdyt?

**Comment by rkoshak** [comment]
I personally don't have a problem with the rule appearing more than once. Rules tend to be more cross cutting that Things and Items so it make sense that they would appear under multiple tags. 

I also like the idea of a tags filter. Either approach would make me happy. 

Though with the tags filter, would it be AND or OR. If I select two tags do I see all rules with either tag, or do I only see rules with both tags?

**Comment by d51x** [comment]
If you select two tags, filtering with OR, you will see all rules with selected tags

**Comment by d51x** [comment]
> > I wonder if it's worth even having the Semantic category at all.
> 
> IMO it’s not, and #2083 removes the semantic tag picker for rules.
> 
> Wrt to filtering and grouping by tags. IMO this is not really needed, because the searchbar is able to search tags. So if you want to get all ruled with a tag, just type the tag name (of course there might be other rules that match the search query as well). 
> @rkoshak @ghys WDYT?

Search bar is "difficult" (ha-ha-ha), you always need to input something in it, with tags filter you can just select what you need with mouse click

**Comment by florian-h05** [comment]
I personally prefer filtering tags over grouping by tags, the tag filter looks pretty nice. IMO we don't need both grouping by tags and filtering, so I would say let's take the filtering approach and remove the grouping.

I will review this PR once the discussion here is finished. The grouping by semantics can also be removed, since IMO semantic tagging in general should be removed from rules. I have proposed this in a PR, that is waiting for review.

> Though with the tags filter, would it be AND or OR. If I select two tags do I see all rules with either tag, or do I only see rules with both tags?

> If you select two tags, filtering with OR, you will see all rules with selected tags

Probably this should be configurable, because I can also think of cases where AND would be useful. WDYT?

**Comment by rkoshak** [comment]
> Probably this should be configurable, because I can also think of cases where AND would be useful. WDYT?

I feel like it might not be worth the added complexity. Even though it's just a checkbox it does increase the mental load to use that page. It doesn't feel like the benefit justifies this increased mental load. But I don't feel strongly about this. 

But another question arises. How does this interact with the search bar? If I select a tag and then add a search term does entering that term narrow the list down or replace the tag selection with the search results? If the former, maybe that's all we need for AND?

**Comment by florian-h05** [comment]
I agree on only having OR for the tag filter.

> But another question arises. How does this interact with the search bar? If I select a tag and then add a search term does entering that term narrow the list down or replace the tag selection with the search results?

It narrows it down. This is how I'd have expected it to work.


FYI I am close to finish review and work on that PR (clean-ups, refactoring, removal of parts of it), so I will soon be able to merge it.
