### ISSUE TITLE
Color Widget lacks default module setting

### ISSUE THREAD

**Issue by stefan-hoehn** [openhab/openhab-webui#2134]
When creating an item that has color state which leads to the default of a oh_colorpicker_card the widget is created in a wrong way

<img width="286" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/eefe9b5c-c58a-4536-8f0f-af1dd7f69671">

The root cause is the missing module setting

<img width="687" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/bfa944c8-7c8b-4a9f-bb1e-d21446f64e9e">

The setting should therefore as follows by default

```
value: ""
config:
  modules:
    - wheel
```

as such 
<img width="635" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/13f18b7a-5aaf-4803-b141-18a49f294d91">

which then reveals a working color widget:

<img width="620" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/44496709-362d-483a-b56b-0193806b0a98">

**Comment by florian-h05** [comment]
I have just had a closer look at this, in fact the widget does not lack default module setting.
I found that the reported issue is a regression from the wrapping inside a div in #1989, which was done to allow the user to modify the colorpicker's style.
