### ISSUE TITLE
[Blockly] Add parseFloat/parseInt Blocks

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#2139]
## The problem

The other day I was helping someone with some Blockly code and I could not find any block to parse a string to a number. While this may not come up often, it will come up, particularly when dealing with data that is transformed in some way as the transform action always returns a String.

## Your suggestion

Add a parse block. The first place I looked was the Math category but I could see it belonging a number of places.

**Comment by stefan-hoehn** [comment]
Sorry, @rkoshak , that it took so long. I really had overlooked that.
Note that I only added parseFloat because I think on block is ok that can handle ints and floats.
