### ISSUE TITLE
Javascript error when actionAnalyzerItems value is a string

### ISSUE THREAD

**Issue by wuschi** [openhab/openhab-webui#2158]
## The problem

I am mostly doing textual configuration for my items in openha because I'm generating the item configuration with a shell script.
My config files have gotten quite complex as I'm also configuring the listWidgets metadata etc. inside this config.

I switched some of my items from number to a read-only dimmer recently, which should be rendered by a oh-label-item listWidget with an analyzer action.

Example:

```
Dimmer  Heizung_Stellwert_EG_Gaeste   "Stellwert[%s %%]" <pressure> (gEG_Gaeste_Heizung) ["OpenLevel", "Opening"] {
        channel="knx:device:bridge:heizungsaktor-anbau:stellwertA",
        stateDescription=" "[
                readOnly="true"
        ],  
        listWidget = "oh-label-item"[
                action="analyzer",
                actionAnalyzerItems="Heizung_Stellwert_EG_Gaeste,Heizung_Soll_EG_Gaeste"
        ],  
        widgetOrder="5"
}
```

The textual configuration syntax doesn't allow the `actionAnalyzerItems` property to be configured as an array, so i had to list the items inside a string. This seems to get accepted by openhab and the property is retrieved by the Main UI as string.

But this leads to a javascript error when the analyzer action is clicked (see Browser Console below)

## Expected behavior

Main UI should open the analyzer event if the property  `actionAnalyzerItems` is configured using a string.

## Steps to reproduce

1. create an item configuration similar to my above example
2. click the analyzer action for the item
3. javascript error is logged on the javascript console

## Your environment

openHAB 4.1.0
Build #3680

## Browser console

```txt
vue.esm.js:628 [Vue warn]: Error in v-on handler: "TypeError: actionAnalyzerItems.join is not a function"

found in

---> <F7ListItem>
       <OhListItem> at src/components/widgets/standard/list/oh-list-item.vue
         <OhLabelItem>
           <GenericWidgetComponent> at src/components/widgets/generic-widget-component.vue
             <F7List>
               <OhList> at src/components/widgets/system/oh-list.vue
                 <GenericWidgetComponent> at src/components/widgets/generic-widget-component.vue
                   <F7CardContent>
                     <F7Card>
                       <ModelCard> at src/components/cards/model-card.vue
                         <LocationCard> at src/components/cards/location-card.vue
                           <ModelTab> at src/pages/home/model-tab.vue
                             <F7Tab>
                               <F7Tabs>
                                 <F7PageContent>
                                   <F7Page>
                                     <Home> at src/pages/home.vue
                                       <F7View>
                                         <F7App>
                                           <App> at src/components/app.vue
                                             <Root>
warn @ vue.esm.js:628
logError @ vue.esm.js:1893
globalHandleError @ vue.esm.js:1888
handleError @ vue.esm.js:1848
invokeWithErrorHandling @ vue.esm.js:1871
invoker @ vue.esm.js:2188
invokeWithErrorHandling @ vue.esm.js:1863
Vue.$emit @ vue.esm.js:3897
Vue.<computed> @ backend.js:5188
eval @ vue-component-dispatch-event.js:4
eval @ vue-component-dispatch-event.js:3
dispatchEvent @ list-item.js:566
onClick @ list-item.js:478
vue.esm.js:1897 TypeError: actionAnalyzerItems.join is not a function
    at VueComponent.performAction (widget-actions.js:259:87)
    at VueComponent.openAccordionOrPerformAction (oh-list-item.vue:157:1)
    at click (oh-list-item.vue:53:1)
    at invokeWithErrorHandling (vue.esm.js:1863:1)
    at VueComponent.invoker (vue.esm.js:2188:1)
    at invokeWithErrorHandling (vue.esm.js:1863:1)
    at Vue.$emit (vue.esm.js:3897:1)
    at Vue.<computed> [as $emit] (backend.js:5188:28)
    at eval (vue-component-dispatch-event.js:4:5)
    at Array.forEach (<anonymous>)
logError @ vue.esm.js:1897
globalHandleError @ vue.esm.js:1888
handleError @ vue.esm.js:1848
invokeWithErrorHandling @ vue.esm.js:1871
invoker @ vue.esm.js:2188
invokeWithErrorHandling @ vue.esm.js:1863
Vue.$emit @ vue.esm.js:3897
Vue.<computed> @ backend.js:5188
eval @ vue-component-dispatch-event.js:4
eval @ vue-component-dispatch-event.js:3
dispatchEvent @ list-item.js:566
onClick @ list-item.js:478
sse.js:72 
```

**Comment by JustinGeorgi** [comment]
I'm not sure this is really an issue.  The `actionAnalyzerItems` is given in the docs as a list type property. That means that if you configure it as a simple string it is not an issue with widget, but with your configuration.

Instead of adding potential confusion by mixing configuration types here, why not just ensure that you have set your configuration properly?

```
actionAnalyzerItems="['Heizung_Stellwert_EG_Gaeste,Heizung_Soll_EG_Gaeste']"
```

**Comment by wuschi** [comment]
@JustinGeorgi because this does not produce an array either and leads to the same error. I checked some other variants, but the config parser doesn't seem to support arrays in metadata properties.

Besides that I think that even if you really only want to allow a list type property here the property should be type-checked nevertheless to avoid a javascript exception.

**Comment by JustinGeorgi** [comment]
> because this does not produce an array either and leads to the same error. I checked some other variants, but the config parser doesn't seem to support arrays in metadata properties.

Interesting.  Sounds like maybe this issue should be addressed there then.  Because certainly for proper configuration it must support that array syntax if someone wants to configure the analyzer to have more than one item.



> Besides that I think that even if you really only want to allow a list type property here the property should be type-checked nevertheless to avoid a javascript exception.

That's reasonable.

**Comment by wuschi** [comment]
@JustinGeorgi one more thing: could you please point me to the docs where the configuration type is given as list type? I checked the component reference for oh-label-item and it is listed as `TEXT` type, and I could not find any other reference for this. Thanks

**Comment by wuschi** [comment]
> Interesting. Sounds like maybe this issue should be addressed there then. Because certainly for proper configuration it must support that array syntax if someone wants to configure the analyzer to have more than one item.

Currently it doesn't even work with a single item because of this .join exception

**Comment by JustinGeorgi** [comment]
> could you please point me to the docs where the configuration type is given as list type?

The `oh-button` component reference gives the full explanation of all the action options.  There it specifically says that `actionAnalyzerItems` should be specified as a list:

![image](https://github.com/openhab/openhab-webui/assets/77952587/be0023dd-1903-450a-8dc1-4e02d7b9ac24)

The same is true, for example, with the photos list for the photo viewer.

> Currently it doesn't even work with a single item because of this .join exception

Right which means that right now the textual configuration in the core is broken.  That's the underlying issue here, in my opinion.  If you can't set the value using the expected format of the configuration, then that should be addressed.  Changing the analyzer action to accept a string just masks the larger issue.

I don't use textual configs, but may you can bypass the problem using the yaml list format instead of the JSON (though this is a long shot).  Does something like this work?
```
Dimmer  Heizung_Stellwert_EG_Gaeste   "Stellwert[%s %%]" <pressure> (gEG_Gaeste_Heizung) ["OpenLevel", "Opening"] {
        channel="knx:device:bridge:heizungsaktor-anbau:stellwertA",
        stateDescription=" "[
                readOnly="true"
        ],  
        listWidget = "oh-label-item"[
                action="analyzer",
                actionAnalyzerItems="
                        - Heizung_Stellwert_EG_Gaeste,Heizung_Soll_EG_Gaeste
                 "
        ],  
        widgetOrder="5"
}
```

**Comment by wuschi** [comment]
> The `oh-button` component reference gives the full explanation of all the action options. There it specifically says that `actionAnalyzerItems` should be specified as a list:

Thanks, I'll have a look.

> 
> I don't use textual configs, but may you can bypass the problem using the yaml list format instead of the JSON (though this is a long shot). Does something like this work?
> 
> ```
> Dimmer  Heizung_Stellwert_EG_Gaeste   "Stellwert[%s %%]" <pressure> (gEG_Gaeste_Heizung) ["OpenLevel", "Opening"] {
>         channel="knx:device:bridge:heizungsaktor-anbau:stellwertA",
>         stateDescription=" "[
>                 readOnly="true"
>         ],  
>         listWidget = "oh-label-item"[
>                 action="analyzer",
>                 actionAnalyzerItems="
>                         - Heizung_Stellwert_EG_Gaeste,Heizung_Soll_EG_Gaeste
>                  "
>         ],  
>         widgetOrder="5"
> }
> ```

Already tried that, it doesn't work either. There's also a [discussion](https://community.openhab.org/t/oh3-add-metadata-to-items-via-configuration-files/112843/20?page=2) on the community form regarding this problem.


> 
> > Currently it doesn't even work with a single item because of this .join exception
> 
> Right which means that right now the textual configuration in the core is broken. That's the underlying issue here, in my opinion. If you can't set the value using the expected format of the configuration, then that should be addressed. Changing the analyzer action to accept a string just masks the larger issue.

It agree with you about the underlying issue.
However the listWidget configuration is frontend-only, and especially the actionAnalyzerItems property may be a little bit over-engineered, as all the `widget-actions.js` code does is join an array of strings with comma as separator and add it as a query parameter to the route that opens the analyzer. The analyzer itself then splits the query parameters into a list of items and does the heavy lifting.

> > Besides that I think that even if you really only want to allow a list type property here the property should be type-checked nevertheless to avoid a javascript exception.
> 
> That's reasonable.
 
This seems to start getting a little bit academic here. But what would then be the correct way of implementing the type check?

* If type check for Array is successful everything is fine - .join() the array as before
* If type check for Array is not successful then what?  (My suggestion: try to pass it as a plain string and let the analyzer itself do the error handling if required, which is btw the same approach as with e.g. non-existent item names)

Kind regards,
Thomas

**Comment by JustinGeorgi** [comment]
> There's also a [discussion](https://community.openhab.org/t/oh3-add-metadata-to-items-via-configuration-files/112843/20?page=2) on the community form regarding this problem.
> 

And the recommendation on that discussion is not to use textual config under these circumstances.  You've got an unusual use case, which is not to say it's right or wrong, but few if any other users are going to run into this issue because they are using a shell script to create the text config files.

There are other ways to solve the issue in your individual case.  Maybe your shell script could call the rest api metadata to add the metadata.  Then you could properly format everything because you'd be sending a json payload.

> the actionAnalyzerItems property may be a little bit over-engineered

That's certainly a valid observation.  But again, the analyzer isn't the only place where widget configurations expect array formatted values; there are many such parameters both OH specific and from the F7 library.  Therefore a general, upstream solution is definitely preferable.

> But what would then be the correct way of implementing the type check?

If array then pass through, if not then fail gracefully with a warning.

Ultimately, it's not my opinion that matters.  I'm not saying the PR is a terrible solution, I just think it muddies the waters a little bit, and believe the matter is worth further consideration.
