### ISSUE TITLE
Update branch protection rules for new Travis CI .com integration

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#216]
The branch status checks (master/2.5.x) for this project need to be updated @openhab/webui-maintainers because it now uses the `travis-ci.com` instead of `travis-ci.org` integration. I did the same for other repos where I can change the settings.

While you're at it, you probably also want to check the Webhooks and delete the now unnecessary webhook for `travis-ci.org`.

---

If they aren't updated, a required check will show that will never pass, e.g.:

![Selection_003](https://user-images.githubusercontent.com/12213581/78757917-8ce65680-797d-11ea-9e14-196f613780c4.png)

This is what the settings look like for openhab-addons:

![Selection_004](https://user-images.githubusercontent.com/12213581/78757947-9cfe3600-797d-11ea-98e2-62d7ee9881f3.png)

**Comment by kaikreuzer** [comment]
Thanks for the hint - I've done the required changes!
