### ISSUE TITLE
Developer sidebar preventing access to other UIs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2177]
## The problem

Using snapshot 3725, Basic UI is no more displayed and accessible at right when the developer sidebar is visible:

![image](https://github.com/openhab/openhab-webui/assets/10186704/4d0c5d00-fac8-450e-8d35-1214e4b71038)

It is hopefully visible when the developer sidebar is hidden:

![image](https://github.com/openhab/openhab-webui/assets/10186704/f6f505bd-401d-473b-8274-4544069fe27b)

**Comment by florian-h05** [comment]
So the developer sidebar just needs to automatically hide itself when the "Other apps" panel is opened.
