### ISSUE TITLE
[MAIN UI] Hide "add with Custom ID" action on Z-Wave binding

### ISSUE THREAD

**Issue by cd-tronic** [openhab/openhab-webui#2219]
## The problem
When Adding a new Z-Wave device using MainUI you can add it using a custom ID. The devices get's added but will stay in the inbox when using a customID. 
See this Thread here:

https://community.openhab.org/t/support-for-z-wave-700-controllers/135793/25

![image](https://github.com/openhab/openhab-webui/assets/7304760/df9f5a88-16a9-4202-8dfb-aa809b3e6f33)

## Expected behavior

Hide the "Add as Thing (with custom ID)" option in Main UI
## Steps to reproduce

1. Include a Z-Wave Device in your network. The Device shows up.
2. Click on Device
3. Select "Add as Thing (with custom ID)"
4. The Thing gets added but will stay in Inbox

## Your environment

```yaml

```

## Browser console

```txt

```

## Additional information
As you can read in the Thread i mentioned above it's not possible to change the bahaviour on the Z-Wave Binding as the binding is completely ID driven and starts collecting data even if the Thing was not added. 
That's why it is neccessary to remove the "...with custom ID" when using this binding.

**Comment by florian-h05** [comment]
@cdjackson As you are Z-Wave maintainer, WDYT of this issue?

**Comment by florian-h05** [comment]
I will close this issue as wontfix, because IMO this should be mentioned in the README of the Z-Wave binding instead of hard-coding something for this into the UI.
