### ISSUE TITLE
[BasicUI] Problem with image element being root of another page => no access to the sub page

### ISSUE THREAD

**Issue by JensHoRi** [openhab/openhab-webui#2233]
Updated yesterday to last version openhab (4.1.0-1) from earlier Version 4.0.x i believe.

I have a Subpage could be entered with an Image item worked before, now breaking the sitemap.

Here an example (be aware, you need an imageitem, an item called Empty (String in my case) and a group for testing:
```
sitemap Home2 label="Home Sweet Home" {
    Frame label="Unser Zuhause" {
        Text label="Subpage ok" 			item=Empty {
            Frame label="Sub 1 Frame ok" {
                Default label="Item ok" 			item=Empty 
            }
        }
        Group label="Group ok"				item=gList
        Text label="Grafik (Work around)"						item=owmCurrentConditionIcon {
            Frame label="Sub 2 Frame ok" {
                Default label="Item ok" 			item=Empty 
            }
        }
        Image label="Grafik"								item=owmCurrentConditionIcon {
            Frame label="Sub 3 Frame Broken" {
                Default label="Item never seen" 			item=Empty 
            }
        }
        Text label="Subpage Click not working because of ealier image" 			item=Empty {
            Frame label="Sub 4 Frame never seen" {
                Default label="Item never seen" 			item=Empty 
            }
        }
    }
}
```

**Comment by lolodomo** [comment]
I tried to reproduce your case with this sitemap but I can't, clicking on the images I went to the sub page as expected.
```
sitemap test15 label="Image as sub page"
{
	Frame {
		Text item=TestString {
			Frame {
				Default item=TestSwitch
			}
		}
		Group item=GTest1
		Image url="https://www.openhab.org/openhab-logo-square.png" label="Image example" icon="material:favorite" {
			Frame {
				Default item=TestSwitch
			}
		}
		Text item=TestString {
			Frame {
				Default item=TestSwitch
			}
		}
		Image url="https://www.openhab.org/openhab-logo-square.png" {
			Frame {
				Default item=TestSwitch
			}
		}
		Text item=TestString {
			Frame {
				Default item=TestSwitch
			}
		}
		Group item=GTest1
	}
}
```
But this is when using image element without any item (just an URL). Normally, it should make no difference for UI if the image element is linked to an item or not. Do you confirm that it works for you too in that case.
I will have to extend my example to have an image item.

**Comment by lolodomo** [comment]
Ok, interesting, I can reproduce your problem using Chrome or Edge.
It works well using Firefox.

**Comment by lolodomo** [comment]
I see the same problem with OH3.4.4 and OH 4.0.4. So this is not something new.

**Comment by lolodomo** [comment]
@JensHoRi : was it working for you in a certain version of openHAB ? If yes, in which one ?

**Comment by lolodomo** [comment]
We even do not need image item, just this sitemap shows the issue in Chrome and Edge:
```
sitemap test16 label="Image as sub page"
{
	Frame label="Several images" {
		Text item=TestString {
			Frame {
				Default item=TestSwitch
			}
		}
		Group item=GTest1
		Image url="https://www.openhab.org/openhab-logo-square.png" {
			Frame {
				Default item=TestSwitch
			}
		}
		Text item=TestString {
			Frame {
				Default item=TestSwitch
			}
		}
		Group item=GTest1
	}
}
```

**Comment by JensHoRi** [comment]
Well, I have an image directly in the item (open weather binding stores that way) but that’s the only difference. 

Got the problem in all browsers including Firefox

**Comment by lolodomo** [comment]
> Got the problem in all browsers including Firefox

Strange, it works for me in Firefox.

Please replace in your sitemap "Image label="Grafik"								item=owmCurrentConditionIcon {" by "Image url="https://www.openhab.org/openhab-logo-square.png" {" and tell me if you still encounter a problem in Firefox.

**Comment by lolodomo** [comment]
After clearing my Firefox cache, I have the same problem with Firefox !

**Comment by lolodomo** [comment]
I have not yet any idea why it does not work in OH versions < 4.1 but I know why it does not work in OH 4.1, this is due to the new header row I introduced for image element which should be ignored for image elements being the trigger of a sub page. I am very probably crashing the JavaScript script at least at this line:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.basic/web-src/smarthome.js#L716

**Comment by JensHoRi** [comment]
With 4.0.x I didn’t had this issue. I updated very often, every stable version

**Comment by lolodomo** [comment]
> With 4.0.x I didn’t had this issue. I updated very often, every stable version

Strange because I can reproduce it easily.
Should check again that my browser cache is really cleared when I switch form one OH to another.

**Comment by JensHoRi** [comment]
I'm no developer, but just looked in Firefox analyzing the item:
![grafik](https://github.com/openhab/openhab-webui/assets/47488279/72620456-2fc9-4ad4-84bb-446292dca75f)
event is missing and style of graphic item looks fully different Interesting: Next "normal" Item event is missing to.

Have no idea where this code is build.

Looked your earlier post, but confused with the brackets what to test:
{" by "Image url="https://www.openhab.org/openhab-logo-square.png" {" ???
