### ISSUE TITLE
[Main UI] Add search box for better discoverability and to simplify navigation

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#224]
WDYT about adding a search box in the new UI so you can easily find and navigate to pages that would otherwise be undiscoverable or many mouse clicks/taps away?

Most OS-es have this functionality nowadays. We also use it on the [homepage](https://www.openhab.org/docs/). HABot also provides it in its own way.

It's probably a lot of work to implement and may not have the highest priority for the first OH3 release. :wink:

**Comment by ghys** [comment]
I've thought about this, i.e. adding an [appbar](https://framework7.io/docs/appbar.html#examples) on the top but for design reasons I would restrict it to 1. the desktop theme on desktop browsers and 2. only when the user is a logged as an admin.
As for implementation that could pose a number of challenges wrt navigation flows, but ultimately I think that could be done. Not the priority indeed though ;)

**Comment by wborn** [comment]
Great! Some limitations to conserve screen real estate on smaller device makes sense. 


Another benefit would be that you can more easily change the UI without confusing/upsetting users.

**Comment by ghys** [comment]
This functionality is offered in the developer sidebar (#437).
