### ISSUE TITLE
Full icon reference with iconset not properly handled for Buttongrid sitemap elements created with Main UI

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2242]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

I have a custom iconset and want to use icons from it as mappings in buttongrid. Basic UI seems to do some invalid parsing of the icon name. I use https://community.openhab.org/t/iconify-icon-provider-4-0-0-0-5-0-0-0/149990 and the icon `oh:mdi:television`.

As item icon is works, but when using as mapping in a buttongrid mapping, the following URL is loaded: `https://openhab/icon/oh?iconset=classic&format=svg&anyFormat=true`
It should load `https://openhab/icon/television?iconset=mdi&format=svg&anyFormat=true`

## Your environment

```yaml
openHAB 4.1
```

**Comment by mueller-ma** [comment]
Issue seems to be in openhab-core. The following line is converted wrong: `KEYCODE_DPAD_UP=Up=oh:mdi:chevron-up`

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/f2fe1ebd-76e1-4c9f-9bad-52c4851baa40)

**Comment by mueller-ma** [comment]
@lolodomo Can you move this issue to openhab-core?

**Comment by lolodomo** [comment]
Try to surround your icon ref with "", it should then work.

**Comment by lolodomo** [comment]
As the ":" is used as separator for the row and column number, there is probably an error that only takes the third element of the string split instead of the third and next.
I hope using "" could be a workaround.
Is it with a sitemap defined in file or through the Maiun UI sitemap generator ?

**Comment by lolodomo** [comment]
For the sitemap generator of Main UI, the problem could be at this line:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java#L382

**Comment by lolodomo** [comment]
Such syntax is properly working for me when I use a sitemap file: `3:5:ALARM_PLUS="Alarm +"=if:lucide:alarm-plus`
So that is fine.
I guess your problem is with the sitemap generator and potentially the code line I previously mentioned.

**Comment by lolodomo** [comment]
I tested using `oh:classic:chart` in a sitemap file and it works as expected. So it confirms the problem is only with sitemaps generated by Main UI.

**Comment by mherwege** [comment]
The line you link is indeed likely causing it. But I don’t rule out an issue in the sitemap builder code as well.

**Comment by lolodomo** [comment]
@mueller-ma : please confirm your issue is fixed in snapshot 3814.

**Comment by mueller-ma** [comment]
Fix confirmed. Thanks :)
