### ISSUE TITLE
[BasicUI] Icons (OH source) in buttongrid mappings aren't updated based on color theme

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2249]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

I have a set BasicUI to dynamic theme and a Firefox to dark theme. Some icons are updated to be white, so the contrast ratio to the background is higher. This doesn't work for icons in buttongrid mappings:

1. Icon is `oh:mdi:chevron_up`
2. Icon is `oh:mdi:chevron_up`
3. Icon is `f7:arrowtriangle_left`

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/bca7dd52-7fee-4a9e-aa6c-0d3ef3a90dbd)

## Expected behavior

All icons should be updated.

## Your environment

```yaml
openHAB 4.2.0
Build #3814
```

**Comment by lolodomo** [comment]
For icons provided by the openHAB server, you need to enable the Baisc UI setting named "inline SVG".
Not necessary for other icon sources (f7, material, iconify).

**Comment by lolodomo** [comment]
Ok, I understand, the specific treatment applied to widget icons (to download and embed the SVG icon in the page) is not applied for icons in buttons (switch or buttongrid).
