### ISSUE TITLE
[BasicUI] Non printable characters in item state breaks UI

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-webui#2250]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

The value of a string-item breaks UI.

```
    Frame label="MyLabel"{
        Text label="Device" icon="none"{
            Frame label="Info"{
                Text item=Device_Log
                Text item=Device_Status
            }
        }
    }
```

```Device_Log``` is a String item with the value ```[0;32m[I][mqtt:224]: MQTT Connected![0m```.
Once I click the on "Device" the whole UI breaks and does not react any more.

## Expected behavior

The UI does not crash and shows the value

## Steps to reproduce

Set item state accordingly, click in GUI.

## Your environment

```yaml
runtimeInfo:
  version: 4.0.4
  buildString: Release Build

```

## Browser console

![grafik](https://github.com/openhab/openhab-webui/assets/10754716/82f9ee7a-4e98-4187-9584-bdd7fedf1816)

**Comment by lolodomo** [comment]
What's exactly this first character? I guess we see how it is rendered but not how it is coded in the item state and so how it is in REST API or SSE message ?

**Comment by lolodomo** [comment]
If you remove the two occurrences of this special character, is the problem solved ?
Just an idea: maybe a problem with encoding of special characters.

**Comment by spacemanspiff2007** [comment]
The value is how I copy pasted it from the rest api.
I think it's supposed to be the ansii color code for green: `\e[0;32m`


> a problem with encoding of special characters.

That's what I think too. I would not expect basicui to display these colors, just that it doesn't crash ...

**Comment by lolodomo** [comment]
I can't reproduce your problem.
I tested on my PC with Firefox and Chrome, opening the page while the strange value is already set and setting it while the page is already opened. In each time, the UI is still OK and continue taking updates.

![image](https://github.com/openhab/openhab-webui/assets/10186704/ab149475-7e42-4181-bf7b-24d68074bfb2)

Here are my updates of the value in the console:
![image](https://github.com/openhab/openhab-webui/assets/10186704/dfb62857-48da-429f-8dc7-0a667d8663f6)

And my sitemap:
```
sitemap test22 label="Test special value"
{
	Frame label="MyLabel" {
		Text label="Device" icon="none" {
			Frame label="Info" {
				Switch item=TestSwitch
				Text item=TestString
			}
		}
	}
}
```

**Comment by spacemanspiff2007** [comment]
Have you sent it as ``\e[0;32m`` or copy pasted from the issue above?

**Comment by lolodomo** [comment]
Copy/paste

**Comment by spacemanspiff2007** [comment]
The � is already a printable char and will not result in an error. 
I'll try to provide a python snipped which causes the issue.

**Comment by lolodomo** [comment]
Also tested with `\e` and still no problem for me:
![image](https://github.com/openhab/openhab-webui/assets/10186704/ec6c97da-6ffb-4f41-9dc6-2593e50182a5)

**Comment by spacemanspiff2007** [comment]
I am unable to create a reproducable example without my network sensors that sends these logs.
How shall we proceed?

**Comment by lolodomo** [comment]
> How shall we proceed?

You could for example add a log in the binding that updates the channel state to log the state value as hexadecimal. Or debug the binding by adding a breakpoint to look at the value of this strange value.

**Comment by spacemanspiff2007** [comment]
While I am not capable of doing that it gave me the correct idea!
The item is updated through mqtt and I was able to log the sent data as bytes and provice a python snippet which results in the error.
Thanks for the hint!


You'll need the [requests library](https://pypi.org/project/requests/) to run this.
Let me know if you need help setting it up.

````python
from requests import put

URL = 'http://localhost:8080/rest/items/TestString/state'
HEADERS = {
    'Content-Type': 'text/plain',
    'Authorization': 'Bearer <TOKEN_FROM_API_EXPLORER>'
}

DATA = bytes.fromhex('1b5b303b33326d5b495d5b6d7174743a3232345d3a204d51545420436f6e6e6563746564211b5b306d')

ret = put(URL, headers=HEADERS, data=DATA)
if ret.status_code != 202:
    print('Error', ret.status_code)
    print(ret.json())
else:
    print('OK')

````

**Comment by lolodomo** [comment]
I have no Python on my PC, sorry.

Looking at your hexa value, the only special character is 1B which is the escape character (and not the backslash which is 5C).
Can you try again without the two 1B in the value to confirm that.
And finally try with only 1B30 for example to confirm with a very simplified value.

Maybe we need to filter all characters < 0x20 ?

**Comment by lolodomo** [comment]
In fact, in your example `\e` was a unique character 0x1b.

**Comment by spacemanspiff2007** [comment]
If I remove `1B` UI works as expected. Sending `1B30` breaks it again.

> Maybe we need to filter all non printable characters (characters < 0x20 and 0x7f) ?

Imho filtering out would be misleading because the item state is different? Maybe replace with the questionmark � to indicate that it's a non-printable character?
What about newline and carriage return?
Or maybe do a character replace like encoding in url?

**Comment by lolodomo** [comment]
Maybe we should simply replace character 0x1b by string `&#27;` ?
Of course same for other control characters.
WDYT ?

**Comment by spacemanspiff2007** [comment]
I'm not sure about it. If I search the internet for ` &#27;` I don't find anything. What kind of replacement syntax is this?
It should be something that is easily searchable (e.g. `\x1d`) but I think it's that's not a a very nice solution because it's not immediately clear where the hex value starts and where it ends.

I think for BasicUI the [unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) is sufficient, because we just want to view values.
That's what the swagger returns, too (see my first post where I copy pasted the value from the api explorer).

**Comment by lolodomo** [comment]
> I'm not sure about it. If I search the internet for ` &#27;` I don't find anything. What kind of replacement syntax is this?

It is just the HTML standard for non standard characters. You provide its code number like that.
1b in hexa equals 27 in decimal.
You can easily find table on internet.

**Comment by spacemanspiff2007** [comment]
> You can easily find table on internet.

I'm aware that 1b hex is 27 dec but if I search for `&#27;` I find nothing :confused: . 
Maybe add an info to the docs that non-printable characters are html escaped and a link to an example table?

In the end I am happy with � or any defined behavior as long as it doesn't crash :laughing:

**Comment by lolodomo** [comment]
But I am also ok with the replacement character if everyone think it is better.

As I have no easy way to test that in practice, are you ready to test a patched version of Basic UI ?

**Comment by lolodomo** [comment]
@spacemanspiff2007 : are you volunteering for testing a fix in a 4.2 snapshot?

**Comment by spacemanspiff2007** [comment]
If I only have to download the lastest snapshot build an run it I'll gladly test it.

**Comment by lolodomo** [comment]
No, you will have also to deploy a specific version of BasicUI I will provide containing the fix I propose.

**Comment by lolodomo** [comment]
Or I have to find a quick and easy way to reproduce your issue (without the need to install additional software).

**Comment by lolodomo** [comment]
A simple change in SendConsoleCommandExtension should allow me to reproduce the problem and so test any fix.

**Comment by lolodomo** [comment]
In BasicUI backend (when the page is first opened), we are using StringEscapeUtils.escapeHtml4 from org.apache.commons.lang3 to escape any non HTML characters. Strange that it would not work. I will check how this method handles the \e character for example.

In BasicUI frontend (when the page content is updated), we use this dedicated JS function handling only 3 special characters (& < >):
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.basic/web-src/smarthome.js#L2314

**Comment by spacemanspiff2007** [comment]
There are also portable python versions available (e.g. WinPython) if you run windows.
If you can reproduce it without python even better! :)
In any case if I can test something without having to set up the dev environment for openHAB I'm happy to help.

**Comment by lolodomo** [comment]
I was finally able to reproduce the issue.
I fixed the opening of the page.
It looks like the update of the item when the page is already opened is working but the non printable characters are not visbile. For consistency, I should also display the unicode replacement character. So I will update the JS function.
