### ISSUE TITLE
Support an arbitrary URL as an icon source

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2255]
Proposal: ~~Icon source `url`, e.g. `url:https://www.example.com/customicon.svg?xxx=yyy`~~
Allow `http(s)://xxx` for icons. The current implementation will simply see this as `http`/`https` icon source.
This would need to be supported by mainui, basicui, android and ios

Example:
```
Sitemap default {
  Text label="test" icon="https://www.example.com/icon.svg"
}
```

### Coordination between maintainers

Notify maintainers of other UIs:
@openhab/webui-maintainers 
@openhab/android-maintainers 
@openhab/ios-maintainers

**Comment by lolodomo** [comment]
We have already 4 possible icon sources and the choice between thousands of icons.

Note that the syntax you propose will not work in items file. This will require an update of the item syntax in core framework.
For sitemap, it would be possible to use your syntax by surrounding the value with double-quotes.
Change in Basic UI would be relatively easy I believe.

**Comment by jimtng** [comment]
The changes required can be done, and I can submit the required PRs.

The main question is: do we want to support this?
Despite the thousands of icons available, there's always something that doesn't quite fit, e.g. special logos.

Currently we'd have to manually download the custom icon and place it inside `conf/icons`.  While this is great from latency aspect, being able to just point to a URL, which is not unlike iconify, would improve the convenience factor tremendously.

**Comment by jimtng** [comment]
I've decided to just manually download the icons for now.
