### ISSUE TITLE
[BasicUI] Missing setting `nbColumns` in `services/basicui.cfg`

### ISSUE THREAD

**Issue by stefan-muc** [openhab/openhab-webui#2261]
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

During upgrade from openHAB 4.0 to 4.1 my Basic UI layout breaks, as the new default are now 3 colums on the desktop as #2018 got merged.

I didn't see this announced in the changelog.

And there also is a setting for it, which is missing in `services/basicui.cfg` - otherwise I would have noticed earlier.

## Expected behavior

I suggest adding this setting to the config file too:

```diff
--- services/basicui.cfg
+++ services/basicui.cfg
@@ -10,6 +10,11 @@
 #
 #condensedLayout=false

+# The number of columns to consider to fill the grid in large screen witdh
+# (desktop) and medium screen witdth (tablet)
+#
+#nbColumns=3-2
+
 # Displays all widget states in uppercase.
 #
 #capitalizeValues=false
```

**Comment by lolodomo** [comment]
I will enhance this file, this is not the only missing setting.
