### ISSUE TITLE
Field "Location" of a thing is editable despite file based configuration

### ISSUE THREAD

**Issue by pelerner** [openhab/openhab-webui#2272]
## The problem
Despite file based configuration, some properties of a thing are open to be edited, s. screenshot.

![openhab-webui](https://github.com/openhab/openhab-webui/assets/24792455/0ba4e832-cdde-4620-859b-b7a74029a00e)

## Expected behavior
For reasons of consistency with file based configuration, field "Location" should not be deletable/editable.

## Steps to reproduce
1. Create file based config for thing.
2. Goto Main UI and try to edit field "Location"

## Your environment
Raspberry Pi 4 Model B Rev 1.4 / 8 GB
aarch64 GNU/Linux with linux-rpi kernel 6.6.10-1-rpi
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
Openhab 4.1.1

**Comment by rkoshak** [comment]
Does it generate an error if you try to save it or does it just silently ignore the change?
