### ISSUE TITLE
OH4.1x MainUI Widget Dropdown List Missing Newly Created Items

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-webui#2281]
## The problem
Newly created items do not show not show up on widget item drop down list. 

## Expected behavior
New items should be in the widget list

## Steps to reproduce
Create new item and create new create page. add Label card and choose item.

1. 

## Your environment
OH4.1.1 Ubuntu Linux

```yaml

```

## Browser console

```txt

```

**Comment by florian-h05** [comment]
Can you please provide the information requested in the issue template? Otherwise this issue is invalid and I will have to close it.

**Comment by lsafelix75** [comment]
Please close it as it was created harshly on my phone to capture that moment of issue. Anyway, the problem is resolved in OH4.1.1
