### ISSUE TITLE
Transformations missing as link in left menu

### ISSUE THREAD

**Issue by Wikibear** [openhab/openhab-webui#2283]
I'm wondering a little bit that there is no direct link to transformations... I feel it like a little bit hidden within administration. My wish was, that there is also a direct link to transformations:

![grafik](https://github.com/openhab/openhab-webui/assets/18314278/79d3debb-c6c8-4ef2-8cd7-f140460752cf)

**Comment by rkoshak** [comment]
This was discussed when Transformations were first added. It was decided that space should be carefully managed in the left menu and transformations did not make the cut. It's not an oversight. It was a deliberate decision.

**Comment by Wikibear** [comment]
OK sounds bad. It's more consistent if everything is avail within administration, without left menu. For me that isn't very intuitive and it confuses me every time.

**Comment by florian-h05** [comment]
Whilst I agree that it might be uncomfortable to not have transformations in the menu bar, this is a deliberate decision made by the UI maintainers.
When transformations were added, we decided to differ between first and second level configuration, and transformations is compared to Items, Things etc. only second level.
As Rich already wrote, we have to be careful what to add to the left menu.

On openHAB 4.1 this might not seem to be a problem as there is only transformations as second level transformation, but with the current openHAB 4.2 snapshot we have a new persistence settings menu as second level configuration, and once I have the time to develop the semantic model edit page, there will be a third entry:

![IMG_2408](https://github.com/openhab/openhab-webui/assets/73423173/3f5d729c-301a-4044-a468-df697ec1817b)

Adding these three entries to sidebar would make it to big, and it would need to be scrollable on some devices, e.g. on my iPad.

**Comment by Wikibear** [comment]
So, then we don't need everything in menue if we discuss here with first level and second level and the you have a third level with automation. This isn't consist for me and it's bad that there isn't another discussion and that the topic is closed now.

**Comment by florian-h05** [comment]
Automation settings are in the third section, but are first class setting.

The way the settings are ordered and structured follows the idea, that you first add a Thing, then add the Items using the model or the Items page and then put the Items on pages.

Then you can set up transformations and persistence, which is not the most important for getting openHAB up and running, and unlikely to be reconfigured as often as Items or Things.

And finally, you can make openHAB smart by adding automation.

In case you have a proposal how to structure the sidebar without growing it too big, feel free to share it.

**Comment by florian-h05** [comment]
Automation settings are in the third section, but are first class setting.

The way the settings are ordered and structured follows the idea, that you first add a Thing, then add the Items using the model or the Items page and then put the Items on pages.

Then you can set up transformations and persistence, which is not the most important for getting openHAB up and running, and unlikely to be reconfigured as often as Items or Things.

And finally, you can make openHAB smart by adding automation.

In case you have a proposal how to structure the sidebar without growing it too big, feel free to share it.
