### ISSUE TITLE
UoM Metadata is not added to an item when created from channel 

### ISSUE THREAD

**Issue by EngiNearEngiFar** [openhab/openhab-webui#2299]
## The problem

When creating a new item form a Channel the metadata infromation "Unit" and “State Description Pattern” are not added to the item. 

## Expected behavior
The metadata information for UoM has to be added. 

## Steps to reproduce

1. Create an item from a Channel:
![grafik](https://github.com/openhab/openhab-webui/assets/83063002/b497a5c6-fc7c-4b06-9916-966425a84de9)
2. metadata information ("Unit" and “State Description Pattern”) is missing: 
![grafik](https://github.com/openhab/openhab-webui/assets/83063002/a7fef6bc-2dec-4461-a36f-da6d1b2d49d6)

## Your environment

```runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Private Build
  osName: Linux
  osVersion: 6.1.11-meson64
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 144815208
  totalMemory: 1073741824
  uptime: 978708
  startLevel: 70

```

## Additional information
remark #1: The problem is also described here:
[openHAB forum](https://community.openhab.org/t/mqtt-unit-of-measurement-is-not-applied-when-creating-a-item/153582?u=tuny)
remark #2:
When creating an item from model view the metadata is created.

**Comment by florian-h05** [comment]
That Item metadata is missing is a bug, I will fix that.
State description metadata however is only saved if you change the pre-filled default value, I will clarify this in the description.
