### ISSUE TITLE
Change Name to <object> ID in all edit pages

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-webui#2335]
Name for the average user is the attribute to name (label) things and not identify them, so `Name` and `Label` both used in the edit page can really confuse the average user.

Also `Name` is used to label things in many other apps, for example: Google Home, Alexa and even Home Assistant.

see discussion here:
https://community.openhab.org/t/item-editor/153739/23?u=massi

## Your suggestion

Change in all MainUI object editing pages:

Name —> <object> ID

so:
Thing ID
Channel ID
Page ID
Item ID
any other ID

**Comment by rkoshak** [comment]
You'll also need to open an issue in the docs repo to change everywhere the Item ID is referred to as "name" everywhere there as well.

openhab-js and openhab-jruby would need an issue to discuss changing the term there also and figure out if there's a way to do so without a breaking change.

OH core might need an issue as the `event` Object injected into a rule (for Rules DSL the implicit variables) also use the term "name".

It's call the "name" in the JSONDB meaning it's also called the "name" in the "Code" tab in MainUI. So it might need another change in core to handle that.

I don't know if the docs for the add-ons need to be reviewed and updated too. 

Note that these are just the user facing places where the Item's ID is called it's "name" and it would need to change. This is a *much* bigger job than just changing a few labels in MainUI. If it only changes in MainUI, all you've done is move the problem and caused confusion. Consistency is important.
