### ISSUE TITLE
Add Item unit, state, description (all fields) when in editMode

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#2353]
PR #2326 **wrongly** removed the visibility of Item configuration fields from the Item UI form when in edit mode.

@jimtng I have created https://github.com/jimtng/openhab-webui/pull/3 so you can have a look at the aligned inputs. This PR also hides unit/state description if not in createMode, let's take care of those later.

_Originally posted by @florian-h05 in https://github.com/openhab/openhab-webui/pull/2326#discussion_r1491116475_

These fields must be re-added in a new PR -- eventually in #2312 or other PR.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by florian-h05** [comment]
Fixed by #2312.
