### ISSUE TITLE
Chrome didn't find favicon.

### ISSUE THREAD

**Issue by Daniel-at-git** [openhab/openhab-webui#238]
Chrome (Version 81.0.4044.122) didn't show favicon.

OH2 running (on port 8080) under /start/ but it tries to fetch favicon from /.

In Chrome console you get the message
favicon.ico:1 GET http://openhab2:8080/favicon.ico 404 (Not Found)

# openhab-cli info
Version:     2.5.4 (Build)

**Comment by lolodomo** [comment]
dashboard got removed with OH3
