### ISSUE TITLE
[habpanel] Item ordering and filtering in template selection

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#239]
Since the order of items is not alphabetically and sometimes quite confusing (see https://github.com/openhab/org.openhab.ui.habpanel/issues/340), a working filter function is essential.

But the ordering when filtering for an item name seems to be quite random. Eg. I filter for "g_EG_Licht", a group containing quite some lights. The filter function seems to include all items within that group as well (which is a nice idea but imho quite confusing) and the real group with the exact name I'm looking for is somewhere mixed in in the results list.

It gets worse when I search for "g_EG" which is a group, but also a partial match to the other group and thus the result contains >30 entries with the wanted one in the middle somewhere.

I'd suggest changing the ordering of the results so that entries that directly match with the item name appear on top of the list and only then the items that match via some hidden criteria (e.g. are contained in the griup that is searched for) are displayed.

**Comment by paullangner** [comment]
I know that this is not the greatest solution, but if you click on the list of items, the list becomes searchable via the web-browser Search function

**Comment by eikowagenknecht** [comment]
Closing my issues with openHAB that seem to have gone stale.
