### ISSUE TITLE
Help page for blockly

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2416]
@florian-h05 / @stefan-hoehn could you please make a special help page for blockly? You're more familiar with the process. I'm going to add a few more features for blockly and it would be handy to have a help page for it.

Thanks!

**Comment by stefan-hoehn** [comment]
What do you need that for? We already have help button in the workspace:

<img width="169" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/0bad8a44-fe63-4abf-959a-4027a272aff5">

Where exactly would you want to link this special help page?

**Comment by jimtng** [comment]
I want one in the developers toolbar.

It serves a different purpose to the ones in the toolbox (your screenshot).

The Dev toolbar one explains general usage of blockly mouse/trackpad navigation, select block and drag away to delete, or simply clicking and pressing delete, etc.

**Comment by stefan-hoehn** [comment]
I think you are refering to the Sidebar (:

<img width="494" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/25dcab91-58c5-4059-a005-c75ec7b83a70">

This has been lately (4.2) redesigned and reimplemented and the whole content now is taken from openhab-docs. 

see https://github.com/openhab/openhab-docs/blob/main/mainui/index.md?plain=1 

in particular the section from 



to

**Comment by jimtng** [comment]
> I think you are refering to that Sidebar, right?

Yes, sorry I didn't know the correct name for it
