### ISSUE TITLE
[PaperUI] configure Channel dialog formatting error

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#246]
In the PaperUI | Channel | Configure dialog box, there is a formatting error. If the configuration parameter is declared as a boolean, then the dialog displays a Switch, but it overwrites the label text. See attached screenshot..

![image](https://user-images.githubusercontent.com/893994/81408794-c6a1ad00-9135-11ea-8bb8-da8141231917.png)

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
