### ISSUE TITLE
HANDLER_INITIALIZING_ERROR: Getting handler 'script.ScriptAction' for module '1' failed: Config parameter 'script' is missing in the configuration of module '1'. 

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#2461]
## The problem

The error "HANDLER_INITIALIZING_ERROR: Getting handler 'script.ScriptAction' for module '1' failed: Config parameter 'script' is missing in the configuration of module '1'. " is shown when I try to add a script action to a new rule.

## Expected behavior

No errors should be shown.

## Steps to reproduce

![grafik](https://github.com/openhab/openhab-webui/assets/22525368/bd506f12-468c-498f-96cf-81b0a94d4210)
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/324a8535-0ea8-4701-8c70-17a570765ad2)
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/1897019d-cf5c-48f8-8d0d-68e46dcfa3cb)

The script text editor now opens for a short moment, but is closed immediately. 
![grafik](https://github.com/openhab/openhab-webui/assets/22525368/db2415aa-b412-412c-a3fa-0c311378f65b)

## Your environment

```yaml
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: de-DE
```

**Comment by florian-h05** [comment]
Fixing this is a bit more complicated, the fix consists of two parts: A core PR and a Main UI PR.
For the core PR, see https://github.com/openhab/openhab-core/pull/4148.
