### ISSUE TITLE
[basicui] [classicui] sitemap Selection widget state display anomalies

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-webui#247]
When using the Selection widget in a sitemap, choices of commands available to the user are defined in a `mappings=[ ]` parameter.   The Item however may have states unrelated to the mappings options.  The widget only displays states that match one of the mappings, and otherwise ignores state presentation options both of the Item definition, and of the sitemap label="blah [format]"

Example, using UP DOWN STOP mappings with a shutter, with state in %.

Demo of the issue - here a Number Item represents alarm states 0-4, with mapped state text.
A Selection widget is desired to show the actual state, but offer only some of the possible states as commands e.g. arm, disarm, but not other states, e.g. fault or ringing. 
The sitemap includes a test Switch to simulate all states for the demo.

Item
`Number testDemo "Demo Alarm [MAP(demo.map):%s]"`

demo.map
```
0=fault
1=disarmed
2=reset
3=armed
4=Ringing
```

sitemap
```
			Switch item=testDemo label="Simulation []" mappings=[0="Fault",1="Disarm",2="Reset",3="Arm",4="Ring"]
			Text item=testDemo label="raw state [%s]"
			Text item=testDemo label="MAPped state"
			Selection item=testDemo mappings=[1="Disarm",2="Reset",3="Arm"]
			Selection item=testDemo label="force raw state [%s]" mappings=[1="Disarm",2="Reset",3="Arm"]
			Selection item=testDemo label="suppress state []" mappings=[1="Disarm",2="Reset",3="Arm"]

```

Results; only matches from mappings are displayed for Item state.
MAP is ignored, only text from mappings is used.
No match, no display.
Empty format in "label []" normally suppresses state display, does not work in BasicUI (this part does work in ClassicUI)
I do not know the behaviour, good or bad, in the "app" UIs

See forum post for images of UI
https://community.openhab.org/t/displaying-states-and-commands-of-a-selection-item-on-a-sitemap/98600/6

**Comment by lolodomo** [comment]
I see nothing that is not expected. Selection widget shows only the values from the defined mappings.

**Comment by Rossko57** [comment]
So by design, you cannot display the state of an Item where it is not included in mappings=[ ]?  I wonder what is the purpose of that.  mappings is about commands, state is something different.

**Comment by lolodomo** [comment]
You can use a switch widget in case you would like the display of state in addition to the command mappings.

**Comment by Rossko57** [comment]
Yes, a circumvention, given few enough mappings.
I'm curious why one widget, like a Switch, would be able to support Items with different state to mappings=[ ] command choices, and the Selection widget will not.  Doesn't seem to be any logic to that.

**Comment by lolodomo** [comment]
I can understand you see that as inconsistent.
For the switch widget, we have 2 objects, the item state and the buttons for mappings.
What would be your proposal of rendering for a selection widget ?
If we keep two objects, this will make 2 texts to present, the item state and the text from the selected option. Will be not understandable to the end user.
If your proposal is to add the current state to the list of options if the user did not define it, I would say that the app will bypass what the user requested from his sitemap. This would require a potential update of the list of options at each item state. Is it your proposal ?
This would be easy to change in ClassicUI as the page is refreshed at any item state.
This would be a more difficult change in Basic UI as this will require a management of the option list in the frontend too.

**Comment by Rossko57** [comment]
> If your proposal is to add the current state to the list of options if the user did not define it,

No, no, not at all.
Using Switch widget as a model, it can display current Item state as plain text in the right hand part of the display line.  `mappings= [ ]` can be used to define some predefined buttons as well.
The state need not be related to any of the buttons text or commands.  The format of the state, or if indeed it is displayed at all, is under the control of [state formatting] element embedded in Item or sitemap label.
The state display does not affect the buttons, which are controlled by mappings.

"ASCII art" example, with `mappings=[100="UP",50="MIDDLE",0="DOWN"]`
**(icon) My Roller     67%  [UP] [MIDDLE] [STOP]**

I'm proposing Selection widget can behave similarly.
When not clicked, it can display current state in the righthand part of the display, under control of label [format] elements, alongside the clickable **>**.   This display does not alter the selection drop-down in any way, and thu user chooses to format or hide it exactly like every other widget.
Without the drop-down selection list visible, the mappings=[ ] are irrelevant at this point.

"ASCII art" example, with `mappings=[100="UP",50="MIDDLE",0="DOWN"]`
**(icon) My Roller     67%  >**

When the **>** is clicked and the drop-down appears, that is entirely controlled by the mappings=[ ] content.  The state value and display is mostly irrelevant.
"ASCII art" example, with `mappings=[100="UP",50="MIDDLE",0="DOWN"]`
**( ) UP**
**( ) MIDDLE**
**( ) DOWN**

Should the actual state match one of the selections, e.g. 50 in this example, then that particular selection can be (should be?) highlighted or pre-selected.

"ASCII art" example, with `mappings=[100="UP",50="MIDDLE",0="DOWN"]` and Item state 50
**( ) UP**
**(X ) MIDDLE**
**( ) DOWN**

**Comment by lolodomo** [comment]
Ok I understand your proposal.
The current behaviour would be unchanged if a matching is found but if not found, the UI would then display the item state according to the defined format in place of an empty string (result of no match found).
To be checked how hardly the displayed text is in the main page is linked to the list of options.

**Comment by lolodomo** [comment]
For ClassicUI, I think it is very easy to change.

**Comment by lolodomo** [comment]
In BasicUI, the change to apply is the same in the backend, that is when the page is first opened, but then this has to be handled in the frontend for the live updates coming from SSE (I have not checked this part).

@kaikreuzer : can we still propose changes/fixes to Basic UI and Classic UI for next 2.5.x distributions ? I guess the PRs have to be pushed to branch 2.5.x ?

Will Basic UI and Classic UI still be in OH3 distributions ? I hope at least Basic UI will.

**Comment by ghys** [comment]
> Will Basic UI and Classic UI still be in OH3 distributions ? I hope at least Basic UI will.

Basic UI will still be there in OH3 but Classic UI will not.

**Comment by lolodomo** [comment]
I fixed Classic UI, there was a stupid bug. I just need to find how to push in the branch 2.5.x.

**Comment by lolodomo** [comment]
BasicUI is fixed too (in branch 2.5:x only).

**Comment by lolodomo** [comment]
> > Will Basic UI and Classic UI still be in OH3 distributions ? I hope at least Basic UI will.
> 
> Basic UI will still be there in OH3 but Classic UI will not.

Good, that will help to validate the new UI against the reference (BasicUI).

**Comment by lolodomo** [comment]
As the 2 PRs have been merged, this issue can be closed now.
