### ISSUE TITLE
[defaultui] Pages don't load properly when "Disable page transition animations" is on

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#250]
I always prefer speed over fancy animations so I turned on all these options for more speed some time ago in "Help & About":

![options](https://user-images.githubusercontent.com/12213581/82139431-03516080-9828-11ea-940d-c73f870089f7.png)

While testing I always noticed I had to manually reload pages or content doesn't load properly. I thought it was just some WIP issue but now I revisited those options and it only seems to be an issue when the "Disable page transition animations" is on. When I disable it the UI is a lot more usable. :wink: 

Should we already create issues for these kinds of issues based on the current development state @ghys?

**Comment by ghys** [comment]
It's been a while since I enabled that option, but it seems you're right @wborn ...although I'm pretty positive it used to work better, so there must have been a regression along the way. It's just a rather ugly CSS override, so with the regular Framework7 upgrades it may have broken at some point. I'll look into it.

> Should we already create issues for these kinds of issues based on the current development state @ghys?

Of course, I think we can consider the UI should be functional by now, and it's a pretty serious issue, thanks for reporting it!

**Comment by ghys** [comment]
@wborn it seems to work much better now with #252.

btw protip: I often put newer jars of the UI that I compile myself or get from Jenkins in `runtime/org/openhab/ui/bundles/org.openhab.ui/3.0.0-SNAPSHOT`, then restart OH3 with:

` rm -rf oh3/userdata/tmp/* && rm -rf oh3/userdata/cache/* && oh3/start.sh`

so I can have the latest UI on my production instance without updating the distribution :)

**Comment by wborn** [comment]
Thanks a lot @ghys, I'll give it a test soon! I build my own distro using updated core/ported add-ons/webui on a regular basis. :wink:

**Comment by wborn** [comment]
It works well now and the UI feels a lot snappier with it enabled. :+1:

When updating a single bundle, I usually update them using `bundle:update`, that way you don't have to restart Karaf or mess with the cache because Karaf knows best what to do. You can update using files or via http:

```
bundle:update org.openhab.ui file:/home/...
bundle:update org.openhab.ui http://...
```

There's also `bundle:watch` which should automatically update bundles when they change. But I never got that to work. But it would further simplify the development flow when you're just working on a single bundle and want to continuously test changes with Karaf.

**Comment by ghys** [comment]
```
bundle:update org.openhab.ui file:/home/...
bundle:update org.openhab.ui http://...
```
Excellent! Thanks for the tip!
