### ISSUE TITLE
Trigger channel create new Item wrongly requires an existing Item to be selected

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#2522]
### Current Behavior

When using Main UI to try to create a new Item linked to a Trigger Channel, the dialog wrongly requires an existing Item to be selected. See screenshot below..

![image](https://github.com/openhab/openhab-webui/assets/893994/80548a9a-d208-44ef-b108-606da1f84f52)

### Expected Behavior

The dialog should NOT require an existing Item to be selected. Instead it should present the dialog fields for configuring a new Item.

### Background

Platform is openHAB 4.2.0.M1 on Linux. Note: I am not sure if recent PRs concerning Item creation will have already solved this issue in the latest snapshots, as I have not tested this on the latest snapshot. 

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by andrewfg** [comment]
=> @mherwege for info..

**Comment by mherwege** [comment]
That needs looking into again, but rather after https://github.com/openhab/openhab-webui/pull/2485. The new PR’s don’t do anything specific for items on trigger channels. As that would need a profile and there is no item-type, creating an item is different.

**Comment by florian-h05** [comment]
It seems the issue has been solved meanwhile, just checked with one of the latest snapshots.
