### ISSUE TITLE
Cannot update using the Code tab

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-webui#2523]
## Which UI are you reporting an issue for?

- [ ] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

It is not possible to update things using the Code tab

## Expected behavior

Update using the Code tab was possible up to 4.1

## Steps to reproduce

1. Pick an existing thing
2. Select the Code tab
3. Try to update any line -> it will be refused 

## Your environment

OH 4.2.0.M1 (it also happens in snapshot 4027)
Windows 11
Zulu Java 17

## Additional information

This is a serious problem with high impact. It also occurs in QNAP / QTS

**Comment by lolodomo** [comment]
Basic UI does not manage things but items.
I guess you declare this issue for Main UI and not Basic UI.

**Comment by florian-h05** [comment]
Please add a link to the forum posts and update the description to something more meaningful. Thanks.

**Comment by moodyblue** [comment]
Here is the link to the forum

https://community.openhab.org/t/openhab-4-2-milestone-discussion/154316/77?u=moody_blue

**Comment by florian-h05** [comment]
So #2526 should fix this, however I’m not able to test this myself as I’m away from home.
You can check after the milestone release if the issue has been fixed.
