### ISSUE TITLE
[defaultui] "Click on the shield" help text confusing when shield does not show

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#254]
The side menu isn't necessarily showing when using a small browser window or accessing the UI on a smartphone

As a result users may get confused when they see this otherwise very helpful text:

![shield](https://user-images.githubusercontent.com/12213581/82189547-d9fc0780-98ef-11ea-9eda-53d3aec416b8.png)

**Comment by ghys** [comment]
You're right, I noticed too and I'm not happy with it either. These hints are supposed to be temporary but they're still a bit confusing, Maybe it's better to let users discover the shield by themselves on the sidebar unless it's displayed. The onboarding experience will be redesigned at some point too, probably with a initial setup wizard and all, so the "empty" home page is likely to look different in the future.

**Comment by wborn** [comment]
When the Apps panel is shown on the empty homepage you might be able to consistently use the top right corner for handling user sign in/out. The top right corner is used by many other web apps for similar interaction (GitHub/Google/Discourse).

**Comment by ghys** [comment]
Since the home page is loosely designed after the iOS app store by default I thought about putting the account management in the same place as well (but it doesn't work if you enabled the "simple navigation bar"):

![image](https://user-images.githubusercontent.com/2004147/82203857-2e10e700-9904-11ea-8b33-4962b24234e4.png)

**Comment by wborn** [comment]
I just tried disabling "Simple navigation bar on home page" to see if something changed but it didn't. What is exactly simplified by it?

**Comment by ghys** [comment]
Disabled:
![image](https://user-images.githubusercontent.com/2004147/82205404-daec6380-9906-11ea-84e2-00b1f41ad187.png)

Enabled:
![image](https://user-images.githubusercontent.com/2004147/82205337-bbedd180-9906-11ea-8ed1-81ecc62857b0.png)

**Comment by wborn** [comment]
Thanks for pointing out the difference! I didn't notice this slight change. :detective:

**Comment by ghys** [comment]
I finally put the hint in the sidebar in #255 along with some other tweaks, there's enough room in it when there are no pages to display. That'll have to do for now ;)

**Comment by wborn** [comment]
Thanks! It will be fine for now.
I just created this issue because every time I see it I'm reminded of it. :wink:
