### ISSUE TITLE
"URI is too large" when opening the page showing the list of items

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2561]
With snapshot 4064, I can see these logs when I open the items page:
```
08:43:51.043 [WARN ] [org.eclipse.jetty.http.HttpParser    ] - URI is too large >8192
08:43:51.063 [WARN ] [org.eclipse.jetty.http.HttpParser    ] - URI is too large >8192
```
I did not have these warnings with OH 4.2 milestone 2.

**Comment by lolodomo** [comment]
With snapshot 4099, I can't reproduce.

**Comment by lolodomo** [comment]
After in,stalling OH 4.2 milestone 4, the problem is back.
I reloaded the app and do Ctrl+F5 many times but no change.
Same errors when I use Firefox or Chrome or Edge.

**Comment by lolodomo** [comment]
@florian-h05 : I am asking myself if the problem is not #2637

**Comment by lolodomo** [comment]
I am now relatively convinced that the reason is #2367.

**Comment by florian-h05** [comment]
Interesting, I cannot see these warnings in openHAB log, but in dev tools I can see that an icon is requested and 414 Request-URI Too Large is returned.
Thanks for finding the root cause!

**Comment by lolodomo** [comment]
The problem was occurring only when the image was relatively big (more than 8KB).

**Comment by florian-h05** [comment]
In any way, no matter how large the image is, it is wasted bandwidth.
It’s an easy fix, I just need to finish checking all usages of-icon when getting back home.

**Comment by ghys** [comment]
Just to add, this is another reason why icons shouldn't be requested via HTTP every time an item changes state.
