### ISSUE TITLE
Is it normal that Main UI is requesting the list of sitemaps ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2566]
Enabling the DEBUG logs for sitemap REST API, I discovered that opening Main UI in a browser, this API is called. Its role is to retrieve the list of available sitemaps. I am just curious why Main UI is doing that while it does not play at all with sitemaps ?

https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java#L245

**Comment by lolodomo** [comment]
Maybe for the sitemap generator ?

**Comment by mherwege** [comment]
Not for the sitemap generator.
But it looks like it is used to check if an access token is required:
https://github.com/openhab/openhab-webui/blob/8779dcf694049a810cef2247999d55dd38021821/bundles/org.openhab.ui/web/src/js/openhab/auth.js#L91

**Comment by florian-h05** [comment]
Yeah, the comment says that.
I think /rest/sitemaps was chosen because its response is relatively small, e.g. compared to /rest/items.

I will close this issue now.
