### ISSUE TITLE
[mainui] Tabbed Pages do not support expressions in configuration options

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#2571]
So i was hoping to use an expression to customize the label in the tabbed page view, like `=items.Lights_All.state`, unfortunately this does not work as the tabbed page is not actually a component that uses the widget mixin that i think does the expression parsing.   Not sure how to fix this properly.   If someone could give a hint on the right way to support this, i could try and take a stab at fixing this.

 Besides labels supporting expressions, my end goal was to submit a PR that would also enable badging on the tabbed links (see screen shot) , but this is only useful if the configuration supports the jsep expression evaluation used in the widget-mixin. 

<img width="499" alt="image" src="https://github.com/openhab/openhab-webui/assets/1903737/c5eaf957-ea2b-419a-8c68-b6c2e25b5c3b">

**Comment by florian-h05** [comment]
@digitaldan Please have a look at #2591, I have just had a look at this and found a solution. If you are fine with it, can you please review my PR?
