### ISSUE TITLE
[blockly] Persistence extension blocks should return full state for QuantityType

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#2595]
See https://github.com/openhab/openhab-webui/pull/2564

Persistence extension blocks return `numericState` and therefore strip the unit.

While this makes backward compatibility easier (just resave the Blockly rule), it makes QuantityType calculations with the result impossible. This was the whole aim of extending the persistence extensions, so I believe the full state should be returned by default.

This would be a breaking change, and therefore it should probably be done before the 4.2 release to keep everything consistent.

**Comment by mherwege** [comment]
@stefan-hoehn @florian-h05 Sorry to do this, but I think the attempt to keep backward compatibility actually hinders use of the new functionality in this case, and it is different for Blockly and other rules engines. So please reconsider on this.

**Comment by florian-h05** [comment]
I think it should be possible to do this without a breaking change for Blockly users.
Add a new drop-down to the persistence block depending on the currently selected „method“, this drop-down allows to select between the properties of the PersistedState or PersistedItem class. 
By putting the „numericState“ drop-down to the first place, this is effectively the default and therefore this change doesn’t break anything. If the users needs a Quantity or the string state, he can easily select this from the drop-down.

WDYT @stefan-hoehn
