### ISSUE TITLE
[MainUI] Setting “Equipment List” and “Item context label” in home page no editable

### ISSUE THREAD

**Issue by sebSmarthome** [openhab/openhab-webui#2597]
## The problem

in the Main UI I can’t change the settings for the page
/settings/pages/home/home
‘Equipment List’ in Location
‘Equipment List’ and ‘Item context label‘ in equipment
‘Item context label’ in property

## Your environment

openHAB 4.1.2
openHAB last Snapshot

Browser : Brave, Safari and Firefox

## Additional information

works by editing yaml

https://community.openhab.org/t/setting-equipment-list-and-item-context-label-in-home-page-no-editable-in-main-ui/156290

**Comment by EngiNearEngiFar** [comment]
Same problem here. Bug is still in version 4.2.1.
