### ISSUE TITLE
Health Check menu order

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2644]
I just saw my MainUI and noticed the health check item. IMO, the item shouldn't be placed first under Settings, it should be last, since it's not something that people would need to access often.

I understand that this is just an opinion.

**Comment by florian-h05** [comment]
I will try to provide a PR ASAP to remove the health menu from the sidebar and put it above the configuration block in the settings menu so it is separated from the config.
Or should I rather put it somewhere else on the settings menu? If yes, where?

**Comment by jimtng** [comment]
It's tricky to pick a good spot for it!

How about inside Help & About?

**Comment by florian-h05** [comment]
I feel that it’s not prominent enough there and help & about is mostly about local settings stuff …
I would put it on the settings page, but are not sure where to put it there

**Comment by jimtng** [comment]
That's why I said it's tricky.
Theoretically it's not something that you'd need often. It feels out of place anywhere else, and it's technically a form of "help".

Alternatively maybe put it after persistence?

**Comment by florian-h05** [comment]
The problem with putting it on the help & about page, is that it is not visible enough there IMO. This is a reason to put it onto the settings page, where one will immediately notice the red badge if there are any issues.

**Comment by florian-h05** [comment]
What about using a floating action button on the settings menu pahe, just like for the Thing inbox:

![image](https://github.com/openhab/openhab-webui/assets/73423173/22e37c7c-97bf-4122-9fc0-4c6223183827)

I will soon create and merge a PR for that, as we otherwise don't have the time before RC2.
