### ISSUE TITLE
openhab 4.2 - nbColums not respected

### ISSUE THREAD

**Issue by moltke69** [openhab/openhab-webui#2667]
## The problem

With update to Openhab 4.2, the nbColums-setting in setting/basicui.cfg is not respected anymore. Also in the administration settings, the number of columns cannot be changed anymore.

## Expected behavior

In openhab 4.1 it was respected.

## Steps to reproduce

Check behaviour in openhab 4.1 and 4.2 and see the differences.

## Your environment

openhab 4.2 with official docker image (openhab/openhab:latest)

**Comment by lolodomo** [comment]
You can now adjust this setting directly in Basic UI (new settings page).

**Comment by moltke69** [comment]
No, in openhab 4.1 there was this setting, in openhab 4.2 it isn't anymore:

![image](https://github.com/user-attachments/assets/16713484-7051-4a8a-9b2f-cf0099abb631)

**Comment by lolodomo** [comment]
Why creating two identical Git issues ?

**Comment by moltke69** [comment]
Sorry. I thought, I can change the "label". But I can't. But I was also not able to close the issue.
