### ISSUE TITLE
openhab 4.2 basicui - nbColumns not respected anymore

### ISSUE THREAD

**Issue by moltke69** [openhab/openhab-webui#2668]
## Which UI are you reporting an issue for?

- [X] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

With update to Openhab 4.2, the nbColums-setting in setting/basicui.cfg is not respected anymore. Also in the administration settings, the number of columns cannot be changed anymore.

## Expected behavior

In openhab 4.1 it was respected.

## Steps to reproduce

Check behaviour in openhab 4.1 and 4.2 and see the differences.

## Your environment

openhab 4.2 with official docker image (openhab/openhab:latest)

**Comment by lolodomo** [comment]
You can now adjust this setting directly in Basic UI (new settings page).

**Comment by moltke69** [comment]
No, sorry. In openhab 4.1 yes, but not in openhab 4.2 anymore:

![image](https://github.com/user-attachments/assets/238847e1-9d55-4ca2-8bb0-dd6c62a1d306)

**Comment by moltke69** [comment]
By the way: Why should I have a configuration file, if it isn't used completely anymore?

**Comment by lolodomo** [comment]
You show me a Main UI page 
The client preferences are now adjustable in Basic UI.
Read the 4.2 release blog post.

**Comment by lolodomo** [comment]
> Why should I have a configuration file, if it isn't used completely anymore?

It is still used for the 2 remaining parameters which are not browser preferences but server preferences.

**Comment by moltke69** [comment]
I showed you the Basic UI configuration
https://[name of openhab-server]/settings/addons/ui-basic

**Comment by moltke69** [comment]
> It is still used for the 2 remaining parameters which are not browser preferences but server preferences.

Hopefully, I can use the the configuration file for all parameters.

**Comment by lolodomo** [comment]
https://www.openhab.org/blog/2024-07-07-openhab-4-2-release.html#basic-ui-enhancements

![image](https://github.com/user-attachments/assets/4b2f254f-b401-4b20-bf99-d6328cce710d)

**Comment by moltke69** [comment]
Thank you, I have seen this. But it's for me not visible. And by the way, I'm not using the UI, I'm using the configuration files. This was my question, that nbColumns is not respected in the services/basicui.cfg file.

Maybe, that the "update-script" is buggy, and that I have to do a full clean of the "userdata". I will check this.

**Comment by lolodomo** [comment]
> This was my question, that nbColumns is not respected in the services/basicui.cfg file.

Yes, it isn't anymore. UI preferences are now handled in a similar way in Main UI and Basic UI (even with 2 common settings), not in a configuration file.

**Comment by moltke69** [comment]
Thank you. That means, with openhab 4.2 the server is not configured only with the configuration files,  but you need also the "UI to configure your system"? Is this right?

**Comment by lolodomo** [comment]
And you cannot set Android app and iOS app preferences in a file but in the app directly.

**Comment by moltke69** [comment]
Depends on the app. E.g. "fairmail" I can configure completly by file.

**Comment by moltke69** [comment]
But this is not the question. A "server" is mainly configured by configuration files and not by an UI. Therefor I asked, if openhab changed their configuration strategy. Nothing else.

**Comment by lolodomo** [comment]
> but you need also the "UI to configure your system"? Is this right?

No for setting up the server but yes for setting up UI preferences to let each user of the system decide what he prefers as rendering by his UI and something that can be different on his phone or desktop screen.

**Comment by lolodomo** [comment]
> Depends on the app. E.g. "fairmail" I can configure completly by file.

I was talking about openHAB apps.

**Comment by lolodomo** [comment]
> Therefor I asked, if openhab changed their configuration strategy. Nothing else.

No change of strategy for configuring the OH server.

Only a change of strategy for Basic UI preferences for the different reasons I explained (convergence with Main UI, advantage to have UI preferences on UI device).

**Comment by moltke69** [comment]
Now I found also the "configuration page" (as in the release 4.2 page, it was not explained, where to find): It top left on the first page of the "sitemap"

![image](https://github.com/user-attachments/assets/732d9b09-e5b1-40ec-b225-d26734b30da1)

Good to know.  I have not seen this, as there have been a "house" for years. Maybe it's a good hint to mention it.

Last question: Where are these parameters stored (as I clean from time to time the "userdata" to get a fresh installation)?

**Comment by moltke69** [comment]
Forget it: I realized, that they are not stored on the server, but as a cookie on the browser.

**Comment by moltke69** [comment]
One stupid question as I'm not so familiar with GitHub, how to open a request? 

If I saw it right, I cannot open a request, therefor I would open one:

## Request

1.) All basicui parameters should be configured also in "services/basicui.cfg" as default parameters
2.) "UI configuration page" should be disabled also by configuration file "services/basicui.cfg"

##Reason

1.) The basicui configuration the "parameters" are stored as "cookies". But cookies are deleted in proper configuration regularly (e.g. if I close my window). Than I have to do the configuration new. If I have the opportunity to define "default parameters" in "services/basicui.cfg", than I do not have to "reconfigure" each time.

2.) If you use basicui also for "guests in your house" on e.g. a tablet, the guest should not reconfigure your parameter. Therefor it should be an opportunity to disable the "ui configuration page".


Thank you.

**Comment by moltke69** [comment]
Forget it. I can do it by myself with my "own css".

@media (min-width: 840px) {
    .mdl-cell--6-col {
        width: calc(50% - 16px);
    }
}

**Comment by lolodomo** [comment]
> 1.) The basicui configuration the "parameters" are stored as "cookies". But cookies are deleted in proper configuration regularly (e.g. if I close my window). Than I have to do the configuration new. If I have the opportunity to define "default parameters" in "services/basicui.cfg", than I do not have to "reconfigure" each time.

Just to have a proper information archived, the settings are of course not lost when you close your browser window (that is even the reverse, they are kept), except if you use the private browsing mode.
You put quotes around cookies, good idea because it is not cookies that are used to store data but browser local storage.
https://en.wikipedia.org/wiki/Web_storage

**Comment by moltke69** [comment]
Thank you. You are right. I was a little bit unprecise, as I use only "incognito windows" in my browser, and after "close" and "open again", cookies and web-storages are gone. And I summarized this uncorrectly with "cookies".

But nevertheless also on "non-incognito windows" in your browser, some people have also a configuration in their browser, that web storage is deleted as soon as their browser is closed.

(sorry in German)
![image](https://github.com/user-attachments/assets/029b7ea1-dfed-4d07-aabd-4932c02031d4)

I, for myself, found a solution with a custom CSS to define as "default" on the server, what I want to define. But maybe some people don't know how to do it.

I really appreaciate all the work of all open source developers. And if I'm allowed as a user to make a modest suggestion, I would propose following:

1. All basicui parameters should be configured as default parameters also in "services/basicui.cfg". That means if you open your basicui on different computer, laptops, tablets, ... you'll ever have automatically "your" configuration. Of course you can change it in the new introduced basicui configuration page.

2. Maybe that in the "services/basicui.cfg" you can disable also the "UI configuration page". This would be helpful, if e.g. your guest should not change the layout on the "terminal window" in the room (e.g. hotel, guest room, ...)

3.) Just as an idea: Maybe that the parameters could be given also by the url directly like https://xxxx/basicui/app?nbcolums=2-2&theme=dark&enableIcons=true

Thank you very much in advance. If you need any help don't hesitate to contact me.
