### ISSUE TITLE
[MainUI] Adding items to trigger-based channel is broken

### ISSUE THREAD

**Issue by egoist6** [openhab/openhab-webui#2669]
openHAB 4.2 Release
![image](https://github.com/user-attachments/assets/339cce55-7f92-4c6e-97c0-909440ff600b)
When clicking on “Create a new item” it does not provide any input fields.
This appears with trigger channels only. For regular channels everything is working as expected.

Furthermore, if you click on "Add Point to Model" in thing settings, the trigger channel disappears from the list:
![image](https://github.com/user-attachments/assets/6ea6bedd-0d2d-4de3-a831-95364734e12e)

**Comment by florian-h05** [comment]
https://community.openhab.org/t/openhab-4-2-release-discussion/157076/96 is probably related.

**Comment by florian-h05** [comment]
Would have been nice to fill out the issue template and provide the requested information there - seems like this is caused by a bug in the JS code of link-add.vue.
