### ISSUE TITLE
[Main UI]  Required configuration parameters not enforced

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#267]
Only when you click on input fields the required parameters show. It's also possible to create Things without providing the required parameters which results in configuration issues.

### Without clicking on the input fields

![nest1](https://user-images.githubusercontent.com/12213581/83063674-ce7fad80-a060-11ea-8e90-540e8403e6cf.png)

### After clicking on the input fields

![nest2](https://user-images.githubusercontent.com/12213581/83063681-d2abcb00-a060-11ea-8b53-ec49d73be8d8.png)

**Comment by ghys** [comment]
> It's also possible to create Things without providing the required parameters which results in configuration issues.

I was actually fine with not enforcing the required flag and only considering it as a simple indication to the user on the client (and the "real" validation should be made on the server anyway), but naturally I see your point too and it's also valid ;)

**Comment by wborn** [comment]
In this case I forgot to enter one of the parameters because the UI didn't prompt me to do so and it also caused me spending time on debugging why the Thing didn't go online. So I think it would be more user friendly if it is immediately clear what should be entered and the UI makes sure it is entered. :wink:
