### ISSUE TITLE
[BasicUI] Input widget converts doublequotes to `&quot;`

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-webui#2675]
Test:

```java
String TestString1
```

```java
sitemap test {
  Input item=TestString1
}
```

Then open the sitemap on a browser, and enter `{"test":[]}`and press enter. BasicUI will send the correct string, but then converts that string to `{&quot;test&quot;:[]}` and displays it.

<img width="487" alt="image" src="https://github.com/user-attachments/assets/ed454b06-c858-4c60-b85b-2ea540196930">

It seems that I can't send another command by pressing enter, unless I modified the string. So I added a space and pressed enter, it would then send the command `{ &quot;test&quot;:[]}` (correctly as entered), but once again it urlencoded that string to `{ &amp;quot;test&amp;quot;:[] }` and displayed that.

Discovered/Reported here https://github.com/openhab/openhab-addons/issues/16479#issuecomment-2232653793

**Comment by mherwege** [comment]
@jimtng I have been trying this in Chrome with a current snapshot (running OH from Eclipse IDE to debug this). I can't reproduce the issue.
What browser are you using?

**Comment by jimtng** [comment]
Chrome Version 120.0.6099.199 (Official Build) (arm64) (macos 14.5)

**Comment by mherwege** [comment]
Strange, I use Chrome Version 126.0.6478.183 (Official Build) (64-bit) on Windows. I tried with the exact same string and it works for me.

**Comment by jimtng** [comment]
Strange indeed. I can reproduce it on Safari and Opera too. Currently running 4.3.0-SNAPSHOT - Build #4194

Just enter anything into the input field with either `&` or `"`

`&` turns into `&amp;` and `"` turns into `&quot;`

**Comment by mherwege** [comment]
Even stranger now. I can reproduce it with &, but not with ".

**Comment by mherwege** [comment]
I found the issue and created a PR.
