### ISSUE TITLE
[BasicUI] Wrong encoding of translated strings

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#2681]
Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

My Phone, and thus Firefox, is configured to prefer Bulgarian language in content. As can been from the screnshot of BasicUI’s 4.2 settings, the translated sentences are not displayed properly.

![Screenshot_20240721_093320_org mozilla firefox](https://github.com/user-attachments/assets/94dd9f0c-dc7d-4593-b87e-20494a389e5c)

**Comment by lolodomo** [comment]
```
$ file *
basic.properties:    ASCII text, with very long lines
basic_bg.properties: UTF-8 Unicode text
basic_ca.properties: UTF-8 Unicode text, with very long lines
basic_cs.properties: UTF-8 Unicode text
basic_de.properties: UTF-8 Unicode text, with very long lines
basic_el.properties: UTF-8 Unicode text, with very long lines
basic_fr.properties: UTF-8 Unicode text, with very long lines
basic_hu.properties: UTF-8 Unicode text, with very long lines
basic_it.properties: UTF-8 Unicode text, with very long lines
basic_iw.properties: UTF-8 Unicode text, with very long lines
basic_lv.properties: UTF-8 Unicode text, with very long lines
basic_nl.properties: UTF-8 Unicode text, with very long lines
basic_no.properties: UTF-8 Unicode text
basic_ru.properties: UTF-8 Unicode text, with very long lines
basic_sv.properties: UTF-8 Unicode text
basic_vi.properties: UTF-8 Unicode text
basic_zh.properties: UTF-8 Unicode text
```
All properties files are apparently all in UTF-8 encoding (including the file containing Bulgarian translations) ... except the default (english).

@openhab/maintainers : any idea ?

**Comment by jlaur** [comment]
> any idea ?

I don't know if this is causing the issue, but the source file should be in UTF-8 - see openhab/openhab-core#2298.

**Comment by lsiepel** [comment]
I don’t expect it to be the file encoding as UTF-8 is the expected format. (The default is wrong) 
easy to test if the same happens with another language.

**Comment by J-N-K** [comment]
.properties are usually encoded as ISO-8959-1/Latin-1, not UTF-8.

**Comment by lsiepel** [comment]
Might be more encoding issues. Jenkins also fails alot lately on the addons repo with this Exception:
```
ERROR: Processing failed due to a bug in the code. Please report this to the issue tracker (https://jenkins.io/redirect/report-an-issue).
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.base/java.util.Properties.loadConvert(Unknown Source)
	at java.base/java.util.Properties.load0(Unknown Source)
```
Found this: https://issues.jenkins.io/browse/JENKINS-21828

Typically when a ISO-8959-1 file is changed to UTF-8 the unknown characters will become `????` The otherway around (i used the theme label as example) it will generate different characters, no questionmarks.

**Comment by lolodomo** [comment]
> I have not yet found the part in core that reads and processes these files.

https://github.com/openhab/openhab-core/blob/506ccd4f4db207f97abe2672a5ee30859b635426/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java#L124

**Comment by lsiepel** [comment]
> > I have not yet found the part in core that reads and processes these files.
> 
> https://github.com/openhab/openhab-core/blob/506ccd4f4db207f97abe2672a5ee30859b635426/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java#L124

That was my starting point, but then i get lost in all the Bundle management classes. Anyway, I can;t reproduce as my firefox (desktop) fails to show the basic ui in bulgarian no matter what i do. So i leave this to someone with more knowledge to this part of openHAB.

**Comment by dilyanpalauzov** [comment]
> I can’t reproduce as my firefox (desktop) fails to show the basic ui in bulgarian no matter what i do. 

This is configured in Settings → Regional Settings in OpenHAB.  Thus browser’s preferences are not honoured.

**Comment by lsiepel** [comment]
> This is configured in Settings → Regional Settings in OpenHAB. Thus browser’s preferences are not honoured.

Ah doh. Was looking at the wrong place because:
> My Phone, and thus Firefox, is configured to prefer Bulgarian language in content.

**Comment by lolodomo** [comment]
I am asking myself if the problem could be a miss of HTML escaping when building the page with these texts.

Will try to reproduce first.

**Comment by wborn** [comment]
I can reproduce it by running openHAB on Windows and then open Basic UI with Chrome on Ubuntu.

It might have to do with the `Content-Type` header that is set to `text/html;charset=iso-8859-1` when OH runs on Windows 
instead of `text/html;charset=utf-8` on Linux:

![Screenshot from 2024-09-07 13-32-57](https://github.com/user-attachments/assets/5e1b1676-5db1-46d9-82f2-8ca5246bb97e)

**Comment by lolodomo** [comment]
Content type is set here:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/WebAppServlet.java#L213
with:
```
private static final String CONTENT_TYPE = "text/html;charset=UTF-8";
```
Strange that `text/html;charset=iso-8859-1` is sometimes found.

**Comment by lolodomo** [comment]
Does `setContentType` need to be called at the very end like in `showSitemapList` ?

**Comment by lolodomo** [comment]
The problem is mentioned for the settings page so the code that is used is rather this one:
```
    private void showSettings(ServletResponse res) throws IOException, RenderException {
        PrintWriter resWriter;
        resWriter = res.getWriter();
        resWriter.append(renderer.renderSettings());

        res.setContentType(CONTENT_TYPE);
    }
```

**Comment by lolodomo** [comment]
Ok, I got the same ??? when setting Bulgarian as language in OH regional settings.

**Comment by lolodomo** [comment]
Same content type as @wborn ; 
![image](https://github.com/user-attachments/assets/5bd1a5f9-a25a-4c34-9257-70f2da3a877a)

**Comment by lolodomo** [comment]
I also got iso-8859-1 as content type with French as language and special characters like accents are properly rendered

**Comment by lolodomo** [comment]
I will trace what is the values returned by the call to the properties files.

**Comment by lolodomo** [comment]
> I am asking myself if the problem could be a miss of HTML escaping when building the page with these texts.

Escaping is already in place through the call to method `escapeHtml`.

**Comment by lsiepel** [comment]
> I will trace what is the values returned by the call to the properties files.

I got completely lost trying to find the file being read from the bundle and see what encoding is used. Hopefully you have better luck.

**Comment by lolodomo** [comment]
Retrieving of values seems to be fine:
```
15:49:25.006 [WARN ] [ui.basic.internal.render.PageRenderer] - theme label = Тема
15:49:25.013 [WARN ] [ui.basic.internal.render.PageRenderer] - theme escapeHtml label = Тема
15:49:25.019 [WARN ] [ui.basic.internal.render.PageRenderer] - theme description = Определи тема за потребителския интерфейс.
15:49:25.026 [WARN ] [ui.basic.internal.render.PageRenderer] - theme escapeHtml description = Определи тема за потребителския интерфейс.
15:49:25.034 [WARN ] [ui.basic.internal.render.PageRenderer] - switch label = Сбит изглед
15:49:25.040 [WARN ] [ui.basic.internal.render.PageRenderer] - switch escapeHtml label = Сбит изглед
15:49:25.046 [WARN ] [ui.basic.internal.render.PageRenderer] - switch description = Когато е включено, променя изгледа така, че да се виждат повече притурки на екрана.
15:49:25.054 [WARN ] [ui.basic.internal.render.PageRenderer] - switch escapeHtml description = Когато е включено, променя изгледа така, че да се виждат повече притурки на екрана.
```

**Comment by lolodomo** [comment]
That might be the escaping that does not work with this language.
Look at in comparison with French:
```
15:52:06.443 [WARN ] [ui.basic.internal.render.PageRenderer] - theme label = Thème
15:52:06.447 [WARN ] [ui.basic.internal.render.PageRenderer] - theme escapeHtml label = Th&egrave;me
```
The non ASCII character is escaped.

**Comment by lolodomo** [comment]
I can see that that HTML code provided to `res.getWriter().append` contains Bulgarian characters:
```
<div class="mdl-form__row mdl-form__row--setting-descr mdl-cell mdl-cell--12-col">
        Когато е включено, променя изгледа така, че да се виждат повече притурки на екрана.
</div>
```

**Comment by lolodomo** [comment]
Ok, I got it, content type has to be set before writing in the response.

**Comment by lsiepel** [comment]
Oke, good to know this is not related to the Jenkins builds failing. Also an encoding issue but not related. That was mainly why I was following this issue closely.

Nice fix!

**Comment by lolodomo** [comment]
@wborn : after the change, the header is as expected:
![image](https://github.com/user-attachments/assets/6aaa9829-b88d-49f3-af6b-89946524c897)

**Comment by lolodomo** [comment]
Note that it was wrong only for the page showing preferences and the page showing list of sitemaps. It was done properly for the rendering of the main sitemap page.

**Comment by wborn** [comment]
> Oke, good to know this is not related to the Jenkins builds failing. Also an encoding issue but not related. That was mainly why I was following this issue closely.

I've now downgraded the Jenkins Artifactory plugin back to 4.0.2 which may help according to https://github.com/jfrog/jenkins-artifactory-plugin/issues/913.
