### ISSUE TITLE
ui.iconset.classic: SAT build failure

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#27]
```
[INFO] --- sat-plugin:0.5.0:report (default) @ org.openhab.ui.iconset.classic ---
[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found: 
 4 error(s)! 
 1 warning(s) 
 0 info(s)
[ERROR] .ui.iconset.classic/META-INF/MANIFEST.MF:[0]
The manifest version did not match the requirements ^2\.3\.0
[WARNING] .ui.iconset.classic.internal.ClassicIconProvider.xml:[3]
There were whitespace characters used for indentation. Please use tab characters instead
[ERROR] .ui.iconset.classic/build.properties:[0]
about.html file must be added to the bin.includes property
[ERROR] org.openhab.ui.iconset.classic.internal.ClassicIconProvider.java:[2]
Header line doesn't match pattern ^ \* Copyright \(c\) 2010-2018 by the respective copyright holders\.$
[ERROR] .ui.iconset.classic/about.html:[0]
Missing about.html file.
```

**Comment by maggu2810** [comment]
I wonder, why I am running to that errors.
Does the build work on your systems or is it known to be broken ATM?

**Comment by kaikreuzer** [comment]
SAT checks are deactivated on the Jenkins build, that's why...

**Comment by maggu2810** [comment]
Then I don't need to wonder. Thanks for the information.

**Comment by wborn** [comment]
It no longer runs SAT at all now, probably because of the POM changes in #15 @martinvw?

**Comment by martinvw** [comment]
Yes if it came through the tycho parent that would explain, I did not deliberately solve this issue 😊

**Comment by martinvw** [comment]
@maggu2810 is the SAT still enable in openhab-core, the only usage of `sat.version` which I see is: https://github.com/openhab/openhab-core/blob/master/features/p2/poms/pom.xml.

Running the first part of the `openhab-core` build also does not show SAT output?

If its enable it openhab-core what would then be the correct / intended inheritance? or should we duplicate the sat now locally?

**Comment by maggu2810** [comment]
@martinvw Didn't you move to a pure Maven build?
All the POMs below features/p2 should not be realted as they are not used by the core bundles.

To answer your question: No, SAT is still not enabled in openHAB Core.

**Comment by maggu2810** [comment]
https://github.com/openhab/static-code-analysis/issues/341

**Comment by martinvw** [comment]
> @martinvw Didn't you move to a pure Maven build?
All the POMs below features/p2 should not be realted as they are not used by the core bundles.

Yes indeed, so it seems that I longer inherit any SAT configuration

> To answer your question: No, SAT is still not enabled in openHAB Core.

So that now also applies to this project, I opened an issue for it: https://github.com/openhab/openhab-webui/issues/32
