### ISSUE TITLE
Hyphen in template cannot be used in sitemap mapping

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-webui#2701]
## Expected Behavior
I am using Fritz!Box Templates to switch between operation modes of the Fritz radiator controller. 
I am setting up a sitemap. I would like to configure the mappings in the UI and be able to see the resulting sitemap code under the "Code" tab. 

## Current Behavior:
The "Code" tab hangs because the hyphen is violating the expected token syntax.  

## Possible Solution
A fix in openhab-addons or more tolerance in sitemap parsing.

## Steps to Reproduce (for Bugs)
1. Setup mapping with hyphen
<img width="1058" alt="Screenshot 2024-08-02 at 20 07 08" src="https://github.com/user-attachments/assets/d2146605-ad53-478e-97e3-4c89065ca177">
2. View sitemap in "Code" tab
<img width="1084" alt="Screenshot 2024-08-02 at 20 07 38" src="https://github.com/user-attachments/assets/918adeaa-1f4e-4b21-ae26-4726939b724b">

## Your Environment

* Version used: 4.2.0 - Release build
* Operating System and version :
```
openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://openhab.jfrog.io/openhab/libs-release

Repository        Version
----------------------------------------
openhab-distro  : 4.2.0
openhab-core    : 4.2.0
openhab-addons  : 4.2.0
karaf           : 4.4.6
```

**Comment by florian-h05** [comment]
@mherwege Can you please take a look?

**Comment by mherwege** [comment]
I will have a look. Please assign to me.

**Comment by mherwege** [comment]
The syntax `cmd=label=icon` in the Nearly parser is exactly what is in the original syntax here: https://github.com/openhab/openhab-core/blob/5eedd273baefc7868c31d80cff513e22cde60425/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext#L219

The thing is, `cmd` can be Number, can an ID but then it has to comply with the ID syntax rules, which is no spaces, no -, starting with a character, or it can be a String. For a string, it has to be enclosed in double quotes.

I tried with something like: `"test-command":test` and that works perfectly fine.

I suspect your syntax will also not work in a `.sitemap` file.

So I propose to close this, as this is a configuration issue.

**Comment by timbms** [comment]
@mherwege: The sitemap defined with mappings is and was working without a flaw.  The issue became apparent only when I switched over to code view. It took me quite a while to establish what was wrong. If this is not a bug, wouldn't it be even better to prevent illegal definition in the Design view. 
Apparently things got already better with openHAB 4.2.1: Error is not overlaid on editor, making it hard to read. Editor remains scrollable even in the case of an illegal value. Still one more issue is apparent: The offending code is wrongly quoted. The offending code truly is at line 56 col 107. However, the lines shown below are not the line 54-56:
<img width="1059" alt="Screenshot 2024-08-12 at 11 26 19" src="https://github.com/user-attachments/assets/f659c57c-6ecb-4271-a93d-70cfd4d85012">

**Comment by mherwege** [comment]
> switched over to code view

And that is exactly what I did in my test above. If the string does not contain a hyphen, the double quotes are not required. If it does, you need to put it in double quotes to make it work. And that is the error it tells you in the code view.
The hyphen without double quote is not valid syntax, also not when defining it in a sitemap file. If it works, you got lucky. I could put in an extra check in the UI to warn for it, but it will not make a difference in that your configuration syntax is not correct.

**Comment by timbms** [comment]
I understand that the configuration is not correct, but it would be great if one would understand the root cause for the syntax error. As things improved already, probably with 4.2.1, it would be even better if the offending lines would be properly shown.

**Comment by mherwege** [comment]
> if the offending lines would be properly shown

I have not been able to do that consistently. The grammer parser generates errors, but these are not always at exactly where it happens.
A better approach is probably to check it in the UI, to make sure there are quotes around it when creating a mapping in the UI. I will look into that.

**Comment by timbms** [comment]
Here the grammar parser reports the right location, but the output shows the wrong lines, here just the end of the file.

**Comment by mherwege** [comment]
We have little control over how Nearly creates that error message unfortunately. Therefore, when I have time I will look into putting checks in the UI to avoid the problem in the first place when creating it from the UI.

**Comment by mherwege** [comment]
Also see https://github.com/kach/nearley/issues/634
