### ISSUE TITLE
Charts do not resize correctly after rotating the phone on iOS

### ISSUE THREAD

**Issue by Beluk** [openhab/openhab-webui#2702]
After updating to 4.2.1 the charts are not resized correctly after rotating the phone. I think it is related to https://github.com/openhab/openhab-webui/commit/3d27333ba48ce1bae279b597533cc53f71f53b22

@florian-h05 can you fix this also?

After opening: (everything looks good)
![IMG_1274](https://github.com/user-attachments/assets/e1ce9844-236b-4966-a23a-b6703b98c542)

Turn phone horizontally:
![IMG_1275](https://github.com/user-attachments/assets/77576492-cf59-4028-88f7-1665af59f976)

Turn phone back vertically:
![IMG_1276](https://github.com/user-attachments/assets/27553851-68fa-43f3-851f-0a03d5321da7)

**Comment by florian-h05** [comment]
Sure, no problem to fix that.
To fix that, I decided to force a re-render of the chart, which causes it to redraw and reset the selected day/period, but this is the only solution I found for now.

**Comment by florian-h05** [comment]
That isn't easily possible as the settings are internal to a sub-sub-component of the chart page, but by moving the rerender logic to this component, the issue should be fixable as well while retaining config and loaded data.

**Comment by florian-h05** [comment]
I have done that with #2710.
