### ISSUE TITLE
[BasicUI] App icons no more rendered in snapshot 4228

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2712]
![image](https://github.com/user-attachments/assets/4a8cb39d-1924-4d85-9320-2cb96b05b633)

It was still working in snapshot 4217

@florian-h05 : could it be due to the merge of #2606 ? I hope you tested the UI before merging.

**Comment by florian-h05** [comment]
I tested it but my testing was fairly limited.
Can you revert that commit locally and then build and try out?

**Comment by lolodomo** [comment]
It works again if I revert gulp upgrade.

**Comment by florian-h05** [comment]
Okay in that case I am sorry that this slipped through, let’s revert it then.

**Comment by lolodomo** [comment]
PR will be submitted in few seconds.

**Comment by florian-h05** [comment]
See #2713.

**Comment by lolodomo** [comment]
Just for my information is there a Git feature to simply revert a merged PR ?

**Comment by florian-h05** [comment]
Yeah, on the bottom of a merged PR you can find a button to easily revert it from the GitHub UI:

![image](https://github.com/user-attachments/assets/d3964729-6c22-4ca6-97e4-47558cdfa491)

**Comment by lolodomo** [comment]
Ok, thank you a lot, I never saw that button !

**Comment by lolodomo** [comment]
I am now trying to investigate what was wrong.
With Basic UI compiled with gulp 5.0.0, I got these errors in browser console:
![image](https://github.com/user-attachments/assets/b7937b57-e71d-4172-b3b2-f132f9609fd1)

If I check the font files sizes created by gulp into folder src\main\resources\web\fonts, they are fully different:

- material-icons.woff:: 164 912 bytes with gulp 4.0.2 while 299 808 bytes with gulp 5.0.0 
- material-icons.woff2 : 128 352 bytes with gulp 4.0.2 while (231 689 bytes with gulp 5.0.0 

Gulp is copying these files from ./node_modules/material-icons/iconfont
The sizes in this folder remains the same. So the problem is the copy of files done by Gulp 5.0.0 which changes the file content !

Our Gulp code:
```
	var paths = {
	        FontLibs: [
			'./node_modules/material-icons/iconfont/material-icons.woff*',
			'./node_modules/framework7-icons/fonts/Framework7Icons-Regular.woff*',
			'./node_modules/framework7-icons/fonts/Framework7Icons-Regular.ttf'
	        ]
	    };
	
	gulp.task("copyFontLibs", function () {
	    return gulp.src(paths.FontLibs)
	        .pipe(gulp.dest('./src/main/resources/web/fonts'));
	});
```

**Comment by lolodomo** [comment]
https://github.com/gulpjs/gulp/issues/2790

With Gulp v5, you need apparently to specify encoding: false to stream.

**Comment by lolodomo** [comment]
Ok, with this updated code, font files are now unchanged:
```
	gulp.task("copyFontLibs", function () {
	    return gulp.src(paths.FontLibs, { encoding: false })
	        .pipe(gulp.dest('./src/main/resources/web/fonts'));
	});
```

Will have to check all Gulp tasks but I believe others are handling non binary files.
