### ISSUE TITLE
Charts on iOS are blank

### ISSUE THREAD

**Issue by Beluk** [openhab/openhab-webui#2789]
After update to 4.2.2, all charts on iOS are gone, only a black screen is displayed.  Maybe this is related with https://github.com/openhab/openhab-webui/issues/2702?

**Comment by florian-h05** [comment]
Wrt to charts there is no difference in the charts' code to the current snapshot, and this one works fine for me on iOS 16, 17 and 18 - I cannot reproduce your issue.

Have you tried to "reload and clear cache" in the about page of Main UI?

**Comment by Beluk** [comment]
I cleared the cache. Now it works perfect. Also rotating the phone work like a charm. Thank you for your help!

**Comment by florian-h05** [comment]
Good to hear!
