### ISSUE TITLE
Dashboard: Refactor localization strings

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-webui#28]
Related to: https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard.properties

@lolodomo @martinvw @wborn 

I feel we should split up strings and remove HTML as much as possible from the localization files, especially as urls and magic strings are involved. Translation will happen by users over on crowdin with potentially very little programming/HTML experience. Imho these would be good steps:

* Split or add placeholder to `setup.check-doc`
* Split or add placeholder to `common.getting-started`
* Split `warn.exposed` into multiple parts, potentially use placeholders
* Use `text-transform: uppercase;` instead of uppercase letters in `warn.exposed`

If you agree, your help with that change would be highly appreciated.

**Comment by kaikreuzer** [comment]
> Will we also automatically get Crowdin translations PRs at that repository?

No, I'll need to set that up...

**Comment by wborn** [comment]
This can be closed. The dashboard got removed with OH3.

**Comment by lolodomo** [comment]
dashboard got removed with OH3

**Comment by wborn** [comment]
There are also several open issues with the "paper ui" and "habmin" tag which probably can also be closed @lolodomo.

**Comment by lolodomo** [comment]
> There are also several open issues with the "paper ui" and "habmin ui" tag which probably can also be closed @lolodomo.

@wborn : done.
