### ISSUE TITLE
Saving thing configuration should use thing endpoint

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#283]
Currently the UI uses the `/rest/config-descriptions` endpoint to save the thing configuration. This results in the thing handle restarting and the `handleConfigurationUpdate` method in the thing handler is not called.

The UI must instead use the `PUT thingId/config` endpoint - this properly handles the thing configuration updates in the thing handler.

Binding that currently assume `handleConfigurationUpdate` is called cannot currently be updated.

**Comment by ghys** [comment]
I'm sorry - It's always been a little confusing to me.
Could you come up with an example, or a PR?

**Comment by cdjackson** [comment]
It’s been quite a while since I looked at this - I think it sends the same information, but to the rest endpoint I referenced (thing/thinguid/config I think), rather than the config endpoint. I’ll see if I can work out how to change REST endpoints in the UI, but I’m still not very familiar with the framework.

**Comment by cdjackson** [comment]
@ghys I can't see where this call is made from. I'm guessing that it's made somewhere in your `config-sheet` control?

Maybe you can point me to where the configuration is saved. However, if it is done in this control, then it might be more complex since I guess you use this same control for all configuration (eg things, bindings, etc). If so, there would need to be a mechanism to use different rest endpoints depending on the configuration.

What needs to happen for thing configuration is to use a `PUT` to the `/rest/things/{thingUID}/config` endpoint, and you just need to write the properties - ie associative array of key/values for the configuration.

I'm happy to look at this further if you like, but I think this ought to be either a simple change to simply change the endpoint - or a more complex change if this somehow needs to change the common configuration control sheet. If it's the first one, then it's probably a 2 minute job for you, and if it's the second one, it's probably something you should do.

I'm however very happy to help if you prefer to explain how this area of the code works a little.

**Comment by ghys** [comment]
As far as I can remember the thing is saved in the save() method of the
thing-details.vue page, and calls `PUT /rest/thing/thingId` which I reckon
saves the entire thing (including the configuration, channels, and so on).
The config sheet is only for displaying purposes. I'll have a look later.

**Comment by cdjackson** [comment]
There are multiple calls made when saving the thing - and I can’t correlate that with the save method. The thing is saved, and read back, but the config is saved as a separate rest call.

**Comment by ghys** [comment]
> but the config is saved as a separate rest call

Really don't know what to tell you, the only non-GET call I see when saving is PUT /rest/things/:thingId, I didn't even notice there was a /rest/things/;thingId/config endpoint until now (according to the Swagger spec the payload to send is the same i.e. the entire thing DTO, which is doubtful).

This are all the network is all I see when I hit Save on a thing page:

![image](https://user-images.githubusercontent.com/2004147/85277309-81d29b00-b483-11ea-9aff-71aff20b865b.png)

**Comment by cdjackson** [comment]
Ok, I missed that the call to the config-descriptions was a GET, however the problem is still the same that I reported - you are not calling the `/rest/things/{thingUID}/config` endpoint. Since this is not called, the thing configuration is not updated in the binding.

You need to call this endpoint with the updated configuration. Or of course we could change the server side, but currently configuration update doesn't work due to this.

**Comment by cdjackson** [comment]
> (according to the Swagger spec the payload to send is the same i.e. the entire thing DTO, which is doubtful).

As mentioned above, I think that it's just the key/value pairs of configuration parameter names and their values.

**Comment by cdjackson** [comment]
From what I can tell looking at the server source, calling the PUT `/rest/things/thingid` will cause the thing handler to be restarted rather than to update the configuration (ie with `handleConfigurationUpdate` method). This is not a nice approach and clearly will mean bindings don't work properly. Using the `/rest/things/thingid/config` instead properly updates the thing config with the appropriate calls to the binding.

I think in general you should not call the `/rest/things/thingid` endpoint at all unless you need to - you should use the `/rest/things/thingid/config ` endpoint if the configuration is updated, and the `/rest/things/thingid` endpoint only if thing level changes are made (label, description etc). This will avoid unnecessarily restarting thing handlers which may cause a lot of additional activity.

**Comment by ghys** [comment]
Right, kind of confusing, thanks for your insights.
#287 should make sure the correct endpoint is used.
If you have the opportunity to to a `git apply` to https://patch-diff.githubusercontent.com/raw/openhab/openhab-webui/pull/287.diff and confirm it works before we merge it, I'll be grateful.
The feedback message will be "Thing configuration updated" instead of "Thing updated" when the /config endpoint is used.

**Comment by cdjackson** [comment]
Thanks Yannick - I’ll test this evening and report back.
