### ISSUE TITLE
[main UI] Allow selecting Thing actions from rule editor

### ISSUE THREAD

**Issue by boehan** [openhab/openhab-webui#2836]
## The problem

I think the initial intention behind [openhab-core#1745](https://github.com/openhab/openhab-core/issues/1745) was the ability to directly select Thing actions via "Add action" in the rule editor. This would IMO simplify a lot of rules, which up to now require simple scripts just to invoke such actions.
Now that the core issue is closed (and action support from thing page is implemented in UI), this part is still missing in UI and should not be forgotten.

## Your suggestion

Allow selecting Thing (and core) actions (from "Add action") in rule editor.
![grafik](https://github.com/user-attachments/assets/419fee58-a575-4f73-8d9c-77e0f2dbf591)

**Comment by florian-h05** [comment]
Thing actions can be selected from UI rules, just click on show all.

(You of course need one of the latest snapshots installed.)

**Comment by boehan** [comment]
Oh, I was following the progress, but from the PR descriptions and discussions I had the impression that only invoking from thing page was supported so far. Even better, if this is already working for rule editor as well. So I'm really looking forward to the next milestone release.

**Comment by florian-h05** [comment]
I have implemented the required bits and contributed them to the PR, but I guess this got a bit lost in the huge discussion there.
The UI in fact needed no changes, core just needed to return the right data from the API.
