### ISSUE TITLE
Color Temperature / Color widget wrongly sends second POST for Color item

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#2849]
@toomtech many thanks for the pcap. It shows something rather odd. See screenshot below. I am pretty sure that this is an error in Main UI. And to be specific the problem is NOT in the OH standard items slider screen, but IS in your Locations | Office widget. 

Your pcap shows the following sequence of events:

1. UI client commands CT item to 67%
2. OH server notifies CT item changed to 66.86%
3. OH server notifies Color item changed to HSB 38.101,56.52900,98.02 // note: S=**56.52900** !!
4. UI client commands Color item to HSB 39,39,98 // note: S=**39** !!
5. OH server notifies CT item changed to Undef
6. OH server notifies Color item changed to HSB 39.016,39.00500,98.02

Specific observation is that the S value massively changes between events 3. and 4. !! => It makes me suspect that your Client | Locations | Office widget is wrongly sending `HHB` instead of `HSB`. _=> We need to look into the widget code!_

![image](https://github.com/user-attachments/assets/9c6048aa-a54c-46eb-b18d-700c9c1ae3f0)

_Originally posted by @andrewfg in https://github.com/openhab/openhab-addons/issues/17643#issuecomment-2448092063_

---

After the user issues a Color Temperature command, and OH sends respective Color Temperature and Color HSB state update responses, the UI Widget is issuing -- on its own initiative -- an extra Color HSB command. There are two problems here..

1. The Widget seems to be sending HHB rather than HSB
2. And -- far more important -- the Widget should not be issuing ANY commands on its own initiative.

**Comment by andrewfg** [comment]
After the user issues a Color Temperature command, and respective Color Temperature and Color HSB responses. The UI Widget is issuing (on its own initiative) a Color HSB command. There are two problems here..

1. It seems to be sending HHB rather than HSB
2. And -- far more important -- it should not be issuing ANY commands on its own initiative.

**Comment by andrewfg** [comment]
@toomtech as I myself don't use these widgets, perhaps you can provide some info for others about the one you are using? Does it have a name? And/or some config settings? Etc.

**Comment by andrewfg** [comment]
^
you must have configured your Locations page and added the Office widget. So how did you do that?

**Comment by andrewfg** [comment]
^
 Unfortunately I don't use any of these UI widgets, so I have very little knowledge on them and their code. So someone else will have to resolve this. And we need to give as much info as possible for that person. I think the bug is not related to the semantic model, but rather related to the actual script code of the actual widget which is loaded into your browser. There are many possible widgets that may have been used. So we (they) need to know as much as possible about the actual widget and its actual code.

**Comment by andrewfg** [comment]
> I'm happy to provide any information you think will help. Just let me know what you need.

@maniac103 / @lolodomo => handing over to you guys.

**Comment by lolodomo** [comment]
> @maniac103 / @lolodomo => handing over t

Don't think we can help as it looks like a bug in a Main UI page. I let @florian-h05 confirm.

**Comment by andrewfg** [comment]
![image](https://github.com/user-attachments/assets/daa6c0be-50f4-4e78-817e-6079928a17ae)

**Comment by andrewfg** [comment]
> video shows clearly Main UI standard screens.

Indeed. And to be more specific the issue only occurs on a screen where there are both a `color` item widget and a `color temperature` slider on the same screen (see below). And the problem is that when the UI POSTS a command to change the `color temperature`, then the OH core (correctly) notifies both the new `color temperature` and `color` values, and then the UI wrongly POSTS a second command for the new `color` value. _**=> This second POST SHALL NOT happen!**_

![image](https://github.com/user-attachments/assets/f6997a17-e60a-43b9-8cda-a5bf1ecfec8e)

**Comment by andrewfg** [comment]
@florian-h05 if you need it, then @toomtech has a Wireshark pcap that he can (perhaps) share with you.

**Comment by florian-h05** [comment]
I think the root cause of problems here is #1268.

**Comment by andrewfg** [comment]
Yes. That issue has been open since 2022 so I am hoping it can finally be fixed.
