### ISSUE TITLE
[Default UI] Unclear pending configuration update

### ISSUE THREAD

**Issue by dansrogers** [openhab/openhab-webui#285]
I tried to go though that UI to update the configuration for a  4-1 Inovelli sensor in battery mode.

Saving the configuration then waking up the device didn't seem to update either config parameters (like when to send a basic set on PIR motion, or PIR triggering time) or to set association groups.

I would input the configuration I want.  Hit save, click three times on the device button to wake it up, then reload the page and the configuration didn't change, and the device behavior didn't change.

I was was able to do this in Hab min however.  In habmin I got a badge above the entrybox when the configuration update was pending and the device behavior updated.

**Comment by cdjackson** [comment]
While this issue is opened against PaperUI, I propose to transfer this to the OH3 UI since PaperUI is end of life. (i'll remove the PaperUI tag in the title)

@ghys you may not be aware of this feature - it's the `GET /rest/things/{thingUID}/config/status` endpoint which can return the following status -:

```
        /**
         * The type for an information message. It is used to provide some general information about a configuration
         * parameter.
         */
        INFORMATION,

        /**
         * The type for a warning message. It should be used if there might be some issue with the configuration
         * parameter.
         */
        WARNING,

        /**
         * The type for an error message. It should be used if there is a severe issue with the configuration parameter.
         */
        ERROR,

        /**
         * The type for a pending message. It should be used if the transmission of the configuration parameter to the
         * entity is pending.
         */
        PENDING;
```

HABmin presents these as a BootStrap badge next to the label I suggest a similar approach here - WDYT?

**Comment by ghys** [comment]
Thanks for the triaging and clarification @cdjackson - I indeed didn't remember (or wasn't aware) config parameters could have a status. I'll come up with something to visualise them nicely.
