### ISSUE TITLE
Implement Colortemperaturepicker in sitemap builder

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#2852]
Related to https://github.com/openhab/openhab-core/pull/4420

**Comment by andrewfg** [comment]
Please note that any PR to resolve this issue should please mirror the solution in #2860 concerning dual POST commands.

**Comment by mherwege** [comment]
@andrewfg This issue is about the sitemap builder UI. It does not have anything to do with running the sitemap in BasicUI or an app, so I don’t see the relevance.

**Comment by andrewfg** [comment]
Ok

**Comment by florian-h05** [comment]
@mherwege Do you want to take care of the sitemap builder adjustment? You have experience with that …

**Comment by mherwege** [comment]
@florian-h05 I intend to, but has been an extremely busy period at work. I have not been able to spend much time on OH recently.
