### ISSUE TITLE
[Habmin] Pending status not clear after z-wave device wakes up

### ISSUE THREAD

**Issue by dansrogers** [openhab/openhab-webui#286]
After inputting configuration changes in the z-wave device configuration UI, I got a notification that the device update was pending via an orange badge.  However when I woke up the device the orange badge did not clear.

Reloading the page cleared the pending status.

**Comment by cdjackson** [comment]
I'd suggest to discuss this on the forum as it's not really a bug - just your understanding of how ZWave works. Basically, battery devices need to be woken up before configuration can be transferred - hence the pending state - it means the data hasn't been transferred yet.

I'll close this - if you want to discuss further then please discuss on the forum.

**Comment by dansrogers** [comment]
That's not the problem I'm describing.  I understand how zwave works.  The issue is that after device wake-up the device correctly recieves the new configuration.  E.g. if it's a new group association I can validate that the device has recieved the new configuration by triggering the PIR and watching the light come on.

However the UI has not updated.  It still shows the configuration update as pending, even though it's clearly no longer pending.  reloading shows the correct status

What I expected to happen:
Config update gets posted in group 1 and picked up by the zwave controller -> zwave controller triggers device event that status is updated -> UI receives an event that clears the pending label (without reload)

**Comment by openhab-5iver** [comment]
[Habmin no longer exists](https://github.com/openhab/openhab-webui/pull/154). Do you have the same issue in the new UI?

**Comment by cdjackson** [comment]
The OH3 UI doesn’t support the states at all from what I could see the other day.
