### ISSUE TITLE
Add "Edit page" link to tabbed pages

### ISSUE THREAD

**Issue by dujal** [openhab/openhab-webui#2899]
## The problem
I often use tabbed pages to display different charts on one page. But when I want to make some changes to one particular tab page, I can’t navigate to edit this page directly (e.g. change chart configuration). If I use the edit button in top right corner I get to the tabbed layout, where I can manage the tabs, but it is not possible to go directly to page of one particular tab. I have to check the page UID and find that page manually on Pages list or using developer toolbar.

It would be really nice to have some shortcut for this use case.

## Your suggestion

I have two suggestions.

The easiest one would be to add second Edit link on tabbed pages, where one would lead to edit of tabbed layout page and second would lead to edit page of currently opened tab.

Something like this:
![image](https://github.com/user-attachments/assets/7bd251b7-8002-46d6-be87-32e66c7adc77)

Second option is to add one entry into submenu of tabbed layout page to list of tabs. That link would lead to edit page of that particular tab.

Something like this:
![image](https://github.com/user-attachments/assets/35ee3c09-17f5-4ef6-9987-a1c1873d096c)

## Your environment

```yaml

```

**Comment by stefan-hoehn** [comment]
@dujal You won't believe how often I cursed about that - thanks for filing this issue!
@florian-h05 And thanks for implementing it so quickly!
