### ISSUE TITLE
[Default UI] Default values for configuration parameters are not visible

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#293]
A lot of configuration parameters have default values. Currently those are not visible when editing the configuration. Thus the user does not know that there is a default and what its value. I suggest to prefill or select those values. An example:

```
...
		<parameter name="retry" type="integer" min="30" unit="s">
			<advanced>true</advanced>
			<label>Retry</label> <!-- German "Wiederholungen" in Screenshot -->
			<description>The retry parameter specifies how often (in seconds) the Pushover servers will send the same
				notification to the user.</description>
			<default>300</default>
		</parameter>
		<parameter name="expire" type="integer" min="0" max="10800" unit="s">
			<advanced>true</advanced>
			<label>Expire</label> <!-- German "Verfall" in Screenshot -->
			<description>The expire parameter specifies how many seconds your notification will continue to be retried for.</description>
			<default>3600</default>
		</parameter>
...
```

![grafik](https://user-images.githubusercontent.com/5131747/87001800-8f449080-c1b8-11ea-92d0-c246f9ac7f85.png)

Additionally we can define the unit attribute (`unit="s"`) or a `<unitLabel>`-tag for configuration parameters. Would be nice to display them next to the configuration parameter so we can omit adding it in the description.

**Comment by ghys** [comment]
You're absolutely right, I noticed it a while ago and this has been on my backlog ever since...
