### ISSUE TITLE
openhab Rel 4.3.0 New log viewer does not appear in the developer 

### ISSUE THREAD

**Issue by humus2002** [openhab/openhab-webui#2935]
## The problem

No button to access the new log viewer in the developer toolbar 

## Expected behavior

I expect to get an additional button in the developer tool section to call the loh 

## Steps to reproduce

1. I created an openhab instance from scratch by using [openHABian v1.9.4] 
2. I restored a CLI backup of my openhab 4.2 installation  biy using CLI 

## Your environment

raspberry PI 4 8GB
openHAB 4.3.0
Release Build
Main UI Commit ed54bf6d

```yaml

```

## Browser console

```txt

```

## Additional information

Overall, 4.3.0 is running fine .

**Comment by florian-h05** [comment]
Please follow the issue template or we have to close your issue.

**Comment by humus2002** [comment]
sorry, I misunderstoof formatting of the template issue

**Comment by florian-h05** [comment]
I don’t understand what your issue is.
There is a button to open the log viewer:

![IMG_5425](https://github.com/user-attachments/assets/b02d820a-23d8-46b2-be00-6c6369a1d339)

**Comment by ghys** [comment]
> Main UI Commit https://github.com/openhab/openhab-webui/commit/ed54bf6d23878e2351c9d278b51a49e55e01d33f

This commit is from Nov 19 so before the log viewer was merged.
Do you have a red button to clear all caches at the bottom of the Help & About screen?
If so click it, if not there should be a in the browser.
Try `bundle:list org.openhab.ui` in the OH (Karaf) console and check the version.

**Comment by humus2002** [comment]
@florian-h05 : Exactly the log viewer button is missing 

@ghys: I have no red button to clear all the caches at the botton of teh Help & About screen.. 

I tried this 
openhab>  bundle:list org.openhab.ui
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version            │ Name
226 │ Active │  80 │ 4.3.0.202411190008 │ openHAB UI :: Bundles :: Main UI

any idea what could be wrong? should I upgrade to lhe

**Comment by florian-h05** [comment]
You MainUI bundle is too old.
You should be able to install the release bundle using the following command in the openHAB console:

```
bundle:update 226 https://openhab.jfrog.io/artifactory/libs-release/org/openhab/ui/bundles/org.openhab.ui/4.3.0/org.openhab.ui-4.3.0.jar
```

**Comment by humus2002** [comment]
@florian-h05  . thanks you very much - the bundle update fixed it !

**Comment by humus2002** [comment]
main UI commit is now 8b8732ce
