### ISSUE TITLE
[Habpanel] Specifying format for button value throws JS error

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-webui#315]
I can set a format for a dummy widget or use the server format without problem.

If I try the same (widget value format set to %.1f) with a button widget then I get this error:
`vendor.js:119 TypeError: Cannot read property 'replace' of undefined
    at updateValue (button.widget.js:60)
    at button.widget.js:115
    at m.$emit (vendor.js:149)
    at openhab.service.js:50
    at vendor.js:132
    at m.$eval (vendor.js:147)
    at m.$digest (vendor.js:144)
    at m.$apply (vendor.js:147)
    at l (vendor.js:99)
    at K (vendor.js:103)`

I think I remember that once the dummy widget had the same problem and it was fixed. But the fix went not into the button widget as it seems.

PaperUI shows the value of the openHAB item used like this: 1.50 °C

**Comment by ghys** [comment]
Thanks! #316 should fix it.

**Comment by sidamos** [comment]
Thank you! Hope this is in openHAB 2.5.9.
