### ISSUE TITLE
[habpanel] Can not load config in 3.x 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#320]
Apologies if this has already been reported (or is a known issue).  Moving my main server to OH3.x this weekend.    HABPanel in 3.x can not load its config from the REST service due to our authentication changes. I know there was some talk about moving this out to not use the config service, but i don't know where that stands yet.  Thanks!

```
Request URL: http://oh:8080/rest/services/org.openhab.core.i18n/config
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 192.168.91.15:8080
Referrer Policy: no-referrer-when-downgrade
``

**Comment by ghys** [comment]
It's very much a known issue, and it'll be fixed this month - at least now there's something to track it :)

In the meantime if you want to use HABPanel you can, but you have to keep the panel configuration local for now:
In the settings screen click on "Edit the local panel configuration (experts only)" link and import - or paste - your configuration there then Save. Keep a backup just in case things go wrong when migrating to the new storage backend!

**Comment by digitaldan** [comment]
Sounds good.  I did import my exported panel config, but i am also seeing issues there, was not sure if they were related since i don't think much has changed in the JS code since 2.x.  I'll open a new ticket.  Thanks!
