### ISSUE TITLE
[MainUI] Can not import Contact items

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#325]
When trying to import textual items , the lexer is not expecting a "Contact" token.  A quick look show there is indeed contact support in there, so not sure whats throwing it off.

Sample contact line
`Contact		ZoneGarageRollup 		"Garage Rollup [%s]"  	    (Zones) 		{channel="omnilink:zone:omni:4:contact"}`

Error message
```
Error: Syntax error at line 1 col 1:

  Contact
  ^
Unexpected identifier token: "Contact". Instead, I was expecting to see one of the following:

A WS token based on:
    _ → _ ● %WS
    Main →  ● _ Items _
A NL token based on:
    _ → _ ● %NL
    Main →  ● _ Items _
A comment token based on:
    _ → _ ● %comment
    Main →  ● _ Items _
A itemtype token based on:
    Type →  ● %itemtype
    Item →  ● Type _ Name Label Icon Groups Tags Metadata
    Items →  ● Item
    Main → _ ● Items _
A "Number" based on:
    Type →  ● "Number" ":" %identifier %WS
    Item →  ● Type _ Name Label Icon Groups Tags Metadata
    Items →  ● Item
    Main → _ ● Items _
A "Group" based on:
    Type →  ● "Group" %membertype
    Item →  ● Type _ Name Label Icon Groups Tags Metadata
    Items →  ● Item
    Main → _ ● Items _
A "Group" based on:
    Type →  ● "Group" %membertype ":" %identifier AggArgs
    Item →  ● Type _ Name Label Icon Groups Tags Metadata
    Items →  ● Item
    Main → _ ● Items _
```

**Comment by ghys** [comment]
Not sure either... it seems to work here? Is it the version with #321 included or without?

![image](https://user-images.githubusercontent.com/2004147/92460059-ca1e7100-f1c7-11ea-9e0a-200750a23fa2.png)

I was thinking, could it be tab characters that were lost during your copy-pasting here, but they should work too...

**Comment by digitaldan** [comment]
>I was thinking, could it be tab characters that were lost during your copy-pasting here, but they should work too...

This looks like to be the culprit.  There are a mix of tabs and spaces in my line, if i copy this back from the ticket, which converted tabs to spaces, it works.
