### ISSUE TITLE
[Main UI] Admin user cannot change password

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#332]
It seems the UI does not provide a way to easily change the admin user password. That makes it complicated if your password got compromised, you entered an unsecure password for quick access during setup or when you have a good habit of changing it.

**Comment by ghys** [comment]
I think this operation should be handled as a servlet in the core (with a proper HTML form and a CSRF token, similar to the sign in flow), rather than from the UI itself and an API endpoint.

In the meantime, for the record, here's a reminder on how you can change your password from the Karaf console (this involves deleting and re-creating your user in JAAS):

```
openhab> jaas:realm-manage --realm openhab
openhab> jaas:user-delete admin
openhab> jaas:user-add admin ####
openhab> jaas:update
```
(replace 'admin' with your actual user name and #### with your password - it will be hidden while you're typing it)

**Comment by JueBag** [comment]
I was trying the commands above, recreated the user admin, however can't get this user to be an `admin`. Even after granting the role  `admin`.

`jaas:userlist` gives:
```
User Name │ Group │ Role
──────────┼───────┼──────
admin     │       │ admin
```

**Comment by ghys** [comment]
Yes the role is actually `administrator`: see [Role.java](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/openhab/core/auth/Role.java).

I forgot to add the role originally, I have updated the comment above.

Btw, while it's nice to have the JAAS commands, I'm actually thinking about adding some openHAB-specific Karaf commands to perform these (normally infrequent but sensible) operations, which could look similar to this:
```
Usage: openhab:users list - lists all users
Usage: openhab:users add <userid> <password> <role> - adds a new user with the specified role
Usage: openhab:users remove <userid> - removes a user
Usage: openhab:users changePassword <userid> <newPassword> - changes the password of a user
Usage: openhab:users clearSessions <userid> - clear the refresh tokens associated with the user (will sign the user out of all sessions)
Usage: openhab:users addApiKey <userid> <keyname> <scope> - add a new API key acting on behalf of the user for the specified scope
Usage: openhab:users removeApiKey <userid> <keyname> - removes the specified API key
```

**Comment by JueBag** [comment]
Thanks for the speedy answer, nowI'm back into testing.

**Comment by kaikreuzer** [comment]
> Btw, while it's nice to have the JAAS commands, I'm actually thinking about adding some openHAB-specific Karaf commands to perform these

I very much like your proposal! Indeed, the JAAS syntax is not straight forward for users and will cause many questions, so having our own commands will be much more user friendly.
