### ISSUE TITLE
[Main UI] [Bug] Stepper Card does not accept decimals

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-webui#333]
When configuring a stepper card, decimals like 0.2 or 1.2 are not accepted for min/max/step value

**Comment by hmerk** [comment]
@ghys I guess I found the issue, but not able to provide a fix, as I can't get a dev IDE up and running for this...

in org.openhab.ui/web/src/assets/definitions/widgets/system/stepper.js min/max/step are defined like
` pn('min', 'Min', 'Minimum value'),
  pn('max', 'Max', 'Maximum value'),
  pd('step', 'Step', 'Minimum interval between values'),
`
I guess it shoud be 
` pd('min', 'Min', 'Minimum value'),
  pd('max', 'Max', 'Maximum value'),
  pd('step', 'Step', 'Minimum interval between values'),
`
WDYT ???

**Comment by ghys** [comment]
Yes that should help, but I think the stepper has more problems...

**Comment by hmerk** [comment]
@ghys really don‘t want to push you, but we need the setpoint/stepper issue solved quickly. More and more people trying oh3 now and run into issues when using heating thermostats.
Could you put this on priority please.
