### ISSUE TITLE
Basic UI Not Auto-Refreshing

### ISSUE THREAD

**Issue by hondagoogle** [openhab/openhab-webui#337]
I have noticed that when I use the web version of the Basic UI, it will not auto-refresh for updated info. Instead, I have to manually reload the page. Classic UI and the Android App do not seem to have this issue. This can be VERY annoying!

**Comment by DerOetzi** [comment]
> Use same sitemap label as sitemap file name like label="default" If file name is default.sitemap.
> In this case there is no refresh issue.
> This should have been discussed on the forum IMHO.

I have changed the label but the problem was not fixed by this change. I investigated a bit deeper and see a 401 Unauthorized for manifest.json inside the developer tools of firefox.

**Comment by ghys** [comment]
No, this manifest is only to allow you to install Basic UI to your home screen or desktop, it doesn't affect functionality.
https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by wborn** [comment]
On OH3 I did see some refresh issues while doing some testing with the demo files which may be related to https://github.com/openhab/openhab-core/issues/1585. So if you also use OH3 that might explain. :wink:

**Comment by DerOetzi** [comment]
No OH3 used here. Response of subscribe looks like this:

```
{
   "status":"CREATED",
   "context":{
      "headers":{
         "Location":[
            "https://xxxxx.xxxxx.xxx/rest/sitemaps/events/3ffa5405-32f8-46ea-8ef6-8d38ce07d561"
         ]
      },
      "committingOutputStream":{
         "bufferSize":0,
         "directWrite":true,
         "isCommitted":false,
         "isClosed":false
      },
      "entityAnnotations":[
         
      ],
      "entityStream":{
         "bufferSize":0,
         "directWrite":true,
         "isCommitted":false,
         "isClosed":false
      }
   }
}
```

**Comment by wborn** [comment]
I created https://github.com/openhab/openhab-core/issues/1655 for the OH3 issue. For me it works fine in OH 2.5.x so I'll prioritize my time on getting the issue in OH3 fixed. :wink: 

If you proxy the calls using Apache/NGINX/HAProxy you should also test if it does work properly without the proxy. It's usually tricky to get the proxy configuration right so SSE works flawlessly.

**Comment by lolodomo** [comment]
Just to mention I fixed my last message. The required matching with the file name is on the sitemap name, absolutely not on the sitemap label.

**Comment by lolodomo** [comment]
I suppose it was a proxy setup problem which was then solved? 
Can we close this issue?

**Comment by lolodomo** [comment]
No more feedback
