### ISSUE TITLE
[Main UI] Integer parameter input won't accept '0' and doesn't respect max/min

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#338]
I have a parameter defined as follows -:

```
			<parameter name="zigbee_networkid" type="integer" min="0" max="3" required="true" groupName="ember">
				<label>Network Index</label>
				<default></default>
				<description>The Network Index used on the NCP</description>
				<limitToOptions>false</limitToOptions>
			</parameter>
```

When entering a value it will not accept 0. I can manually type this in, but it is removed as soon as the input looses focus. If I use the arrows to change the value, I can enter -1, then step up and it's blank, then step up and it's 1.

In the console I see the following when using the arrows to scroll up/down the value -:
```
app.js:12 {"zigbee_networkid":null}
12.app.js:1 Update zigbee_networkid to -1
app.js:12 {"zigbee_networkid":-1}
12.app.js:1 Update zigbee_networkid to -2
app.js:12 {"zigbee_networkid":-2}
12.app.js:1 Update zigbee_networkid to -3
app.js:12 {"zigbee_networkid":-3}
12.app.js:1 Update zigbee_networkid to -2
app.js:12 {"zigbee_networkid":-2}
12.app.js:1 Update zigbee_networkid to -1
app.js:12 {"zigbee_networkid":-1}
12.app.js:1 Update zigbee_networkid to 0
app.js:12 {"zigbee_networkid":null}
12.app.js:1 Update zigbee_networkid to 1
app.js:12 {"zigbee_networkid":1}
12.app.js:1 Update zigbee_networkid to 2
app.js:12 {"zigbee_networkid":2}
```

When it gets to 0, the value is "null".

I should say I'm probably running code that's a week or so behind master in case this was fixed recently.

I should also note that it allows me to enter values outside of the max/min, and I can also save with an out of range value (eg 6). If values are out of range there probably should be an error, and for sure it shouldn't be able to save the configuration.

**Comment by ghys** [comment]
Pretty nasty bug indeed, thanks - #339 fixes it, hopefully with no side effects.

**Comment by cdjackson** [comment]
Thanks Yannick - I was just trying to deal with the resulting null, so I’ll pull this down and give it a whirl.

Cheers
Chris
