### ISSUE TITLE
Update the color scheme for dashboard and Paper UI

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-webui#34]
With respect to the [logo update](https://community.openhab.org/t/new-logo-for-openhab/35140) I'd suggest to revisit PaperUI and dashboard styling to reflect the color scheme of the logo.

I collected the scheme in one manageable place for you to preview:
https://coolors.co/ffffff-b2b2b2-474747-e64a19-2196f3

**Comment by hmerk** [comment]
Won‘t fix as this is openHAB 2.5.x related and we have a feature freeze.
