### ISSUE TITLE
[mainUI] inconsistent behavior saving sitemaps/pages

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#340]
I am testing OH3 Build 1933 at the moment and found the save behavior inkonsistent in the area of sitemaps/pages. If a sitemap is developed i the new main ui we have the option to save the sitemap. We have two options to saver the map

1.) In the upper right corner is an icon to save the map "Save (CTRL-S)" 
![image](https://user-images.githubusercontent.com/40339145/93455195-4a398a80-f8dc-11ea-902f-aba6c1f521b8.png)
If i use this icon and click on it, then the sitemap is saved and closed so that i come back to the sitemap overview page

2.) If i use the keyboad shortcut CTRL-S the sitemap is saved (updated), but i stay in edit modus.

From my point of view the behavior should be consistent or better described. Personally things often. The easiest was to fix this is to change the upper right icon to "Save" and give somewhere on the page the hint that CRTL-S ist for intermediate saving

**Comment by MHerbst** [comment]
Another option would be to have two types of save function:

- Save: saves the changes and leaves the editor
- Apply: saves the changes but editor stays open

I have also seen a web bases editor where the save "button" is a combobox with two functions "Submit" and "Submit and stay" (default is "Submit"):
![image](https://user-images.githubusercontent.com/616792/94997889-6876da00-05ae-11eb-8acd-9425c86b65d6.png)

**Comment by TBail** [comment]
I like the idea og two buttons Svane & Leave and Apply the combo box is from my point of view a little bit unhandy.

**Comment by ghys** [comment]
Now both the save button and ctrl-S won't go back to the previous page.
This is applicable to the page editors, sitemap editor, rule editor and widget editor.
This includes when creating a new object.
