### ISSUE TITLE
Item linked to two channels is displayed twice

### ISSUE THREAD

**Issue by lucky62** [openhab/openhab-webui#341]
I am trying to configure OpenHAB to control the ESP-01 WiFi Relay flashed with Tasmota following this tutorial:
[Control Tasmota flashed devices via MQTT](https://community.openhab.org/t/control-tasmota-flashed-devices-via-mqtt/104099)
I have created the item Power to show/control the relay state.
This Item is linked to two MQTT channels (according tutorial):
    tele/WiFiRelay2/STATE
    stat/WiFiRelay2/POWER
Then the Item is displayed twice in ClassicUI and in PaperUI/Control. See attached screenshots.

![TwoChannels_SingleItem](https://user-images.githubusercontent.com/16965519/93686934-ea003f80-fab9-11ea-8494-47cc93efe27a.png)
![Doubled_Item_PaperUI](https://user-images.githubusercontent.com/16965519/93686937-ee2c5d00-fab9-11ea-8dae-a2af9a05e63d.png)
![Doubled_Item_ClassicUI](https://user-images.githubusercontent.com/16965519/93686938-f08eb700-fab9-11ea-976e-5602a68ecc95.png)

**Comment by hmerk** [comment]
Please show us your thing and item config. Your screenshots look like a misconfiguration, as it shows your power item on two different relay channels.
Please note, PaperUI shows all channels linked to items.

**Comment by lucky62** [comment]
ok, according the mentioned tutorial (link in first post) I have created two channels for relay POWER state.
Both CHANNELS are linked to the same ITEM.

First channel is for direct relay control. Relay is receiving MQTT message:
> **cmnd/WiFiRelay2/POWER** ON|OFF

and response is:
>08:54:30 MQT: stat/WiFiRelay2/RESULT = {"POWER":"ON"}
08:54:30 MQT: **stat/WiFiRelay2/POWER** = ON

Second Channel is for periodic update - relay is sending the message every 5min.
Channel is updating the same THING using POWER state retrieved from JSON message:
>08:56:56 MQT: tele/WiFiRelay2/STATE = {"Time":"2020-09-22T08:56:56","Uptime":"0T00:05:09","UptimeSec":309,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,**"POWER":"ON"**,"Wifi":{"AP":1,"SSId":"********","BSSId":"xx:xx:xx:xx:xx:xx","Channel":5,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:03"}}

This approach is decribed in the tutorial (especially in chapter **Status on startup**).
In the tutorial the configuration files were used. In my case the configuration was made via PaperUI.

So questions:
Is this behavior a bug?
Is the tutorial wrong?
Is the behavior differrent for config files and for PaperUI?

**Comment by hmerk** [comment]
I think there is a big Misunderstanding.
You dont have to create two channels, one for sending command and one for receiving status updates, but you have to configure two topics within the same channel. 
Here is a simple config example I use:
`Bridge mqtt:broker:mosquitto "Mosquitto MQTT Broker" @ "NUC" [ host="localhost", secure=false ] {
    Thing topic iFan02 "Sonoff iFan02" @ "Wohnzimmer" {
        Channels:
            Type switch : light "FanLight" [
                stateTopic="tasmota/sonoff_sz-2675/stat/POWER1",
                commandTopic="tasmota/sonoff_sz-2675/cmnd/POWER1"
            ]
    }
`

**Comment by lucky62** [comment]
I agree, there is some misunderstanding...

The approach I am using was published in the second post of the tutorial by @hafniumzinc with title:
**Slightly more advanced configurations**

In the example there is a this Thing (note the channel **power** and **state_power**):
>Thing mqtt:topic:swBedroomSideLight "Switch Bedroom Side Light" (mqtt:broker:MosquittoMqttBroker) {
	Channels:
		Type switch : **power** "Power Switch" [ 
			commandTopic="cmnd/swBedroomSideLight/POWER", 
			stateTopic="stat/swBedroomSideLight/POWER",
			on="ON",
			off="OFF"          
		]
		Type switch : reachable "Reachable" [
			stateTopic = "tele/swBedroomSideLight/LWT",
			on="Online",
			off="Offline"
		]
		Type number:rssi "RSSI" [
			stateTopic="tele/swBedroomSideLight/STATE",
			transformationPattern="JSONPATH:$.Wifi.RSSI"
		]
		Type switch:**state_power** "State Power" [
			stateTopic="tele/swBedroomSideLight/STATE",
			transformationPattern="JSONPATH:$.POWER"
		]
}

An ITEM example is linked to both channels:

> Switch sBedroomSideLight "Bedroom Side Light"  { channel="mqtt:topic:swBedroomSideLight:**power**", channel="mqtt:topic:swBedroomSideLight:**state_power**" }

So if this is not correct, then tutorial needs to be corrected...

**Comment by Rossko57** [comment]
As to PaperUI "problem", it is quite legitimate to link a single Item to more than one channel.
As PaperUI is the administrative interface, we want it to show active channels and the Items linked to them.
So yes, in these circumstances it will show the 'same Item' twice because there are two channels to display.  This is intentional.

**Comment by hmerk** [comment]
@lucky62 Please feel free to ask for a correction of the tutorial in the community. It is absolutely not necessary to have two individual channels for state and command.
@Rossko57 Yes Ross, it is legitimate, but I would call it a special use case where you link one Item to different Things (channels). For MQTT, it is not needed, you can combine both topics within one channel having individual inbound and outbound transformation.
As it should be clear now, not being UI related, I would assume to close this issue here.

**Comment by servim** [comment]
> stateTopic="tasmota/sonoff_sz-2675/stat/POWER1",
> commandTopic="tasmota/sonoff_sz-2675/cmnd/POWER1"

If you stop the OX, change the state of the switch, start the OX, will the OX display the real state of the switch for the time set in the Tasmota TelePeriod?
