### ISSUE TITLE
UI needs to support users with accessibility needs

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-webui#353]
Currently the UI shows required fields in red and message doesn't indicate that the fields are actually required. For example:

![image](https://user-images.githubusercontent.com/838221/94191218-d0bd1180-fe72-11ea-865a-cca2d22c5127.png)

This approach can cause problems for users with low vision, colorblind users, users with cognitive disabilities, and users with visual disabilities. 

A couple of good articles on this topic are:

- [The Anatomy of Accessible Forms: Required Form Fields](https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/)
- [How to Design for Color Blindness](https://usabilla.com/blog/how-to-design-for-color-blindness/)

**Comment by ghys** [comment]
Okay , not sure what are you suggesting?

**Comment by robnielsen** [comment]
The UI needs to be accessible, which it currently isn't.

**Comment by robnielsen** [comment]
There is also a [W3C Web Accessibility Initiative](https://www.w3.org/WAI/) that might be helpful.

**Comment by kaikreuzer** [comment]
> message doesn't indicate that the fields are actually required

The message reads: **"Please fill in this field."**. I think this is a VERY clear indication and fully accessible to everyone.

**Comment by robnielsen** [comment]
> The message reads: "Please fill in this field.". I think this is a VERY clear indication and fully accessible to everyone.

How is this accessible for a person who has vision problems?  

I don't know if you are aware, but color blindness  affects around 1 in 12 men and 1 in 200 women worldwide. So the red text won't mean anything to them about importance. A common and a recommended practice for accessibility is to put a * at the end of the label for required fields. For example:

![image](https://user-images.githubusercontent.com/838221/94272337-8a19f680-ff08-11ea-9880-b11dc9e3d65b.png)
This is accessible, and it's very clear that name is required and age isn't.

Please read the article [The Anatomy of Accessible Forms: Required Form Fields](https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/). It starts out with:

> Recently, I tried to order a cupcake on a new website and I utterly failed. I selected my choice of cake, added it to cart, tried to fill my delivery address and there started the road to chaos.
> 
> When I filled the details and submitted the form, a message saying “Please fill Address line 2” arose. Somehow, I sailed through and went to the “payment” section. Every time I clicked “submit,” it gave the same message: “please fill in the required field.” I scanned the forms to see if they gave any clue identifying these mandatory fields, but this effort was in vain.
> 
> Then, someone told me that the fields that were required would show in red color if they weren’t completed. If a person without disabilities couldn’t grasp these simple things while filling forms, I could imagine how people with visual, physical, and cognitive disabilities would feel.
>

**Comment by ghys** [comment]
Is this really the hill we're willing to die on?

> I scanned the forms to see if they gave any clue identifying these mandatory fields, but this effort was in vain.

In this case the validation message - which again is the result of https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-validationmessage which includes other constraints than a missing value, and whose wording the Chromium/Firefox and other browser developers probably chose carefully even if you disagree - is displayed right after the invalid field so the above statement doesn't really apply here.

That being said, you do have a point about a11y in general; it's a vast and often overlooked topic, and the UI is currently lacking in that department. I'm notably talking about keyboard navigation, making sure the focused element is properly outlined, and screen readers work well with it. It's a lot of work and tbh rather low priority, but I think the focus should probably be on the end user-facing pages before the administration area.

**Comment by robnielsen** [comment]
Isn't the goal of the new UI to create a better end user experience? I'd think implementing * for required fields would be an fairly easy thing to do, or am I wrong? Such a simple change would go along ways in usability.
