### ISSUE TITLE
UI allows things to be added without selecting a bridge

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-webui#360]
When a thing is associated to a bridge, there isn't any indication that the bridge is required, nor is there any validation to ensure a bridge was selected. The UI should both indicate that the bridge is required, along with the proper validation.

**Comment by ghys** [comment]
Not true, there's a clear message (which disappears when one is associated):
![image](https://user-images.githubusercontent.com/2004147/95003807-83b00c80-05e3-11eb-9878-506fa8e0fc28.png)

Not associating to a bridge is an abnormal but not unsupported situation, and might even be useful in certain circumstances so there's no enforcing to be done.
