### ISSUE TITLE
[habpanel] unable to edit custom widget settings

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-webui#361]
I'm unable to edit any custom components settings in 3.0.0-snapshot version of habpanel.
The problem seems to be here https://github.com/openhab/openhab-webui/blob/8420bbd9fbcd2272485f2b5bb107e83c1a1f3c7d/bundles/org.openhab.ui.habpanel/web/app/widgets/template/template.widget.js#L152.

```
                if ($rootScope.configWidgets[$scope.widget.customwidget]) {
```
$rootScope.configWidgets is undefined so the line throws an Error.
Should a check be added or $rootScope.configWidgets is supposed to always be defined? I have not enough knowledge about the project. Thanks in advance.

**Comment by ghys** [comment]
It was supposed to always be defined in OH2.5 but I removed (disabled) this feature with #327, so I added some more checks but sadly left this one out... thanks for the report! Fixed in #363.
