### ISSUE TITLE
JS Transformation chashes OH3 items

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#362]
Today i tried to fransform a value von 0 to 254 to a percent scale using a JS Transformation.

To do this i opens the respective Items and added the transformation to the state description metadata. That is in my understanding the new way to transform values to display in diffferent formats.

![image](https://user-images.githubusercontent.com/40339145/94560232-a0a2b380-0262-11eb-8505-ea240b9bf6c6.png)

In the log i got the following error:

`2020-09-29 14:02:04.855 [ERROR] [rg.apache.cxf.jaxrs.utils.JAXRSUtils] - Problem with writing the data, class org.openhab.core.io.rest.Stream2JSONInputStream, ContentType: application/json
`
The UI is endless loading
![image](https://user-images.githubusercontent.com/40339145/94559670-e0b56680-0261-11eb-8932-aee7f7a4dada.png)

Deleting the Pattern directly from the json DB solves the problem.

**Comment by ghys** [comment]
This probably should be filed under openhab-core.

**Comment by TBail** [comment]
I will open the same issue under openhab-core, But maybe there is a solution for the ui, so that an editing of the json db files is not neccessary.
