### ISSUE TITLE
[Main UI] Output of a confirmation message if Back is pressed and there are unsaved changes

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#367]
If you edit a rule or schedule and you press the Back link then your changes if you did not save them before. Some sort of confirmation would be nice in this situation to avoid frustration because of accidentally lost edits.

**Comment by ghys** [comment]
Agreed, I'd been thinking about this for some time but it's not this easy to do, I haven't found a way to intercept it cleanly.
