### ISSUE TITLE
layout and POM hierarchy

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#38]
@martinvw already migrated that repository to a POM first approach.

It seems he decided to use a parent POM that is part of openHAB Core.
Personally I don't see any reason for it and I don't know if it complicates the release process because it refers to a parent that version number is not control of the project itself.

Additionally the base POM in this reactor uses the "bundles" POM as parent which should not be necessary for non bundle modules.

I would also suggest to use a layout similar to core and the migrated addons repo.
IMHO it would be "better" to use one layout for all repositories that provides bundles.

With respect to testing I also would like to provide a BOM of all bundles in that repository.

If you agree with all that points, I can do the "cleanup" for you.
If you don't agree with all points, all fine.
If you agree with some and disagree with others, tell me your ideas.

**Comment by martinvw** [comment]
> It seems he decided to use a parent POM that is part of openHAB Core.

I mistakenly assumed that this was desired, if it should just be independent that would indeed be way nicer :-)

**Comment by maggu2810** [comment]
It is up to @openhab/webui-maintainers 
If you decide by noon tomorrow, I can finish it before my vacation.

**Comment by martinvw** [comment]
I'm not one of them but I vote 👍 

Others?

**Comment by kaikreuzer** [comment]
> I would also suggest to use a layout similar to core and the migrated addons repo.
> IMHO it would be "better" to use one layout for all repositories that provides bundles.

I am definitely for this, so in this respect, it isn't really up to @openhab/webui-maintainers, but rather the suggested way of how all addon repos should be structured - the openhab2-addons probably being the best reference for it.

**Comment by maggu2810** [comment]
fixed by #44
