### ISSUE TITLE
[Main UI] Manually created Things related to a Bridge should be created with proper ThingUID

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#380]
When creating a `Thing` manually via UI and assign it to a `Bridge` the resulting `ThingUID` does not contain the bridge id.

Create a Thing:

![grafik](https://user-images.githubusercontent.com/5131747/95477592-ce85a780-0988-11eb-8a94-fa7969bdaaff.png)

Assign it to a Bridge - Identifier changes properly:

![grafik](https://user-images.githubusercontent.com/5131747/95477833-11477f80-0989-11eb-9ae1-819809ef1d98.png)

Use "Create Thing" and sniff POST request - UID does not contain the bridge id anymore and thus it will be created wrongly:

![grafik](https://user-images.githubusercontent.com/5131747/95477842-14427000-0989-11eb-801d-cacda03cc8a4.png)

Related to https://github.com/openhab/openhab-core/pull/1704
See also https://github.com/openhab/openhab-addons/pull/7496#discussion_r425425821

**Comment by ghys** [comment]
oof 😬 

https://github.com/openhab/openhab-webui/blob/1e5a41f0f967ff1f63455298723f15519e4b3a49/bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue#L109
