### ISSUE TITLE
[Main UI] Understanding profiles in main ui

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#382]
Currently i am testing with OH 3 Build #1963 and tried to setup a profile. I found two things that i do not really understand.

1.) If no profile is selected none of the radio button ist selected. If i select any of the other displayed profiles nothing more happens. From my point of view based on the selected profile something should happen. i.e. give the option to select the channel to follow with the follow profile

2.) The functionality of the radiobuttons ist not clear to me either. The "(No Profile)" could be selectetd, but is never saved even if the save button is pressed. If i select "Standard" it could be saved, but it is not possible to switch back to "(No Profile)".

So maybe there is an explanation for this behaviour

**Comment by ghys** [comment]
That's normally what happens with e.g. the JSONPATH, JS, offset or other profiles.
The "follow" profile doesn't have a config description therefore there's nothing to configure.
The issue about the "(No Profile)" not being checked, or the check disappearing, is a bug.

**Comment by TBail** [comment]
@ghys Do i understand it right, that beside the bug the profiles that i can selecht im main ui have not function at all?
