### ISSUE TITLE
[Main UI] Context Password not applied for voice services in section "Other services"

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#387]
See [config.xml](https://github.com/openhab/openhab-addons/blob/168913baba81ba2ca5bbfc802fc62f2a91a7c3ef/bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/config/config.xml#L23) - Parameter `clientSecret` should be display in input of `type="password"`.

<input name="clientSecret" type="text" autocomplete="" data-validate="true" class="input-with-value" required="">

![grafik](https://user-images.githubusercontent.com/5131747/95762538-220c3400-0cae-11eb-8ed7-487413b51e4a.png)

![grafik](https://user-images.githubusercontent.com/5131747/95762484-102a9100-0cae-11eb-84dd-8d4eeebf1ac9.png)

**Comment by ghys** [comment]
https://github.com/openhab/openhab-addons/blob/168913baba81ba2ca5bbfc802fc62f2a91a7c3ef/bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/config/config.xml#L23
`<context>Password</context>`

https://github.com/openhab/openhab-webui/blob/22b5e9f478f68f52b63cda40a371de22aa5889de/bundles/org.openhab.ui/web/src/components/config/controls/parameter-text.vue#L13

in other words, it's assumed to be case-sensitive and lowercase.

I'm not sure whether the official specs say on this, are they supposed to be case-sensitive or not, but if it's the only instance of a context with a capital P, I would suggest to fix that and be done with it :)

**Comment by cweitkamp** [comment]
Thanks for the hint. I submitted https://github.com/openhab/openhab-addons/pull/8744 to fix it.

In general I am thinking we should go with lowercase context. At least all [examples](https://www.openhab.org/docs/developer/bindings/config-xml.html#supported-contexts) in the docs are written in lowercase.
