### ISSUE TITLE
[habpanel] Unable to edit imported widget

### ISSUE THREAD

**Issue by MDAR** [openhab/openhab-webui#388]
Hi

Thank you all for all your incredible hard work with OH3

I've noticed something strange with HabPanel in OH3.

I can import a widget (which works perfectly with OH 2.5.x HabPanel)

Placing it in a dashboard is okay, but when clicking on Edit absolutely nothing happens. (I can move / copy & delete)

If I find the widget code among the XML file for HabPanel, I can change the fields and the widget works perfectly.

So far I've only tried importing three Widgets, but they all behave the same way.

**Comment by kaikreuzer** [comment]
Done.

**Comment by MDAR** [comment]
I'm happy to supply the widgets and associated Items of it helps

**Comment by ghys** [comment]
I thought this was fixed with #363 two weeks ago?
Are you using openHAB 3.0.0.M1?

**Comment by MDAR** [comment]
I didn't know that, I'll update and try again.

Thanks for the heads up

**Comment by MDAR** [comment]
I'm so sorry for posting this issue, I've updated to M1 and it's working perfectly now.

Thank you all so much.
