### ISSUE TITLE
[Main UI] Toggling a marker on floorplan does not work properly on iOS

### ISSUE THREAD

**Issue by Trickx** [openhab/openhab-webui#389]
openHAB version: 3.0.0
I created a simple floorplan with a marker to toggle some lights.
While the marker properly toggles my lights accessing the page via Firefox or Chrome under Window 7 or Macosx,
it does not under iOS (iPhone SE 1. Gen or iPad Mini 3, both running iOS 14.0.1).
It looks like the action, toggling in my case, is executed twice per touch event in most cases.
The lights start to flicker a bit, but remain/return in their original state.
Sometimes it works though.

**Comment by ghys** [comment]
Is this issue still current? Can anyone confirm this? I couldn't reproduce it on an iPhone recently.

**Comment by Ronson1909** [comment]
Yes, I can confirm this issue with current openHAB 3.0.1 Release Build in the iOS Webinterface (but have not yet tested it in different browsers). Would be great to get it fixed.
