### ISSUE TITLE
[MainUI] Filter Channels by whether or not they have an Item linked

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#395]
Some discussion of this is located at https://community.openhab.org/t/openhab-3-0-my-getting-started-and-notes/106467.

Once an OH system is set up there are times where one only cares about the Channels of a Thing that are linked to Items. This is most important for Things with lots and lots of Channels like Astro and the various weather bindings.

Obviously this is a very low priority feature request. But as I was gradually migrating my OH 2 instance to OH 3 I would have found such a feature very useful.

**Comment by ghys** [comment]
You'll note that while it's true that you can't filter, you do have a visual clue to identify channels that are already linked:
the blue "1" badge on the right represents the number of links.

![image](https://user-images.githubusercontent.com/2004147/96168195-b67dcd00-0f20-11eb-9660-ed31799eb931.png)

**Comment by rkoshak** [comment]
Yes I did notice that and it's one of the reasons why this is merely a suggestion that if it gets closed I won't have any heart burn about it.
