### ISSUE TITLE
[MainUI] Move the discovered Things below the menu items to manually create a Thing

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#398]
This is likely going to primarily be a problem for the Network binding but it's a very annoying problem. There might be other bindings that have lots of Things to discover that one may not care about, maybe MQTT. Anyway, what happens is you get to the place where you want to manually create a new Thing and the menu entry jumps around as the binding goes into discover mode and starts to discover things.

https://gyazo.com/926b4afe4fbdb15d7969be930bac9853

(I don't know if the above works or not but it shows what I mean, I wish I knew how you guys capture those snazzy animated GIFs). 

Depending on how fast it discovers new Things and how many there are it can become very annoying to have to wait for it to finish before the menu stabilizes enough to click the menu to manually create the Thing you want.

**Comment by ghys** [comment]
It's surely annoying, but I don't think I agree with your solution to move the discovery results to the bottom.
Maybe instead:
- not start the scan right away, let the user click on the scan button.
- while it's scanning change the scan button to "stop the scan" - note that you actually can't abort a scan, but this would stop listening for events so the "discovered" list will stop being populated with new entries.

**Comment by ghys** [comment]
> I wish I knew how you guys capture those snazzy animated GIFs

On Linux Peek works quite well: https://github.com/phw/peek
On Windows, LICEcap or ShareX: https://getsharex.com

**Comment by rkoshak** [comment]
I'm not married to the solution. Anything that makes it so I don't have to sit and wait for the discovery to settle or trying to type my clicks to get the right menu item works for me. :-)

>while it's scanning change the scan button to "stop the scan" - note that you actually can't abort a scan, but this would stop listening for events so the "discovered" list will stop being populated with new entries.

Does this open a potential problem if the user initiates a new scan while another scan is already going?

**Comment by ghys** [comment]
> Does this open a potential problem if the user initiates a new scan while another scan is already going?

Not sure, but I don't think so, because IIRC Paper UI allowed to click the scan button without disabling it until the scan timer expired.
