### ISSUE TITLE
[cometvisu UI] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-webui#4]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in cometvisu UI depend on Full JRE:

- org.openhab.ui.cometvisu.internal.config depends on javax.xml.bind (Full JRE)
- org.openhab.ui.cometvisu.internal.config depends on javax.xml.bind.annotation.adapters (Full JRE)
- org.openhab.ui.cometvisu.internal.config.beans depends on javax.xml.bind (Full JRE)
- org.openhab.ui.cometvisu.internal.config.beans depends on javax.xml.bind.annotation (Full JRE)
- org.openhab.ui.cometvisu.internal.config.beans depends on javax.xml.bind.annotation.adapters (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by peuter** [comment]
Is this still relevant? The link to the documenation is not woring anymore. It its relevant I would need some guidance on how to replace that.

**Comment by wborn** [comment]
This can be closed. JAXB became an optional dependency with Java 11.
