### ISSUE TITLE
[paper] States with decimals save properly only the first time

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-webui#40]
* Create an Item of type Number
* Create a new rule
* Add a Trigger or Condition with a required State of 2.1
![image](https://user-images.githubusercontent.com/21967853/54684674-537d4780-4aeb-11e9-8371-c504590dc71f.png)

* Save Rule
* Open automation_rules.json and observe...

```
          "configuration": {
            "itemName": "Virtual_Number_1",
            "state": "2.1"
          },
```

* Open the Rule and the Trigger/Condition, and then save without making any changes
* Note the Trigger/Condition will save the state like...

```
          "configuration": {
            "itemName": "Virtual_Number_1",
            "state": 2.1
          },
```
This will cause the rule to not work as expected. In the UI, this issue is not even noticable, unless you happen to use a decimal like 2.0, which will visually change to 2. This issue was [reported in the forum](https://community.openhab.org/t/paperui-rule-bug-state-with-decimal/70627). I observed it in S1557.

**Comment by lolodomo** [comment]
PaperUI was removed in OH3.
