### ISSUE TITLE
[MainUI] Channel links have to be locked when defined in conf files

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#413]
For the channel links created in conf files, the UI should not allow to remove them.
![image](https://user-images.githubusercontent.com/10186704/96367417-fece0280-114d-11eb-9151-7352bf3406c7.png)

A lock icon should be displayed somewhere and the 2 buttons "Unlink & Remove item" and "Unlink ionly" should be greyed and not clickable.

Additionally, for a link defined by the UI. if the item is defined in a conf file, the button "Unlink & Remove item" should be greyed and not clickable. Only the button "Unlink only" should be usable in this case.

**Comment by ghys** [comment]
I think I had a look at the time, and links don't have an `editable` flag, so we can't know whether they come from textual configuration and therefore can't be removed or not. Maybe that would be relatively to figure out and implement in core.

> Additionally, for a link defined by the UI. if the item is defined in a conf file, the button "Unlink & Remove item" should be greyed and not clickable. Only the button "Unlink only" should be usable in this case.

Fair.

**Comment by lolodomo** [comment]
@kaikreuzer  @wborn @cweitkamp : would it be possible to update the core to identify the channel links that are managed or not?

**Comment by cweitkamp** [comment]
After a quick look I would say that it is possible. We have to Introduce an `EnrichedItemChannelLinkDTO` extending the `ItemChannelLinkDTO` by the requested `editable` property. If it is editable could be validated against the `ManagedItemChannelLinkProvider`. Straight forward. Similar to what we are doing for Things or Items.

**Comment by ghys** [comment]
I removed the buttons when the item is not editable in #473, and filtered out non-editable items when reusing an existing item when creating a link from the UI. I think it's safe to assume that if an item is going to be defined with textual configuration, so is the link.

**Comment by lolodomo** [comment]
You can have your items defined in config files but your things managed through the UI. In this case, it is important to be able to link to an item defined in a config file.

**Comment by ghys** [comment]
Yes, but if you're defining your items in config files, chances are you're going to go ahead and define the link with
`{ channel="uid" }`
in the config file anyway. I don't think there are many cases of links being created in the UI while the item is not.

**Comment by lolodomo** [comment]
Yes, that is the most probable but why adding this constraint ?

**Comment by ghys** [comment]
Since the editable status of links cannot be determined yet, I figured it would be good to prevent these kinds of situations (links to non-editable items where we don't actually know if the link itself can be deleted) to happen in the first place?
