### ISSUE TITLE
[MainUI] API Explorer in developer tools not usable

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#415]
When I open the API explorer page, all REST API are displayed but I can't use them. All input fields are locked and and I see no "run" button.
This is with OH3 started from Eclipse (dev env).

**Comment by ghys** [comment]
There should be a "try it out" button on the right, which will unlock the fields and add an "Execute" button.
Why the Swagger UI devs thought it was necessary, I have no idea, but AFAIK it can't be changed.

**Comment by lolodomo** [comment]
Got It. Not very intuitive but ok
