### ISSUE TITLE
[Main UI / Basic UI] Nested frames in Basic UI

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#420]
I am running OH3 build #1975 and reconized that the pages editor for Basic UI sitemaps allowes nested frames. These nested frames are displayed correctly in the web implementation.

![image](https://user-images.githubusercontent.com/40339145/96450912-1de49700-1217-11eb-8d4a-79573efad3cb.png)

If i open the sitemap in the android app those nested frames are gone/not functional anymore.

![image](https://user-images.githubusercontent.com/40339145/96451319-aebb7280-1217-11eb-83c4-5690ca586a7c.png)

Personally i like the idea of nested frames but i can live without them. Never the less the should be a clear communication about this feature/bug and according action should be taken on this.

Option 1: Implement this feature in Android app
Option 2: Deimplement this feature in Main UI / Basic UI

**Comment by lolodomo** [comment]
As option 2 is not a reasonable option, I would suggest to create a feature request for the Android app (option 1).

**Comment by lolodomo** [comment]
@ghys : I am suggesting to close this issue and tag it with "won't fix".

**Comment by ghys** [comment]
thanks @lolodomo - agreed it's not something that shouldn't be client-specific, so closing until there's a common approach.

**Comment by lolodomo** [comment]
@mueller-ma @maniac103 : for your information, a feature request for Android app.

**Comment by maniac103** [comment]
@lolodomo That request came up before, but @kaikreuzer said nested frames are not a supported use case, IIRC. (Which we're glad about, because I don't see how one would go about implementing it in a reasonable way in the app)
