### ISSUE TITLE
[MainUI] Accentuated caracters disappear from generated item names

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-webui#421]
the group item is labelled "Départment" is changed to dpartement
![image](https://user-images.githubusercontent.com/3328789/96453381-ad3f7980-121a-11eb-9314-fe8b862304e1.png)

In general all accentuated chars are dropped (éèô...)

**Comment by ghys** [comment]
Not related to the actual problem but here's a tip: when you use "Add Thing as Equipment" the prefix of the default name for the Point items (linked to channels) is the name of the Equipment item defined above. The default name is computed when you check the channel. So if you fix the name of the equipment to "AlertesDepartement", and uncheck/recheck the channels, they will have "AlertesDepartement" as the prefix.

**Comment by Rossko57** [comment]
I'm not sure that accented characters are allowed in Item names.  There are other restrictions, like not beginning with a number.  The name is for "internal use".

**Comment by clinique** [comment]
Agree but my first idea would be to normalize accentuated chars : éèê => e

**Comment by ghys** [comment]
This article has a comparison of the libraries that can help with this:
https://medium.com/javascript-in-plain-english/not-so-obvious-removal-of-diacritics-in-javascript-explained-and-done-right-52f4aeb3c85

I think I'll try the recommandation, `diacritic`.
