### ISSUE TITLE
[MainUI] Display of thing channels no more happening

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#422]
After 2 hours searching what could be the error in the code I changed today, I finally discovered that even with another binding (unchanged), the main UI is now no more able to display the thing channels. There is a kind of blinking.
![image](https://user-images.githubusercontent.com/10186704/96506428-ea762c80-1257-11eb-8724-0a66b9ad38ee.png)
My Eclipse resolves with this version: 
![image](https://user-images.githubusercontent.com/10186704/96506033-3f657300-1257-11eb-8fde-e3b80dfc7502.png)
Yesterday, it was working but I think the UI was from the 16th of this month.

**Comment by ghys** [comment]
I think it's due to a regression/bug introduced by https://github.com/openhab/openhab-core/pull/1713.
If you check the browser's dev tools, the thing-types & channel-types API are likely 403 forbidden to administrators.
I fixed it in https://github.com/openhab/openhab-core/pull/1735.
