### ISSUE TITLE
[MainUI] How to delete an item ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#430]
I found how to create a new item, how to update an existing event but I don"t find in the UI how to remove an item.

**Comment by TBail** [comment]
Select item in the left menu

![image](https://user-images.githubusercontent.com/40339145/96776780-c5b1be80-13e9-11eb-861e-7e680a16d434.png)

Then you will see a list of all your items and in the upper right corner is an option to select.

![image](https://user-images.githubusercontent.com/40339145/96776880-e9750480-13e9-11eb-9683-f81ee74fbb97.png)

If selected with a click in front of each item a check mark is displayed.

![image](https://user-images.githubusercontent.com/40339145/96776995-06a9d300-13ea-11eb-8602-14a40da5d488.png)

There you could select one or more items and the use the delete. You will find the remove option in the left lower area of the screen

![image](https://user-images.githubusercontent.com/40339145/96777190-4d97c880-13ea-11eb-963f-47b9eb49f2fd.png)

**Comment by lolodomo** [comment]
Thank you a lot, I did not see the "remove" at the lower left !
