### ISSUE TITLE
Deleting other session causes browser to forget about its own session

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#441]
While testing the session management I found that when deleting another session causes the browser to forget about its own session details (see https://github.com/openhab/openhab-core/pull/1735#issuecomment-715880403).

I made a little video that shows the issue. In the video you can see I'm logged in via Chrome (dark UI) and create a second session in Firefox (light UI). When I delete the new session in Chrome, both browsers can no longer use their session:

![video](https://user-images.githubusercontent.com/12213581/97108139-e15be400-16cb-11eb-9724-f7b4a90cf42f.gif)

Afterwards I also looked at the cookie set in Chrome just after deleting the Firefox session:

![cookie](https://user-images.githubusercontent.com/12213581/97108143-e6209800-16cb-11eb-8798-722c537c9962.png)

It seems the session ID is set to "":

**Comment by wborn** [comment]
I think it is because the TokenResource [unconditionally sets a new cookie](https://github.com/openhab/openhab-core/blob/acdbdfa4d7639b3ebb48a9ad78fad0448158a2a1/bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java#L244-L253) regardless if it is the current session?

**Comment by ghys** [comment]
Of course, you're right... The cookie should only be cleared when it matches the session Id being deleted.
Thanks for investigating!
