### ISSUE TITLE
repo name vs. group ID

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#45]
While working on #44 I wonder about the choosen group ID.
The groupId prefix is `org.openhab.ui` and the repository name of `openhab-webui`.

Why has not been used a groupId similar to `org.openhab.webui`?

Do you plan to rename that repo to `openhab-ui` some time?

**Comment by kaikreuzer** [comment]
No, the repo names are not meant to be in sync with the groupIds as we have many repos that have no relation to Maven whatsover. The Maven groupIds rather reflect the Java package naming.

**Comment by maggu2810** [comment]
Okay, it could make things easier but its your decision.
