### ISSUE TITLE
OH3 Number input configuration parameters do not allow option values outside of the defined range

### ISSUE THREAD

**Issue by rogierhofboer** [openhab/openhab-webui#459]
Options are not taken in to account for Number configuration parameters which also have options outside of the range. 

The range is set as min and max of the f7-list-input control, but this way option values outside of this range are not accepted. 

Unfortunately the built-in validation of the f7-list-input control cannot be used in this case and a custom validation should be made to check the range and allow all options (even when outside of the range).

See: https://www.openhab.org/docs/developer/bindings/config-xml.html

Property | Description
-- | --
parameter.min | The minimal value for numeric types, or the minimal length of strings. Note that the value of any options may be outside of this value (optional).
parameter.max | The maximum value for numeric types, or the maximum length of strings. Note that the value of any options may be outside of this value (optional).

**Comment by ghys** [comment]
I simply disabled the min/max checks in #473 when there are options present, it will have to do for this niche case as options outside the normal range can now be set again. PR welcome to improve this.
