### ISSUE TITLE
[MainUI] Cannot save rule script action from code editing page

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#460]
When editing the code in the text code entry pop-up (also when using the full page editor) pressing ctrl-s brings up the little toast saying that the rule was updated, but the rule is not actually updated. One must exit the editor, exit the configuration panel and then ctrl-s or click the save link at the top for the changes to take effect.

**Comment by ghys** [comment]
This used to work but due to recent changes, not anymore...

**Comment by ghys** [comment]
#469 fixes this and improves the editing of scripts drastically - but only when you the little "shortcut" icon
in the script module to open the new editor:

![image](https://user-images.githubusercontent.com/2004147/97778647-dd6f0c80-1b78-11eb-930e-d1589282a4d4.png)

When you open the module configuration popup then click on "edit script", nothing changes - it will still apply the changes to the rule when you close it.
