### ISSUE TITLE
[Main UI] things from uninstalled binding can't be deleted

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-webui#461]
STR:

Install samsungtv binding, add a thing, uninstall binding. Thing is displayed as "unitialized", clicking on the thing results in a never loading page, so "Delete Thing" is never displayed. No errors in log.

**Comment by ghys** [comment]
was fixed yesterday in #454.

**Comment by J-N-K** [comment]
That was fast :-)

**Comment by ghys** [comment]
The only thing is that the first time the thing does to the REMOVING state, and stays in that state because he's waiting for the non-existent binding, so you have to go back and delete it a second time with the "force" option to actually remove it for good.
I didn't address this specific case.

**Comment by J-N-K** [comment]
That‘s ok and the same before in PaperUI. And makes Sense.
