### ISSUE TITLE
p2 repo

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#47]
The repository still contains a p2 repo generation.
Is this still necessary of can this been dropped.

**Comment by kaikreuzer** [comment]
Do we have a working IDE for people doing binding development? As long as this is not in place, we imho should keep the old one in place.

**Comment by wborn** [comment]
I did some binding development using the Demo App and Basic/Paper UI worked for me. Do you think we can remove the p2 repo now?

**Comment by kaikreuzer** [comment]
Definitely!
