### ISSUE TITLE
[Main UI] Icon not display

### ISSUE THREAD

**Issue by mccaffm** [openhab/openhab-webui#472]
Using editor to create a page cell produces the following YAML. but no icon is displayed

```
component: oh-label-cell
config:
icon: oh:sun
title: window
item: BathroomWindow
slots: null
```

openHAB 3.0.0
Build #1984

**Comment by Tukks** [comment]
![image](https://user-images.githubusercontent.com/5930169/97758362-02bf3480-1aff-11eb-903c-372809072960.png)
You can find a 404 in the network section, the url seems to be wrong (does not work on local access, and on remote acces via openhabcloud)
