### ISSUE TITLE
[MainUI] Inbox / add as thing: let the user decide the thing id

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#474]
When you add an inbox entry as thing, the pop-up propose to edit the thing label. It would be cool to have a way to edit the thing id (last part of the thing UID) too because it is something no more editable later.

**Comment by ghys** [comment]
Agreed, but it's not really a "webui" problem since the `/rest/inbox/{thingUID}/approve` API only lets you approve inbox entries where the thing ID has been already decided. I suggest moving it to core to propose a change to the API.

**Comment by lolodomo** [comment]
Ok with your suggestion ;)

**Comment by lolodomo** [comment]
@ghys : can you please reopen this issue.
I have implemented the feature on core side: openhab/openhab-core#1848

**Comment by lolodomo** [comment]
Change in core is now merged. 
@ghys : it would be super now if the MainUI could be enhanced to provide a new field in the popup to enter an optional thing id (that will replace the one set by the discovery).

**Comment by ghys** [comment]
Okay, there's no dialog with 2 text fields available so there will be a need for a completely redesigned UI to approve.

**Comment by ghys** [comment]
Adding the question label until the problem with the API is fixed (see https://github.com/openhab/openhab-core/pull/1848#issuecomment-744064244)

**Comment by lolodomo** [comment]
@ghys : API is now fixed in core framework (PR merged).

**Comment by lolodomo** [comment]
@ghys : I don't understand how it was enhanced.
Here is the dialog box when I add a thing for the inbox:

![image](https://user-images.githubusercontent.com/10186704/104130151-80a98280-536f-11eb-842b-3d145f6c538f.png)

As before, I have a control only on the label but not on the thing id.

**Comment by ghys** [comment]
When you click on a thing and get the menu you should have a new "Add as Thing (with custom ID)" option, if not that might be a cache problem, go to Help & About and select the purge caches option if you have it, otherwise Reload app.
![image](https://user-images.githubusercontent.com/2004147/104139070-275e4500-53a9-11eb-88b8-a9d19d372a52.png)

**Comment by lolodomo** [comment]
Oh yes, I see the menu on my phone. 
I will try to understand why the menu is not displayed on my PC while I cleared the 
WEB browser cache.

**Comment by lolodomo** [comment]
@ghys : I know what is happening. Your menu is OK in the "Inbox" page. The problem is that this menu is not proposed in the "Add a new Thing xxxxxx" page.
There is a workaround, I just have to return to the inbox page before adding my thing. But this is something usual to search a thing and to add it directly for the "add a new thing" page.

**Comment by lolodomo** [comment]
In fact, I am just discovering again my feature request #416  ;)

**Comment by ghys** [comment]
I didn't forget about #416, I regularly check issue lists, and it will probably come in conjunction with it when/if it gets implemented.
#775 was mostly about fixing #744 to include it as part of the 3.0.1 patch release, I just added it because it was safe to add and in the same file :)
