### ISSUE TITLE
[MainUI] Hidden things if binding not installed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#480]
If a thing exists on the server side but the underlying binding is not installed, this thing is not displayed in the things page.
I believe it should be.

**Comment by ghys** [comment]
Mh, you sure about that? Just tested and I cannot reproduce this. The thing lists contains what the API returns, nothing more, nothing less.

**Comment by lolodomo** [comment]
When I remove my jar file from the addons folder, my things linked to this removed binding are still there in UI. If I restart OH, they are no more listed even if a things file exists.
But the console command "things list" does not list them too.
And the things REST API does not list them too.

If I add again my jar file, things are appearing again.

So there is no issue in the UI, maybe more something weird on server side.
