### ISSUE TITLE
[MainUI] Edit script button no more working

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#486]
Snapshot 2003
Nothing happens when I click on the button "Edit script".
It was working in older snapshots.
My rules are DSL rules coming from a config file.

**Comment by lolodomo** [comment]
Correctly fixed, thank you. The new integration, rather than a small pop-up, is even better than before.

**Comment by ghys** [comment]
I think so too, and I want the future developer sidebar (#437) to remain accessible while editing (especially if you edit the script in the UI).
