### ISSUE TITLE
[MainUI] Properties display: missing access to chart for some of the items

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#488]
For my temperatures which are stored in rrd4j, MainUI is providing an access to the chart for some of them but not all.
![image](https://user-images.githubusercontent.com/10186704/97842855-a3bd1380-1ce8-11eb-992b-d000359eb6ed.png)
I have a RRD4J file for each of them: TemperatureBureau.rrd and TemperatureExt.rrd
My feeling is that access to the chart is currently only for number items with a dimension.

**Comment by ghys** [comment]
Yes the default is currently only to open the analyzer for numbers with dimensions, but this behavior is expanded to other types, you can enable it ad hoc for an item by modifying its "default list item widget" metadata - choose e.g. Label Item and then the Analyze action, and specify your items in the "Analyze Items" parameter.
