### ISSUE TITLE
[MainUI] Properties display: sorting of properties

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#489]
How properties are sorted ?
I don't see any logic. It does not follow the ordering of definition in my config file. It is not sorted on item name, nor in item label.

**Comment by lolodomo** [comment]
Using the order of items in the config file would be appreciated.

**Comment by ghys** [comment]
It's planned to let the order by modified with a metadata config property in the "default list item widget" metadata (`listWidget`).

**Comment by lolodomo** [comment]
That would be cool if you could put a relative high priory to this enhancement. 
Without a way to control how stuff are sorted in UI, the UI is not pleasant to use.
