### ISSUE TITLE
basicUI with visibility not work correct

### ISSUE THREAD

**Issue by Gozilla01** [openhab/openhab-webui#49]
Problem:
With the use of the visibility function the updating of the field with chrome browser does not work correctly. See simulation

Chrome error is present
Edge works
IOS app works

OH versione openHAB 2.5.0 Build #1564
Chrome version Versione 73.0.3683.103 (Build ufficiale) (a 64 bit)
Edge Microsoft EdgeHTML 17.17134
App. iOS Openhab 2.0.3.0

I opened this discussion to attach an animated git to reproduce the problem.
[https://community.openhab.org/t/basicui-with-visibility-not-work-correct/71800/2](https://community.openhab.org/t/basicui-with-visibility-not-work-correct/71800/2)

**Comment by lolodomo** [comment]
Please try again with a recent snapshot. I guess it was already fixed.

**Comment by lolodomo** [comment]
@ghys : please close this issue. No feedback after more than one year. The problem was very probably already fixed.
