### ISSUE TITLE
[MainUI] Properties display: custom icons ignored

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#490]
Example of item:
```
Switch TvMute "Sourdine TV" <mute> (GTvSalon) [ "Switch", "SoundVolume" ] { channel="remoteopenhab:server:oh2:TvMute" }
```
And here is the rendering:
![image](https://user-images.githubusercontent.com/10186704/97844180-d962fc00-1cea-11eb-85b9-0cdd5b75306b.png)
No icon displayed.
Here is the rendering in BasicUI:
![image](https://user-images.githubusercontent.com/10186704/97844334-1f1fc480-1ceb-11eb-88ad-f80a0db255af.png)
And here are my custom icons:
```
$ ls mute*
mute-off.png  mute-on.png  mute.png
```

**Comment by lolodomo** [comment]
@ghys : With all the fixes you already provided, this issue is now one of the most annoying for me. For certain items, I tale more attention to the icon than to its value. If you could make this relatively high in your TODO list, that would be reaaly appreciated.

**Comment by ghys** [comment]
The problem I reckon is that the UI fetches SVG icons by default, there needs to be options to force widgets to fetch the PNG version instead.

[CONTRIBUTING.md](https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/CONTRIBUTING.md)

**Comment by lolodomo** [comment]
In OH2, I implemented in the core framework the code returning the good icon, in PNG if only available in PNG or in SVG if available in SVG format.
Basic UI is requesting the SVG format too but can get as returned a PNG file. I could have added a specific URL parameter for that, I don't remember exactly nown but can check the code in Basic UI.

**Comment by lolodomo** [comment]
Hiere is my PR from August 2019.
https://github.com/openhab/openhab-core/pull/978
You have to use the parameter `anyFormat` and set it to `true` in your URL request.

**Comment by lolodomo** [comment]
And here is the JavaScript code in Basic UI:
https://github.com/openhab/openhab-webui/blob/32ca168e7fbf6a33be84fa03b25ef9df8a31f985/bundles/org.openhab.ui.basic/web-src/smarthome.js#L370
