### ISSUE TITLE
[MainUI] Properties display: no default icon rendered

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#491]
Example of item:
```
Switch preamp_power "Préampli allumé" (GPreampli) [ "Switch", "Power" ] { channel="rotel:rsp1066:preamp:mainZone#power" }
```
The rendering in BasicUI:
![image](https://user-images.githubusercontent.com/10186704/97845021-49be4d00-1cec-11eb-8e12-815547ac8640.png)
The rendering in MainUI:
![image](https://user-images.githubusercontent.com/10186704/97845112-6d819300-1cec-11eb-9d7d-81f2c5260fcf.png)
A default icon should be rendered for each item type.

**Comment by ghys** [comment]
Where are the default icons defined?

**Comment by lolodomo** [comment]
I think it was defined by the item type or sitemap element, I mean default icon "switch" for Switch and so on.
But I will check again Basic UI code to refresh my mind. I am expecting something more or less handled by the icon provider.
I tell you later in this day.

**Comment by lolodomo** [comment]
@ghys : in fact, this is handled by the core framework (method `getCategory`):
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L145

**Comment by florian-h05** [comment]
Closing as the default icons are now rendered by MainUI (Item list, properties, locations, equipment cards etc.) on openHAB 3.4.0.
