### ISSUE TITLE
[MainUI] Properties display: font size

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#492]
The font size is relatively small on a phone.
Is a setting possible to adjust the font size ? Something that will depend on device ?

**Comment by rgrollfitz** [comment]
You should be able to adjust the font-size with css in the most cases. For some components you might need to use the f7 css-variables for this as quoted in the framework7 component description [here](https://framework7.io/vue/)

**Comment by lolodomo** [comment]
That's being said, the font size is similar as in Basic UI,  the difference is that you can easily zoom in Basic UI while the zoom is apparently locked in the Main UI as soon as you open a page containing properties. 
Is it possible to unlock the zoom? 
I am talking about zoom on a phone with fingers.

**Comment by lolodomo** [comment]
In fact, the zoom is possible everywhere but is weird and not always easy doable when you are inside a card (tabs locations, equipment and properties). 

By the way, the best would be a setting to choose between few sizes of text.

**Comment by s0170071** [comment]
+1 from me. However if you use fully browser (popular for Android tablets) you can set a general font scaling factor. 125% works nicely for me.  Go to settings->Web zoom and scaling -> set font size

**Comment by lolodomo** [comment]
Just for information, I discovered that the rendering of openHAB UI inside the openHAB Android app is aaprently taking into account the system font size. To be clear, I get a bigger font in the Android app rather than in the WEB browser.
So I will now rather use the Android app on my phone to rneder openHAB UI.

**Comment by florian-h05** [comment]
Closing this issue as it has been „solved“ by using the Android app or changing scaling in the browser.
