### ISSUE TITLE
[MainUI] Back button closing the app

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#498]
On Android phone, the back button of the phone is closing the app. Very annoying.

**Comment by ghys** [comment]
Well, it works here from the beginning, or I would've addressed it a long time ago.

Also... you do realize this is a terrible bug report? No details, no Android/browser version, no phone model...
it's probably time for some issue templates!
Please go to Help & About > Technical information > View details and copy what you have under clientInfo.

**Comment by lolodomo** [comment]
I go in Locations tab and then click the back button of the phone. The browser goes to my WEB page before I open the Main UI. 

Phone is a Xiaomi Android 10. Browser is Chrome. 

clientInfo:
  device:
    ios: false
    android: true
    androidChrome: true
    desktop: false
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: android
    osVersion: "10"
    webView: false
    webview: false
    standalone: false
    pixelRatio: 2.75
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: fr-FR
    languages:
      - fr-FR
      - fr
      - en-US
      - en
    onLine: true
    platform: Linux armv8l
  screen:
    width: 393
    height: 851
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default

**Comment by lolodomo** [comment]
It is not on all pages, if I open the things page for example, the back button is working.
The problem occurs at least when you show the tabs Locations, Equipment and Properties.

**Comment by ghys** [comment]
Ah, ok, now we're getting somewhere.
That's because those cards are not handled by the router so when they're expanded, you're still technically on the home page. I implemented something for the cell widgets to address this which I still have to reproduce for these.

**Comment by lolodomo** [comment]
The back button is working well in all other parts of the app, at least all those I tested.
