### ISSUE TITLE
[MainUI] Point "OpenState" is ignored

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#499]
I tagged some of my door/window sensors with `[ "OpenState", "None" ] `.
This kind of point/property is ignored by the Main UI in locations, equipment or properties tabs.

And there is no card "None" in the properties tab.

PS: what would be the appropriate point/property to select for such a door/window state ?

**Comment by ghys** [comment]
There is no "None" property tag in the ontology.
The 4th tab is only to display points which have a related semantic property.
Your best bet is to tag your parent equipment as "Window", then you'll see all your windows in "Equipment".

**Comment by lolodomo** [comment]
None is proposed in the UI and you can create such an item.
![image](https://user-images.githubusercontent.com/10186704/97914318-f8e04000-1d4f-11eb-849a-50d1b6ccd1dc.png)
If "None" is not valid, why proposing it ?

I also tried earlier to set only [` "OpenState" ]` as tag. Is it allowed to have a point without property ?

If I set `[ "Status", "Presence" ]` on a motion detector, it is correctly handled, even without any equipment. The properties are attached to the location.

Is the UI ignoring points without a property ? In this case, what to do when you find no appropriate property in the ontology ... like for representing an opned or closed door/window ?

**Comment by lolodomo** [comment]
If you have no property, you need an equipment. Understood.

**Comment by ghys** [comment]
It doesn't have to be like this, in fact, but it's just that I saw little value in presenting the types of Points in a tab, having the Properties instead was more interesting. But your case is interesting too, there's no property normally associated with a open/closed state, so you have to go to the Equipment tab to see your windows and their state. The problem, I assume, is that you'll see every other Point related to the window, like the battery level of the sensor attached to them, while you're just interested in whether they're open or closed...

> If "None" is not valid, why proposing it ?

None is just the label for "no tag" so your item would be a Point with no related Property, those are not shown separately in the home page. :)

**Comment by lolodomo** [comment]
> But your case is interesting too, there's no property normally associated with a open/closed state, so you have to go to the Equipment tab to see your windows and their state. The problem, I assume, is that you'll see every other Point related to the window, like the battery level of the sensor attached to them, while you're just interested in whether they're open or closed...

Exactly !

As the open/close is a very standard property, I think we should define a property and add it to the ontology. Just have to find a clear name and it is not obvious ;)

> None is just the label for "no tag" so your item would be a Point with no related Property, those are not shown separately in the home page. :)

Ok, fine.

**Comment by lolodomo** [comment]
Maybe a generic property "Other" should be added. It would allow to attach any item as property for a location.

**Comment by lolodomo** [comment]
I opened openhab/openhab-core#1791.
I thing a new "Opening" property could be the solution.
