### ISSUE TITLE
[Main UI] [Bug] group members readonly after restart

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-webui#501]
I have created a oh-label-cell to display my air conditioners on the overview page.

`component: oh-label-cell
config:
  action: group
  actionGroupPopupItem: gClimate
  item: gClimate
  title: Klimaanlage
  stateAsHeader: true
  expandable: false
  color: '=(items.gClimate.state === "OFF") ? "white" : "blue"'
`

![image](https://user-images.githubusercontent.com/5521736/97961286-4a6de680-1db3-11eb-8bf1-5cf99094c2a9.png)

Selecting one of the air-conditioners, I get the details page, but all channels are readonly, not being able to change e.g. the mode (Betriebsart).

![image](https://user-images.githubusercontent.com/5521736/97961380-8012cf80-1db3-11eb-8ab9-a27c1ad0bb57.png)

Deleting the thing and readding will bring me back to a controllable state, but after the next upgrade, it will be the same again.

**Comment by ghys** [comment]
> Deleting the thing and readding will bring me back to a controllable state, but after the next upgrade, it will be the same again.

I don't understand this, do UI-related things change when you upgrade openHAB? That seems unlikely.

**Comment by hmerk** [comment]
Just tested, same behaviour after a simple restart of openHAB.
Screenshot after newly added equipment for my AC, as you can see, I can change the mode:
![image](https://user-images.githubusercontent.com/5521736/98215235-d7e23f80-1f47-11eb-9747-bde00f04ec3b.png)
After restart, mode is no longer changeable
![image](https://user-images.githubusercontent.com/5521736/98215584-432c1180-1f48-11eb-9cd1-28195a0c348e.png)

**Comment by ghys** [comment]
Strange. I suspect an issue with the binding.
Do you observe the same when you add the item to a sitemap (as default)?
When you pull `/rest/items/{itemName}` (either directly or with the API Explorer in the Developer Tools) do you have the options in the stateDescription?

**Comment by hmerk** [comment]
Nah, I wrote the binding ;-) 
Strange thing I see, the same binding lists the mode when I pull /rest/items/{itemName} in openHAB 2.5.10, but it does not in openHAB 3.0.
So indeed, it is not an UI issue, but something else. I will have to investigate further .....

**Comment by hmerk** [comment]
@ghys Indeed, ther was a little nasty bug in my binding, not setting the channel options when a channel already exists. Just provided a PR to fix this.
Thanks for pointing me in th right direction.
