### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by lafrank** [openhab/openhab-webui#503]
Hey Guys, could someone please point to any documentation on how to use this repository to update an earlier version of HABmin installed with OpenHAB ?  I can only see a download lin in OpenHAB pointing to an archived repository, that is referring to this one, but can't find any installer, bat file, or a "readme.for.dummies.txt" at least.

**Comment by lafrank** [comment]
Oh yes, on top of this, the GUI appeareance has nothing to do with the screenshots here : https://www.openhab.org/docs/configuration/ui/habmin/#features
Different version ? Different OS ?Don't have a clue...

**Comment by hmerk** [comment]
If you switch to the 2.5.x branch, you will see the habmin sources under bundles folder.

**Comment by lafrank** [comment]
Thanks @hmerk, appreciate your help here.
Could you please guide me a bit further, and let me know what shall I do with this bunch of directories ? Simply delete the old folders from current installation and overwrite with these ? Kind of a copy-paste install you mean ?

![Screenshot 2020-11-03 181435](https://user-images.githubusercontent.com/15701860/98156385-07f1fa00-1ed8-11eb-931a-bdc4ff96b10e.jpg)

**Comment by hmerk** [comment]
What do you want to achieve?
Installing openHAB 2.5.10 will install the latest version from this repo.
If you want to change sources, you need to setup an IDE and biuld the package with maven.
The resulting jar file can be copied to addons folder to be used.

**Comment by lafrank** [comment]
Unfortunatley not, installing the latest OpenHAB and selecting HABmin add-on the below is installed : 

![Screenshot 2020-11-04 211702](https://user-images.githubusercontent.com/15701860/98163561-46d97d00-1ee3-11eb-9181-74ee3b305ba9.jpg)

If I go to releases, I can find release 3.0.0.M2 or at least 2.5.10. And I can't find the proper way to upgrade to the latest release:

![Screenshot 2020-11-04 211937](https://user-images.githubusercontent.com/15701860/98163790-94ee8080-1ee3-11eb-88f1-a9712494f51f.jpg)

Thank you.

**Comment by rkoshak** [comment]
I think HABmin hasn't been touched since Version 2.0.0 some three or four years ago, or if there have been updates they are minimal. But I think that date timestamp after the version number tells you when it was built. So, in short, you are running the latest version. If I recall correctly, HABmin has been removed from OH 3.

**Comment by hmerk** [comment]
HABmin has it's own version number and like @rkoshak wrote has not been touched for a long time. And he is also right, HABmin will not be part of openHAb 3.0.

**Comment by lafrank** [comment]
Weird, what is then release 3.0.0.M2 published a few days ago ? Nevermind, I will drop this if it does not have a real support.
Thanks for your responses so far.

**Comment by ghys** [comment]
As said, openHAB 3.0 does not include HABmin and it has not been actively maintained in years.

**Comment by lafrank** [comment]
I just have realized what is the confusion here, at least from my side.
If one went to check [HABmin repo on github]( https://github.com/openhab/org.openhab.ui.habmin) here they would found an alert that the repository has been archived and moved to  OpenHAB WebUI :

![Screenshot 2020-11-05 103428](https://user-images.githubusercontent.com/15701860/98223530-868b7d80-1f52-11eb-9d53-60ab1812bc38.jpg)

So I was under the impression the product has been _**renamed**_, and the later repository is still for HABmin only under a different name. But now it looks like this repository is essentially OH3 and has nothing to do with HABmin anymore. Or not ?

**Comment by ghys** [comment]
You'll find HABmin and the other UIs that have been removed from OH3 if you switch the branch from master (the current default) to 2.5.x (the former default).
