### ISSUE TITLE
[MainUI] no item states over Myopenhab Cloud Connector

### ISSUE THREAD

**Issue by acidburn78** [openhab/openhab-webui#504]
Im using Openhab3 M2  and also tested with an actual Snapshot.
i created more than one Label Cards with an item.
When i work local all item states are displayed, but when i connect over myopenhab.org or a nginx reverse proxy no item states are displayed i only see an "-" 

The item states are displayed in a generated sitemap

I have installed Openhab 3 on Docker on a Synology

**Comment by ghys** [comment]
Please check the browser developer tools for errors and report them here.

**Comment by acidburn78** [comment]
Hi,
so i checked the Developer Tools from Chrome when im using myopenhab.org
![item state](https://user-images.githubusercontent.com/13540011/98207679-546f2100-1f3c-11eb-9525-40d2a9ef3671.JPG)
![equipment](https://user-images.githubusercontent.com/13540011/98207739-6bae0e80-1f3c-11eb-8c13-91f89fb7d33a.JPG)

as you can see no item States when i look under items in the ui
![items](https://user-images.githubusercontent.com/13540011/98207956-c0ea2000-1f3c-11eb-8d53-a6863ccc8cdf.JPG)

and here is the log:
> app.js:27 Initializing state tracking store proxy
app.js:27 Start tracking states
app.js:22 new SSE connection: https://home.myopenhab.org/rest/events/states, 1 open
app.js:22 [EventSource]0: EventSource {url: "https://home.myopenhab.org/rest/events/states", withCredentials: false, readyState: 0, onopen: ƒ, onmessage: ƒ, …}length: 1__proto__: Array(0)
app.js:27 Proxy: need HandyMarkus_Online
app.js:27 updateTrackingList: No connection id, not calling the API
app.js:27 Setting initial tracking list: ["HandyMarkus_Online"]
app.js:22 SSE error
app.js:22 EventSource {url: "https://home.myopenhab.org/rest/events/states", withCredentials: false, readyState: 0, onopen: ƒ, onmessage: ƒ, …}
app.js:27 Setting initial tracking list: ["HandyMarkus_Online"]
app.js:22 SSE error
app.js:22 EventSource {url: "https://home.myopenhab.org/rest/events/states", withCredentials: false, readyState: 0, onopen: ƒ, onmessage: ƒ, …}
app.js:22 card opened
app.js:27 Proxy: need RST2BadObenHKTBadOben_Betriebsmodus
app.js:27 Proxy: need RST2BadObenHKTBadOben_Luftfeuchtigkeit
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_Schimmelwarnung
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_Fensterabsenkungaktiv
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_NiedrigerBatteriestatus
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_Solltemperatur
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_AktuelleTemperatur
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Proxy: need RST2BadObenHKTBadOben_Frostwarnung
app.js:27 updateTrackingList: Pending tracking list update, not calling the API
app.js:27 Updating tracking list: ["HandyMarkus_Online","RST2BadObenHKTBadOben_Betriebsmodus","RST2BadObenHKTBadOben_Luftfeuchtigkeit","RST2BadObenHKTBadOben_Schimmelwarnung","RST2BadObenHKTBadOben_Fensterabsenkungaktiv","RST2BadObenHKTBadOben_NiedrigerBatteriestatus","RST2BadObenHKTBadOben_Solltemperatur","RST2BadObenHKTBadOben_AktuelleTemperatur","RST2BadObenHKTBadOben_Frostwarnung"]
app.js:22 Uncaught (in promise) Not Found
(anonymous) @ app.js:22
Promise.catch (async)
(anonymous) @ app.js:22
vf @ app.js:22
postPlain @ app.js:22
(anonymous) @ app.js:27
(anonymous) @ app.js:7
Qe @ app.js:7
Promise.then (async)
Ye @ app.js:7
at @ app.js:7
updateTrackingList @ app.js:27
(anonymous) @ app.js:9
u.dispatch @ app.js:15
dispatch @ app.js:9
get @ app.js:27
(anonymous) @ app.js:15
e._render @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn @ app.js:7
(anonymous) @ app.js:7
Sn.$mount @ app.js:7
Sn.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn @ app.js:7
(anonymous) @ app.js:7
Sn.$mount @ app.js:7
Sn.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
h @ app.js:7
d @ app.js:7
h @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn @ app.js:7
(anonymous) @ app.js:7
Sn.$mount @ app.js:7
Sn.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn @ app.js:7
(anonymous) @ app.js:7
Sn.$mount @ app.js:7
Sn.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn @ app.js:7
(anonymous) @ app.js:7
Sn.$mount @ app.js:7
Sn.$mount @ app.js:7
init @ app.js:7
(anonymous) @ app.js:7
d @ app.js:7
h @ app.js:7
d @ app.js:7
(anonymous) @ app.js:7
O @ app.js:7
(anonymous) @ app.js:7
e._update @ app.js:7
a @ app.js:7
hn.get @ app.js:7
hn.run @ app.js:7
pn @ app.js:7
(anonymous) @ app.js:7
Qe @ app.js:7
Promise.then (async)
Ye @ app.js:7
at @ app.js:7
(anonymous) @ app.js:7
hn.update @ app.js:7
pe.notify @ app.js:7
set @ app.js:7
mn.set @ app.js:7
(anonymous) @ app.js:22
setTimeout (async)
cardOpening @ app.js:22
qe @ app.js:7
n @ app.js:7
qe @ app.js:7
e.$emit @ app.js:7
(anonymous) @ app.js:7
t.a @ app.js:7
dispatchEvent @ app.js:15
onOpened @ app.js:15
(anonymous) @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
K @ app.js:22
(anonymous) @ app.js:22
r @ app.js:1
c @ app.js:1
Show 55 more frames
app.js:27 Setting initial tracking list: ["HandyMarkus_Online","RST2BadObenHKTBadOben_Betriebsmodus","RST2BadObenHKTBadOben_Luftfeuchtigkeit","RST2BadObenHKTBadOben_Schimmelwarnung","RST2BadObenHKTBadOben_Fensterabsenkungaktiv","RST2BadObenHKTBadOben_NiedrigerBatteriestatus","RST2BadObenHKTBadOben_Solltemperatur","RST2BadObenHKTBadOben_AktuelleTemperatur","RST2BadObenHKTBadOben_Frostwarnung"]
app.js:22 SSE error
app.js:22 EventSource {url: "https://home.myopenhab.org/rest/events/states", withCredentials: false, readyState: 0, onopen: ƒ, onmessage: ƒ, …}
`

**Comment by ghys** [comment]
Can you go to the Network tab in the developer tools and check why the requests fail?

**Comment by acidburn78** [comment]
Hello,
when i go to the Network tab i see the following

![Unbenannt](https://user-images.githubusercontent.com/13540011/98519690-6967ef00-2271-11eb-84e3-1a9ce02b57bb.JPG)

i see that the states are requestet but  i dont get an answer in time so i think it is an Timeout

when i call the api directly 
https://home.myopenhab.org/rest/events/
it takes a long long time before i get an answer
also on 
https://home.myopenhab.org/rest/events/states/1b6b4f24-89b8-4364-9ad9-c35bbf0ad23f
whe  call this in  browser i'll get an http error 405

**Comment by ghys** [comment]
There is definitely something wrong:
`app.js:22 SSE error`
but based on your screenshot the network traffic looks OK...
If you click on one of the pending "states" requests, there should be an "EventStream" tab with the state updates coming. I have confirmed that it works on home.myopenhab.org, so it could be something on your side. Copy what you have in Help & About > Technical Information > View details (mostly the `clientInfo` part).
Also try a incognito window, it will disable most browser add-ons, one of them could be interfering. Or maybe you have a HTTP proxy that doesn't like the SSE requests.

**Comment by florian-h05** [comment]
As this is working now, I consider this as fixed.
