### ISSUE TITLE
Consistent UX with Delete & bulk operations in lists

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-webui#506]
When adding rules via Main UI, rules can't be deleted, just disabled
![image](https://user-images.githubusercontent.com/1429498/98129121-0bc25400-1eb9-11eb-8d78-bdb9920eb8dd.png)

Version 3.0.0M2

**Comment by rkoshak** [comment]
It's not intuitive, but to delete a rule first click "Select" in the upper right hand corner and then check those rule(s) you want to delete and there will be a delete option at the bottom.

**Comment by cribskip** [comment]
Thanks @rkoshak, working well as you described.

From a UX perserspective: Things may be deleted from "the bottom of the page". Here it's a different way to do it. And as I just noticed, its the same for items.

So maybe change thing handling to be the same as items/rules or the other way round?

**Comment by ghys** [comment]
Agreed, in the end there should be some consistency in this.
The intent with this "Select" then select Delete in the toolbar is that they may be more "bulk" operations like these in those toolbars in the future beside Delete - disable or enable things, add tags or groups to items, etc.
