### ISSUE TITLE
Can't edit or delete a rule created with a "/" in Unique ID from web

### ISSUE THREAD

**Issue by Ungeridus** [openhab/openhab-webui#508]
I created a rule with a slash in the unique id and it made it to where I couldn't delete the rule or edit it.

![1](https://user-images.githubusercontent.com/31721178/98184180-59e25200-1ecf-11eb-832c-a2e0e43c2e6a.png)
![2](https://user-images.githubusercontent.com/31721178/98184186-5fd83300-1ecf-11eb-8bc3-cc990b11fec3.png)

I deleted it in the console but shouldn't there be a check against using a bad unique id?

**Comment by ghys** [comment]
I'm honestly thought it was the case! But apparently not.
