### ISSUE TITLE
groupId + artifactId: common layout

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-webui#51]
The "common" filesystem layout has been used by #38

The "common" groupId and artifactId layout is still missing.

**Comment by wborn** [comment]
Is this still an issue? It looks like this was fixed with https://github.com/openhab/openhab-webui/pull/52.

**Comment by maggu2810** [comment]
It has not been fixed.

See e.g.

https://github.com/openhab/openhab-webui/blob/master/features/pom.xml#L6-L12

**Comment by wborn** [comment]
I think we can add a karaf dir here like we have in openhab-core?
Does the bom dir also need an update?
Looks like the project names in the POMs also need to be updated. 
Do you see anything else that still needs to be updated?

**Comment by maggu2810** [comment]
> I think we can add a karaf dir here like we have in openhab-core?

AFAIK the intention has been to remove the karaf subdirectory as there will be only karaf features anymore (as p2 has been removed).

IIRC The directory layout is fine, just not all GAVs has been set "correctly".
