### ISSUE TITLE
OH3 side view only shows the menu symbol when the screen is narrow

### ISSUE THREAD

**Issue by chofstaetter** [openhab/openhab-webui#523]
It would be helpful we you could hide the menu bar on the left for pure operating computers or tablets when pages are displayed. With a narrow width thats possible, but not with 1920.

**Comment by hubsif** [comment]
Hi!

I started looking at OH3 and have the same requirement. I'd like to use Pages on my tablet as replacement for HABPanel.

I think I found a quite simple way to enable this, which is to let the user toggle the "visibleBreakpoint" of the side panel. When activated (=breakpoint disabled) it makes the UI behave the same as with narrow screens.

Here are my changes as a patch file and an animation showing the result.
Please note that I have only low experience with Javascript and before this none at all with Vue.js or Framework7. It needs to be reworked (esp. the CSS part) and maybe redesigned, I just wanted to share my idea here. That's also the reason why I didn't go into creating a pull request and such.

That said I wasn't able to get it working in the template only, I had to create a method. Also note that I had to remove the breakpoint call in home.vue, without knowing (and understanding) what it's actually for (I guess it might actually only be required at the end of the setup wizard).

```diff
diff --git a/bundles/org.openhab.ui/web/src/components/app.vue b/bundles/org.openhab.ui/web/src/components/app.vue
index 091f19b..947ab21 100644
--- a/bundles/org.openhab.ui/web/src/components/app.vue
+++ b/bundles/org.openhab.ui/web/src/components/app.vue
@@ -91,6 +91,10 @@
         </f7-list-item>
       </f7-list>

+      <f7-link class="breakpointPin" @click="toggleVisibleBreakpoint">
+        <f7-icon slot="media" :f7="this.visibleBreakpointDisabled ? 'pin_slash' : 'pin'" color="gray"></f7-icon>
+      </f7-link>
+
       <div slot="fixed" class="account" v-if="ready">
         <div class="display-flex justify-content-center">
           <div class="hint-signin" v-if="!$store.getters.user && !$store.getters.pages.filter((p) => p.uid !== 'overview').length">
@@ -203,6 +207,12 @@
       width 100%
       margin-bottom 0
       height calc(var(--f7-tabbar-labels-height) + var(--f7-safe-area-bottom))
+  .breakpointPin
+    position fixed
+    bottom calc(var(--f7-tabbar-labels-height) + var(--f7-safe-area-bottom))
+    right 0
+    margin 10px
+

 .theme-dark
   .panel-left
@@ -330,6 +340,7 @@ export default {
       sitemaps: null,
       pages: null,
       showSidebar: true,
+      visibleBreakpointDisabled: false,
       loginScreenOpened: false,
       loggedIn: false,

@@ -477,6 +488,10 @@ export default {
         ev.stopPropagation()
         ev.preventDefault()
       }
+    },
+    toggleVisibleBreakpoint () {
+      this.$f7.panel.get('left').toggleVisibleBreakpoint();
+      this.visibleBreakpointDisabled = this.$f7.panel.get('left').visibleBreakpointDisabled;
     }
   },
   created () {
diff --git a/bundles/org.openhab.ui/web/src/pages/home.vue b/bundles/org.openhab.ui/web/src/pages/home.vue
index ea3a7e4..39e151f 100644
--- a/bundles/org.openhab.ui/web/src/pages/home.vue
+++ b/bundles/org.openhab.ui/web/src/pages/home.vue
@@ -146,7 +146,6 @@ export default {
       this.$store.dispatch('stopTrackingStates')
     },
     onPageInit () {
-      this.$f7.panel.get('left').enableVisibleBreakpoint()
       if (window.OHApp) {
         if (window.OHApp.pinToHome) this.showPinToHome = true
         if (window.OHApp.exitToApp) this.showExitToApp = true
```

![fullscreen](https://user-images.githubusercontent.com/2242688/101613745-6ac13e80-3a0c-11eb-9834-5fdf70651e06.gif)

**Comment by ghys** [comment]
Very cool @hubsif huge thanks for having a look at this!
Your patch looks fine, I just tried it and you should definitely propose it as a PR.

Maybe the placement of the pin icon isn't ideal because it might get in front of menu entries eventually. Maybe put it as a (smaller) icon in the white area with the logo? I'm not sure.

But it seems to work well.

> Also note that I had to remove the breakpoint call in home.vue, without knowing (and understanding) what it's actually for (I guess it might actually only be required at the end of the setup wizard).

Yes you figured it out - it's important to restore the breakpoint to what it was once we get out of the setup wizard. There is a similar line in setup-wizard.vue in the onPageAfterOut but I don't remember exactly why it wasn't enough, maybe it didn't work so well so I added it there too. Probably some testing required.
