### ISSUE TITLE
[MainUI] Issue showing configuration parameters

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#525]
The TR-064 binding uses some advanced configuration parameters which are not shown in the UI. I am not sure if this is an UI issue or a malformed configuration description. The UI probably expects a list of options here ...

![grafik](https://user-images.githubusercontent.com/5131747/99395473-c05c6c80-28e0-11eb-9162-09379fcc2a4f.png)

```JSON
{
	"4": {
		"description": "List of answering machines (starting with 0).",
		"label": "TAM",
		"name": "tamIndices",
		"required": false,
		"type": "TEXT",
		"readOnly": false,
		"multiple": true,
		"advanced": true,
		"verify": false,
		"limitToOptions": true,
		"options": [],
		"filterCriteria": []
	}
}
```

![grafik](https://user-images.githubusercontent.com/5131747/99395541-dff39500-28e0-11eb-979f-801838d1e109.png)

**Comment by ghys** [comment]
An unfortunate dereferencing failure.
It's an UI issue, however you'll note that in the absence of options, even if `limitToOptions` is true, it will display a textarea where values can be set, one per line:

![image](https://user-images.githubusercontent.com/2004147/99397317-306bf200-28e3-11eb-9b9e-467aa6c16063.png)

![image](https://user-images.githubusercontent.com/2004147/99397466-6315ea80-28e3-11eb-989d-ab31db66dc6c.png)

**Comment by cweitkamp** [comment]
Quick, reliable, @ghys. Thank you very much for the analysis.
