### ISSUE TITLE
[MainUI] Icon displayed for humidity is not depending on the value

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#534]
## The problem

The icon displayed for a humidity value is not depending on the item value.
In the following example, you can see the icon displayed for "Humidité dans le bureau".

![image](https://user-images.githubusercontent.com/10186704/99570023-a6e71d80-29d1-11eb-995b-dc3cfa9e6925.png)

## Expected behavior

Display an icon depending on value, like in Basic UI:

![image](https://user-images.githubusercontent.com/10186704/99570152-d26a0800-29d1-11eb-887a-da19520e46e4.png)

## Steps to reproduce

Use an item of this kind with icon "humidity":
```
Number HumiditeBureau "Humidité dans le bureau [%.0f %%]" <humidity> (Bureau,GHumiditeInt) [ "Measurement", "Humidity" ] {channel="..."}
```

And open any card that shows this item.

**Comment by ghys** [comment]
I activated this behavior (`iconUseState: true`) for items of certain types:

https://github.com/openhab/openhab-webui/blob/cd66d064a76d3ccf59d5fb40cdf718d33eff2b59/bundles/org.openhab.ui/web/src/components/widgets/standard/list/default-list-item.js#L96

I'm not in favor of doing it for other types Numbers or Strings by default because some could be changing frequently and that would mean too many icon requests. (Looking back even Group was a bad idea - some hold averages in their state etc.).

You can enable it on an per-item basis by modifying its `listItem` (Default List Item Widget) metadata. In the future you'll also be able to specify only config options to "merge" to the default widget.
(looking back Group is probably not a good idea either).

**Comment by lolodomo** [comment]
> You can enable it on an per-item basis by modifying its listWidget (Default List Item Widget) metadata. In the future you'll also be able to specify only config options to "merge" to the default widget.

How complex is it !!! I just does not understand what to select and fill when I open the page you mention !!!
This was imagined for very clever users, not for someone like mme !
Will try again tomorrow...

**Comment by lolodomo** [comment]
The first is the one from my config file; the second is the one I created with the UI:
![image](https://user-images.githubusercontent.com/10186704/99580306-9ccc1b80-29df-11eb-8e45-f3ce44f81718.png)

![image](https://user-images.githubusercontent.com/10186704/99580429-c2f1bb80-29df-11eb-8ef6-ef359b09a7bf.png)

![image](https://user-images.githubusercontent.com/10186704/99580541-dbfa6c80-29df-11eb-992a-34caf8360a1c.png)

Now in Locations, the item appears without value and still wrong value:

![image](https://user-images.githubusercontent.com/10186704/99580666-04826680-29e0-11eb-99a8-47bc0a2cd53b.png)

I am clearly lost.

**Comment by lolodomo** [comment]
I f I remove the metadata, the value is back but of course without the icon:

![image](https://user-images.githubusercontent.com/10186704/99581097-925e5180-29e0-11eb-9ef7-7ca4570b6c4c.png)

**Comment by lolodomo** [comment]
I finally found that I have to select "Label list item" and not "list item" to get the value. But in this case, the icon is still not dependent on the value. See how it looks:
![image](https://user-images.githubusercontent.com/10186704/99598736-4e784600-29fa-11eb-8caf-0dfc09ce29a2.png)

Here is now how is defined my default list item widget:
![image](https://user-images.githubusercontent.com/10186704/99598862-87b0b600-29fa-11eb-83ea-0ad213e8c21d.png)

What is still missing ?

**Comment by lolodomo** [comment]
Ok, found, it is hidden in advanced configuration settings...
![image](https://user-images.githubusercontent.com/10186704/99599153-0efe2980-29fb-11eb-8334-588af53009e4.png)

For something that everybody will want by default, sorry to say that but it is terribly complex to achieve.

But at least I know how to do it now, it just took me few hours to find.
