### ISSUE TITLE
[MainUI] Cannot attach an icon to an item

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#535]
## The problem

When I create or edit an item, I cannot attach an icon to the icon.
Editing an item defined in a config file, it looks like the icon is displayed in "Category" field of the page.
But when th eitem is created wiith the UI, this field is greyed.

![image](https://user-images.githubusercontent.com/10186704/99577688-ffbbb380-29db-11eb-97b8-0281a0c4e80c.png)

## Expected behavior

I should be able to select an icon for my item, either an icon from the classic iconset or a custom icon.

## Steps to reproduce

Open the page to create a new item or edit an existing item.

**Comment by ghys** [comment]
it's a placeholder... 😏

**Comment by lolodomo** [comment]
Sorry, I don't understand. How can I set the icon for my item when I create it ?

**Comment by lolodomo** [comment]
Why not just providing a field with a picklist to select the icon ?
