### ISSUE TITLE
[MainUI] Knob or Gauge widgets overriding the Close button 

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#536]
## The problem

After selecting a knob or a gauge for a number item, I can't click on the Close button at the bottom of the window.

![image](https://user-images.githubusercontent.com/10186704/99581672-5f688d80-29e1-11eb-9fc2-1767da738ea4.png)

For the Know, there is no visual overriding but when you click on the Close button, it just selects the "40" value.

![image](https://user-images.githubusercontent.com/10186704/99581850-96d73a00-29e1-11eb-8369-d5835b83edf2.png)

For the Gauge, there is a clear visual overriding.

## Expected behavior

Keep the necessary space for the selected widget and allow to push the button "Close".

Addtionaly, I am asking myself if the gauge or knob should not be more at the right rather than at the center.

## Your environment

Firefox on Windows 10 or Google Chrome on Android smartphone.

## Additional information

This looks promising to be able to choose these kinds of widgets.

**Comment by lolodomo** [comment]
![image](https://user-images.githubusercontent.com/10186704/99583473-d9017b00-29e3-11eb-81c5-100de15ad206.png)

**Comment by ghys** [comment]
Obviously (or so I thought) you're not supposed to choose widget types
other than list items as the default list item widgets. Just noticed the
standard standalone widget library is presented though. I'll remove it.
Keeping the issue open to track.
