### ISSUE TITLE
[MainUI] Dynamic icon not working with Number:Dimensionless

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#547]
## The problem

When requesting a dynamic icon with an item of type Number:Dimensionless, the icon is not displayed.
Here is an example of item:
```
Number:Dimensionless OWMHumiditeExt "Humidité ext. OWM [%d %%]" <humidity> (GOpenWeatherMap,GHumiditeExt) [ "Measurement", "Humidity" ] { channel="openweathermap:weather-and-forecast:api:local:current#humidity", listWidget="" [iconUseState=true] }
```
And the rendering:
![image](https://user-images.githubusercontent.com/10186704/99875502-85b04800-2bf0-11eb-8913-82015ec2099e.png)

## Expected behavior

Get an icon displayed, depending on the value.

## Steps to reproduce

With the item example I proviuded, open the "Humidity" card.

## Additional information

I have only Number:Dimensionless with a dynamic icon but maybe any number with a dimension is concerned and not working.

The dynamic icon is working with a simple Number (without dimension).

**Comment by ghys** [comment]
Cannot reproduce this.

You removed this from the template, despite it telling it up front not to:
```
## Browser network traffic

<!--
Open the developer tools in your browser, go to the Network tab and paste
screenshots of the network traffic and the details of individual requests that failed.
-->
```
That would have helped.

**Comment by lolodomo** [comment]
Here is th errror:

![image](https://user-images.githubusercontent.com/10186704/100542412-f9360300-3249-11eb-9c44-922214c872ef.png)

Maybe an encoding problem with the % ?

![image](https://user-images.githubusercontent.com/10186704/100542454-3ac6ae00-324a-11eb-8216-445a06aa071b.png)

My item:
```
Number:Dimensionless UpsChargeBatterie "Batterie onduleur [%d %unit%]" <battery> (GOnduleur) [ "Measurement", "Level" ] { channel="remoteopenhab:server:oh2:UpsChargeBatterie", listWidget="" [iconUseState=true, action=""] }

```

**Comment by lolodomo** [comment]
In fact, the problem could rather be that the state unit is set in the icon URL ?

**Comment by lolodomo** [comment]
@ghys  : is it something you can fix? 
Do you have enough information now?
