### ISSUE TITLE
[MainUI] Creating Equipment from Thing with 2 channels of same type 

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-webui#549]
## The problem
I have a thing with 2 channels of same channel-type (`switch`) and id `switch_01` and `switch_02`. It's a single physical device which controls 2 switches.
When adding from MainUI the Thing as Equipment I select both channels, the proposed Name (ID) of the Points is composed using the channel-type label (Switch) and not the channel-id, leading to 2 suggested items with identical Name (ID). Therefore if added to model only one Point is created.
There are several other examples where Things have several channels of the same channel-type (e.g. temperature) but different ids.

## Expected behavior
In `Add Items from Thing` the items created from channel should use the channel id and not the channel-type label.

## Your environment
OH 3.0 SNAPSHOT from dev environment (openHAB UI :: Bundles :: Main UI (3.0.0.202011202304))

![2switch-ch](https://user-images.githubusercontent.com/12682715/99884412-6f28e180-2c2e-11eb-9cd5-8938c72623aa.png)

**Comment by marcelrv** [comment]
same challenge, esp with mqtt binding having many channels gives same issue indeed

**Comment by MHerbst** [comment]
@ghys I have tested it again with M4 and at least for the names used by the Homematic binding it is not solved :-(
![image](https://user-images.githubusercontent.com/616792/101537897-8d1b7380-399c-11eb-9605-6f62ffbb063d.png)

The channel number (marked in yellow) is missing in the derived name and that leads to duplicate item names.
