### ISSUE TITLE
[Design/Spec] Location semantic cards: header

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-webui#556]
This issue discusses the design and features of the header of a location card, when not customized by users using slots.
As a semantic card it inherits a number of common properties described in #555 (like background color/image).

## Title
By default, the title is the label of the item (or its name if it has none).

## Subtitle
If the location has a parent, the label or name of the parent is the default (but it should be possible to remove it, for instance if the cards are manually put in groups by the user (see #555).

## At-a-glance modules

The built-in at-a-glance modules (or "complications" as in watch screens) use the semantic model to gather information about the location and display it in a summarized manner with little icons and eventually a short label, "rewarding" the time taken to build a well-designed model by automatically providing information in the header of the card. The goal is not to be exhaustive, rather cover what should be the most popular scenarios. There will still of course be cases outside this anticipated well-known scenarios, and esoteric needs; therefore ideally users should be able to customize these modules, or add more (with slots). It should also be possible to hide automatically shown modules that doesn't work well or aren't desired.

A location card with all modules having something to display should resemble the following example ("worst case scenario"):

![image](https://user-images.githubusercontent.com/2004147/100102623-265a6e00-2e64-11eb-8e58-59b2d71e6506.png)

It is a little busy, but the average card should be much less so since a module isn't displayed when there is nothing to show.

### General principles for querying data from the model

- Normally the user will have put Equipment in the Locations. Most of these pieces of equipment will have Points. Gathering states from Points is always preferred as opposed to gathering states from Equipment item themselves, but we do it anyway if we couldn't find any matching Point. For instance, for blinds, look for OpenState points in equipment tagged Blinds (the preferred default), but if we can't find any, analyze the state of the Equipment items themselves - and consider a state of OPEN, or CLOSED appropriately.

- In order to leave out any ambiguity about which Points to consider, the admin has the option of relating Points directly to the Location without any Equipment in between. There are many ways to do it:
  * a Point can be made a member of both its parent Equipment, and also the Location it's in.
  * the item could be duplicated at the Location level and linked to the same channel so that it reflects the same data
  * a Group with an aggregation function (e.g. average) can be added as a Point to the Location to compute a state for the location from the state of the desired items.
<br />we should therefore prioritize the results by considering first only the Points which have a direct _hasLocation_ relation to the location; but if none match, we can consider those indirectly related through their equipment items.

#### ![image](https://user-images.githubusercontent.com/2004147/100102773-57d33980-2e64-11eb-963d-a109917144ba.png) Number of alarms (after the title)

__Point_Alarm__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Alarm__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

Count those with the state `ON`: if any result, display the count after the title as shown.

#### ![image](https://user-images.githubusercontent.com/2004147/100103443-332b9180-2e65-11eb-9031-43e4ff910145.png) Nb. Lights on

__Point_Control*__ _relatedTo_ __Property_Light__ _hasLocation_ __(the location)__ with the state
___If no matching item found:___
__Point_Control*__ _relatedTo_ __Property_Light__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

Count those with the state  `ON`, integer>0 or H,S,B with B > 0: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100104468-80f4c980-2e66-11eb-9a3e-4fccf906dade.png) Nb. of Open Windows

__Point_Status_OpenState__ _isPointOf_ __Equipment_Window__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Window__ _hasLocation_ __(the location)__

Count those with the state `OPEN`: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100105088-42134380-2e67-11eb-8c95-3c20a27e4438.png) Nb. of Open Doors

__Point_Status_OpenState__ _isPointOf_ __Equipment_Door__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Door__ _hasLocation_ __(the location)__

Count those with the state `OPEN`: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100105203-60793f00-2e67-11eb-881b-4b56a20f9589.png) Nb. of Open Garage Doors

__Point_Status_OpenState__ _isPointOf_ __Equipment_GarageDoor__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_GarageDoor__ _hasLocation_ __(the location)__

Count those with the state `OPEN`: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100105349-89013900-2e67-11eb-9c37-2b4bc3c2acf4.png) Nb. of Open Blinds

__Point_Status_OpenState__ _isPointOf_ __Equipment_Blinds__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Blinds__ _hasLocation_ __(the location)__

Count those with the state `OPEN` or integer>0: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100105840-18a6e780-2e68-11eb-99ab-59db6bd18ae8.png) Presence Detected

__Point_Status__ _relatedTo_ __Property_Presence__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Status__ _relatedTo_ __Property_Presence__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

If any result has the state `ON` or `OPEN`, display the icon.

#### ![image](https://user-images.githubusercontent.com/2004147/100106269-a682d280-2e68-11eb-893e-22ec7dcfaab0.png) Locks

__Point_Status__ or __Point_Control*__ _isPointOf_ __Equipment_Lock__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Lock__ _hasLocation_ __(the location)__

If all results have the state `CLOSED` or `OFF`: display ![image](https://user-images.githubusercontent.com/2004147/100107368-da122c80-2e69-11eb-8309-a5e35b0ac90f.png)

If any result has the state `ON` or `OPEN`: single result, display the icon ![image](https://user-images.githubusercontent.com/2004147/100106269-a682d280-2e68-11eb-893e-22ec7dcfaab0.png); multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100107597-18a7e700-2e6a-11eb-835a-9cae2c5e916a.png) Climate Control Powered On (A/C, Heating)

__Point_Status__ or __Point_Control*__ __relatedTo_ __Property_Power__ _isPointOf_ __Equipment_HVAC__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_HVAC__ _hasLocation_ __(the location)__

If any result has the state `ON`, display the icon.

#### ![image](https://user-images.githubusercontent.com/2004147/100108170-ca471800-2e6a-11eb-89f5-2b6ac2b83ff5.png) Nb. of Screens Powered On

__Point_Status__ or __Point_Control*__ __relatedTo_ __Property_Power__ _isPointOf_ __Equipment_Screen__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Screen__ _hasLocation_ __(the location)__

Count those with the state `ON`: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100108678-55c0a900-2e6b-11eb-9a46-073f96633e94.png) Nb. of Speakers/AV Receivers Powered On

__Point_Status__ or __Point_Control*__ __relatedTo_ __Property_Power__ _isPointOf_ __Equipment_Speaker__ or __Equipment_Receiver__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Speaker__ or __Equipment_Receiver__ _hasLocation_ __(the location)__

Count those with the state `ON`: single result, display the icon only; multiple results, display the icon and the count.

#### ![image](https://user-images.githubusercontent.com/2004147/100108973-a89a6080-2e6b-11eb-91ed-d34c7094bcf1.png) Nb. of Projectors Powered On

__Point_Status__ or __Point_Control*__ __relatedTo_ __Property_Power__ _isPointOf_ __Equipment_Projector__ _hasLocation_ __(the location)__
___If no matching item found:___
__Equipment_Projector__ _hasLocation_ __(the location)__

Count those with the state `ON`: single result, display the icon only; multiple results, display the icon and the count.

##### Measurement part:
__Point_Measurement__ _relatedTo_ __Property_Temperature__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Measurement__ _relatedTo_ __Property_Temperature__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

Compute the average of the valid values (if single result, take the result a fortiori), and display if valid.

##### Setpoint part:
__Point_Setpoint__ _relatedTo_ __Property_Temperature__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Setpoint__ _relatedTo_ __Property_Temperature__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

There should be only one result in theory; out of an abundance of caution, compute the average of the valid values (if single result, take the result a fortiori), and display if valid between parentheses after the measurement.

#### ![image](https://user-images.githubusercontent.com/2004147/100110410-30349f00-2e6d-11eb-8ac0-45b2211f3a31.png) Humidity (Measurement)

__Point_Measurement__ _relatedTo_ __Property_Humidity__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Measurement__ _relatedTo_ __Property_Humidity__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

Compute the average of the valid values (if single result, take the result a fortiori), and display if valid.

#### ![image](https://user-images.githubusercontent.com/2004147/100112490-928e9f00-2e6f-11eb-8d77-70a8835b3ab3.png) Luminance/Ambient Light (Measurement)

__Point_Measurement__ _relatedTo_ __Property_Light__ _hasLocation_ __(the location)__
___If no matching item found:___
__Point_Measurement__ _relatedTo_ __Property_Light__ _isPointOf_ __(any equipment)__ _hasLocation_ __(the location)__

Compute the average of the valid values (if single result, take the result a fortiori), and display if valid.

**Comment by kaikreuzer** [comment]
Sounds like an awesome reward for taking the time of building a semantic model!

**Comment by bodiroga** [comment]
This is freaking A-W-E-S-O-M-E, @ghys! Thank you very much for all your work!

**Comment by hmerk** [comment]
Excellent as usual !!!!!!
Love the idea

**Comment by ghys** [comment]
Implemented in #562.

**Comment by fxpde** [comment]
There's a small visual glitch with the display of Temperature (Measurement & Setpoint) using Safari.
<img width="131" alt="image" src="https://user-images.githubusercontent.com/14113610/102022488-75bafc80-3d87-11eb-8293-f3cd50e07a6f.png">
Due to the small-tag, the setpoint has a lower baseline than the temperature. When I remove the line-height of 20px for the glance-label class, they are aligned, but on lowered on the baseline of the icon. So also not perfect. Any idea how to fix this?

**Comment by fxpde** [comment]
Also an issue related to the Locks. For me, it's only showing the unlocked icon. When it's locked, there is no icon displayed. But from the description above, it's suggested that both states should be displayed.

**Comment by gunther1977** [comment]
This is super.  Very nice design.

Would it be possible to add the state PLAY next to ON state for speakers.  Since the control of wifi speakers most of the time use the play/pause status in the control.  
I did work with a workaround with an extra item

**Comment by guny74** [comment]
Hello, 

it is possible to enhance the "open Windows" badge to "open/close/tilted" ? Or is this possible right now ?

Thank you.

Regards

**Comment by matchews** [comment]
Would it be possible to query the displayState first, then if that doesn't exist, the state of the item?  My alarm binding reports Normal vs Violated for each zone.  I tried setting the state descriptions and the code appears to ignore them.

Thanks!

**Comment by dastrix80** [comment]
For Motion sensors by Aeotec that display OK, instead of ON/OPEN, how can we get the presence?

**Comment by Maceschine** [comment]
Hello Yannick, Hello together,

Excellent work.

However, I have a small question:
How do you display the unit ° **C** in the badge?

Many greetings
Marcel
