### ISSUE TITLE
openHAB 3.0.0 M2 sitemap designer syntax error on design view

### ISSUE THREAD

**Issue by flo-mic** [openhab/openhab-webui#564]
On openHAB 3.0.0 M2 there is an issue in the syntax validator on new sitemap pages.

If I create a new sitemap with an switch item that is named with "**Group_Item..._Switch**" I can controll the related switch without any issues. But if I switch to the Code section of the sitemap designer I recive an validation error because the item name starts with **Group**.

For this reason I can not modify the sitemap on the code page and have to use the design page for all customizations. If I customize this on the code page the changes where not saved.

**Example sitemap (This sitemap is working without any issues in the BasicUI, but I recive the validation error in the Code view):**
```
sitemap page_1db4f856b6 label="New Sitemap" {
    Switch icon="switch" item=Group_Lampen_Wohnzimmer_Schalter label="Switch"
}
```

**Error I receive in the Code view of the sitemap designer:**

> Error: Syntax error at line 2 col 31:
       Switch icon="switch" item=Group
                              ^
> Unexpected lwidget token: "Group". Instead, I was expecting to see one of the following:
> 
> A string token based on:
    WidgetAttrValue →  ● %string
    WidgetAttr → WidgetAttrName ● WidgetAttrValue
    WidgetAttrs → WidgetAttrs _ ● WidgetAttr
    Widget$ebnf$1 → Widget$ebnf$1 ● WidgetAttrs
    Widget → %nlwidget _ ● Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
> 
> ......

**Comment by toweosp** [comment]
Problem persists in final release of openHAB 3.0.0

**Comment by EnziinSystem** [comment]
The error still exists at the version 3.4.0 snapshot.

```
sitemap sitemap_controls label="asfasfsdfsd" {
    Switch
}
```

The message:

```
Error: Syntax error at line 2 col 5:

      Switch
      ^
Unexpected identifier token: "Switch". Instead, I was expecting to see one of the following:

A NL token based on:
    _ → _ ● %NL
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace ● _ Widgets _ %rbrace
    Main → _ ● Sitemap _
A WS token based on:
    _ → _ ● %WS
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace ● _ Widgets _ %rbrace
    Main → _ ● Sitemap _
A nlwidget token based on:
    Widget →  ● %nlwidget _ Widget$ebnf$1
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A lwidget token based on:
    Widget →  ● %lwidget _ Widget$ebnf$2
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
A lwidget token based on:
    Widget →  ● %lwidget _ Widget$ebnf$3 __ %lbrace __ Widgets __ %rbrace
    Widgets →  ● Widget
    Sitemap → %sitemap _ SitemapName __ SitemapLabel __ %lbrace _ ● Widgets _ %rbrace
    Main → _ ● Sitemap _
```

**Comment by mherwege** [comment]
I think this issue has been solved in the mean time.
