### ISSUE TITLE
[MainUI] No access to commands in Locations card (properties tab)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#568]
## The problem

While the item state is null, selection of any command is not possible when you open a Location card and the Properties tab.
It is important to mention that it is working normally if I open the Property card in the Properties view.
As soon as the item has a state, the commands are available through a popup when you click on th eproperty.

## Expected behavior

I expect an access to the commands even if the item state is currently undefined (null) in the Locations view.

## Steps to reproduce

Here is an item example:
```
String Mode "Mode" (Salon) [ "Control", "Power" ] { listWidget="" [action="options", actionItem="Mode", actionOptions="TV=TV,PS3=PS3,OFF=Eteint"], stateDescription="" [options="TV=TV,PS3=PS3,OFF=Eteint"] }
```

## Your environment

Issue is not depending on the environment. I can reproduce it in Windows 10 Firefox and in Android Chrome.

## Browser console

No error in console.

**Comment by lolodomo** [comment]
In fact, I just discovered and understood that the problem is very similar to #569 .
In fact, it does not work (commands not displayed in a popup) when the location card first displays the equipment tab and you switch to the properties tab.
When the location card displays first thje properties tab, then the popup opens to display the available commands.
In fact it has no link with the current state being NULL or not.

**Comment by ghys** [comment]
Cannot reproduce, same as #569.
