### ISSUE TITLE
[MainUI] Access to chart sometimes failing from a Location card (properties tab)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#569]
## The problem

After opening a Location card and the properties tab, when you click on an item to show the corresponding chart, it can occur that nothing happens.
It is important to mention that it is working well on a Equipment card or a Property card, and even on a Location card in the equipment tab.

## Expected behavior

I expect an access to the chart even in a Location card properties tab, not something working randomly.

## Steps to reproduce

Here are two of my items:
```
Group Bureau "Bureau" <office> (Etage) [ "Office" ]
Group GSondeBureau "Sonde bureau" <temperature> (Bureau) [ "Sensor" ]

Number TemperatureBureau "Température dans le bureau [%.1f °C]" <temperature> (Bureau,GSondeBureau,GTemperatureInt) [ "Measurement", "Temperature" ] {channel="rfxcom:temperaturehumidity:rfx:Bureau:temperature"}
Number HumiditeBureau "Humidité dans le bureau [%.0f %%]" <humidity> (Bureau,GSondeBureau,GHumiditeInt) [ "Measurement", "Humidity" ] {channel="rfxcom:temperaturehumidity:rfx:Bureau:humidity", listWidget="" [iconUseState=true] }
```

1. Open the Bureau card (you are in equipment tab)
2. Switch to properties tab
3. Click on "temperature dans le bureau" => nothing happens, chart page is not displayed.
4. Close the card
5. Reopen the card => this time the properties tab is displayed
6. Click on "temperature dans le bureau" => this time the chart is displayed as expected
7. Switch to equipment tab
8. Switch again to properties tab
9. Click on "temperature dans le bureau" => nothing happens, chart page is not displayed.

## Your environment

Not depending on environment. Can be reproduced on Firefox Windows 10 and Chrome Android.

## Browser console

No error in console (Firefox).

**Comment by ghys** [comment]
![2020-11-30_00-01-13](https://user-images.githubusercontent.com/2004147/100555967-48f2e980-329f-11eb-8bdb-cd6d14c7cb8a.gif)

¯\\\_(ツ)\_/¯
I find it surprising that you don't get any errors.

**Comment by lolodomo** [comment]
Here is what I can see.
When it opensthe chart, here is the code:

![image](https://user-images.githubusercontent.com/10186704/100557018-85761380-32a6-11eb-961e-a5b2886b8acf.png)

When it does nothing, here is the code:

![image](https://user-images.githubusercontent.com/10186704/100556913-e51fef00-32a5-11eb-88d5-d0a7c1841c94.png)

As you can see the order is not the same, item is sometimes before sometimes after action.

Is it something talking to you ?

**Comment by ghys** [comment]
It shouldn't matter.

**Comment by lolodomo** [comment]
Apparently it does. 
Why is it not always in the same order? 

I can't imagine I will be alone with this issue, especially when I can trigger it on different environments.

**Comment by ghys** [comment]
Correlation is not causation, I have the same and it works:

![image](https://user-images.githubusercontent.com/2004147/100585239-8aaa8100-32ed-11eb-8bd9-2a3cc19e4da8.png)

The attributes order is arbitrary and is of no significance. It's not surprising that your client environment has no influence if there's something wrong with your instance's particular configuration. Try to reproduce it on a new instance.

**Comment by lolodomo** [comment]
Someone else will probably come with more information than I can provide. 

All my items are defined in config files. 

I am starting from scratch at each new snapshot install.
