### ISSUE TITLE
[basic] UI fails to load resources

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#57]
As you can see below Basic UI now fails to load its resources (404 Not Found) causing strange looks on the Demo:

![basicui](https://user-images.githubusercontent.com/12213581/56100779-389cc800-5f1d-11e9-8995-75bbd9a51403.png)

Maybe it's caused by one of your recent PRs @maggu2810 ?
It also hasn't gone unnoticed in the [community forums](https://community.openhab.org/t/whats-wrong-with-my-basic-ui/72441?u=wborn).

**Comment by maggu2810** [comment]
The only one that come in my mind is 249e33b2f88356650db66d85a5aba243fe6176f8
But my intention was only to change the directory layout.
Can this be related?

**Comment by maggu2810** [comment]
The file `./bundles/org.openhab.ui.basic/.gitignore` states, that all files and directories below this one that name is equal to `web` should be ignored. So also the directory `web` inside `src/main/resources` should be ignored.
That's the reason this directory gets lost.
I don't know if this is done this way by intention as the three following ignore makes no sense. They ignore files inside `src/main/resrouces/web` that directory itself is ignored.

**Comment by wborn** [comment]
Thinks for fixing the issue @maggu2810 . The ignore was probably added to prevent modified files after having build the project, see https://github.com/openhab/openhab-webui/pull/15#issuecomment-466648852.

**Comment by kandersen01** [comment]
I´m having this issue as well.. I dont recall changing anything, not even the openhab build. I´m using openhab 2.5M1 build #1575, and have been using it for a few weeks now. I just noticed this issue today. I dont recall seeing this before.
BasicUI does seem to work fine though.
