### ISSUE TITLE
[MainUI] Location card headers should consider property Opening

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#571]
First I would like to say that it was a very good idea to add these "headers" on the  location card.

## The problem

Headers "Open Windows", "Open Doors", "Open Garage Doors" and "Open Blinds" are based only on **Point_Status_OpenState**.
We recently introduced the property **Property_Opening** and it should be considered too (in conjonctiuon with **Point_Status**).

**Comment by ghys** [comment]
You can have `Point_Status_OpenState` and `Property_Opening` at the same time.

**Comment by lolodomo** [comment]
You:re right, that is the solution I think,
