### ISSUE TITLE
[MainUI] Location card headers should consider property Illuminance

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#572]
## The problem

We recently iontroduced the property **Illuminance*.
The header "Luminance/Ambient Light" should consider this property (in conjonction with Point_Measurement ) in addition or in replacement to the property Light.

**Comment by ghys** [comment]
Or "Illuminance" should never have been added in the first place... It seems redundant with "Light" and if there's any difference at all, it is tenuous at best. I'd vote to remove it again.

**Comment by lolodomo** [comment]
We can discuss that in the relevant issue. This is not one of my proposal.

**Comment by ghys** [comment]
Agreed. I'll add a remark in https://github.com/openhab/openhab-core/issues/1791.

**Comment by lolodomo** [comment]
I close this issue as Illuminance property will be removed.
