### ISSUE TITLE
[MainUI] Create new item in the "Link Channel to Item" screen should take default channel tags from channel/ChannelType

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-webui#576]
## The problem

When a channel (channelType) is defined with the valid semantic tags, the item that is created for it I expect would take those default tags. Note, I tried both with adding the tags to the ChannelType as well as to the channel itself.
Note, the expected behaviour is shown for other elements like the category, type and label

The tags are visible in the REST interface.
![image](https://user-images.githubusercontent.com/5871213/100551572-cc9ddd80-3281-11eb-86e7-8f4abd8db3bc.png)

but not visible during item creation.
![image](https://user-images.githubusercontent.com/5871213/100551594-0242c680-3282-11eb-897f-abc428cbcaaf.png)

When an item is created without tags also the channel / channelType default tags are not taken. 

![image](https://user-images.githubusercontent.com/5871213/100552261-52bc2300-3286-11eb-9c14-9ce55340e7df.png)

**Comment by ghys** [comment]
Nice to finally see some semantic tags defined in channel types!

**Comment by marcelrv** [comment]
@ghys do you think there is a way to remove the strong dependency on the sequence of the tags.
It seems the sequence is not maintained through the framework
