### ISSUE TITLE
Can't set height on webview when editing a sitemap in the main UI

### ISSUE THREAD

**Issue by Ungeridus** [openhab/openhab-webui#579]
## The problem

Can't set height on webview when editing a sitemap in the main UI

## Expected behavior

I can set the height on a separate sitemap I edit textually and it displays fine.

## Additional information

This works but isn't tall enough to display web page
```
Text item=DateTime label="Cameras [%1$tl:%1$tM %1$tp]" icon="camera" {
	Webview url="http://10.10.0.3:8080/static/cams.html" icon="camera"
}
```
When I set the height

```
Text item=DateTime label="Cameras [%1$tl:%1$tM %1$tp]" icon="camera" {
	Webview url="http://10.10.0.3:8080/static/cams.html" height=24 icon="camera"
}
```
the sitemap no longer loads and throws an error on openhab.log that starts with
```
2020-11-30 01:57:17.893 [ERROR] [omponents.UIComponentSitemapProvider] - Cannot build sitemap default
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
```

**Comment by ghys** [comment]
Probably the `normalizeType` doesn't work in this case.

https://github.com/openhab/openhab-core/blob/13c2d7bf2be051fe8c72046d637770a92f517781/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java#L286
