### ISSUE TITLE
openHAB3 Delete button for sitemaps missing

### ISSUE THREAD

**Issue by soenkekueper** [openhab/openhab-webui#584]
Hey,

when creating an sitemap with openHAB3 there is no possiblity to delete this within the UI.
When editing an Item threre is always an "Remove item" button below - but i think its missing here.

When performing an HTTP REST DELETE Request on the URL of the sitemap delete works, so i assume only the button is missing.

Sönke

**Comment by bigbasec** [comment]
There isn't a way to delete any of the items under the Pages section from what I can see.   Once you create it you're basically stuck unless you want to modify the jsondb.   Less than ideal for sure, but I'd assume that feature will have to come.

**Comment by bigbasec** [comment]
I have this fixed in sitemaps, I'll look into the rest of them and submit a PR tomorrow for it.

**Comment by bigbasec** [comment]
PR should fix this : https://github.com/openhab/openhab-webui/pull/834

**Comment by bigbasec** [comment]
Aaaaaaand nevermind.   I've closed the PR as I found out that you can simply hold down the control key while clicking an item in the "Pages" view and you can delete all of them if you want.   

@ghys This item should be closed, it's a non-issue.

**Comment by florian-h05** [comment]
When you are in the UI pages list view, you can use the select feature to tick and remove pages, including sitemaps.
