### ISSUE TITLE
[Main UI] Opening UI creates warnings in openhab log

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-webui#592]
Every time I open the UI in chrome (on Android) or using the android app, the OH log writes at least 2 of the following warnings:

`apache.cxf.jaxrs.utils.ResourceUtils] - No resource methods have been found for resource class javax.ws.rs.core.Response 2020-12-05 08:37:05.171 [WARN ] [apache.cxf.jaxrs.utils.ResourceUtils] - No resource methods have been found for resource class javax.ws.rs.core.Response 2020-12-05 08:37:05.180 [WARN ] [apache.cxf.jaxrs.utils.ResourceUtils] - No resource methods have been found for resource class javax.ws.rs.core.Response`

**Comment by helmar74** [comment]
I also have this issue in OH3 Release. How can it be fixed?

**Comment by MikeJMajor** [comment]
@ghys did you close this because you couldn't reproduce it or because it was opened in the wrong repository?

@helmar74 in the end I filtered that warning out by adding the following to log4j2.xml:

```
<Logger level="ERROR" name="org.apache.cxf.jaxrs.utils.ResourceUtils"/>
```

**Comment by ghys** [comment]
Please open it again in the openhab-core repo since it's a backend problem, and provide actionable repro steps if you want it to be picked up.
