### ISSUE TITLE
[mainUI]

### ISSUE THREAD

**Issue by yfre** [openhab/openhab-webui#597]
meta data namespaces are currently fixed, e.g. accessory types for homekit are currently "hard-coded" in main ui
openhab-webui/bundles/org.openhab.ui/web/src/assets/definitions/metadata/homekit.js 

as result, an introduction of new homekit accessory type would required an update on main UI project as well (or user would need to enter new type manually).

maybe we could introduce namespace registry in openhab-core and a binding could register its namespace with the list of supported meta data tags and parameters.

**Comment by lolodomo** [comment]
Is it possible to set a title?

**Comment by ghys** [comment]
Similar to #397.
It already exists in core, look for MetadataConfigDescriptionProvider.

**Comment by yfre** [comment]
> Is it possible to set a title?

sorry, missed it somehow :(

**Comment by yfre** [comment]
> Similar to #397.
> It already exists in core, look for MetadataConfigDescriptionProvider.

thank you. i will add support for it to homekit binding
