### ISSUE TITLE
Travis MIA

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#60]
Travis is no longer triggered for this repo. Maybe the webhook needs to be readded like we did to resolve the same issue for openhab-core https://github.com/openhab/openhab-core/pull/700#issuecomment-481258286?

**Comment by kaikreuzer** [comment]
I think the issue here was that openhab-bot had no admin rights on that repo - I've added them now, let's see if that makes a change.

**Comment by wborn** [comment]
Thanks for looking into it. I just force pushed to https://github.com/openhab/openhab-webui/pull/50 but Travis is still MIA. :cry:

**Comment by kaikreuzer** [comment]
Will have another look the next days...
There are indeed no webhooks about Travis installed. When does the Github app create them and if it didn't do so, how can it be retriggered?

**Comment by wborn** [comment]
I fixed openhab-core by clicking the "Add webhook" button in the top right of the Webhooks settings. Then I  entered/selected all the webhook configuration details based on those of another openHAB project. After that Travis was no longer MIA.

**Comment by kaikreuzer** [comment]
Ok, I did it the same way now, although I would have expected the Travis Github app to be in full control of the webhooks. What looks weird is that the webhook that you added to openhab-core is notifying travis.org, while the new Travis Github app is using travis.com...

**Comment by wborn** [comment]
I think the webhook still needs to be used until the existing repos are migrated from travis-ci.org to travis-ci.com . The migration is only possible after entering the beta.

See:
* [Existing Open Source Repositories on travis-ci.org](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg)
* [Beta - Migrating repositories to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)
