### ISSUE TITLE
The unit is not always displayed in the UI for every Item

### ISSUE THREAD

**Issue by Sprocket02** [openhab/openhab-webui#600]
From my point of view I have configured the items correctly (see screenshot) but sometimes the automatically generated UI does not show them. For some items, however, the units are displayed correctly. But they are configured the same way, I have checked several times. 

![image](https://user-images.githubusercontent.com/37394766/101374657-ba89f380-38ae-11eb-9f0f-fec55deed75a.png)

![image](https://user-images.githubusercontent.com/37394766/101374256-3afc2480-38ae-11eb-86cb-5d86807a3eda.png)

**Comment by hmerk** [comment]
please check your item type. Is it Number:Temperature or just Number. If last, this is absolutely correct behaviour.

**Comment by Sprocket02** [comment]
It's Number:Temperatur

**Comment by hmerk** [comment]
As far as I can see in the KNX binding docu, there are no Number:Temperature **channels**, just number. In that case, defining the Item as Number:Temperature will not show a unit.
So i come to the conclusion, that what you are decribing is not a bug but expected behaviour.

**Comment by Sprocket02** [comment]
But then why is a unit shown in the item list?
![image](https://user-images.githubusercontent.com/37394766/101452042-6a9e4180-392d-11eb-928e-edd577f3c32e.png)

**Comment by ghys** [comment]
Go to Developer Tools > API Explorer > open items > GET items/{itemname} > Try it out on the right > put "Aussentemperatur_Sued" in the itemname box > Execute
Then paste the response body here.

**Comment by Sprocket02** [comment]
Here is the result. I can already see that a State Description (Pattern: "0.1f °C") exists. I created it once, but deleted it afterwards, because I thought that if I set the type correctly, I don't need it anymore (see screenshot above).

`{
  "link": "http://10.0.0.131:8080/rest/items/Aussentemperatur_Sued",
  "state": "3.0 °C",
  "stateDescription": {
    "pattern": "%.0f",
    "readOnly": false,
    "options": []
  },
  "editable": true,
  "type": "Number:Temperature",
  "name": "Aussentemperatur_Sued",
  "label": "Außentemperatur Süd",
  "category": "temperature",
  "tags": [
    "Measurement",
    "Temperature"
  ],
  "groupNames": [
    "gAussenbereich"
  ]
}`

**Comment by ghys** [comment]
That's what I thought - you have a state description pattern, probably set by the binding, that basically removes the unit.
You can add it back with state description metadata, but this should be fixed in the KNX binding.

**Comment by Sprocket02** [comment]
OK, [there](https://community.openhab.org/t/oh3-semantic-units/109691) is a similar discussion in the forum, where only the KNX binding causes problems.

**Comment by Sprocket02** [comment]
What happens now? Does an issue have to be created in the KNX binding?
