### ISSUE TITLE
[BASICUI] No Default control for Number missing

### ISSUE THREAD

**Issue by laundy** [openhab/openhab-webui#62]
When adding a `Number` item (e.g. with the HTTP binding)
`Number NumberSample "A Number" {http="<[http://domain.com:1000"}`

and adding a `Sitemap` entry for this item:
`sitemap NumberSitemap label="No UI control shown" {
  Frame label="Controls" {
     Default item=NumberSample
  }
}`

The corresponding UI control is missing in Basic UI.
![image](https://user-images.githubusercontent.com/15380131/56745563-e78d9f00-677a-11e9-8279-0d7ee4698586.png)

Is this a bug or a "feature"?

**Comment by lolodomo** [comment]
If you want to get a value displayed, update the item definition like that for example:
`Number NumberSample "A Number [%f]" {http="<[http://domain.com:1000"}`

This issue can be closed, there is no issue.

**Comment by laundy** [comment]
@lolodomo Thanks for you reply, but this is not tackling the actual issue. The issue is that no default control is implemented for the Number item type.

**Comment by lolodomo** [comment]
What controls are you expecting? 
A Number is rendered by UIs like a text.

**Comment by laundy** [comment]
For every other element a default control exists that allows me to control the value. If I have a number, e.g. a target value for a sensor, I'm not able to control it in the UI by using the Number item type. In my opinion, this is inconsistent.

**Comment by lolodomo** [comment]
It exists several kinds of sitemap element that can be linked to a Number item, like Slider, Setpoint, Text... They are appropriate to each need.
By default, the text widget is considered as we cannot guess what is the expected control for any number.

**Comment by laundy** [comment]
Thank you for clarification.
This is not a behavior I would expect as a user (rather a number input field or something similar), but as you see no need to change the default behavior I think we can close this issue. Thanks again!

**Comment by lolodomo** [comment]
By the way, no widget representing an input field exists.
