### ISSUE TITLE
[MainUI] French translation of semantic classes in UI

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#623]
For the card title, I would suggest these changes for the properties (only few of them use the plurial)
* Volumes => **Volume sonore**
* Températures => **Température**

For the equipment, I would suggest these changes:
* Amplificateurs => **Amplificateurs audio** (it wil then be homogeneous with "Enceintes audio")
* Web services => **Services WEB**

**Comment by lolodomo** [comment]
Sorry, I tag that as a bug but it is more an enhancement.

**Comment by ghys** [comment]
Please go to translate.openhab.org for i18n discussions.
