### ISSUE TITLE
[MainUI] Chart Window doesn't close after timeFrame has been altered

### ISSUE THREAD

**Issue by jeffstagedoor** [openhab/openhab-webui#628]
## The problem
When I click on "Analyse" of an item I get to the chart view of the stored values. If I then adjust the timeframe on the top right and *then* click back I can't get the popup closed again. I'm trapped in an endless circle.
However: If I click on "Controls" at the bottom I can get back with clicking on "back" again as I should (although I then land on the "all items" view, not on the one I was editing before).

## Expected behavior

Clicking "back" should close the chart-view (at least after the history of my timeframe changes have elapsed)

## Your environment
OH3 M5
Browser: Vivaldi

## Browser console
no errors/msgs there

**Comment by ghys** [comment]
Cannot reproduce this, sorry.
Please provide reproductible steps and do a video if you can.

![2020-12-13_20-56-32](https://user-images.githubusercontent.com/2004147/102022239-c6c9f100-3d85-11eb-90a3-199414b3a6d2.gif)

**Comment by jeffstagedoor** [comment]
a classic:
- I reproduced several times to find out when exactly it happens (and couldn't find a reproduceable pattern, though it was most of the time).
- Downloaded a screen-recorder.
- Cannot reproduce anymore.
Sorry, I should have had investigated more carefully before filing an issue and wasting your precious time.
