### ISSUE TITLE
[MainUI] Custom MetaData Namespace doesn't show up an can't be edited

### ISSUE THREAD

**Issue by jeffstagedoor** [openhab/openhab-webui#629]
## The problem
When adding a Cusom Namespace Metadata to an Item, it won't show up afterwards (although non-constum namespaces will show up) when viewing an item. Therefore it's not obvious of how to edit, let alone remove, this metadata.
I can see, that the request only asks for the predefined namespaces:
```
Request URL: http://openhab2:8080/rest/items/myItem?metadata=semantics,stateDescription,commandDescription,synonyms,widget,listWidget,cellWidget,widgetOrder,autoupdate,expire,alexa,homekit,ga
```

When I want to edit the previously entered custom metadata I have to click on "Add Metadata" and type the same namespace as before - doable, but not intuitive. Then I get what I previously added as editable yaml.
```
Request URL: http://openhab2:8080/rest/items/myItem?metadata=customNamespace
```

Could be, that the API doesn't provide a call to get *all* metadata. If so, I'm happy to move this somewhere else or remain quiet!

## Expected behavior
Custom Namespaces should show up just as the pre-defined ones do.

**Comment by ghys** [comment]
Agreed but will be solved along with #397 so I'm going to close this, you can monitor progress in #397, thanks!
