### ISSUE TITLE
Rule Editor: Trigger on thing status change - make the thing optional to be triggered by any thing changing

### ISSUE THREAD

**Issue by martingruening** [openhab/openhab-webui#645]
## The problem

In the Rule Editor there is a trigger available called 'a thing status changes'. My objective is handle _any_ thing that goes from ONLINE to OFFLINE like discussed in [](https://community.openhab.org/t/monitoring-thing-status/78131/5) with a single rule.

## Your suggestion

![thingrule](https://user-images.githubusercontent.com/36659742/102219096-43bcae00-3edf-11eb-84bd-7497fee89ba1.PNG)

Make the 'Thing' selection in the UI optional to trigger on all thing changes occuring.

## Your environment

OpenHAB 3.0.0M5

**Comment by ghys** [comment]
The UI doesn't decide how the rule modules can be configured - this has to be changed in core, if the maintainers agree. Moving.
