### ISSUE TITLE
Add favicon as touch icon for iOS

### ISSUE THREAD

**Issue by fxpde** [openhab/openhab-webui#666]
## The problem

When adding the main UI to the home screen on iOS, the icon is set as a screenshot of the current screen. This does not look very nice.

## Your suggestion

The favicon should also be listed as apple-touch-icon so that it can be used as icon on the homescreen.
`<link rel="apple-touch-icon" href="apple-touch-icon.png">`

**Comment by hmerk** [comment]
Can‘t confirm with RC1 and earlier versions. I have correct openHAB icons on several iOS devices..

**Comment by fxpde** [comment]
Hm okay. I started with one of the first milestone releases and right now I am on the latest snapshot. I have purged the cache and reloaded the app, but that did not help. But maybe there is still something left in the browser cache. In Safari, it shows the favicon in the tab overview, but it does not use it when adding it to the home screen.

**Comment by fxpde** [comment]
The corresponding code line is already in the code. So it seems to be an issue with my device.
