### ISSUE TITLE
Add a clock standard widget

### ISSUE THREAD

**Issue by hubsif** [openhab/openhab-webui#669]
## The problem

Some people would like to have a clock as widget (see [Community Forum](https://community.openhab.org/t/oh3-ui-show-clock/110369) and [a general Javascript issue](https://github.com/openhab/openhab-webui/issues/626)). As long as custom widgets don't support Javascript code, this needs to come as standard widget.

## Your suggestion

A simple digital clock card widget, including date display.

## Additional information

I added a clock widget to the standard library which I'm going to open a pull request for.

**Comment by hubsif** [comment]
Screenshots:
![clock_light](https://user-images.githubusercontent.com/2242688/102711516-8f45d200-42ba-11eb-89fe-0ea890dc8f60.png)
![clock_dark](https://user-images.githubusercontent.com/2242688/102711518-9371ef80-42ba-11eb-9874-b44187f1bb96.png)
<img width="637" alt="clock_settings" src="https://user-images.githubusercontent.com/2242688/102711520-98cf3a00-42ba-11eb-9526-3c3bf20d2d42.png">

**Comment by rkoperdak** [comment]
Hi, how can I use this widget? I have OH 3. Thank you Robert
