### ISSUE TITLE
Make the searchbar selected by default in new opened windows/views

### ISSUE THREAD

**Issue by XeS0r** [openhab/openhab-webui#677]
## The problem
You open a new view and there is a searchbar which you have to select first. At least for me I have to use search a lot because I have plenty of things available in the views.

## Your suggestion
Searchbar could be selected as default. This would make it easier to select and find something in most cases because you don't have to navigate to search first.

## Your environment

```yaml
Konfigurationsverzeichnis
/etc/openhab
Verzeichnis für Anwenderdaten
/var/lib/openhab
Verzeichnis für Protokolldateien
/var/log/openhab
Betriebssystem
Linux/5.4.0-1025-raspi (arm)
Java Runtime
Ubuntu
11.0.9.1 (undefined)
```

## Additional information
OH3 RC2

**Comment by mhilbush** [comment]
This is a definite must for items. I have about 2000 items, so the first thing I do when bringing up the list of items is go to the search box.

**Comment by eikowagenknecht** [comment]
I agree. I often start typing just to see that the search field is not active because I forgot clicking into it first :-)

**Comment by ghys** [comment]
Okay, but on mobile it brings up the virtual keyboard, which can be annoying. Maybe only do it on desktops then, or with the desktop "Aurora" theme.

**Comment by XeS0r** [comment]
I would agree to only enable this feature on desktops and not on mobile. At least in my humble opinion it could be really annyoing on mobile. Maybe it's possible to only focus search when a phsysical keyboard is available. If it's possible to check that in the frontend.
