### ISSUE TITLE
link to docs in "about" page needs to point to next.openhab.org

### ISSUE THREAD

**Issue by LightIsLife** [openhab/openhab-webui#687]
I would expect the link to the docs in "IP-of-OH3:8080/#!/about/" to point to next.openhab.org 
Instead it points to https://www.openhab.org/docs/ which are the docs for 2.X; this may confuse especially newbies

**Comment by kaikreuzer** [comment]
> https://www.openhab.org/docs/ which are the docs for 2.X

No, this is the documentation of 3.x

V2 is now available at v2.openhab.org
