### ISSUE TITLE
[habmin] Replace vis.js (almende/vis) dependency due to EOL

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-webui#69]
As stated in https://github.com/almende/vis/issues/4259 vis.js (almende/vis) is no longer maintained.

The build may fail one day when their GitHub project is removed for some reason (see https://github.com/openhab/openhab-webui/pull/68#issuecomment-495942012).

CC: @cdjackson

**Comment by cdjackson** [comment]
I don't think it is practically possible to replace visjs without a lot of work - if the build fails, then we'll have to deal with this or remove all charting etc.

**Comment by wborn** [comment]
You can also use one of the forks (see linked issue) instead of removing everything. ;-)

**Comment by kaikreuzer** [comment]
@cdjackson Why did you close the issue?

**Comment by cdjackson** [comment]
There are lots of dependencies that are not maintained - do we really want to open issues for them all. 

I simply suggest that if there is an issue in future, then we deal with it. I don’t really see why anything should stop compiling, or stop working - the dependencies that already exist should not be removed, and if they are, then let’s worry about it then.

**Comment by kaikreuzer** [comment]
I thought to understand from https://github.com/openhab/openhab-webui/pull/68#issuecomment-495942012 that there actually IS already an issue and that our codebase does not build anymore.

**Comment by cdjackson** [comment]
Oh, I hadn’t seen that - feel free to reopen this but I have no time at the moment to look at it.

**Comment by wborn** [comment]
The issue is fixed for now since the repository got reenabled so habmin builds again. But since the project is EOL it might be a good idea to investigate if it can be replaced with one of the forks.

**Comment by kaikreuzer** [comment]
Thanks for the clarification, @wborn. Instead of relying on a foreign fork, shall we simply create a fork of it under the openhab org and point out build to that?

**Comment by wborn** [comment]
It might be a good idea to fork it so if it goes down again we have backup and can create an alternative.

**Comment by cdjackson** [comment]
Thanks...

**Comment by kaikreuzer** [comment]
Created https://github.com/openhab/vis - anybody wants to adapt our build to use it?

**Comment by wborn** [comment]
I'll close this issue since HABmin is no longer supported in OH3 (https://github.com/openhab/openhab-webui/pull/154).
