### ISSUE TITLE
Empty tags are generated when changing the Semantic Class of an Item

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#690]
## The problem

Unneccessary empty tags get generated when changing the Semantic Class of an item.

## Expected behavior

There should be no "Non-Semantic Tags"

## Steps to reproduce

1. Create an item, set Semantic Class to e.g. "Equipment", Save: 
![image](https://user-images.githubusercontent.com/1475672/103026051-583e1d80-4553-11eb-95d6-f7eb045f7839.png)

2. Set Semantic Class to "None":
![image](https://user-images.githubusercontent.com/1475672/103026143-8d4a7000-4553-11eb-9f96-08f14e513ee2.png)

3. An empty tag has been generated and saved:
![image](https://user-images.githubusercontent.com/1475672/103026107-7441bf00-4553-11eb-845a-58becd84bd55.png)

## Your environment

OH3, see my previous issues.

```yaml

```

## Additional information

I have not seen any problems resulting out of this, so it's a very minor issue. The not needed tag can also be deleted manually just fine.

**Comment by toweosp** [comment]
Furthermore one has to select "None" before being able to change the semantic class to a class of another "class type" (location, equipment, point).
