### ISSUE TITLE
[MainUI] [OH3 Final] Items defined in .items file can be linked but not unlinked

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#693]
## The problem

When you create your items with .items files and not the MainUI you can still link them in MainUI when you start in the "Model" view (see https://github.com/openhab/openhab-webui/issues/685). But you can not unlink them anymore in the items view (or anywhere else?).

Item created in MainUI (unlinking options are shown):
![image](https://user-images.githubusercontent.com/1475672/103031880-000d1880-455f-11eb-8d33-dc03f2b91379.png)

Item created in .items file (buttons are missing):
![image](https://user-images.githubusercontent.com/1475672/103031947-25018b80-455f-11eb-88a1-050cc803fd18.png)

## Expected behavior

Items that can be linked shouls also be unlinkable.

## Steps to reproduce

1. Create item in .items file
2. Go to Model view and Link it to a Point from there.
3. Try to unlink it

**Comment by ghys** [comment]
This is a side effect of my decision to discourage item linking in the UI if the item is created in a file, discussed in https://github.com/openhab/openhab-webui/issues/413#issuecomment-719923775.
If you choose to use files for your items, you should link them there as well - `{channel="..."}`.
This is an arbitrary limitation, not sure it was a wise one after all, but it's either this or always show the buttons and let the user face an error if the link was made in the file, until we have a way of figuring out if it's actually editable by the UI.

**Comment by eikowagenknecht** [comment]
I think this really is **not** a good limitation, because now items defined in .items files **can** be linked (see #685 where I describe how to do it) and never unlinked again (maybe it is possible in some other dialog as the linking is also only possible in some dialogs not others).

In #413 you say "I don't think there are many cases of links being created in the UI while the item is not."
I'm not sure that is true. I remember that when I started using openHAB some years ago that the guides I used suggested this practice and I sticked to it. Maybe today it's not encouraged as much, but as long as openHAB has this possibility I think the main user interface (mainUI) should also support it.

I understand that it is a bit annoying for users who  bind items in .items files when there is an "unlink" button in the mainUI. But I would prefer an error "Oops. Seems like you defined that link in a file. Please remove it there." over the current state.

The best solution would of course be to be able to determine from the UI side upfront where a link was defined and only provide edit / unlink functionality for the ones defined in mainUI. I guess this would need some API enhancement?
