### ISSUE TITLE
[MainUI] Editing DSL rules is broken

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#697]
I am now running the stable 3.0 release.

Trying to edit any DSL rule (they are defined in a .rules file) and nothing happens (no page loaded).

Same thing on Windows 10 Firefox and Android Chrome.

I found nothing in Firefox debugger.

It was of course working in the past. I can't say at which time exactly the behaviour was broken,

@ghys: let me know if you can't reproduce and I will try to provide more information.

**Comment by lolodomo** [comment]
I don't know if it has a direct link byt when I open the page listing the rules, I see this error:
![image](https://user-images.githubusercontent.com/10186704/103093663-41530600-45fb-11eb-91fb-f89c41afb96c.png)

**Comment by ghys** [comment]
I noticed that too late that you can't open the script action module for non-editable rule. It's not super important either since, well, it's in your file and you cannot edit it with the UI.
