### ISSUE TITLE
[ui] No map is shown if mapview widget has no state

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#7]
Basic UI:
![basic](https://user-images.githubusercontent.com/22525368/52504776-c096e680-2be9-11e9-9b7e-4da0cd9395aa.JPG)

HTML:
![html](https://user-images.githubusercontent.com/22525368/52504778-c4c30400-2be9-11e9-893a-af71b1a9f455.JPG)

REST API:
![rest](https://user-images.githubusercontent.com/22525368/52504784-c8568b00-2be9-11e9-9bf5-ab147be429d1.JPG)

There is a similar issue in the Android app (https://github.com/openhab/openhab-android/pull/1195). It shows a map, but it's centered at 0",0":
![screenshot_20190208-213905](https://user-images.githubusercontent.com/22525368/52504913-2b482200-2bea-11e9-818a-6aad8ff21be7.png)
![screenshot_20190208-213913](https://user-images.githubusercontent.com/22525368/52504914-2b482200-2bea-11e9-9e0f-a99b416133ee.png)

IMO we should find a similar solution for both UIs. I suggest to replace the map by an icon (https://materialdesignicons.com/icon/map-marker-off) and a hint.

**Comment by lolodomo** [comment]
I discovered that Basic UI does not uypdate the mapview widget ! I will see if I can fix that.

Replacing the map by an icon is not so obvious in Basic UI and Classic UI.
I propose to display a map centered on 0,0 without any marker when the location is undefined.

**Comment by lolodomo** [comment]
I created PR #101 for Basic UI : refresh of location is now handled when the page is opened and the UNDEF state is now handled by the display of a special icon in place of the map.

**Comment by lolodomo** [comment]
And PR #102 for Classic UI.

**Comment by lolodomo** [comment]
I think this issue can now be closed. 
No state is now handled by Basic UI and Classic UI. It was already in Android app.

**Comment by mueller-ma** [comment]
Can you post a screenshot how Basic UI now displays a MapView widget without state?

**Comment by lolodomo** [comment]
Here is an example in Basic UI:
![image](https://user-images.githubusercontent.com/10186704/63815309-6d417700-c934-11e9-8bed-2f5d04015e63.png)

**Comment by lolodomo** [comment]
Finally it looks like it is not yet implemented in Android app.
