### ISSUE TITLE
Pick thing/model is not working

### ISSUE THREAD

**Issue by meisterfuu** [openhab/openhab-webui#701]
## The problem

When you choose a model or thing in the popup when creating an equipment the view goes back and nothing happens. And the URL reverts to http://localhost:8080/#

The browser goes back to the last page.

Edit: Same thing happen when clicking changing the semantic class. Clicking on e.g. shutter lets the browser go back.

## Expected behavior
You can pick a thing. The dialog closes and the chosen thing/model is shown in the form.

## Steps to reproduce

1. Got to Model. Click "Create Equipment from Thing". 
2. PickThing
3. Page goes back without picking a thing.

Same happens when creating Equipment through the Thing(Adding Equipment to Model) when choosing a parent. The view goes back to the channels of the thing.

## Your environment

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: D:\OpenHab\openhab-3.0.0\conf
  userdataFolder: D:\OpenHab\openhab-3.0.0\userdata
  logFolder: D:\OpenHab\openhab-3.0.0\userdata\logs
  javaVersion: 11.0.6
  javaVendor: AdoptOpenJDK
  javaVendorVersion: AdoptOpenJDK
  osName: Windows 10
  osVersion: "10.0"
  osArchitecture: amd64
  availableProcessors: 24
  freeMemory: 146189080
  totalMemory: 645922816
bindings:
  - airquality
  - ambientweather
  - astro
  - avmfritz
  - chromecast
  - denonmarantz
  - exec
  - feed
  - fsinternetradio
  - http
  - hue
  - ipcamera
  - ipp
  - kodi
  - mpd
  - mqtt
  - network
  - openuv
  - openweathermap
  - systeminfo
  - tankerkoenig
  - telegram
  - tplinksmarthome
  - upnpcontrol
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 24
    language: de-DE
    languages:
      - de-DE
      - en-DE
      - de
      - en-US
      - en
      - ko
    onLine: true
    platform: Win32
  screen:
    width: 3440
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.88 Safari/537.36
timestamp: 2020-12-26T03:44:54.585Z

## Browser console

Nothing is shown in the console

## Browser network traffic

No failing requests

## Additional information

--

**Comment by meisterfuu** [comment]
It works in firefox. Not in Chrome. I cannot figure out why.

**Comment by MHerbst** [comment]
@meisterfuu You can try to refresh and clear the cache in Chrome with Ctrl+F5. I had similar problems because of older files in the browser cache.

**Comment by meisterfuu** [comment]
> @meisterfuu You can try to refresh and clear the cache in Chrome with Ctrl+F5. I had similar problems because of older files in the browser cache.

Indeed - that did help indeed. Thank you. I totally forgot to try that.
