### ISSUE TITLE
Selection of Google Assistant Class not selected when edit item metadata page is opened 

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#711]
Item with Google Assistant metadata `ga="Switch" [roomHint="Hauswirtschaftraum"]`:

![image](https://user-images.githubusercontent.com/5131747/103172062-0b0ec400-4851-11eb-9684-3c6b83b1e6ef.png)

Selection of Google Assistant Class not selected when edit item metadata page is opened:

![image](https://user-images.githubusercontent.com/5131747/103172079-24177500-4851-11eb-9980-7d06ed7f0e2e.png)

Code is correct:

![image](https://user-images.githubusercontent.com/5131747/103172090-37c2db80-4851-11eb-812c-48b6e24cf3e5.png)

**Comment by eikowagenknecht** [comment]
Fixed with #722
