### ISSUE TITLE
Mqtt Broker LocaleZone Problem

### ISSUE THREAD

**Issue by haybolat** [openhab/openhab-webui#716]
## The problem
When I select Configuring locales tr_TR.UTF-8 in the system settings, the mqtt broket settings page appears blank. Please kindly ask that this error be examined and corrected.

## Steps to reproduce

1. 

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by hubsif** [comment]
Hi @haybolat,

I wasn't able to reproduce this issue. Is it still valid?

**Comment by florian-h05** [comment]
I will close this issue as it obviously went stale -- the author did not answer the request.
