### ISSUE TITLE
Alexa Metadata Documentation Link is wrong

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#717]
While adding Alexa metadata i tried to access den documentation trough the offered link.

![image](https://user-images.githubusercontent.com/40339145/103219273-7e7e0780-491d-11eb-9576-1559fc37ad08.png)

Unfortunately the link goes to https://www.openhab.org/link/alexa with a

![image](https://user-images.githubusercontent.com/40339145/103219312-a1102080-491d-11eb-858b-95c3c284ff30.png)

**Comment by eikowagenknecht** [comment]
Fixed in https://github.com/openhab/website/pull/265
