### ISSUE TITLE
Items from .items files are outside the desired location in the Model tree view after reboot

### ISSUE THREAD

**Issue by LCN-User** [openhab/openhab-webui#736]
## The problem

The Item in the .items file (The group "gBadezimmerUnten" inserts the item in the desired location):
![Screenshot 2020-12-31-item](https://user-images.githubusercontent.com/76812252/103415934-a7ec9c80-4b84-11eb-81c9-e62a2deaba9c.jpg)
 
The Model in the Main UI looks good:
![Screenshot 2020-12-31-Model-tree-view1](https://user-images.githubusercontent.com/76812252/103415982-ceaad300-4b84-11eb-9338-6ac68a68d327.jpg)

After reboot the RaspberryPi the item is outside the house in the Model tree view:
![Screenshot 2020-12-31-Model-tree-view2](https://user-images.githubusercontent.com/76812252/103416229-0ebe8580-4b86-11eb-8ded-a98b51ceabc1.jpg)

Now I delete "gBadezimmerUnten" in the .items file and save the file. After that I (re-)add the deleted group and all is fine, untill the next reboot. 

## Expected behavior

see above

## Steps to reproduce

see above 

## Your environment
Raspberry Pi 4B, 4GB, Rev. 1.2
Openhabian 3.0.0 release, fresh installed on a new 64 GB SD-card
.items, .sitemaps files copied from the old openhab 2.5 installation
LCN-Binding

## Browser console

```txt

```

**Comment by jeffstagedoor** [comment]
have you tried making "gBadezimmerUnten" the _first_ group the Item EG_BU_BMI_1 is added to? 
I don't know in what order OH processes the groups an item is connected to via file-config, but I experienced, that when I add an item to a semantic group _first_ and later added the non-semantic groups (g_BMI, g_BMI_EG) they showed up in the model as they should.
Maybe worth a try.

**Comment by LCN-User** [comment]
Hello Jeff, 
I just changed the item as suggested and restarted the RaspberryPi. Unfortunately this did not solve the problem. Even if the item is only a member of the group "gBadzimmerUnten", it does not work. Thanks for the tip though, it was worth a try.

**Comment by ghys** [comment]
If you go to the point's detail page (click on it on the right) when this occurs, does the parent gBadezimmerUnten group appear in "Parent groups"? If not it's a problem with the core, not the UI, and this issue should be moved there.

**Comment by LCN-User** [comment]
I think this is what you mean.
![Screenshot 2021-01-04-Item-Details](https://user-images.githubusercontent.com/76812252/103540674-64eb3b80-4e9a-11eb-98a5-10e6b2330fdf.jpg)

**Comment by ghys** [comment]
This is a problem with the SemanticsMetadataProvider - see the screenshot above: no "hasLocation" relationship. Moving to core.
