### ISSUE TITLE
[Main UI] Add support for playing sounds / webaudosink

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-webui#743]
OHC provides a feature to stream sounds and audio notifications via a webaudosink. Legacy UIs supported playing these streams. I would be great if we can reintroduce this feature for the new UI.

**Comment by bf8392** [comment]
+1

**Comment by JueBag** [comment]
Is somebody working on that? Otherwise the mentioned UI in the [multimedia documentation ](https://www.openhab.org/docs/configuration/multimedia.html) should be removed.

**Comment by wborn** [comment]
I recently also ran into this issue while testing if MaryTTS still worked after reworking commons-io.
So I've updated the docs so others won't waste their time on this in https://github.com/openhab/openhab-docs/pull/1561.
