### ISSUE TITLE
OH3 webapp does not work on iOS 9.3.5

### ISSUE THREAD

**Issue by konsulten** [openhab/openhab-webui#759]
Cannot get OH3 webpage to work on Ipad 2 running ios 9.2.5
"A problem occured with this web page, so it was reloaded"
"A problem repeatedly occured on "https://192.168.4.200:8443/"

This error "Viewport argument key "viewport-fit" not recognized and ignored.
Suggests similar fix as: https://github.com/longzheng/cordova-plugin-googlemaps/commit/e17078fb110b527fccaab29db00101b2f94f3f3a

Then its a SyntaxError: Unpexpected keyword 'function'
(anonymous)@ VMundefined app.js:10

I'm more than happily to debug and so if someone needs some input on how to solve this. I have two ipad 2 which now cannot be used with OH3 in a nice manner :(

**Comment by kuifje123** [comment]
Also noticed this on an Ipad 3.
Would be nice to be able to use it again.

**Comment by konsulten** [comment]
Anyone who has some experience that can look into this? Or is it thought that iOS 9.3.5 is unsupported? From what I saw in the babel configuration, it is intended to work? 
targets: {
        browsers: [
          'Android >= 5',
          **'IOS >= 9.3',**
          'Edge >= 15',
          'Safari >= 9.1',
          'Chrome >= 49',
          'Firefox >= 31',
          'Samsung >= 5'
        ]
      }

**Comment by crnjan** [comment]
Would you mind trying out (I don't have 9.3.5 device) https://community.openhab.org/t/oh3-mainui-on-smart-tvs/116209/6 ?

**Comment by konsulten** [comment]
@crnjan I will give it a go this evening if I get time :)!

**Comment by konsulten** [comment]
@crnjan Sadly not, I currently don't get any output from the web page. "A problem occured with this web page, so it was reloaded" is the only thing showing.

**Comment by crnjan** [comment]
Hey! Please see my updated answer - but Framework7 (v5) needs Safari 9.1 and iOS 9.3.5 ships with Safari 9.0 so unfortunately MainUI will not run on iOS 9.3.5 - iOS 10 is required as minimum. Maybe @ghys can confirm or correct me, but afaik there is no way around this. Sorry.

**Comment by konsulten** [comment]
That was sad :( Yeah I checked now and in the forums of Framework7 it seems they talk about iOS>=10
Thanks anyway

**Comment by ghys** [comment]
Right it would appear that's the case. Not too surprising to have dropped support for a 5-year-old browser IMHO - you probably would have encountered other problems anyway.
