### ISSUE TITLE
[MainUI] Add widget metadata to item results in missing selection of widget

### ISSUE THREAD

**Issue by kuifje123** [openhab/openhab-webui#766]
## The problem
Using OH3 #2115 I notice that adding widget metadata to an item results in an empty page.

## Expected behavior

On previous builds I was able to select the widget. This selection is now missing.

## Steps to reproduce

Tested with various different items. All with same result.

## Your environment

runtimeInfo:
  version: 3.1.0
  buildString: "Build #2115"
locale: en_NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.4.59+
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 124337888
  totalMemory: 346030080
bindings:
  - astro
  - exec
  - harmonyhub
  - http
  - icloud
  - irobot
  - mqtt
  - network
  - ntp
  - openweathermap
  - tr064
  - zwave
clientInfo:
  device:
    ios: true
    android: false
    androidChrome: false
    desktop: false
    iphone: false
    ipod: false
    ipad: true
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    os: ios
    osVersion: 14.0.1
    webView: true
    webview: true
    standalone: true
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-gb
    languages:
      - en-gb
    onLine: true
    platform: MacIntel
  screen:
    width: 834
    height: 1112
    colorDepth: 32
  support:
    touch: true
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: true
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
timestamp: 2021-01-06T21:04:01.323Z

## Browser console

Warning processing windowTypes: This property is deprecated global.min.js:250
    makeError resource://gre/modules/Schemas.jsm:518
    logWarning resource://gre/modules/Schemas.jsm:1230
    logDeprecation resource://gre/modules/Schemas.jsm:1222
    checkDeprecated resource://gre/modules/Schemas.jsm:1258
    normalizeBase resource://gre/modules/Schemas.jsm:1381
    normalize resource://gre/modules/Schemas.jsm:2212
    r resource://gre/modules/Schemas.jsm:1906
    withPath resource://gre/modules/Schemas.jsm:603
    checkProperty resource://gre/modules/Schemas.jsm:1905
    normalize resource://gre/modules/Schemas.jsm:1978
    normalize resource://gre/modules/Schemas.jsm:1514
    fixedArgs resource://gre/modules/Schemas.jsm:2571
    map self-hosted:221
    checkParameters resource://gre/modules/Schemas.jsm:2566
    stub resource://gre/modules/Schemas.jsm:2672
    a moz-extension://91accb6c-4650-4a01-8e30-128fda0dd962/global.min.js:250
    apply self-hosted:2644
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    fire resource://gre/modules/ExtensionChild.jsm:806
    recvRunListener resource://gre/modules/ExtensionChild.jsm:810
    recvRunListener self-hosted:1161
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsChild.jsm:184
    (Async: JSActor query)
    _send resource://gre/modules/ConduitsChild.jsm:61
    _send resource://gre/modules/ConduitsParent.jsm:228
    _send self-hosted:1265
    listener resource://gre/modules/ExtensionParent.jsm:1001
    apply self-hosted:2644
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    applySafe resource://gre/modules/ExtensionParent.jsm:508
    async resource://gre/modules/ExtensionCommon.jsm:2413
    (Async: promise callback)
    async resource://gre/modules/ExtensionCommon.jsm:2411
    listener chrome://browser/content/parent/ext-windows.js:102
    (Async: promise callback)
    listener chrome://browser/content/parent/ext-windows.js:92

## Browser network traffic

![network](https://user-images.githubusercontent.com/10101529/104001459-fd860200-519f-11eb-9d71-ae3366c0ffae.png)

**Comment by kuifje123** [comment]
![EE324597-782D-4931-BBEC-38B77E832427](https://user-images.githubusercontent.com/10101529/103819786-6324a200-506b-11eb-98af-dcddeff62452.png)
![BD049F70-D6BD-4CC6-8D13-C505F3B2217E](https://user-images.githubusercontent.com/10101529/103819788-6455cf00-506b-11eb-9dec-e852695c6ca8.png)
![4E9C0390-086E-4F99-A0DA-5A2ACE6760D0](https://user-images.githubusercontent.com/10101529/103819789-6455cf00-506b-11eb-92c3-95da42ddfe9f.png)

**Comment by ghys** [comment]
> ## Browser console
> ## Browser network traffic

**Comment by kuifje123** [comment]
Hi @ghys I added these in the issue above.
I hope it will help.
If there are additional things I can test, let me know.

**Comment by ghys** [comment]
The console output above doesn't look like the apps, but a browser extension.
Can you try again in Chrome or equivalent, in incognito mode, also paste the contents of the response of the network request that ends with "? metadata=widget". Thanks.

**Comment by kuifje123** [comment]
**Chrome console output:**


app.js:7 ReferenceError: $store is not defined
    at orderedPersonalWidgets (20.app.js:1)
    at fn.get (app.js:7)
    at fn.evaluate (app.js:7)
    at o.orderedPersonalWidgets (app.js:7)
    at o.<anonymous> (20.app.js:1)
    at o.e._render (app.js:7)
    at o.a (app.js:7)
    at fn.get (app.js:7)
    at fn.run (app.js:7)
    at pn (app.js:7)
Ge @ app.js:7
We @ app.js:7
Ue @ app.js:7
e._render @ app.js:7
a @ app.js:7
fn.get @ app.js:7
fn.run @ app.js:7
pn @ app.js:7
(anonymous) @ app.js:7
Qe @ app.js:7
Promise.then (async)
Ye @ app.js:7
at @ app.js:7
(anonymous) @ app.js:7
fn.update @ app.js:7
pe.notify @ app.js:7
set @ app.js:7
mn.set @ app.js:7
(anonymous) @ 20.app.js:1
Promise.then (async)
onPageAfterIn @ 20.app.js:1
qe @ app.js:7
n @ app.js:7
qe @ app.js:7
e.$emit @ app.js:7
(anonymous) @ app.js:7
t.a @ app.js:7
dispatchEvent @ app.js:20
onPageAfterIn @ app.js:20
(anonymous) @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
(anonymous) @ app.js:9
value @ app.js:9
value @ app.js:9
U @ app.js:9
(anonymous) @ app.js:9
(anonymous) @ app.js:9
r @ app.js:1
c @ app.js:1

**Comment by kuifje123** [comment]
**Network response:**

`{"link":"http://diskstation918.fritz.box:8080/rest/items/TSV_BedroomN_Setpoint","state":"18 °C","stateDescription":{"pattern":"%.0f","readOnly":false,"options":[]},"editable":true,"type":"Number:Temperature","name":"TSV_BedroomN_Setpoint","label":"Slaapkamer Niels Setpoint","category":"heating","tags":["RadiatorControl"],"groupNames":[]}`

**Comment by ghys** [comment]
Wow, serious lack of testing of #724...
That's what happens when you review PRs on your phone during the holidays...
#768 should fix it, thanks for the report!

**Comment by kuifje123** [comment]
Thanks for the quick fix 👍

**Comment by johannesbonn** [comment]
Hello @ghys,

can you tell me, when the fix will be available in the snapshots?

thank you!

**Comment by kuifje123** [comment]
@ghys 
Just installed snapshot 2131, this issue does not appear to be solved yet, is that correct?

**Comment by ghys** [comment]
Hm, yes indeed there's still a problem, sorry for that.
