### ISSUE TITLE
[MainUI] The 'By Binding' views should have a two level sort

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#792]
## Problem

In both `MainUI/Settings/Things` and `MainUI/Settings/Things/Inbox` there are two selections 'Alphabetical' and 'By Binding'. The latter view does not sort elegantly..

-  `MainUI/Settings/Things/Alphabetical` and `MainUI/Settings/Things/Inbox/Alphabetical` do sort elegantly.
-  `MainUI/Settings/Things/By Binding` and `MainUI/Settings/Things/Inbox/By Binding` do **_not_** sort elegantly.

![image](https://user-images.githubusercontent.com/893994/104359299-64d8e480-5507-11eb-9ff4-f86c35c8af51.png)

## Solution

The 'By Binding' views should have a _two level_ sort: 
1. First level sort on the Binding Name (in addition to being grouped on the Binding name), and then 
2. Second level sort (within its respective group) on the Thing name (as is done already).

**Comment by rkoshak** [comment]
This is still the case in OH 4.0 SNAPSHOT 3352 (my not so subtle way to bump this issue back to being noticed). It's increasingly irksome.
