### ISSUE TITLE
OH3 - Addons section suddenly dissapeared

### ISSUE THREAD

**Issue by davidmprz** [openhab/openhab-webui#802]
## The problem

Hello everybody,

I have been running OH3 on raspberry pi for a few days without issues. I had setup a couple of lights, motion & temperature sensors (aqara) and so on. For that, i had to install a few bindings (e.g HUE, network, Xiaomi, etc)

The other day I wanted to add more functionalities to OH3, and when I was going to add a new binding, i found out that the ADDONS section completly dissapeared! Therefore, i cannot add new bindings.

I do not know when this happened, or what caused the issue as I have NOT been doing any configuration or maintenance on OH3.

Any ideas of what could be the issue here? my things & items still work (with the previously installed bindings)

PS: I signed in & out several times, closed all open sessions... etc. 

Thanks in advance

![image](https://user-images.githubusercontent.com/77438604/104579157-e8a3e580-565b-11eb-9a6c-e26add14bc49.png)

## Your environment

```yaml

```
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_ES
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 117183088
  totalMemory: 194969600
bindings:
  - amazonechocontrol
  - hue
  - mihome
  - network
  - remoteopenhab
  - zigbee
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: es-ES
    languages:
      - es-ES
      - en
      - es
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-14T10:32:19.240Z

## Browser console

```txt

```

In the Developer Tools sections, it also seems to have missing options/tabs 

![image](https://user-images.githubusercontent.com/77438604/104579969-f60d9f80-565c-11eb-9ece-37a7d8a0e65d.png)

**Comment by rallecoe** [comment]
Cleaning the cache solved the problem for me.

**Comment by davidmprz** [comment]
> Cleaning the cache solved the problem for me.

That worked! yes!

Thank you!

**Comment by pezoli** [comment]
> Cleaning the cache solved the problem for me.

Spent a day fixing binding installations manually, after the addon menu disappeared. Running v3.2.0. Cleaning cache (deleteing cache and tmp folders) solved the issue. Many thanks!
