### ISSUE TITLE
Extend semantic model location types

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-webui#809]
## The problem

Semantic model is missing some types to fit to my configuration  

## Your suggestion

There should be more types:

```
     - Room: Office
     - Room: HobbyRoom
     - Room: StorageRoom
     - Room: BoilerRoom

     - Building: GardenShed

     - Location: External <- For external APIs mainly the location where equipment WebService would be like CoronaStats, Tankerkönig, NTP etc.
```

**Comment by DerOetzi** [comment]
> ## The problem
> Semantic model is missing some types to fit to my configuration
> 
> ## Your suggestion
> There should be more types:
> 
> For location:
> - Room: Office
> - Room: HobbyRoom
> - Room: StorageRoom
> - Room: BoilerRoom
> 
> ```
>  - Building: GardenShed
> 
>  - Location: External <- For external APIs mainly the location where equipment WebService would be like CoronaStats, Tankerkönig, NTP etc.
> ```

**Comment by lolodomo** [comment]
Office is already there. 
There is an open issue in the core repo to discuss changes of semantics.

**Comment by lolodomo** [comment]
@ghys : you can close this feature request here. The right place is the core repo and this issue:
https://github.com/openhab/openhab-core/issues/1791

**Comment by lolodomo** [comment]
And the request is apparently not based on official 3.0 as office and boiler room are already there.

**Comment by ghys** [comment]
Indeed, thanks!

**Comment by DerOetzi** [comment]
Thanks for information. I wasn't sure which is correct repo for this. 

Will add this as documentation request. Because  I am working on official OH3 using the image on the very top from https://openhab.org/docs/tutorial/model.html to find which types are available for usage. Maybe there should be a kind of listing on this page.
