### ISSUE TITLE
[OH3 MainUI] Widgets do not show any values after testing authentication with additional user

### ISSUE THREAD

**Issue by icompas** [openhab/openhab-webui#816]
I tried to use authentication. During this, I added an additional user via Karaf to the configuration.

`openhab:users add openHABUser passwd user`

I tested authentication, switched on the visibility for users and administrator for some pages and widgets. After this I deleted the user via Karaf,

 `openhab:users remove openHABUser`

## Expected behavior

Just work as before since the admin user wasn't touched at all and all views where turned back to the following visibilty,

<img width="768" alt="grafik" src="https://user-images.githubusercontent.com/44095390/104846887-2499ad80-58dd-11eb-9285-198967b14f26.png">

## Steps to reproduce

Well, since I can't revert this issue, I can not reproduce it.

## Your environment

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+55-CA
  osName: Linux
  osVersion: 4.19.0-13-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 5787992
  totalMemory: 563085312
bindings:
  - astro
  - avmfritz
  - bluetooth
  - http
  - mail
  - network
  - ntp
  - openweathermap
  - systeminfo
  - tr064
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 6
    language: de
    languages:
      - de
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2304
    height: 1296
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0
timestamp: 2021-01-17T15:01:54.577Z

## Browser console (IP Address is masked, but it is local private network)

```
new SSE connection: http://xxxx.xxxx.xxxx.100:8080/rest/events?topics=openhab/items/*/added,openhab/items/*/removed,openhab/items/*/updated, 1 open app.js:27:1028984
Array []
app.js:27:1029067
Firefox kann keine Verbindung zu dem Server unter http://xxxx.xxxx.xxxx.100:8080/rest/events?topics=openhab/items/*/added,openhab/items/*/removed,openhab/items/*/updated aufbauen. 2 app.js:27:1028649
SSE error app.js:27:1028828
=!= Event source connection broken... app.js:27:1028879
Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil! 192.168.2.100:8080
SSE connection closed: http://xxxx.xxxx.xxxx..100:8080/rest/events?topics=openhab/items/*/added,openhab/items/*/removed,openhab/items/*/updated, 0 open app.js:27:1031210
Array []
app.js:27:1031296
new SSE connection: http://xxxx.xxxx.xxxx.100:8080/rest/events?topics=openhab/things/…hab/things/*/updated,openhab/things/*/status,openhab/inbox/*, 1 open app.js:27:1028984
Array []
app.js:27:1029067
SSE error app.js:27:1028828
=!= Event source connection broken... app.js:27:1028879
Firefox kann keine Verbindung zu dem Server unter http://192.168.2.100:8080/rest/events?topics=openhab/things/*/added,openhab/things/*/removed,openhab/things/*/updated,openhab/things/*/status,openhab/inbox/* aufbauen. 2 app.js:27:1028649
SSE connection closed: http://xxxx.xxxx.xxxx..100:8080/rest/events?topics=openhab/things/…hab/things/*/updated,openhab/things/*/status,openhab/inbox/*, 0 open app.js:27:1031210
Array []
app.js:27:1031296
Start tracking states app.js:32:2597
new SSE connection: http://xxxx.xxxx.xxxx.100:8080/rest/events/states, 1 open app.js:27:1028984
Array []
app.js:27:1029067
SSE error app.js:27:1028828
=!= Event source connection broken... app.js:27:1028879
Firefox kann keine Verbindung zu dem Server unter http://xxxx.xxxx.xxxx.100:8080/rest/events/states aufbauen. 2 app.js:27:1028649
Proxy: need cFboxMacOnlineEva app.js:32:2146
updateTrackingList: No connection id, not calling the API

```
## Additional information

Status of authentication setting,

<img width="758" alt="grafik" src="https://user-images.githubusercontent.com/44095390/104847021-02545f80-58de-11eb-8b70-9f98fdcd7c66.png">

**Comment by ghys** [comment]
A bit surprising if the removal of the user was related. If you go to http://yourip:8080/rest/events/states (or  with curl) do you see something like  "event: ready" / "id: 0"?

**Comment by icompas** [comment]
No, I don't. I recveive:

error |  
message | "Authentication required"
http-code | 401

Toggling the switch for basic authentication does not change anything in behavior.

From the web console, I almost think the issue is related to authentication,

![grafik](https://user-images.githubusercontent.com/44095390/104882123-c8796c80-5962-11eb-82fd-99068d4aaf6a.png)

**Comment by ghys** [comment]
It's working as expected and support for the advanced parameter "implicit user role for unauthenticated requests" being disabled was just added in Main UI a few days ago. The other UIs still don't support it.
Both of the options in the API Security settings shouldn't be touched much atm (including Basic auth which can have a performance impact if not careful).
