### ISSUE TITLE
IconSize expression in oh-plan-marker isn't editable in dialog

### ISSUE THREAD

**Issue by stefan-hoehn** [openhab/openhab-webui#837]
## The problem
When editing an oh-plan-marker widget it is possible to configure an expression in the yaml which allows to dynamically compute the iconSize like so

  iconSize: "=(items.myalarm.displayState === 'Alarm') ? 32: 16"

however, this is not shown in the dialog of the marker nor can it be edited probably because the dialog expects numbers only

# Expected behavior

The expression should be shown and editable in the dialog

**Comment by hubsif** [comment]
I think for most users it's actually adequate to limit the input to numbers. In my opinion, expressions are advanced use and it's ok to have advanced users to switch to yaml and add the expression there.

@ghys, What do you think?

**Comment by ghys** [comment]
Yes or maybe try to detect a `=` when choosing the control to render and display a regular text input (or even an advanced one with autocompletion, why not) if an expression is detected.

**Comment by stefan-hoehn** [comment]
@ghys I noticed this one again. First of all, I wouldn't perceive it as a bug, secondly I am not sure how much the effort is to implement your idea and if it is worth the effort. If you feel, it cannot be done easily I would be happy to close that with "won't fix" (as I am not able to do it myself unfortunately)
