### ISSUE TITLE
Plan widget Zoom Visibility Maximum setting error

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#844]
## The problem

The floor plan widget editor's advanced setting of Zoom Visibility Maximum is reading the wrong value; it's set to zoomVisibilityMin here: [line 44](https://github.com/openhab/openhab-webui/blob/0a29ec6f9efb6a6f4b83bbb930bd89aab01ad902/bundles/org.openhab.ui/web/src/assets/definitions/widgets/plan/index.js#L44) and so mirrors the Zoom Visibility Minimum field instead.

## Expected behavior

Separate field should have separate variable...

## Steps to reproduce

1. Try to set the Zoom Visibility Maximum of a plan widget

## Your environment

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_US
systemInfo:
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+21-CA
  osName: Linux
  osVersion: 4.15.0-118-generic
  osArchitecture: amd64

**Comment by ghys** [comment]
Good catch 😓 PR would be appreciated ;)

**Comment by JustinGeorgi** [comment]
Never done a PR in a community git before, but I can take a crack at it.  Stumbled across a second minor issue as well so I'll see what I can do.
