### ISSUE TITLE
[RESTDOC] Can't read swagger JSON

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#86]
I'm running openHAB 2.5.0 Build #1635 but I do not know when this problem first occurred as I don't use the Rest API Docs that frequently. 

When I try to access the REST API docs I get the following error on the screen:

`Can't read swagger JSON from https://<address of OH>/rest/swagger.json`

There is no error in openhab.log.

**Comment by ghys** [comment]
I had the same but with errors in the log (see #67).
https://github.com/openhab/openhab-webui/issues/67#issuecomment-503198047
Can you try uninstalling the Jinja add-on if you have it installed?

**Comment by rkoshak** [comment]
I saw that issue but because I am not getting an exception and have never had the Jinja add-on installed. Wasn't even aware there was a Jinja transform now. That's cool!

**Comment by ghys** [comment]
Probably a different issue then indeed.
Do you get anything in particular when you request https://<address of OH>/rest/swagger.json directly?

**Comment by rkoshak** [comment]
A 404 error:

`{"error":{"message":"HTTP 404 Not Found","http-code":404,"exception":{"class":"javax.ws.rs.NotFoundException","message":"HTTP 404 Not Found","localized-message":"HTTP 404 Not Found"}}}`

I interpret it to mean it can't find the JSON file, right? Is this file dynamically generated or does it exist somewhere I can look and verify whether it's there?

**Comment by ghys** [comment]
That's right - It's dynamiccally generated - I would have said "try uninstalling-reinstalling the REST docs add-on", but apparently you're not the only one with this problem (https://community.openhab.org/t/karaf-console-remove-password-and-timeout/61854/9) and it doesn't seem to work. It seems to be affecting recent snapshots only.

Is it a fresh install or an upgrade? In the former case I'd advise opening an issue in openhab-core, that's where the swagger.json generation code is, this repo only hosts the client.

**Comment by ghys** [comment]
For comparison, this is what I have Swagger-related in another older working snapshot's bundle list:
```
openhab> bundle:list | grep -i swagger
209 x Active x  80 x 1.1.1.201605111122    x Swagger Provider
216 x Active x  80 x 1.5.8                 x swagger-annotations
217 x Active x  80 x 1.5.8                 x swagger-core
218 x Active x  80 x 1.5.8                 x swagger-jaxrs
219 x Active x  80 x 1.5.8                 x swagger-models
257 x Active x  80 x 1.5.8.v20160511-1038  x swagger-jersey2-jaxrs (wrap)
```

**Comment by rkoshak** [comment]
It's an upgrade. Should I file an issue over at core even though it's a upgrade? It does seem like generation of the swagger.json that is the problem.

Here is my Swagger-related stuff:

```
openhab> bundle:list | grep -i swagger
208 │ Active │  80 │ 1.1.1.201605111122    │ Swagger Provider
224 │ Active │  80 │ 1.5.8                 │ swagger-annotations
225 │ Active │  80 │ 1.5.8                 │ swagger-core
226 │ Active │  80 │ 1.5.8                 │ swagger-jaxrs
227 │ Active │  80 │ 1.5.8                 │ swagger-models
297 │ Active │  80 │ 1.5.8.v20160511-1038  │ swagger-jersey2-jaxrs (wrap)
```

The interesting thing is they are the same versions as yours.

**Comment by ghys** [comment]
I'd go ahead and open the issue in openhab-core, folks over there are more knowledgeable.
The reason I asked if it were an upgrade is because it's probably going to be harder to reproduce and troubleshoot the problem if it's working on a fresh install, and caused by a configuration due to the upgrade.

**Comment by rkoshak** [comment]
I added a comment to https://github.com/openhab/openhab-core/pull/905 first as Scott thinks its related to this PR. I'll open a new issue if it's not. Thanks for the help!
