### ISSUE TITLE
Item list looses filter

### ISSUE THREAD

**Issue by aurelio1** [openhab/openhab-webui#861]
## Issue
I am in the Item list and do the following:

1. enter a filter, eg. "airQ_" to show all items containing airQ_
2. I go into an Item
3. In the view of the single Item, I press "back" in the upper left corner
4. the Item list appears with "airQ_" in the filter entry box, but the entries are not filtered

## Expected behavior
I would expect that the list is still filtered when I go back to the Item list.

## Steps to reproduce
See above

1. 

## Your environment

runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_CH
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 4.19.66-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 58748504
  totalMemory: 247332864
bindings:
  airq
  (other bindings omitted)
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 8
    language: de
    languages:
      - de
      - en-US
      - en
      - es-AR
    onLine: true
    platform: Linux x86_64
  screen:
    width: 1920
    height: 1080
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
timestamp: 2021-01-28T21:17:34.620Z

```yaml

```

## Browser console

```txt

```

**Comment by eikowagenknecht** [comment]
Same here. One addition: When going back the list first *is* filtered and then after half a second or so it is apparently refreshed and unfiltered. Also: Going into the search bar and pressing enter doesn't fix it, only removing and readding a character leads to filtering it again.

**Comment by thomaszlow** [comment]
I can confirm the bug and behavior reported by @aurelio1 and @eikowagenknecht.

**Version:** `Openhab 3.0.1 Release Build`
