### ISSUE TITLE
incorrectly formatted  unit displayed in the analyse tab

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-webui#870]
## The problem

The unit displayed in the analyse tab is incorrectly formatted
For the item with definition
`Number:Dimensionless paddestoel__humidity    "Paddenstoelen Growbox Humidity [%.0f %%rH]"          <humidity> (gPaddestoel) ["Measurement","Humidity"] {channel="mqtt:topic:mosquitto:padde]`
it shows as unit `%%rH`
![image](https://user-images.githubusercontent.com/5871213/106398984-5dc23980-6416-11eb-95f6-3a4caafbf5d8.png)

## Expected behavior
Expected formatting like when displaying the item `%rH`
![image](https://user-images.githubusercontent.com/5871213/106398979-5733c200-6416-11eb-8cbf-f01625e6cde7.png)

## Steps to reproduce
Create item as above

## Your environment

OH3.1-snapshot

**Comment by Rossko57** [comment]
I think you've got what you asked for. [%.0f %%rH]
Have you tried [%.0f %rH]?
