### ISSUE TITLE
[PaperUI] Configuring channels is not possible

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#88]
There doesn't seem to be a way to configure channel parameters in PaperUI. I'm sure that in the past this was possible with a popup in the channel-item link page of the thing, but now the only option seems to be to set the profile. (maybe I'm just not looking in the right place, but others also can't find this).

Currently therefore there doesn't appear to be a way to set channel configuration data. Note that this is available in HABmin if anyone stumbles across this issue.

**Comment by kaikreuzer** [comment]
I cannot confirm. Just checked with distro snapshot 1640 and the LIFX binding and I am seeing the configuration options for channels:

![Bildschirmfoto 2019-07-28 um 23 52 59](https://user-images.githubusercontent.com/3244965/62012761-02fdb100-b193-11e9-942b-f7449d8efc7d.png)

**Comment by cdjackson** [comment]
Interesting - thanks Kai. ZigBee channel configuration is available in HABmin, but not in PaperUI -:

https://community.openhab.org/t/zigbee-binding/15763/2202 <https://community.openhab.org/t/zigbee-binding/15763/2202>

Just to confirm, where did you get to this screen? Is it by clicking on the pencil icon on the right of your image? In general most (all) of my channels don’t show this in PaperUI - I’ll take a closer look.

**Comment by kaikreuzer** [comment]
>  Is it by clicking on the pencil icon on the right of your image?

Yes, exactly!

>  In general most (all) of my channels don’t show this in PaperUI

I do not remember the details, but afair the config url is expected to have a specific syntax by which the config description is mapped to the channel - maybe something is not fully correct there for Zigbee?

**Comment by cdjackson** [comment]
I recall that it needs “channel” in the URI somewhere - it looks from a first look as though PaperUI isn’t making the REST call to the config endpoint. HABmin is doing this, and is displaying the configuration for the ZigBee channels, so I don’t think it’s directly the config provider. I’m reasonably sure this used to work on ZigBee with PaperUI and it seems that PaperUI must think there is no config for this channel and therefore isn’t calling the endpoint.

I’ll try and trace this through in PaperUI.

Thanks.

**Comment by kaikreuzer** [comment]
With some luck @triller-telekom has an idea about it as he also worked on such parts in the Paper UI.

**Comment by cdjackson** [comment]
Looking at the thing REST response I can see that there are configuration parameters in the channels (see below).

The problem *might* be seen below - this is only showing the edit button if there is channel configuration in the channelTypeUID - but ZigBee doesn't have this since the configuration is provided dynamically and is only available in the channel - not the channel type. I recall a similar issue in the past - I can't remember if it was in the channel, or the thing. I'll see if I can find it in ESH.

![image](https://user-images.githubusercontent.com/1041475/62013343-055b0d80-b189-11e9-9899-c1873c4d5097.png)


```
{  
   "statusInfo":{  
      "status":"ONLINE",
      "statusDetail":"NONE"
   },
   "firmwareStatus":{  
      "status":"UNKNOWN"
   },
   "editable":true,
   "label":"OSRAM Classic A60 TW",
   "bridgeUID":"zigbee:coordinator_ember:b492b22e",
   "configuration":{  
      "zigbee_macaddress":"7CB03EAA0000067D"
   },
   "properties":{  
      "zigbee_logicaltype":"ROUTER",
      "zigbee_powerlevel":"FULL",
      "zigbee_manufacturercode":"0xbbaa",
      "modelId":"Classic A60 TW",
      "zigbee_networkaddress":"30078",
      "zigbee_powersource":"MAINS",
      "zigbee_stkversion":"2",
      "zigbee_datecode":"20140331CNLS****",
      "zigbee_zclversion":"1",
      "zigbee_routes":"[]",
      "zigbee_lastupdate":"",
      "zigbee_stkcompliance":"0",
      "vendor":"OSRAM",
      "zigbee_powermode":"RECEIVER_ON_IDLE",
      "zigbee_powersources":"[RECHARGABLE_BATTERY, MAINS, DISPOSABLE_BATTERY]",
      "hardwareVersion":"1",
      "firmwareVersion":"0x01020412",
      "zigbee_neighbors":"[{\"joining\":\"ENABLED\",\"address\":\"4076\",\"depth\":\"1\",\"lqi\":\"108\",\"macaddress\":\"000A8000FC0093A3\"},{\"joining\":\"ENABLED\",\"address\":\"41853\",\"depth\":\"1\",\"lqi\":\"44\",\"macaddress\":\"0017880102136536\"},{\"joining\":\"ENABLED\",\"address\":\"0\",\"depth\":\"1\",\"lqi\":\"66\",\"macaddress\":\"000B57FFFE07A6E9\"}]",
      "zigbee_applicationVersion":"0",
      "zigbee_device_initialised":"true",
      "zigbee_devices":"[]"
   },
   "UID":"zigbee:device:b492b22e:7cb03eaa0000067d",
   "thingTypeUID":"zigbee:device",
   "channels":[  
      {  
         "linkedItems":[  
            "zigbee_device_b492b22e_7cb03eaa0000067d_7CB03EAA0000067D_3_colortemperature"
         ],
         "uid":"zigbee:device:b492b22e:7cb03eaa0000067d:7CB03EAA0000067D_3_colortemperature",
         "id":"7CB03EAA0000067D_3_colortemperature",
         "channelTypeUID":"system:color-temperature",
         "itemType":"Dimmer",
         "kind":"STATE",
         "label":"Color Temperature",
         "defaultTags":[  

         ],
         "properties":{  
            "zigbee_endpoint":"3"
         },
         "configuration":{  
            "zigbee_reporting_polling":7200
         }
      },
      {  
         "linkedItems":[  
            "zigbee_device_b492b22e_7cb03eaa0000067d_7CB03EAA0000067D_3_dimmer"
         ],
         "uid":"zigbee:device:b492b22e:7cb03eaa0000067d:7CB03EAA0000067D_3_dimmer",
         "id":"7CB03EAA0000067D_3_dimmer",
         "channelTypeUID":"zigbee:switch_level",
         "itemType":"Dimmer",
         "kind":"STATE",
         "label":"Level Control",
         "defaultTags":[  

         ],
         "properties":{  
            "zigbee_endpoint":"3"
         },
         "configuration":{  
            "zigbee_reporting_polling":900
         }
      }
   ]
}
```

**Comment by cdjackson** [comment]
The issue below could be a related regression -:

https://github.com/eclipse/smarthome/issues/4823


> Currently it seems that PaperUI is only displaying the configuration of the channel-type, and not the channel itself.

> This means it's not possible to have channel specific configuration shown in PaperUI as the system supports. A direct call to the rest interface with the above config uri works fine.

**Comment by ghys** [comment]
Sorry for hijacking this issue - I only recently became aware that things' and channels' configuration could differ from their respective types i.e. an UI should get them from `/rest/config-descriptions/thing:<uid>` resp. `/rest/config-descriptions/channel:<uid>` rather than what's in the response from `/rest/things/<uid>`.

I had a quick look and new UI for OH3 that will eventually replace Paper UI should behave correctly; nonetheless:
@cdjackson - it looks as good a time as any to ask - since I don't use the Zigbee binding, would you be willing to have a quick look at the new UI and report whether or not it's the case?
The following is a current build:
[ui.zip](https://github.com/openhab/openhab-webui/files/3447916/ui.zip)
To test you just have to extract the zip file in the `html` folder of your configuration and navigate to http://ip:8080/static/ui/
Next go to Settings (on the left side) then Things, click on the thing and go the Channels tab, expand the channel and click the _Configure Channel_ link.
Don't treat the whole thing as functional (though the configure channel/item linking should mostly work). 😅 

By the way: if you wish you can also test the recent changes on the "Info" tab for Z-Wave things (incl. the network map and actions), you probably have a better test environment than me :)
If you have remarks that would be off-topic to this issue maybe it's better to PM on the forum instead of replying here.
Thanks!

**Comment by cdjackson** [comment]
No problem to test this in my production system - but - do you know if it possible to run this in the (new) IDE? I’m trying to test some changes to ZigBee but I can’t currently run HABmin, and PaperUI seems to have a bug so it would be great if this can be run in the UI somehow?

**Comment by ghys** [comment]
I'm still getting acquainted to the new way of developing things in Java -as everybody is- tbh ;)
But if you *really* want to get into the new UI development ways, you could clone the https://github.com/ghys/openhab-ui-f7 repo and run `npm install` then `npm start` - but the development server is currently configured to forward REST API queries to localhost, you could change that by modifying: https://github.com/ghys/openhab-ui-f7/blob/master/build/webpack.config.js#L21 beforehand.
