### ISSUE TITLE
Consider item type for the selected profile when creating links

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-webui#885]
When creating a link, the user can choose a profile to use.
Profiles have a set of supported item types. The "Timestamp on update" for example can only be linked to a `DateType` item.

<img width="742" alt="Screenshot 2021-02-07 at 00 54 50" src="https://user-images.githubusercontent.com/3244965/107132408-1be63700-68df-11eb-884b-f32219a08d74.png">

The UI does not consider this - when "Create a new Item" is selected, it will invariably create an item of the type that is defined for the channel, but not the type that is defined by the profile. This leads to an item being created with an invalid link:

<img width="736" alt="Screenshot 2021-02-07 at 00 57 04" src="https://user-images.githubusercontent.com/3244965/107132440-6cf62b00-68df-11eb-83ba-0a8199ef8731.png">

Likewise, when selecting an existing item ("Select item to link"), the list shows all available items, while it should only offer those of supported types.

**Comment by ghys** [comment]
👀 

https://github.com/openhab/openhab-webui/blob/c3bafcf50b6cebdcb08b9713fa691ca30f610e39/bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue#L259-L262

I had enough problems already determining the compatible item types (e.g. a Color channel can be linked to a Dimmer or Switch item etc.), started getting invalid 'The channel and item type are not compatible' messages, and then I noticed the profiles would make this even more complex so I kind of gave up 😅

**Comment by kaikreuzer** [comment]
Maybe you find a quiet moment to revisit this - it'll imho be a huge simplification for the user if he only sees a filtered list, especially for large setups.

**Comment by Rossko57** [comment]
As a sort-of related enhancement, the MainUI display of a channel and its linked Items seems to hide the _channel_ type.
It would be a useful enhancement to display this in channel details, as it is for Item types.
Example display in this post, and difficulty arising from missing info -
https://community.openhab.org/t/struggling-with-mqtt/118196

**Comment by hubsif** [comment]
Hi!
I thought about working on this issue, starting by trying to understand the "base" behind this. Unfortunately, I didn't get further than general item linking:

> I had enough problems already determining the compatible item types (e.g. a Color channel can be linked to a Dimmer or Switch item etc.),

I tried to understand the core code. I'm not very experienced in Java, but in the [REST endpoint method](https://github.com/openhab/openhab-core/blob/b64c84e8b961587d8d2f84510c426c973e70257f/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java#L141) and the used `ItemChannelLink` class, I couldn't find any check for compatible channel/item types. Does that mean the core accepts just any linking, even if the types don't match?
If not, can you point me to where it's checked?
If so, can't that lead to issues and is the UI expected to filter that? Shouldn't that be the core's task instead?

Thanks!

**Comment by ghys** [comment]
The relevant Paper UI code seems to be here:

https://github.com/openhab/openhab-webui/blob/2fc6a70d1f213e93e40c8cb8e96c3ca9b98d2994/bundles/org.openhab.ui.paper/web-src/js/things/controller.things.js#L111-L142

and here:

https://github.com/openhab/openhab-webui/blob/2fc6a70d1f213e93e40c8cb8e96c3ca9b98d2994/bundles/org.openhab.ui.paper/web-src/js/things/controller.things.js#L36-L58

**Comment by hubsif** [comment]
Ok, so from your answer I understand that my assumptions are correct, meaning the core accepts just any link and the UI is (has been before) to only allow for matching links.

Then I'd like to forward my question to @kaikreuzer: I would assume that accepting all kinds of links in the core could lead to unpredictable issues, e.g. when a datetime item tries to update a player type channel. If I'm right here, I think it would be the core's task to prevent that from happening, wouldn't it?

Independently of the core the UI could of course also filter for wrong linking (alone to prevent backend error responses). So, @ghys, would you like me to try tackling this (and #884)?

**Comment by ghys** [comment]
Sure, the problem with my original attempt was that it was not good enough and there were cases where the UI would prevent the link from being created when in fact it would have been perfectly valid.
So I removed the checks - the rationale was, it's better to allow creating an invalid link, if the user can eventually delete and recreate it, than prevent creating a valid one.
But if you come up with a correct implementation, it's better to have the checks in place, of course.

**Comment by Rossko57** [comment]
As per first post, **profiles** can be applied to channel-Item links and can make completely arbitrary transformations - a player type channel to DateTime type Item, a switch type channel to a Location type Item etc.  The UI must permit this for advanced users.

Which does suggest a halfway house perhaps - an initial offering of "naturally"matching types (probably only one) and a click-for-more "advanced" button giving the more exotic possibilities.

**Comment by ghys** [comment]
@Rossko57 yes the problem is actually two-fold:

- hard constraints on the item types that can be created for a given channel/profile combination (and the fact that some item types can be "downgraded" like Color => Dimmer => Switch)
- determining the most appropriate item type to suggest, for instance no matter what the channel's canonical item is, if the profile is "timestamp on update", the item type should be "DateTime".

**Comment by Rossko57** [comment]
Applying profiles is I would say an "advanced" user case.  I think you're at the boundary between offering guidance for clueless, or making it foolproof against the adventurous.
