### ISSUE TITLE
Cannot link trigger channel to an item

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-webui#886]
When looking at a trigger channel of a thing, the UI does not allow creating an item link:

<img width="726" alt="Screenshot 2021-02-07 at 01 01 23" src="https://user-images.githubusercontent.com/3244965/107132522-058cab00-68e0-11eb-9299-259e9903db2f.png">

The hint to use rules for using the channel is not really correct as their main purpose is to allow being linked to an item through a profile. Just like for state channels, I would expect the UI to show the available profiles (the ones that apply to trigger channels as per [the documentation](https://www.openhab.org/docs/configuration/items.html#profiles)).
It is probably not needed (and rather misleading) to offer the creation of a new item, but it should be feasible to create a link against an existing item that has the type that is supported by the selected profile.

**Comment by ghys** [comment]
I guess I never fully understood profiles then :)

**Comment by kaikreuzer** [comment]
I'm happy to teach you, it's a cool feature once you get your head around it :-D

**Comment by hubsif** [comment]
Hi @kaikreuzer,
I thought about attending to this and have a question:
Currently, the UI gets the available profiles via REST API endpoint "profile-types", providing the channelTypeUID.

To test for triggers, I created a trigger channel using the "Generic MQTT Thing". The channelTypeUID seems to be "mqtt:trigger".
Now, when calling the "profile-types" endpoint with this channelTypeUID, the server only returns an empty array instead of trigger profiles. Is this because it's special to the mqtt binding or is this a fault of the server?

**Comment by kaikreuzer** [comment]
Hi @hubsif, many thanks for looking into these issues! I'm very happy to see progress in profile support in the UI! 👍 
I will have to analyse what the server exactly does and whether there's a bug or not - I hope to find some time tonight to look into it. Will come back to you soon.

**Comment by kaikreuzer** [comment]
@hubsif Ok, I have had a look. I think you are doing everything alright, it is just that the MQTT binding is a bad example - it provides this very generic trigger channel, but there is no compatible profile for it - the binding doesn't bring a custom profile and all the [system trigger profiles](https://www.openhab.org/docs/configuration/items.html#profiles) do not apply, since they expect system channel types. We do not (yet) have any generic system profiles - probably it would make sense to create one, which simply maps the trigger event to a String item...

So for testing, I'd suggest to simply try another binding. I have successfully tested it with a `gpstracker:tracker` thing, which has a trigger channel of type `gpstracker:regionTrigger`. If you use this in the REST API, I get this as a response:
```
[
  {
    "uid": "gpstracker:trigger-geofence",
    "label": "Geofence",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Switch"
    ]
  }
]
```
Another good example (that is using system and not custom profiles) is the `enocean:rockerSwitch` thing type, which has a channel `rockerswitchA` of type `system:rawrocker`, which results in this response:
```
[
  {
    "uid": "system:rawrocker-to-stop-move",
    "label": "Raw Rocker To Stop/Move",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Rollershutter"
    ]
  },
  {
    "uid": "system:rawrocker-to-up-down",
    "label": "Raw Rocker To Up/Down",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Rollershutter"
    ]
  },
  {
    "uid": "system:rawrocker-to-play-pause",
    "label": "Raw Rocker To Play/Pause",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Player"
    ]
  },
  {
    "uid": "system:rawrocker-to-on-off",
    "label": "Raw Rocker To On Off",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Switch",
      "Dimmer",
      "Color"
    ]
  },
  {
    "uid": "system:rawrocker-to-next-previous",
    "label": "Raw Rocker To Next/Previous",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Player"
    ]
  },
  {
    "uid": "system:rawrocker-to-rewind-fastforward",
    "label": "Raw Rocker To Rewind/Fastforward",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Player"
    ]
  },
  {
    "uid": "system:rawrocker-to-dimmer",
    "label": "Raw Rocker To Dimmer",
    "kind": "TRIGGER",
    "supportedItemTypes": [
      "Dimmer"
    ]
  }
]
```

**Comment by hubsif** [comment]
Hi @kaikreuzer,
Thank you for your response, eventually I found some time to continue looking into this and the Enocean Rocker Switch works just fine.
Though, another question came up: As it seems I'm able to link an arbitrary item to a trigger channel without selecting a profile. And it seems for trigger profiles there's no default profile available. So:
- what happens actually when linking an item to a trigger channel without a profile?
- should the UI prevent that and force the user to select a matching profile? (though IMO that's actually (also) the backend's task)

**Comment by kaikreuzer** [comment]
Hi @hubsif,

> what happens actually when linking an item to a trigger channel without a profile?

This is indeed undefined and should not be allowed. 

> should the UI prevent that and force the user to select a matching profile? (though IMO that's actually (also) the backend's task)

Yes, the UI should not offer this option and only allow links if the REST API returns any profile(s).
And yes, I agree that the backend should also validate this and not allow linking items to trigger channels without a profile configuration. I've created https://github.com/openhab/openhab-core/issues/2407 for it.
