### ISSUE TITLE
OH3: Unsupported request method HEAD

### ISSUE THREAD

**Issue by balajisraghavan** [openhab/openhab-webui#888]
Connecting via myopenhab.com to OH3 results in `[WARN ] [io.openhabcloud.internal.CloudClient] - Unsupported request method HEAD`

==> /var/log/openhab/openhab.log <==
2021-02-07 17:15:51.944 [WARN ] [io.openhabcloud.internal.CloudClient] - Unsupported request method HEAD

## Expected behavior
myopenhab.com displays the UI, as was the case in OH2

## Steps to reproduce

1. Install OH3 and openhab cloud connector
2. add the UUID and secret to myopenhab
3. Go to dashboard
4. Displays empty page in browser. Sitemaps takes 3 minutes to timeout. UI loads after that

![Screenshot 2021-02-07 at 5 32 59 PM](https://user-images.githubusercontent.com/14067738/107145887-acb62480-696a-11eb-9ddd-a5013769d7db.png)

## Your environment
Ubuntu 20 LTS

**Comment by ghys** [comment]
This looks related to https://github.com/openhab/openhab-cloud then, not the UI.
Ping @openhab/openhab-cloud-maintainers

**Comment by candiesdoodle** [comment]
Bump. Got the same issue. Have to try many times to get this working. When it doesn't work, I get the `Unsupported request method HEAD` error

**Comment by candiesdoodle** [comment]
How do we get some attention to this?
There are more and more people reporting this issue

https://community.openhab.org/t/openhabcloud-http-protocol-violation-authentication-challenge-without-www-authenticate-header/

https://community.openhab.org/t/my-openhab-doesnt-work-properly-after-upgrading-to-oh3/

https://community.openhab.org/t/android-app-beta/41382/

**Comment by lolodomo** [comment]
Just for information, I discovered that the page is finally displayed after several ... minutes !
Hopefully @ghys just proposed a fix.

**Comment by ghys** [comment]
This seems consistent with the screenshot in the OP (the requests lasts 3 minutes).
I figure openHAB Cloud logs the "unsupported method" message but keeps the connection open until it eventually timeouts, then the UI continues loading.
#908 will hopefully fix this.

**Comment by bf8392** [comment]
I have the same issue on multiple instances...how can I help fix this?
