### ISSUE TITLE
To #! or not

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-webui#895]
I love to have multiple tabs open (on things, specific items etc).
It works to click on things/items/... in the left hand main menu to make the main frame show that, but it does not work to open
that in a new tab.
Absolute link has to be http://openhab:8080/#!/settings/things/ but Main UI actually links to http://openhab:8080/settings/things/ which is what is opened on new tab/bookmarking.

**Comment by ghys** [comment]
Duplicate of #710
