### ISSUE TITLE
Invalid custom ID suggestions when adding a Thing

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#899]
## The problem

I'm using the Homematic binding and added the "Gateway Extras" thing from it.

Adding it with "Add as Thing" gives it the ID "homematic:GATEWAY-EXTRAS-CCU3:ccu3:GWE00000000" and works fine.

Adding it with "Add as Thing (with custom ID) instead with the default setting (which is the same as the automatically generated name above):

![image](https://user-images.githubusercontent.com/1475672/107433714-0284fb00-6b2a-11eb-949f-78f57d0d0a83.png)
![image](https://user-images.githubusercontent.com/1475672/107433825-2c3e2200-6b2a-11eb-8cc0-9a531a19b883.png)
![image](https://user-images.githubusercontent.com/1475672/107433790-22b4ba00-6b2a-11eb-8fb2-585b28563ff9.png)

Changing this to e.g. "GWE00000000" leads to a name of "homematic:GATEWAY-EXTRAS-CCU3:GWE00000000" which works fine but is different to the generated name.

## Expected behavior

Either one of these:
- The generated default should not contain anything but the allowed values (and check for this on clicking ok, not just abort everything later) or
- The generated name should be allowed

## Steps to reproduce

See above.

## Your environment

OH 3.0.1

**Comment by ghys** [comment]
I'd go with:

> The generated name should be allowed

Only the first 2 parts of the UID is semantically important (binding/thing type) but it's possible to have more than one part afterwards (many bindings have 4-part UIDs with the bridge's UID as 3rd even if it's "wrong", and that's what's happening here).

Moving to core.
