### ISSUE TITLE
[mainui] CronBuilder puts monday as day 1

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-webui#902]
In the main ui the cronbuilder puts day 1 as Monday. However, openHAB-core has Sunday as day 1. This differences probably is caused by the fact that openHAB used the Quartz library in the past, while the rest of the world seems to put Monday as day 1.
See also this discussion: https://community.openhab.org/t/oh3-cron-trigger-1-day-out/ So unless we decide to change this to use Monday as day 1 this is a UI bug.

**Comment by ghys** [comment]
There are multiple side-effects to this "deviation from the rest of the world":

1) the cron expression builder is under our control so we can change it
2) the library translating the expressions to human-readable text is https://github.com/bradymholt/cRonstrue. As it happens (!) it "Supports Quartz Job Scheduler cron expressions" and has an option (phew!)
> dayOfWeekStartIndexZero: boolean - Whether to interpret cron expression DOW 1 as Sunday or Monday. (Default: true)
3) in the schedule page, planned occurrences are computed with a fork of https://github.com/bunkat/later - according to http://bunkat.github.io/later/parsers.html#cron it doesn't seem to support setting the first DOW.
However, I'm looking forward to https://github.com/openhab/openhab-webui/pull/815 and https://github.com/openhab/openhab-core/pull/2125 being included which should address the schedule (and other problems too).

**Comment by Hilbrand** [comment]
We could change the core cron scheduler (I actually did some testing on that). But that means it breaks all existing cronjobs. So this would need to be discussed. Wdyt?

**Comment by ghys** [comment]
Note that for 1. above I checked and it actually already puts the unambiguous abbreviations when selecting "Specific day of week".

![image](https://user-images.githubusercontent.com/2004147/107544013-0e27fe80-6bca-11eb-8c31-28a2f8d8d982.png)

[Btw I seem to remember that the scheduler doesn't support every option here - esp. the last 5 ones, some work but I'm pretty sure "nearest weekday" (1W-5W) doesn't.]

> We could change the core cron scheduler (I actually did some testing on that). But that means it breaks all existing cronjobs. So this would need to be discussed

It would break all existing _affected_ cronjobs, not sure if there are that many.
Usually I hate breaking changes and go to lengths to avoid them; but in this case, ***with a proper heads-up*** and the fact that:
- we'd realign with the convention (0/7=Sunday) that seems to be used and documented pretty much everywhere, including https://linux.die.net/man/5/crontab and https://en.wikipedia.org/wiki/Cron
- we wouldn't have to worry so much about a library or tool supporting the non-standard 1=Monday

I think we could afford to introduce one.
But of course it's a decision for @openhab/core-maintainers :)
