### ISSUE TITLE
removing invalid link fails silently for links defined in .items file

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#903]
## The problem

I am currently switching to defining my links in the .items file and encountered the following issue:

I have an invalid link (typo or whatever) and I see that link in the item details page. Clicking on it I'm asked if I want to remove it. Being curious what removing can to for an item that is defined in a file, I clicked on it and... 

![image](https://user-images.githubusercontent.com/1475672/107492463-c636b680-6b8c-11eb-8dfe-9a1d9e1edda3.png)

... nothing happens. At all. No error message telling me I can't do this, no log entry etc.

## Expected behavior

It should be displayed to the user why this isn't working (e.g. "You can't remove a link you defined in a file").

## Steps to reproduce

1.  Create broken link in file
2. Try to remove it with MainUI

## Your environment

OH 3.0.1
## Browser console

![image](https://user-images.githubusercontent.com/1475672/107492807-24639980-6b8d-11eb-9c6d-9e6ff8d70461.png)

So it *is* known to the frontend, just not showing it to the user. Should make the fix quite easy.

**Comment by hubsif** [comment]
I started looking into this and thought it might be good to disable link editing at all for file-defined items, when I found that items defined in a file can have both, links created by file and links created via UI.
Unfortunately, in contrast to items, which return an attribute `editable` via REST, links don't share this information, so it cannot be determined if a link has actually been created by file or not 😕.

Actually, I think the best solution would be to add this to the core and then have non-editable links locked in the UI (indicated by a lock icon, just as with items).

Now, simply showing an error message in case the invalid link could not be deleted (just as with "unlink" in the link-edit screen) would be the quickest solution. Though, I think it's more like a workaround and changing the core would be much cleaner.

So, @ghys, in your experience, would it make sense to open a ticket to add this to the core or do you think it would be too complex to add this to the core (shortly) and we should go for the workaround instead (or do both 😉)?

**Comment by ghys** [comment]
@hubsif this was already discussed in #693 and https://github.com/openhab/openhab-webui/issues/413#issuecomment-711411015. Adding the editable flag to the core shouldn't be too hard but nobody has tackled that problem yet.

Originally I thought it was acceptable to arbitrarily limit UI links to items also defined in the UI (which have an `editable` flag), but since it was not well accepted I reversed stance and allowed them back again. So I'm fine with the workaround only (display an error message when the link is not editable after attempting to delete it).

**Comment by hubsif** [comment]
Hm, these are all tickets in "openhab-webui". Shouldn't we open a ticket in the core repository?

**Comment by ghys** [comment]
You're right so we could either move #413 with a mention that adding the editable flag should be added to the API, or create a fresh new issue refencing those in webui.

**Comment by cweitkamp** [comment]
The implementation of the `editable` flag for ItemChannleLinks (https://github.com/openhab/openhab-core/pull/2318) has been merged. You are now able to add some improvements to the UI.

**Comment by hubsif** [comment]
Oh, that was fast. Thank you, Christoph!
