### ISSUE TITLE
Opening the "Locations" tab too fast results in empty display

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#909]
## The problem
Opening the "Locations" tab (or "Equipment" or "Properties" for that matter) quickly after the Dashboard part of MainUI has been loaded results in display of an empty page. This can only be fixed by switching the tab to something else and then switching back again.

This happens to me all the time and is quite annoying.

![image](https://user-images.githubusercontent.com/1475672/107938205-4b530e80-6f85-11eb-95c0-bebcbee7ec77.png)

## Expected behavior
No matter how fast I click, the worst case should be that it takes some tome to load.

## Steps to reproduce
1. Click "Settings"
2. Click "Back"
3. Click "Location" quickly (<1s)

## Your environment
OH3.0.1

## Browser console
![image](https://user-images.githubusercontent.com/1475672/107938295-70478180-6f85-11eb-8e59-8a16f2ecad18.png)

## Browser network traffic
No failures, all code 200.
![image](https://user-images.githubusercontent.com/1475672/107938414-a6850100-6f85-11eb-8b8c-09676b5b5139.png)

**Comment by lolodomo** [comment]
I have the same issue just after opening MsinUI.

**Comment by rkoshak** [comment]
I've seen this too but only when viewing the UI through a reverse proxy. I just assumed it had to do with that and haven't looked into it any more. I've also noticed it's the same for all three of the autogenerated tabs, not just Locations.

**Comment by NCO3** [comment]
I recognize this, too. And I am not working with any reverse proxy

**Comment by eikowagenknecht** [comment]
My guess is that this happens when the request to /items?... is not completed before you click on the UI (700ms in my example). Probably a reverse proxy adds some latency so you don’t need to click as fast and this happens more often.
