### ISSUE TITLE
[basic] Frame visibility in sitemap ignored until refresh

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-webui#92]
OH version: S1650 (but I think this has happened since S1627)

Possibly related to https://github.com/openhab/openhab-android/issues/1437

In this example, changing the state of the Mode Item does not change the visibility of the frame until the page is refreshed.
```
sitemap Test label="Test" {
    Frame visibility=[Mode == "Morning"] {
        Text item=Mode
    }
}
```
Classic UI displays properly without having to refresh.

**Comment by openhab-5iver** [comment]
Moved to OHC... https://github.com/openhab/openhab-core/issues/954

**Comment by lolodomo** [comment]
I implemented this feature several years ago. It should have been broken by the recent changes about visibility management in the core framework. 
Does it work in Android App?

**Comment by openhab-5iver** [comment]
Nope... but should in the next build. See link above with details.

**Comment by lolodomo** [comment]
Reproduced.

**Comment by lolodomo** [comment]
It is fixed; in case of a frame, we receive an update event without event data.
