### ISSUE TITLE
Preview in widget designer doesn't work for widgets based on oh-* components

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#923]
## The problem

When you develop a widget and base it on some oh-* widget, e.g. oh-label-item, the preview does not show anything at all:

![image](https://user-images.githubusercontent.com/1475672/108845739-10348900-75de-11eb-960d-4408d00780c6.png)

When you use an f7-* component instead it works, but looks broken (obviously because some parts from the oh-* component are needed):
![image](https://user-images.githubusercontent.com/1475672/108846011-66a1c780-75de-11eb-86bb-5c7fae98a269.png)

This makes creating new widgets, especially list item widgets, quite hard because you need to actually place them on a page to see the result.

## Expected behavior
Preview should also work for widgets based on oh-* components.

## Steps to reproduce

1. Copy the YAML from one of [Rich Koshaks examples](https://community.openhab.org/t/example-custom-list-widgets/116265 ) and insert it into a new widget.

## Your environment
OH3.0.1

## Browser console
As soon as you type a valid oh-* name:
![image](https://user-images.githubusercontent.com/1475672/108846404-cef0a900-75de-11eb-933f-417e52b21036.png)

**Comment by hubsif** [comment]
Actually, I think in contrast to what the title suggests, the actual issue here is not that oh-* components don't work, it's about list items not being displayed or displayed properly due to a missing parent list, as mentioned in #892.
