### ISSUE TITLE
Percent sign in pattern of state description (meta data) is displayed incorrectly as %% in Analyze chart

### ISSUE THREAD

**Issue by thomaszlow** [openhab/openhab-webui#928]
## The problem

In the state description the value %d %% is entered as a pattern:

![s1](https://user-images.githubusercontent.com/79666256/109214349-06637f00-77b2-11eb-8675-bbfde4d0e07c.PNG)

In the analyze chart %% is displayed on x axis as well as the selectable axis in the control area.

![s2](https://user-images.githubusercontent.com/79666256/109214802-91447980-77b2-11eb-97cc-07d7ea10b189.PNG)

## Expected behavior

Only % is displayed like for other values e.g. kWh or °C.

## Steps to reproduce

1. Select a dimmer item
2. Add a state description as meta data
3. Enter the value `%d %%` as pattern in the state description 
4. Go back to item
5. Click on "Analyze"

## Your environment

openHAB 3.0.1 Release Build
Docker on Synology DS918+

## Browser console

Error occurs seems to occur in the backgound but not in the analyze overlay.

![image](https://user-images.githubusercontent.com/79666256/109215394-6870b400-77b3-11eb-853f-6416738e2962.png)

## Browser network traffic

![image](https://user-images.githubusercontent.com/79666256/109215515-8ccc9080-77b3-11eb-9abb-5b21a1db3401.png)

## Additional information

None

**Comment by Rossko57** [comment]
See also https://github.com/openhab/openhab-webui/issues/870

**Comment by hubsif** [comment]
Actually, that doesn't seem easy to solve. Afaik openHAB doesn't actually keep a unit parameter with an item, only a "dimension", like temperature. The unit is then chosen by the locale setting and can be overwritten in the state description, to e.g. automatically convert from °F to °C.

Right now, for charts the UI simply assumes the unit to be the second part of either the transformed state, state or if set the state description. While this mostly works, it breaks in multiple situations:
1. if the state description converts the dimension for some reason (e.g. °C to °F), the chart still displays °C (IMHO this is actually a new, different bug)
2. the correct unit is not detected for dimensionless items, and even displays wrong when the state description doesn't follow the "<value> <unit>" pattern. Instead for currency values defined as `$ %d` it shows %d as value
3. it doesn't take the required double percent sign into account, required for the server side printf(?) (unfortunately, the dimension "percentage" doesn't exist explicitly, which I also would have liked to use multiple times)

For now I think the UI could simply detect the double %%, which would solve many cases. But I think for 1. and 2. there's no easy solution...
