### ISSUE TITLE
sort and filtering item list

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-webui#933]
## The problem

It would be very practical to be able to sort items according to their affiliation.
This would provide a better overview.

## Your suggestion
Add a dropdown option list to sort all the items by group, name or whatever.

[Sort option](https://ibb.co/rpd6nJn)
[Main UI overview example](https://ibb.co/0BCBKYq)

## Additional information

It is also practical that the groups are already displayed in the dropdown field and you do not have to know or search them.

**Comment by SterreN** [comment]
I agree that this would be a nice enhancement. I'll start to work on it.

**Comment by SterreN** [comment]
What about taking a similar approach as to how Things and Pages can be sorted (see images). In case of Items we could indeed sort on "Alphabetical" and "By group". I think this would be clean + consistent. 
 
<img width="793" alt="orderingProposal1" src="https://user-images.githubusercontent.com/15819720/110934355-31aba980-832e-11eb-81ca-d3121d5fb286.png">
<img width="792" alt="orderingProposal2" src="https://user-images.githubusercontent.com/15819720/110934363-35d7c700-832e-11eb-8edf-f656326e3d7a.png">

**Comment by ghys** [comment]
The items list is different from the others as it is a [virtual list](https://v5.framework7.io/docs/virtual-list.html), to avoid performance problems since the list of items can go well into the hundreds if not thousands (as do the other lists, but it's less frequent). Virtual lists mandate a fixed item height to work so it prevents having group headers.

**Comment by SterreN** [comment]
I see, thank you for the explanation.

**Comment by Gifford47** [comment]
> The items list is different from the others as it is a [virtual list](https://v5.framework7.io/docs/virtual-list.html), to avoid performance problems since the list of items can go well into the hundreds if not thousands (as do the other lists, but it's less frequent). Virtual lists mandate a fixed item height to work so it prevents having group headers.

ok, but one could expand the "Template7 itemTemplate" with more coloums, so that after the item's value comes the parent groups and eventually the associated thing. then you could apply a "searchAll function" that searches all items with any group and allow no duplicates of groups. therefore you have a list of all groups and/or things. this function could be started "onload" or by user click. then we could sorting or filtering the items.

is it possible?

**Comment by ghys** [comment]
Could be me, but I'm not exactly sure what you mean.

You already can navigate up or down the group hierarchy with the item details page (as you have thee items' parent groups, and, for groups, their members), or the Model page (with the non-semantic option checked) so it's not evident IMO what would be the benefit of adding another way to sort items according to their parent group.

**Comment by Gifford47** [comment]
ok, you're right. i haven't used the function yet, but it fulfils almost all my wishes :)

thank you!
