### ISSUE TITLE
[MainUI - Development] lint scripts do not work on Windows

### ISSUE THREAD

**Issue by DarkC35** [openhab/openhab-webui#951]
## The problem

`npm run lint` and `npm run lint:fix` scripts do not work on Windows because double quotes are required for `glob` syntax.
> If you want to use node glob syntax, you have to quote your parameter (using double quotes if you need it to run in Windows)
see: https://eslint.org/docs/user-guide/command-line-interface

![grafik](https://user-images.githubusercontent.com/38973046/110674862-994ce200-81d2-11eb-98fc-273fe5f41580.png)

## Expected behavior

`npm run lint` and `npm run lint:fix` should work on Windows too.

## Additional information

There are currently some lint errors on `main` branch:
![grafik](https://user-images.githubusercontent.com/38973046/110675780-90104500-81d3-11eb-9b7c-e29a622fc090.png)

Those are not covered by the GH Action since it only covers `src`:

https://github.com/openhab/openhab-webui/blob/0a1848e9af6658b5f4034ee76597098fcecc4307/.github/workflows/mainui.yml#L42

Maybe the lint script should be unified and `npm run lint` used in the Action?

**Comment by ghys** [comment]
> Maybe the lint script should be unified and npm run lint used in the Action?

You're absolutely right, and exactly my thoughts from a day ago...!
I figured what worked best was indeed `npx eslint --ext js --ext vue src`
If you want to take care of this, that would be appreciated.
